---
title: "딥워크"
author: "Cal Newport"
---

# 서론: 몰입의 힘

스위스 칸톤인 세인트 갈렌에는 취리히 호수의 북쪽 둑 근처에 볼링겐이라는 마을이 있다. 1922년 정신과 의사 칼 융이 이곳을 선택하여 은신처를 짓기 시작했다. 그는 탑이라고 부르는 기본적인 2층 석조 주택에서 시작하였다. 그는 인도 여행을 마치고 돌아온 뒤 가정에 명상실을 추가하는 관행을 관찰한 뒤 단지를 확장해 개인 사무실을 갖추게 했다. 융은 "퇴직하는 방에는 나 혼자 있다"고 그 공간에 대해 말했다. "나는 열쇠를 항상 가지고 있고 내 허락을 제외하고는 아무도 거기에 들어갈 수 없다."

저널리스트 메이슨 커리는 그의 저서 '일과의 법칙(Daily Rituals)'에서 융에 대한 다양한 소스를 분석해 타워에서 정신과 의사의 근무 습관을 재창조했다. 커리는 "융은 오전 7시에 일어나 큰 아침 식사를 한 뒤 자신의 개인 사무실에서 두 시간 동안 방해받지 않는 글쓰기 시간을 보냈다"고 전했다. 그의 오후는 종종 명상이나 주변 시골에서 긴 산책으로 구성되었다. 탑에는 전기가 없어 낮이 밤으로 갈수록 기름등에서 빛이, 벽난로에서 열이 나왔습니다. 융은 오후 10시까지 잠자리에 들기로 했다며 "이 탑에서 느꼈던 휴식과 쇄신의 감정은 처음부터 강렬했다"고 말했다.

볼링겐 타워를 휴양지로 생각하면 유혹적이지만 이 시점에서 융의 경력 맥락에 넣으면 호숫가 수련소가 일탈 탈출구로 지어졌지는 않다는 것이 분명하다. 1922년 융이 부동산을 매입하면서 휴가를 보낼 여유가 없었다. 불과 1년 전인 1921년 그는 융의 사유와 그의 한때 친구이자 멘토였던 지그문트 프로이트의 사상 사이에 오랫동안 전개되어 온 많은 차이점을 확고히 한 획기적인 책인 '심리학적 유형'을 발표했다. 1920년대 프로이트와 의견이 일치하지 않는 것은 과감한 행동이었다. 그의 책을 뒷받침하기 위해, 융은 날카롭게 지내고 그의 새로운 사유학의 궁극적인 이름인 분석 심리학을 더욱 뒷받침하고 확립하는 스마트한 기사와 책을 줄줄이 생산해야 했다.

융의 강의와 상담 실습은 그를 취리히에서 바쁘게 유지시켰는데 이는 분명하다. 그러나 그는 바쁜 일만으로는 만족하지 않았다. 그는 우리가 무의식을 이해하는 방식을 바꾸고 싶었고 이 목표는 바쁜 도시 생활 속에서 그가 감당할 수 있는 것보다 더 깊고 신중한 생각을 요구했다. 융은 프로 생활을 피해가기 위해서가 아니라 진출을 위해 볼링겐으로 후퇴했다.

칼 융은 20세기에 가장 영향력 있는 사상가 중 한 명이 되었다. 물론 그의 궁극적인 성공에는 여러 가지 이유가 있다. 그러나 이 책에서 나는 그의 성취에 거의 확실히 핵심적인 역할을 한 다음 기술에 대한 그의 헌신에 관심이 있다.

딥워크: 인지적 역량을 한계로 밀어내는 산만함이 없는 집중 상태에서 수행되는 전문적 활동이다. 이러한 노력은 새로운 가치를 창출하고, 당신의 기술을 향상시키며, 복제하기 어렵다.

현재의 지적 능력에서 가치의 마지막 한 방울을 끌어내기 위해서는 깊은 노력이 필요하다. 우리는 이제 심리학과 신경과학 모두에서 수십 년 동안의 연구를 통해 딥 워크을 수반하는 정신적 스트레스의 상태도 능력을 향상시키는 데 필요하다는 것을 알고 있습니다. 즉, 심층 작업은 20세기 초 학문 정신 의학과 같이 인지적으로 까다로운 분야에서 두각을 나타내기 위해 필요한 노력의 유형이었다.

심층 작업이라는 용어는 필자의 것으로서 칼 융이 사용했을 것이 아니라 이 시기 그의 행위는 그 근본적인 개념을 이해한 사람의 것이었다. 융은 자신의 직업생활에서 딥 워크을 촉진하기 위해 나무 속에 돌로 탑을 쌓았는데, 이 작업은 시간과 에너지, 돈이 필요했다. 그것은 또한 그를 더 즉각적인 추구에서 멀어지게 했다. 메이슨 커리가 쓴 것처럼, 융의 정기적인 볼링겐 여행은 "그가 자신에게 의지하는 많은 환자를 가졌지만, 융은 휴가를 갖는 것에 부끄러움을 느끼지 않았다"고 언급하면서, 그의 임상 작업에 보내는 시간을 줄였다.

실제로 먼 역사와 최근의 역사에서 다른 영향력 있는 인물들의 삶을 연구한다면 딥 워크에 대한 헌신이 공통적인 주제임을 알게 될 것이다. 예를 들어 16세기 수필가 미셸 드 몽테인은 그가 남쪽 탑에 세워놓은 사립 도서관에서 자신의 프랑스 성의 돌담을 지키며 일함으로써 융과 같은 모습을 보여주었고 마크 트웨인은 여름을 보내고 있던 뉴욕 채석장 재산을 축사에서 톰 소이어의 모험을 많이 썼다. 트웨인의 학문은 본가와 너무 고립되어 있어 그의 가족이 식사를 위해 그의 관심을 끌기 위해 경적을 울리려고 노력했다.

역사를 전개하면서 시나리오 작가이자 감독인 우디 앨런을 생각해 보자. 1969년부터 2013년까지 44년간 우디 앨런은 아카데미상 후보 23편을 받은 44편의 영화를 작사, 연출했는데, 이는 예술적 생산성의 터무니없는 비율이다. 이 시기 내내 앨런은 컴퓨터를 소유한 적이 없었고 대신 전자적 산만함으로부터 벗어나 독일 올림피아 SM3 수동 타자기로 모든 글을 완성했다. 앨런은 노벨상을 수상했다는 사실이 알려지자 언론인들이 그를 찾을 수 없을 정도로 단절된 고립 상태에서 자신의 작업을 수행하는 이론물리학자 피터 힉스가 컴퓨터에 대한 거부에 동참한다. 반면에 JK 롤링은 컴퓨터를 사용하지만 이 기간이 기술의 부상과 미디어 인물의 인기와 일치했음에도 불구하고 해리포터 소설을 쓰는 동안 소셜 미디어에 부재한 것으로 유명하다. 롤링의 직원은 2009년 가을에 그녀가 캐주얼 베이컨시를 작업하면서 마침내 그녀의 이름으로 트위터 계정을 시작했고, 첫 1년 반 동안 그녀의 유일한 트윗은 "이것이 진정한 나이지만, 당신은 나에게서 자주 듣지 못할 것이다. 나는 지금 펜과 종이가 나의 우선 순위이기 때문에 두렵다."

딥 워크는 물론 역사적인 것, 테크노포빅적인 것에 국한되지 않는다. 빌 게이츠 마이크로소프트 CEO는 유명한 'Think Week'을 연 2회 실시했는데, 이 기간 동안 그는 스스로(대부분 호숫가 오두막에서) 고립되어 큰 생각만 읽고 생각하는 일을 하지 않았다. 게이츠가 마이크로소프트의 관심을 넷스케이프 커뮤니케이션이라는 신생 기업으로 돌린 유명한 '인터넷 조수(Internet Tidal Wave)' 메모를 쓴 것은 1995년 싱싱크 위크(Think Week) 때였다. 그리고 아이러니하게도 인터넷 시대의 대중적 개념을 형성하는 데 도움을 준 평가를 받는 사이버 펑크 작가인 닐 스티븐슨은 전자적으로 접근하는 것이 거의 불가능합니다. 그의 웹사이트는 이메일 주소를 제공하지 않으며 그가 소셜 미디어 사용에 의도적으로 나쁜 이유를 설명하는 에세이가 있습니다. 그가 한 번 누락을 설명한 바는 다음과 같다: "내가 긴 연속적인 끊김 없는 타임 을 많이 얻는 방식으로 내 삶을 정리하면, 나는 소설을 쓸 수 있다. [나 대신 방해를 많이 받으면] 대체하는 것은 무엇입니까? 오래 있을 소설 대신... 내가 개별에게 보낸 이메일 메시지가 무더기로 있다."

영향력 있는 개인들 사이에서 심층 작업의 편재성은 심층 작업의 가치를 빠르게 잊고 있는 대부분의 현대 지식 작업자의 행동과 극명하게 대조되기 때문에 강조하는 것이 중요하다.

지식 종사자들이 심층 업무에 대한 친숙도를 잃어가고 있는 이유는 네트워크 도구라는 것이 잘 정립되어 있다. 이메일과 SMS와 같은 커뮤니케이션 서비스, 트위터와 페이스북과 같은 소셜 미디어 네트워크, 버즈피드와 레딧과 같은 인포테인먼트 사이트의 반짝이는 엉킴을 포착하는 광범위한 범주입니다. 종합하면, 스마트폰 및 네트워크화된 사무용 컴퓨터를 통한 유비쿼터스 액세스와 결합된 이러한 도구의 부상으로 인해 대부분의 지식 작업자의 주의가 슬리버로 분절되었다. 2012년 맥킨지의 연구에 따르면 평균 지식 근로자는 이제 주당 60% 이상을 전자 통신 및 인터넷 검색에 종사하며 근로자의 거의 30%가 이메일 읽기 및 답변에만 할애된다.

이러한 파편화된 주의의 상태는 오랜 기간의 중단 없는 사고를 필요로 하는 딥 워크을 수용할 수 없다. 그러나 동시에 현대 지식 노동자들은 허술하지 않는다. 사실 그들은 그 어느 때보다 바쁘다고 보고합니다. 불일치는 무엇 때문에 발생합니까? 많은 부분이 또 다른 유형의 노력으로 설명될 수 있으며 이는 딥 워크의 개념에 대응하는 것을 제공한다.

피상적 작업: 인지적으로 요구되지 않는 물류 스타일의 작업으로, 종종 산만하게 수행된다. 이러한 노력은 세상에 새로운 가치를 많이 창출하지 못하는 경향이 있으며 복제하기 쉽다.

다시 말해, 네트워크 도구의 시대에 지식 작업자는 점점 더 딥 워크을 피상적인 대안으로 대체한다. 새로운 비즈니스 전략을 형성하거나 중요한 보조금 신청서를 작성하는 것과 같이 깊은 사고로 잘 봉사되는 더 큰 노력은 침묵된 품질을 생성하는 산만한 대시로 분절된다. 심도에 대한 문제를 더 악화시키기 위해, 피상적인 영역으로의 이러한 이동이 쉽게 되돌릴 수 있는 선택이 아니라는 증거가 증가하고 있다. 광란의 피상적인 상태에서 충분한 시간을 보내면 딥 워크을 수행할 수 있는 능력을 영구적으로 줄일 수 있습니다. "네트가 하는 것 같으면 집중력과 관조 능력을 떨어뜨리는 것 같다"라고 언론인 니콜라스 카는 2008년 자주 인용된 대서양 기사를 통해 인정했다. "(그리고) 나만 있는 것은 아니다." 카는 이 주장을 퓰리처상 최종 후보에 오른 책 생각하지 않는 사람들(The Shallows)로 확장했다. 《생각하지 않는 사람들》를 쓰기 위해서는 적절하게 카가 객실로 이동하여 강제로 연결을 끊어야 했다.

네트워크 도구가 우리의 작업을 깊은 몰입의 영역에서 피상적인 영역으로 밀어붙이고 있다는 생각은 새로운 것이 아니다. 《생각하지 않는 사람들》는 최근 일련의 책 중 처음으로 인터넷이 우리의 두뇌와 작업 습관에 미치는 영향을 조사했다. 이러한 후속 제목에는 윌리엄 파워스의 햄릿의 블랙베리, 존 프리먼의 이메일 폭정, 알렉스 섭정-킨 팡의 주의 분산 중독이 포함되며 이들은 모두 네트워크 도구가 지속적인 집중력을 요구하는 작업에서 주의를 분산시키는 동시에 집중력을 유지하는 능력을 저하시킨다는 데 다소 동의한다.

이러한 기존의 증거들을 감안할 때, 나는 이 논점을 확립하기 위해 이 책에서 더 많은 시간을 할애하지 않을 것이다. 우리는 네트워크 도구가 심층 업무에 부정적인 영향을 미친다고 규정할 수 있기를 바란다. 나는 또한 이러한 주장이 불변의 균열을 여는 경향이 있기 때문에 이러한 변화의 장기적인 사회적 결과에 대한 모든 큰 논쟁을 피할 것이다. 논쟁의 한쪽에는 적어도 현재 상태에서 이러한 도구 중 많은 부분이 사회에 피해를 준다고 의심하는 야론 라니에와 존 프리먼과 같은 테크노 회의론자가 있고 다른 한쪽에서는 클라이브 톰슨과 같은 테크노 낙관론자가 확실히 사회를 변화시키고 있지만 우리를 더 잘 살게 할 수 있는 방식으로 변화시키고 있다고 주장한다. 예를 들어 구글은 우리의 기억력을 줄일 수 있지만 우리가 알아야 할 모든 것을 검색할 수 있는 순간처럼 더 이상 좋은 기억은 필요하지 않다.

나는 이 철학적 논쟁에 아무런 입장을 가지고 있지 않다. 이 문제에 대한 나의 관심은 오히려 훨씬 더 실용적이고 개별화된 관심의 테제 쪽으로 돌아간다: 우리의 작업 문화가 피상적인 일으로 전환됨(철학적 측면에서 좋든 나쁘든)은 이 추세에 저항하고 깊이를 우선시할 가능성을 인식하는 소수에 대한 막대한 경제적, 개인적 기회를 노출하고 있다.

당신이 우리 경제에서 가치가 없다는 것을 발견하는 방법은 여러 가지가 있다. 제이슨 벤에게 교훈은 금융 컨설턴트로 취업한 지 얼마 되지 않아 그가 작업 책임의 대다수가 "뭉쳐진" 엑셀 스크립트에 의해 자동화될 수 있음을 깨달았을 때 분명해졌다.

벤을 고용한 회사는 복잡한 거래에 관여하는 은행들에 대한 보고서를 제작하였다. ("소리만큼 흥미로웠다" 벤은 인터뷰 중 하나에서 농담을 했다. 보고서 작성 과정은 작업련의 엑셀 스프레드시트에서 수동으로 수작업하는 시간이 소요되었다. 그가 처음 도착했을 때, 벤은 이 단계를 완료하는 데 보고서당 최대 6시간이 걸렸다(회사에서 가장 효율적인 베테랑은 약 절반의 시간 안에 이 작업을 완료할 수 있었다). 이것은 벤과 잘 어울리지 않았다.

"그것이 나에게 가르쳐진 방식은 과정이 어설프고 수동으로 집약적으로 보였다"고 벤은 회상한다. 그는 엑셀에 사용자가 공통 작업을 자동화할 수 있는 매크로라는 기능이 있다는 것을 알고 있었다. 벤은 주제에 대한 기사를 읽고 곧 새로운 워크시트를 작성했는데, 이 워크시트는 수동 데이터 조작의 6시간 과정을 거쳐 기본적으로 버튼 클릭으로 대체할 수 있는 일련의 매크로와 연결되어 있다. 원래 그에게 하루 종일 일하던 보고서 작성 과정은 이제 1시간 미만으로 줄일 수 있었다.

벤은 영리한 사람이었습니다. 그는 엘리트 대학(버지니아 대학)에서 경제학 학위를 취득했고 그의 상황에서도 많은 사람들과 마찬가지로 그의 진로에 대한 야망을 가지고 있었다. 그의 주요 전문 기술들이 엑셀 매크로로 포착될 수 있는 한 이러한 야망들이 좌절될 것이라는 것을 깨닫는 데는 그리 오래 걸리지 않았다. 그는 따라서 세계에 자신의 가치를 높여야 한다고 결정했습니다. 한동안의 연구 끝에 벤은 가족들에게 인간 스프레드시트라는 직업을 그만두고 컴퓨터 프로그래머가 될 것이라는 결론에 도달했다. 그러나 그러한 웅장한 계획의 경우에도 종종 그러하지만 제이슨 벤은 코드를 작성하는 방법을 전혀 알지 못했다는 문제가 있었다.

컴퓨터 과학자로서 나는 컴퓨터 프로그래밍이 어렵다는 분명한 점을 확인할 수 있다. 대부분의 신규 개발자는 첫 직무 이전에 4년 간의 대학 교육을 줄타기를 위해 바친다. 제이슨 벤은 이번에는 없었다. 엑셀 환기 후 금융사에서 일을 그만두고 집으로 옮겨 다음 걸음을 준비했다. 그의 부모는 그가 계획이 있다는 것에 기뻐했지만 이 귀국이 장기적일 수 있다는 생각에 만족하지 않았다. 벤은 힘든 기술을 배워야 했고 그렇게 빨리 해야 했다.

여기서 벤은 많은 지식 노동자들이 더 폭발적인 경력 궤도로 탐색하는 것을 방해하는 것과 동일한 문제에 직면했다. 컴퓨터 프로그래밍과 같은 복잡한 것을 배우는 것은 칼 융을 취리히 호수를 둘러싼 숲으로 몰아넣은 유형의 집중력인 인지적으로 까다로운 개념에 대한 집중력을 지속적으로 필요로 한다. 이 과제는 다시 말해 딥 워크의 행위이다. 그러나 대부분의 지식 종사자는 앞서 이 서론에서 주장했듯이 심층 작업을 수행할 수 있는 능력을 상실했다. 벤은 이러한 추세에 예외가 아니었다.

벤은 "나는 항상 인터넷에 접속해 이메일을 확인하고 있었고, 멈출 수 없었고, 그것은 강박이었다"고 재무직을 그만두기까지의 기간 동안 자신을 묘사했다. 자신의 어려움을 깊이 있게 강조하기 위해 벤은 금융회사의 감독이 한 번 자신에게 가져다 준 프로젝트에 대해 나에게 말했다. 그는 "그들은 내가 사업 계획을 작성하기를 원했다"고 설명했다. 벤은 사업계획서를 작성하는 방법을 알지 못하여 필요한 것을 이해하기 위해 기존의 다섯 가지 다른 계획을 찾아서 읽어보고 비교하고 대조하기로 결정했다. 이것은 좋은 생각이었지만 뱅은 "집중을 유지할 수 없었다"라는 문제가 있었다. 이 기간 동안 그는 거의 모든 분(내 시간의 98%)을 웹 서핑에 보낸 날이 있었다고 이제 인정한다. 사업계획 프로젝트-경력 초기에 자신을 구별할 수 있는 기회-가 도마 위에 떨어졌다.

그만두는 즈음에는 딥워크로 어려움을 잘 알고 있었기 때문에 코딩을 배우는 데 전념할 때, 딥워크를 하는 방법을 동시에 마음속에 가르쳐야 한다는 것을 알았다. 그의 방법은 과감했지만 효과적이었다. "컴퓨터가 없는 방에 갇혔는데, 교과서와 노트카드, 형광펜만 있었다." 그는 컴퓨터 프로그래밍 교과서를 강조하고 아이디어를 노트카드로 옮긴 다음 큰 소리로 연습을 했다. 전자적 산만함으로부터 자유로운 이러한 기간들은 처음에는 힘들었지만, 벤은 자신에게 다른 선택의 여지가 없었는데, 그는 이 자료를 배워야 했고, 그는 그 방 안에 자신을 산만하게 할 것이 없도록 했다. 그러나 시간이 지나면서 집중력이 좋아지면서 결국 이 힘든 새로운 기술을 배우는 데 방해받지 않고 집중하면서 하루에 5시간 이상 단절된 시간을 정기적으로 방에서 관찰하는 지점까지 이르렀다. 그는 "나는 아마 끝날 때까지 주제에 대한 18권의 책을 읽었을 것"이라고 회상한다.

두 달 동안 학업을 계속한 벤은 악명 높은 데브 부트캠프, 즉 웹 애플리케이션 프로그래밍의 주당 백시간의 충돌 과정에 참석했다. (프로그램을 연구하는 동안, 벤은 데브를 "내 인생에서 내가 한 것 중 가장 힘든 일"이라고 묘사한 프린스턴에서 박사 학위를 받은 학생을 발견했다. ) 그의 준비와 심층 작업을 위한 새로 연마된 능력을 모두 고려할 때, 벤은 탁월했다. 그는 "일부 사람들은 준비되지 않은 채 나타나게 된다"고 말했다. 그들은 집중할 수 없습니다. 그들은 빨리 배울 수 없다. 벤과 함께 프로그램을 시작한 학생들 중 절반만이 제때 졸업을 하게 되었다. 벤은 졸업했을 뿐만 아니라, 자신의 반에서 최상위 학생이었다.

깊은 노력이 결실을 맺었습니다. 벤은 벤처 펀딩과 직원 선별로 2천500만 달러를 지원한 샌프란시스코 기술 스타트업의 개발자로 빠르게 취업했다. 벤은 불과 반년 전만 해도 금융 컨설턴트 직장을 그만두자 연 4만 달러를 벌고 있었다. 컴퓨터 개발자로서의 그의 새로운 직업은 그의 기술 수준과 함께 실리콘 밸리 시장에서 본질적으로 제한 없이 계속 성장할 수 있는 금액인 10만 달러를 지불했다.

내가 벤과 마지막으로 이야기했을 때, 그는 새로운 직책에서 번창하고 있었다. 심층근로에 신진한 그는 사무실 건너편 아파트를 빌려 다른 사람이 도착하기 전에 새벽에 나타나서 산만하지 않고 일할 수 있게 했다. 그는 "좋은 날에는 첫 만남 전에 4시간 동안 집중할 수 있다"고 나에게 말했다. "따라서 오후에 3~4시간 더 걸릴 것 같아요. 그리고 '포커스'를 말하는데, 이메일도 없고 해커 뉴스도 없고 단지 프로그래밍만 하는 것"이라며 가끔 자신의 예전 직업에서 하루의 98%까지 웹 서핑에 보낸다고 인정했던 사람에게는 제이슨 벤의 변신이 놀라울 따름이다.

제이슨 벤의 이야기는 중요한 교훈을 강조하는데, 심층 작업은 20세기 초의 작가와 철학자들의 향수적 감정이 아니다. 대신 오늘날 큰 가치를 지닌 기술이다.

이 가치는 두 가지 이유가 있습니다. 첫 번째는 학습과 관련이 있습니다. 우리는 빠르게 변화하는 복잡한 시스템에 의존하는 정보 경제를 가지고 있다. 예를 들어, 벤이 배운 컴퓨터 언어 중 일부는 10년 전에 존재하지 않았으며 10년 후에 구식일 것이다. 마찬가지로 1990년대 마케팅 분야에서 떠오른 사람은 오늘날 디지털 분석을 마스터해야 한다는 것을 전혀 몰랐을 것이다. 따라서 우리 경제에서 가치를 유지하려면 복잡한 것을 빠르게 배우는 기술을 마스터해야 합니다. 이 작업은 딥 워크이 필요합니다. 이 능력을 배양하지 않으면 기술이 발전함에 따라 뒤처질 가능성이 있다.

딥워크가 가치가 있는 두 번째 이유는 디지털 네트워크 혁명의 영향이 양방향을 모두 끊었기 때문이다. 당신이 유용한 것을 만들 수 있다면, 그것의 도달 가능한 청중(예컨대 고용주나 고객)은 본질적으로 무한하며 이는 당신의 보상을 크게 확대한다. 반면에, 당신이 생산하는 것이 평범하다면, 청중이 온라인에서 더 나피상적인 대안을 찾는 것이 너무 쉽기 때문에 당신은 곤경에 처해 있다. 컴퓨터 프로그래머, 작가, 마케터, 컨설턴트, 기업가든 당신의 상황은 프로이트를 능가하려고 시도하는 Jung이나 뜨거운 창업에서 자신의 것을 유지하려고 시도하는 Jason 벤과 유사해졌습니다. 성공하려면 당신이 생산할 수 있는 최고의 것을 생산해야 합니다. 깊이가 필요한 작업입니다.

심층 작업의 필요성이 커지는 것은 새로운 일이다. 산업 경제에서는 딥워크가 중요한 소규모 숙련 노동과 전문직 계층이 존재했지만 대부분의 노동자들은 산만함 없이 집중할 수 있는 능력을 배양하지 않고도 잘할 수 있었다. 그들은 위젯을 크랭크하기 위해 돈을 받았고 그들이 위젯을 보관하는 수십 년 동안 그들의 직업에 대해 많은 부분이 변하지 않았다. 그러나 정보 경제로 전환함에 따라 우리 인구의 점점 더 많은 사람들이 지식 노동자이며 대부분의 사람들이 아직 이 현실을 인식하지 못했더라도 심층 작업이 핵심 화폐가 되고 있다.

심층 작업은, 다시 말해, 무관하게 떨어지는 구식 기술이 아니다. 대신, 그것은 돈을 벌지 못하는 사람들을 씹고 뱉는 경향이 있는 글로벌 경쟁 정보 경제에서 앞서 나가려는 모든 사람에게 중요한 능력이다. 실제 보상은 페이스북을 이용하는 것이 편한 사람들(피상적 작업, 쉽게 복제할 수 있는 작업)이 아니라 서비스를 운영하는 혁신적인 분산 시스템을 구축하는 것이 편한 사람들(결정적으로 딥 워크, 복제하기 어려운 작업)에게 예약되어 있다. 비즈니스 작가 에릭 바커의 표현을 사용하려면 "21세기의 초강대국"이라고 생각하기 때문에 심층 작업이 매우 중요하다.

우리는 이제 이 책에서 다음 모든 것의 기초를 제공하는 아이디어로 결합할 수 있는 두 가지 사고 가닥을 보았는데, 하나는 심층 작업의 증가하는 희소성에 대한 것이고 다른 하나는 가치 증가에 관한 것이다.

심층 작업 가설 심층 작업을 수행하는 능력은 우리 경제에서 점점 더 가치가 높아지는 동시에 점점 더 희귀해지고 있다. 결과적으로 이 기술을 배양한 후 이를 직업 생활의 핵심으로 삼는 소수는 번창할 것이다.

이 책은 두 가지 목표를 가지고 있으며 두 부분으로 구성되어 있습니다. 첫 번째는 1부에서 다룬 것으로 심층 작업 가설이 사실임을 확신시키는 것이다. 2부에서 다룬 두 번째는 두뇌를 훈련시키고 업무 습관을 변형시켜 심층적인 일을 직업 생활의 핵심에 두어 이러한 현실을 활용하는 방법을 알려주는 것이다. 그러나 이러한 세부 사항에 들어가기 전에 어떻게 깊이의 열중자가 되었는지 설명하는 데 잠시 시간을 할애할 것이다.

나는 지난 10년 동안 어려운 일에 집중하는 능력을 키워왔다. 이러한 관심의 기원을 이해하기 위해서는 내가 MIT의 유명한 컴퓨팅 이론 그룹에서 박사 교육을 수행한 이론 컴퓨터 과학자라는 것을 아는 것이 도움이 된다.

이 기간 동안, 나는 합법적으로 술을 마실 수 있을 만큼 나이가 들기 전에 MIT에 고용된 맥아더 "천재" 수혜자 교수로부터 복도 아래 대학원생 사무실을 공유했다. 이 이론가도 공용 공간에 앉아 화이트보드에 표시된 표시를 응시하고 그를 둘러싼 방문 학자 그룹이 조용히 앉아 응시하는 것을 발견하는 것은 드문 일이 아니었다. 몇 시간 동안 계속될 수 있어요. 나는 점심을 먹으러 갈 것이고 나는 돌아와 여전히 쳐다볼 것이다. 이 특정 교수님은 연락하기 어렵습니다. 그는 트위터에 있지 않으며 당신을 모르는 경우 귀하의 이메일에 답장할 가능성이 낮습니다. 작년에는 16편의 논문을 발표했습니다.

이러한 치열한 집중은 학생 시절에 대기에 스며들었다. 당연히 나는 곧 깊이에 대한 유사한 의지를 갖게 되었다. 제 책에서 함께 일한 다양한 홍보가사와 친구 모두의 안타까움을 위해, 저는 페이스북이나 트위터 계정, 블로그 외부의 다른 소셜 미디어에 존재한 적이 없습니다. 나는 웹 서핑을 하지 않으며 집에서 배달되는 워싱턴 포스트와 NPR에서 대부분의 뉴스를 얻는다. 저 또한 일반적으로 연락이 어렵습니다. 저자 웹사이트에는 개인 이메일 주소가 제공되지 않으며 2012년까지 첫 번째 스마트폰을 소유하지 않았습니다.

반면에 깊이에 대한 헌신은 저에게 보상을 주었습니다. 대학 졸업 후 10년간 4권의 책을 출판하고, 박사 학위를 취득하고, 높은 비율로 동료 검토 학술 논문을 작성했으며, 조지타운 대학교의 재임 기간 교수로 채용되었다. 주중 오후 5시나 6시를 넘어서 거의 일하지 않으면서도 이 방대한 생산량을 유지했다.

이렇게 압축된 일정은 내가 삶의 은 부분을 최소화하고 이것이 자유롭게 하는 시간을 최대한 활용하기 위해 상당한 노력을 기울였기 때문에 가능하다. 나는 내 일정을 신중하게 선택한 심층 작업의 핵심으로 만들고 내 일정의 주변에서 더 작은 폭발로 묶인 피상적인 활동을 피할 수 없다. 일주일에 5일씩 하루 3~4시간 동안 중단 없이 주의 깊게 지시된 집중은 많은 가치 있는 산출물을 생산할 수 있는 것으로 나타났다.

깊이에 대한 나의 헌신은 또한 비전문적인 이익을 반환했습니다. 대부분 퇴근 후 퇴근한 시간부터 새로운 근무일이 시작되는 다음날 아침(아이들이 잠자리에 든 후에 쓰는 블로그 글이 주요 예외) 사이에 컴퓨터를 만지지 않는다. 직장에서 단순 이메일 수표를 몰래 몇 번이나 넣거나 SNS를 자주 조회하는 일반적인 관행과 달리, 완전히 연결을 끊을 수 있는 이 능력은 저녁에 아내와 두 아들과 함께 참석하고 바쁜 두 아이의 아버지를 위해 놀라울 정도로 많은 책을 읽을 수 있게 해준다. 더 일반적으로, 내 삶의 산만함의 부족은 사람들의 일상 생활에 점점 더 스며드는 것처럼 보이는 신경 정신 에너지의 배경 을 억제한다. 지루한 것은 편하고 특히 나태한 D.C. 여름 밤에 라디오에서 천천히 펼쳐지는 내셔널스 경기를 듣는 것은 놀랍도록 보람 있는 기술이 될 수 있다.

이 책은 나의 매력을 피상적인 일 이상으로 깊이 있게 형식화하고 설명하고 이 매력에 대해 행동하는 데 도움이 된 전략의 유형을 자세히 설명하려는 시도로 가장 잘 설명된다. 나는 이 생각을 부분적으로 말로 전념하여 심층 작업을 중심으로 삶을 재구성하는 데 있어 나의 선도를 따르도록 했지만 이것이 전체 이야기가 아니다. 이러한 생각을 증류하고 명확히 하는 데 있어 나의 또 다른 관심은 내 자신의 실천을 더욱 발전시키는 것이다. 심층 작업 가설에 대한 나의 인식은 내가 번성하는 데 도움이 되었지만 나는 아직 나의 완전한 가치 생산 잠재력에 도달하지 못했다고 확신한다. 앞으로의 장에서 나온 아이디어와 규칙으로 투쟁하고 궁극적으로 승리할 때, 당신은 내가 그 뒤를 따르고 있다는 확신을 가질 수 있다. (이 책의 결론에서 내가 어떻게 지내고 있는지 알게 될 것이다.)

칼 융은 정신의학 분야에 혁명을 일으키고자 할 때 숲속의 수련소를 지었다. 융의 볼링겐타워는 그가 깊이 생각하는 능력을 유지하고 그 기술을 적용하여 세상을 바꿀 정도로 놀라운 독창성의 작품을 제작할 수 있는 장소가 되었다. 앞으로의 페이지에서 나는 우리 자신의 개인적인 볼링겐 타워를 건설하기 위한 노력에 나와 함께하고, 점점 더 산만해지는 세계에서 진정한 가치를 생산하는 능력을 배양하고, 과거 세대의 가장 생산적이고 중요한 인물이 품은 진리를 인식하도록 설득하려고 노력할 것이다. 깊은 삶은 좋은 삶이다.

# 1부. 왜 딥 워크인가

## 1장. 딥 워크는 가치 있다

2012년 선거일이 다가오면서 뉴욕타임스 웹사이트의 트래픽이 급증했는데, 이는 국가적 중요시의 순간에는 당연한 일이었다. 그런데 이번에는 양상이 달랐다. 일부 보고서에 따르면 이 트래픽의 매우 불균형적인 부분(일부 보고서에 따르면 70%)은 광범위한 도메인의 단일 위치를 방문하고 있었다. 그것은 1면 속보가 아니었고, 이 신문의 퓰리처상 수상 칼럼니스트 중 한 사람의 해설도 아니었으며, 대신 네이트 실버라는 이름의 선거 예측가가 된 야구 통계 괴짜가 운영하는 블로그였다. 1년도 채 되지 않아 ESPN과 ABC 뉴스는 스포츠에서 날씨, 네트워크 뉴스 세그먼트, 아마도 아카데미 시상식 텔레비전에 이르기까지 모든 분야에서 실버 운영에 역할을 부여하는 주요 거래에서 실버를 타임스에서 유인했다. 실버의 손으로 조정된 모델의 방법론적 엄격성에 대한 논쟁이 있지만 2012년에 이 35년 된 데이터 위즈가 우리 경제에서 승리했다는 것을 부인하는 사람은 거의 없다.

또 다른 수상자는 루비 온 레일즈 웹사이트 개발 프레임워크를 만든 컴퓨터 프로그래밍 스타 데이비드 하인마이어 한슨으로, 현재 트위터와 훌루를 포함한 웹에서 가장 인기 있는 목적지의 기반을 제공합니다. 한슨은 영향력 있는 개발기업 베이스캠프(2014년까지 37시그널로 불린다)의 파트너다. 한슨은 베이스캠프나 다른 수익원으로부터 얻은 이익의 크기에 대해 공개적으로 말하지 않지만, 한슨은 시카고, 말리부, 스페인 마르벨라에서 시간을 분할하고 고성능 경주차 운전에 뛰어든다는 점을 감안할 때 수익성이 있다고 가정할 수 있다.

우리 경제에서 확실한 승자의 세 번째이자 마지막 사례는 유명한 실리콘밸리 벤처캐피털 펀드 클라이너 퍼킨스 코필드 & 바이어스의 일반 파트너인 존 도어이다. 도어는 트위터, 구글, 아마존, 넷스케이프, 선마이크로시스템 등 현재 기술혁명을 부추기는 핵심 기업 중 많은 기업에 자금을 지원했다. 이러한 투자에 대한 수익은 천문학적으로 훌륭했으며 이 글을 쓰는 현재 도어의 순 자산은 30억 달러 이상이다.

실버, 한손, 도어가 왜 이렇게 잘했을까. 이 질문에 대한 답은 두 가지 유형이 있다. 첫 번째는 범위가 미시적이며 이 삼중주의의 상승을 주도하는 데 도움이 된 성격 특성과 전술에 중점을 둔다. 두 번째 유형의 답변은 개인에 덜 초점을 맞추고 그들이 나타내는 작업 유형에 더 집중한다는 점에서 더 거시적이다. 이 핵심 질문에 대한 두 가지 접근 방식이 중요하지만 거시적 답변은 현재 경제가 보상하는 바를 더 잘 조명하기 때문에 우리의 논의와 가장 관련이 있는 것으로 판명될 것이다.

이 거시적 관점을 탐구하기 위해 우리는 2011년 영향력 있는 책인 머신에 대항하는 레이스에서 특히 디지털 기술의 부상으로 인해 예상치 못한 방식으로 노동 시장이 변화하고 있다는 강력한 사례를 제시한 MIT 경제학자 에릭 브린졸프슨과 앤드루 맥애피에게 돌아간다. 브린졸프손과 맥애피는 저서 초반에 "우리는 대구조화의 초기 단계에 있다. "우리의 기술은 앞서고 있지만 많은 기술과 조직이 뒤처져 있다." 많은 근로자에게 이러한 지연은 나쁜 소식을 예측한다. 지능형 기계가 향상되고 기계와 인간의 능력 사이의 격차가 줄어들면서 고용주는 "새로운 사람" 대신 "새로운 기계"를 고용할 가능성이 점점 높아지고 있으며 인간만 할 때 통신 및 협업 기술의 개선은 원격 작업을 이전보다 쉽게 만들고 있으며 기업들이 주요 역할을 스타에게 아웃소싱하도록 동기를 부여하여 지역 인재 풀을 고용하지 못하게 하고 있다.

그러나 이러한 현실은 보편적으로 암울하지는 않다. 브린졸프손과 맥아피가 강조하는 것처럼 이번 대구조화는 모든 일자리를 몰아치는 것이 아니라 오히려 분업화하고 있다. 기술이 자동화되거나 쉽게 외주로 공급됨에 따라 이 새로운 경제에서 점점 더 많은 사람들이 손실을 입을 것이지만 생존할 뿐만 아니라 번성하여 이전보다 더 가치 있게(따라서 더 많은 보상을) 될 다른 사람들이 있다. 브린졸프손과 맥애피는 경제에 대한 이 쌍봉 궤적을 제안하는 데 혼자가 아니다. 예를 들어 2013년 조지 메이슨 경제학자 타일러 코웬은 디지털 분할이라는 이 논지를 그대로 반영한 책인 '평균은 넘는다'를 펴냈다. 그러나 브린졸프손과 맥애피의 분석이 특히 유용한 것은 이 구분의 수익성 있는 쪽에 속하고 지능형 기계 시대의 이점을 불균형적으로 수확할 세 가지 특정 그룹을 식별하는 것을 진행한다는 것이다. 당연히 실버, 한손, 도어가 속한 것은 이 세 집단에 속한다. 이 각 그룹을 차례로 다루어 갑자기 왜 그렇게 가치가 있는지 더 잘 이해하도록 하자.

고숙련 노동자

브린졸프손과 맥애피는 네이트 실버가 의인화한 그룹을 '고숙련' 노동자로 부른다. 로봇공학이나 음성인식과 같은 발전은 많은 저숙련 직책을 자동화하고 있지만 이러한 경제학자들이 강조하듯이 "데이터 시각화, 분석, 고속 통신, 신속한 프로토타이핑과 같은 다른 기술은 보다 추상적이고 데이터 기반 추론의 기여를 증가시켜 이러한 직업의 가치를 높였다." 즉, 점점 더 복잡한 기계에서 가치 있는 결과를 작업하고 놀리는 구두 능력을 가진 사람들은 번창할 것이다. 타일러 코웬은 이 현실을 좀 더 밋밋하게 정리하는데, "핵심 질문은 지능형 기계로 일을 잘하느냐, 하지 않느냐"가 될 것이다.

물론 네이트 실버는 데이터를 대형 데이터베이스에 공급한 뒤 이를 그의 신비한 몬테카를로 시뮬레이션으로 빼내는 편안함이 고숙련 노동자의 전형이다. 지능형 기계는 실버의 성공에 장애가 되지 않고 대신 그 전제조건을 제공한다.

슈퍼스타즈.

에이스 프로그래머 데이비드 하인마이어 한슨은 브린졸프슨과 맥애피가 우리의 새로운 경제에서 번창할 것으로 예측하는 두 번째 그룹인 '슈퍼스타'의 예를 제공한다. 고속 데이터 네트워크와 이메일 및 가상 회의 소프트웨어와 같은 협업 도구는 지식 업무의 많은 부문에서 지역주의를 파괴했다. 예를 들어, 한슨과 같은 세계 최고의 프로그래머 중 한 명에게 당면한 프로젝트를 완료하기에 충분한 시간만큼의 비용을 지불할 수 있는 대신 전업 프로그래머를 고용하고 사무실 공간을 제쳐두고 혜택을 지불하는 것은 더 이상 의미가 없다. 이 시나리오에서 당신은 아마도 적은 돈에 더 나은 결과를 얻을 것이고 반면 Hansson은 연간 더 많은 고객에게 서비스를 제공할 수 있으므로 결국 더 나은 결과를 얻을 것이다.

Hansson이 스페인 Marbella에서 원격으로 일하고 있지만 귀하의 사무실이 Iowa Des Moines에 있다는 사실은 통신 및 협업 기술의 발전으로 인해 프로세스가 거의 원활하게 이루어지기 때문에 귀하의 회사에는 중요하지 않습니다. (그러나 이 현실은 데스모인스에 거주하고 꾸준한 급여를 필요로 하는 덜 숙련된 지역 프로그래머에게 중요하다.) 이 같은 경향은 컨설팅, 마케팅, 글쓰기, 디자인 등 생산적인 원격 작업을 가능하게 하는 기술이 증가하는 분야에도 적용된다. 일단 인재 시장이 보편적으로 접근 가능하게 되면 시장의 정점에 있는 사람들은 번성하고 나머지는 고통받는다.

1981년 경제학자 셔윈 로젠은 중요한 논문에서 이러한 "승자-전체-취하" 시장의 뒷면에 있는 수학을 연구했다. 그의 핵심 통찰력 중 하나는 "불완전한 대체"를 가진 요인으로 공식에 변수 q를 사용하여 무해하게 표지된 인재를 명시적으로 모델링하는 것이었는데, 로젠은 다음과 같이 설명한다. "보통한 가수의 연속을 듣는 것은 하나의 뛰어난 성과에 합산되지 않는다." 즉, 인재는 필요한 수준에 도달하기 위해 대량으로 구매하고 결합할 수 있는 상품이 아니다. 최고라는 프리미엄이 있다. 따라서 소비자가 모든 연주자에게 접근할 수 있고 모든 사람의 q 가치가 명확한 시장에 있다면 소비자는 최고의 것을 선택할 것이다. 실력 사다리 아래로 내려간 다음 단계에 비해 최고층의 인재 우위가 작더라도 여전히 슈퍼스타들이 시장의 대부분을 차지한다.

로젠은 1980년대 이 같은 효과를 연구할 때 뮤직 스토어나 영화관 등 명확한 시장이 존재하고 관객이 서로 다른 공연자에게 접근할 수 있고 구매 결정을 내리기 전에 그들의 재능을 정확하게 추정할 수 있는 영화배우나 뮤지션과 같은 사례에 초점을 맞췄다. 통신 및 협업 기술의 급속한 부상으로 인해 이전에는 다른 많은 지역 시장이 유사하게 보편적인 바자회로 변모했다. 컴퓨터 프로그래머나 홍보 컨설턴트를 찾는 소규모 회사는 이제 레코드 스토어의 출현으로 소도시 음악 팬이 세계 최고의 밴드의 앨범을 구입하기 위해 지역 음악가를 우회할 수 있었던 것과 같은 방식으로 국제적인 인재 시장에 접근할 수 있다. 즉, 슈퍼스타 효과는 로젠이 30년 전에 예측할 수 있었던 것보다 오늘날 더 광범위하게 적용된다. 우리 경제에서 점점 더 많은 사람들이 이제 그들의 부문의 록 스타들과 경쟁하고 있습니다.

주인분들.

우리의 새로운 경제에서 번창할 마지막 그룹(존 도어에 의해 구체화된 그룹)은 대구조화를 주도하는 새로운 기술에 투자할 자본을 가진 사람들로 구성된다. 마르크스 이래로 이해한 바와 같이 자본에 대한 접근은 엄청난 이점을 제공한다. 그러나 어떤 기간은 다른 기간보다 더 많은 이점을 제공하는 것도 사실이다. 브린졸프손과 맥애피가 지적하듯이, 전후 유럽은 급격한 인플레이션과 공격적인 세금의 조합이 놀라운 속도로 오래된 부를 쓸어버렸기 때문에 현금 더미 위에 앉기 어려운 시기의 한 예였다(우리가 "다운턴 애비 효과"라고 부를 수 있다).

대구조화는 전후기와 달리 특히 자본에 접근하기 좋은 시기이다. 그 이유를 이해하기 위해 우선 표준 경제 사고의 핵심 요소인 교섭 이론이 자본 투자와 노동의 결합을 통해 돈이 만들어지면 투입된 것에 대략적으로 비례하여 보상이 반환된다고 주장한다는 것을 상기하자. 디지털 기술이 많은 산업에서 노동의 필요성을 줄여주면서 지능형 기계를 소유한 사람에게 돌아가는 보상의 비중이 커지고 있다. 오늘날의 경제에서 벤처 자본가는 인스타그램과 같은 회사에 자금을 조달할 수 있는데, 인스타그램은 결국 10억 달러에 팔렸지만 고용자는 13명에 불과하다. 역사상 언제쯤 이렇게 적은 양의 노동이 이렇게 많은 양의 가치에 관여할 수 있었을까? 노동의 투입이 거의 없는 상황에서 기계 소유주(이 경우 벤처 투자자)에게 다시 흘러가는 이 부의 비율은 전례가 없다. 내가 마지막 책을 위해 인터뷰한 한 벤처캐피탈리스트가 '모두가 내 직업을 원한다'는 것에 대해 약간의 우려를 표명한 것은 놀라운 일이 아니다.

지금까지 돌아온 실을 정리해 보겠습니다. 현재 경제학적 사고는 내가 조사한 바와 같이 기술의 전례 없는 성장과 영향이 우리 경제의 대규모 구조 조정을 만들고 있다고 주장한다. 이 새로운 경제에서 지능형 기계로 잘하고 창의적으로 일할 수 있는 사람, 자신이 하는 일에 최고인 사람, 자본에 접근할 수 있는 사람 등 세 집단이 특별한 이점을 갖게 될 것이다.

분명히 말해서, 브린졸프슨, 맥애피, 코웬과 같은 경제학자들이 확인한 이 대구조화는 현재로서는 중요한 유일한 경제 동향이 아니며, 앞서 언급한 세 그룹만이 잘할 유일한 그룹은 아니지만, 이 책의 주장에서 중요한 것은 이러한 경향이 단독이 아니더라도 중요하다는 것이며, 이러한 그룹은 단독이 아니더라도 번창할 것이라는 것이다. 따라서 이러한 그룹에 참여할 수 있다면 잘할 것입니다. 못하면 그래도 잘할 수도 있지만 당신의 입지는 더 위태롭다.

우리가 지금 직면해야 하는 질문은 명백한 질문이다: 어떻게 이 수상자들과 함께 할 수 있는가? 나는 당신의 높아지는 열정을 잠재울 위험을 무릅쓰고 먼저 자본을 빠르게 쌓아 차기 존 도어가 되는 비결이 없다는 것을 고백해야 한다. (내가 그런 비밀을 갖고 있었다면, 나는 그것을 책에 공유할 것 같지 않다.) 그러나 다른 두 개의 승리 그룹은 접근할 수 있습니다. 그들에게 접근하는 방법은 우리가 다음으로 해결해야 할 목표입니다.

### 새로운 경제에서 승자가 되는 법

나는 이제 막 두 개의 그룹을 식별했는데, 두 그룹은 번창할 준비가 되어 있고 접근 가능하다고 주장합니다. 지능형 기계와 창의적으로 일할 수 있는 그룹과 해당 분야의 스타입니다. 디지털 격차가 확대되는 이 수익성 있는 부문에 착륙하는 비결은 무엇인가? 나는 다음 두 가지 핵심 능력이 중요하다고 주장한다.

새로운 경제에서 번창하기 위한 두 가지 핵심 능력

1. 복잡하고 어려운 일을 빠르게 마스터하는 능력.
2. 품질과 속도 양면에서 최고 수준(엘리트 레벨)의 성과를 창출하는 능력.

첫 번째 능력부터 시작하겠습니다. 우선, 우리는 트위터와 아이폰과 같은 많은 소비자 대면 기술의 직관적이고 드롭 데드-단순한 사용자 경험에 의해 상하게 되었음을 기억해야 한다. 그러나 이러한 예는 심각한 도구가 아닌 소비자 제품이며 대구조화를 주도하는 대부분의 지능형 기계는 이해하고 마스터하는 데 훨씬 더 복잡하다.

복잡한 기술로 잘 일하며 번창하는 사람의 초기 예인 네이트 실버를 생각해 보자. 그의 방법론에 더 깊이 들어가면 데이터 기반의 선거 예측을 생성하는 것이 검색창에 "누가 더 많은 표를 얻을 것인가?"를 입력하는 것만큼 쉽지 않다는 것을 알게 된다. 그는 대신 스타타코프라는 회사가 생산하는 인기 있는 통계 분석 시스템인 스타타에 공급하는 대규모 여론조사 결과 데이터베이스(250명 이상의 여론조사자 수천 건)를 유지하고 있다. 숙달하기 쉬운 도구가 아닙니다. 예를 들어 Silver이 사용하는 현대 데이터베이스에서 작업하려면 알아야 할 명령 유형이 다음과 같습니다.

도시 선택 이름, 인구, 고도로부터의 연합 선택 이름, 인구, 고도로부터의 도시를 선택하기 위한 뷰를 생성한다.

이러한 유형의 데이터베이스는 SQL이라는 언어로 질문된다. 당신은 저장된 정보와 상호 작용하기 위해 여기에 표시된 것과 같은 명령을 그들에게 보낸다. 이러한 데이터베이스를 조작하는 방법을 이해하는 것은 미묘합니다. 예시적인 명령은 예를 들어, "view"를 생성하는데, 이는 다수의 기존 테이블로부터 데이터를 함께 끌어들이는 가상 데이터베이스 테이블이며 이는 표준 테이블과 같이 SQL 명령에 의해 처리될 수 있다. 언제 뷰를 생성하고 어떻게 잘 만들지라는 것은 까다로운 질문이며 실제 데이터베이스에서 합리적인 결과를 도용하기 위해 이해하고 마스터해야 하는 많은 질문 중 하나이다.

네이트 실버 사례 연구를 고수하면서 그가 의존하는 다른 기술인 스타타를 고려해보자. 이것은 강력한 도구이며 약간의 조기를 한 후에 직관적으로 배울 수 있는 것은 절대 아닙니다. 예를 들어, 이 소프트웨어의 가장 최신 버전에 추가된 기능에 대한 설명이 있습니다. "Stata 13은 처리 효과, 다단계 GLM, 전력 및 샘플 크기, 일반화된 SEM, 예측, 효과 크기, 프로젝트 관리자, 긴 문자열 및 BLOB 등과 같은 많은 새로운 기능을 추가합니다." 실버는 일반화된 SEM 및 BLOB와 함께 복잡한 소프트웨어를 사용하여 맞물림 부분: 다중 회귀를 사용하여 사용자 지정 매개변수에 대해 수행한 다음 확률적 표현에 사용되는 사용자 지정 가중치로 참조하는 복잡한 모델을 구축합니다.

이러한 세부 사항을 제공하는 목적은 지능형 기계가 복잡하고 숙달하기 어렵다는 점을 강조하는 것이다. 따라서 이러한 기계로 잘 작업할 수 있는 그룹에 합류하려면 어려운 것을 마스터하는 능력을 연마해야 합니다. 그리고 이러한 기술들은 빠르게 변화하기 때문에, 어려운 것을 마스터하는 이 과정은 결코 끝나지 않습니다. 당신은 그것을 다시, 다시, 다시 빨리 할 수 있어야 합니다.

물론 어려운 것을 빨리 배우는 이러한 능력은 지능형 기계와 잘 작동하는 데만 필요한 것이 아니라 기술과 거의 관련이 없는 분야에서도 거의 모든 분야에서 슈퍼스타가 되려는 데 핵심적인 역할을 한다. 예를 들어, 세계적인 요가 강사가 되기 위해서는 점점 더 복잡한 신체 기술을 마스터해야 합니다. 의학의 특정 분야에서 탁월하기 위해서는 다른 예를 들자면 관련 절차에 대한 최신 연구를 빠르게 마스터할 수 있어야 한다. 이러한 관찰을 좀 더 간결하게 정리하자면, 학습하지 못하면 번성할 수 없다.

이제 앞서 보여준 목록에서 두 번째 핵심 능력인 엘리트 수준의 생산을 생각해 보자. 슈퍼스타가 되고 싶다면 관련 기술을 익히는 것은 필요하지만 충분하지 않습니다. 그런 다음 잠재된 잠재력을 사람들이 중요하게 생각하는 유형적인 결과로 변환해야 합니다. 예를 들어 많은 개발자들이 컴퓨터를 잘 프로그래밍할 수 있지만 일찍이 우리의 예시적인 슈퍼스타인 데이비드 핸슨은 그의 명성을 얻은 프로젝트인 루비 온 레일을 생산하기 위해 이 능력을 활용했다. 루비 온 레일즈는 한손이 현재 자신의 실력을 한계로 밀어내고 분명하게 가치 있고 구체적인 결과를 만들어내야 했다.

이러한 생산 능력은 지능형 기계를 마스터하려는 사람들에게도 적용됩니다. 네이트 실버가 대규모 데이터 세트를 조작하고 통계 분석을 실행하는 방법을 배우는 것만으로는 충분하지 않았으며 그런 다음 그는 이 기술을 사용하여 많은 청중이 관심을 갖는 이러한 기계에서 정보를 놀릴 수 있음을 보여줘야 했다. 실버는 야구 프로스펙터스에서 일하던 시절 많은 통계 괴짜들과 함께 일했지만 이 기술을 새롭고 더 수익성이 높은 선거 예측의 영역에 적응시키기 위해 노력한 사람은 실버 혼자였다. 이것은 우리 경제에서 승자의 대열에 합류하기 위한 또 다른 일반적인 관찰을 제공하며 당신이 아무리 숙련되거나 재능이 있더라도 생산하지 않으면 번성하지 않을 것이다.

기술로 혼란을 겪는 새로운 세계에서 앞서 나가기 위해 기본이 되는 두 가지 능력을 확립한 우리는 이제 명백한 후속 질문을 할 수 있다. 여기에서 우리는 이 책의 중심 논지에 도달하는데, 방금 설명한 두 가지 핵심 능력은 심층 작업을 수행하는 능력에 달려 있다. 이 기초 기술을 익히지 못한다면, 당신은 어려운 것을 배우거나 엘리트 수준에서 생산하기 위해 고군분투할 것이다.

이러한 능력이 심층 작업에 의존하는 것은 즉시 명백한 것이 아니며 학습, 집중 및 생산성의 과학을 자세히 살펴야 한다. 앞의 섹션에서는 이러한 면밀한 모습을 제공하며 그렇게 함으로써 심층 작업과 경제적 성공 사이의 이러한 연결이 예상치 못한 것에서 비난할 수 없는 것으로 전환되는 데 도움이 될 것입니다.

### 딥 워크는 어려운 일을 빠르게 배우도록 돕는다

"주의의 수렴하는 광선 덕분에 당신의 마음이 렌즈가 되도록 하라; 당신의 영혼은 지배적이고 완전히 흡수되는 아이디어로서 당신의 마음에 확립된 무엇이든 모든 것에 집중하게 하라."

이 조언은 도미니카 수도승이자 도덕 철학 교수인 안토닌-달마세 세르틸랑제스가 20세기 초에 '지적 생명'이라는 얇지만 영향력 있는 책을 저술한 데서 나온 것이다. 세르틸랑스는 이 책을 사상의 세계에서 생계를 유지하도록 소명된 사람들을 위한 '마음의 발달과 심화'에 대한 지침서로 썼다. 세르틸랑즈는 지적 생활 전반에 걸쳐 복잡한 자료를 숙달해야 할 필요성을 인식하고 독자가 이 도전에 대비하도록 돕는다. 이 때문에 그의 책은 사람들이 어떻게 열심히(인지) 기술을 빨리 마스터하는지 더 잘 이해하기 위한 우리의 탐구에 유용하다는 것을 증명한다.

세르틸랑게스의 충고를 이해하기 위해 앞서 인용한 내용으로 돌아가 보자. 지적 생활에서 여러 형태로 울려 퍼지는 이 말에서 세르틸랑즈는 자신의 분야에 대한 이해를 발전시키기 위해서는 관련 주제를 체계적으로 다루어야 하며 각각의 잠재된 진실을 발견할 수 있도록 "수렴되는 주의 광선"을 허용한다고 주장한다. 즉, 그는 배우기 위해서는 강렬한 집중이 필요하다. 이 아이디어는 그 시간보다 앞선 것으로 밝혀졌습니다. 1920년대 정신의 삶을 성찰하면서 세르틸랑스는 학계가 공식화하는데 70년이 더 걸릴 인지적으로 까다로운 과제를 마스터하는 것에 대한 사실을 발견했다.

이러한 형식화의 과제는 1970년대 들어서면서 본격적으로 시작되었는데, 때로는 수행 심리학이라고 불리는 심리학의 한 분야가 (다양한 분야의) 전문가를 다른 모든 사람들과 구별하는 것이 무엇인지 체계적으로 탐구하기 시작하였다. 1990년대 초, 플로리다 주립대학의 K. 안데르스 에릭슨 교수는 증가하는 연구 문헌과 일치하는 이러한 가닥을 하나의 일관된 답변으로 끌어 모았으며 그는 의도적인 연습이라는 펀치한 이름을 부여했다.

에릭슨은 "우리는 이러한 차이들[전문 연주자와 정상 성인들 사이의]이 불변하다는 것을 부인한다... 대신에, 우리는 전문가 연주자와 정상 성인 사이의 차이들이 특정 영역에서 성과를 향상시키기 위한 의도적인 노력의 평생을 반영한다고 주장한다."라는 강력한 주장으로 이 주제에 대한 그의 획기적인 논문을 시작한다.

특히 미국 문화는 신동에 관한 이야기를 좋아합니다. 영화 《굿 윌 헌팅》에서 맷 데이먼이 연기한 주인공 윌은 세계 최고의 수학자들이 쩔쩔매는 난제를 단숨에 풀어내며 "이게 나한테 얼마나 쉬운지 알아요?"라고 외치죠. 에릭슨이 추진하고 현재 널리 받아들여지고 있는(주의사항\*을 포함) 연구 라인은 이러한 신화를 불안정하게 만든다. 인지적으로 까다로운 작업을 마스터하려면 이러한 특정 형태의 연습이 필요하며 천연 재능에 대한 예외는 거의 없다. (이 점에서도 세르틸랑게스는 "천재의 인간 스스로가 자신의 전량을 보여주기로 한 지점에 모든 힘을 들여와야 위대했다."라고 지적 생활에서 주장하면서 그의 시대를 앞서 있었던 것으로 보인다.

이것은 우리에게 실제로 어떤 고의적인 실천이 요구되는지에 대한 질문으로 이어진다. 그것의 핵심 구성 요소는 일반적으로 다음과 같이 식별된다: 주의가 향상시키려고 하는 특정 기술 또는 마스터하려고 하는 아이디어에 집중된다; 피드백을 받아 접근법을 수정하여 주의를 가장 생산적인 곳에 정확히 유지한다. 첫 번째 구성 요소는 주의 분산과 함께 의도적인 연습이 존재할 수 없으며 대신 중단되지 않은 집중이 필요함을 강조하기 때문에 우리의 논의에 특히 중요하다. 에릭슨이 강조하듯이, "확산된 주의는 고의적 실천이 요구하는 집중된 주의와 거의 대립한다"(내 강조).

심리학자로서 에릭슨과 그의 분야의 다른 연구자들은 고의적인 실천이 왜 작동하는지에 관심이 없으며 단지 효과적인 행동으로 식별하고 있다. 그러나 에릭슨이 이 주제에 대한 첫 번째 주요 논문을 발표한 이후 수십 년 동안 신경 과학자들은 사람들의 어려운 작업에 대한 개선을 주도하는 물리적 메커니즘을 탐구해 왔다. 저널리스트 다니엘 코일이 2009년 저서인 재능 코드에서 조사한 바와 같이, 이 과학자들은 그 해답이 뉴런 주위에 성장하는 지방 조직 층인 미엘린을 포함하고 있으며 세포가 더 빠르고 깨끗하게 발화할 수 있도록 하는 절연체처럼 작용한다고 점점 더 믿고 있다. 개선에 있어서의 수초의 역할을 이해하기 위해서는 지적이든 신체적이든 기술이 결국 뇌 회로로 축소된다는 것을 명심해야 한다. 이 새로운 성능 과학은 당신이 관련 뉴런 주위에 더 많은 수초를 발달시키면서 더 쉽고 효과적으로 해당 회로가 발사할 수 있게 할수록 기술에서 더 좋아진다고 주장한다. 어떤 일을 잘한다는 것은 잘 수초화되는 것이다.

이러한 이해는 숙의적 실천이 왜 효과가 있는지에 대한 신경학적 토대를 제공하기 때문에 중요하다. 특정 기술에 집중함으로써, 당신은 특정 관련 회로가 고립되어서 계속해서 발사하도록 강요하고 있다. 특정 회로를 반복적으로 사용하면 희소돌기세포라고 하는 세포가 회로의 뉴런 주위에 수초층을 감싸기 시작하여 기술을 효과적으로 강화한다. 따라서 주의 분산을 피하면서 당면한 작업에 집중하는 것이 중요한 이유는 이것이 유용한 골수 분해를 유발할 만큼 관련 신경 회로를 격리하는 유일한 방법이기 때문이다. 반대로, 당신이 낮은 집중 상태에서 복잡한 새로운 기술(예컨대, SQL 데이터베이스 관리)을 배우려고 시도한다면(아마도 페이스북 피드도 열어두었을 수도 있다), 당신은 실제로 강화하고 싶은 뉴런 그룹을 분리하기 위해 너무 많은 회로를 동시에 무작위로 발사하고 있다.

안토닌-달마세 세르틸랑게스가 주의 광선을 집중하기 위해 마음을 렌즈처럼 사용하는 것에 대해 처음 쓴 이후로 지난 세기 동안 우리는 이 높은 비유에서 올리고덴드로사이트 세포의 관점에서 표현된 확실히 덜 시적인 설명으로 발전했다. 그러나 사고에 대한 이러한 사고의 순서는 피할 수 없는 결론을 가리키는데, 어려운 것을 빨리 배우려면 주의가 산만하지 않고 집중해야 한다. 학습하는 것은, 다시 말해, 딥 워크의 행위이다. 깊숙이 들어가기 편하다면 우리 경제에서 번창하는 데 필요한 점점 더 복잡한 시스템과 기술을 익히는데 편할 것이다. 대신 깊이가 불편하고 산만함이 도처에 있는 많은 사람들 중 한 명으로 남아 있다면 이러한 시스템과 기술이 쉽게 당신에게 다가올 것으로 기대해서는 안 된다.

### 딥 워크는 최고 수준의 성과를 창출하게 한다

애덤 그랜트는 엘리트 수준에서 제작을 합니다. 내가 2013년 그랜트를 만났을 때, 그는 펜실베니아의 와튼 경영대학원 재직기간을 수여받은 최연소 교수였다. 1년 후, 이 장을 쓰기 시작했을 때(그리고 제 자신의 재임 과정에 대해 생각하기 시작했음), 주장이 업데이트되었다: 그는 현재 와튼의 가장 어린 정교수\*이다.

그랜트가 학계의 한 구석에서 이렇게 빨리 진출한 이유는 간단하게, 그가 생산한다는 것이다. 그랜트는 2012년에 주요 학술지에 7개의 기사를 발표했다. 이것은 그의 분야(교수들이 혼자 또는 소규모 전문 협업으로 일하는 경향이 있고 그들의 연구를 지원할 대규모 학생 팀과 포닥이 없는)에 대해 터무니없이 높은 비율이다. 2013년에는 이 수가 5명으로 감소했다. 이는 여전히 터무니없이 높지만 그의 최근 기준에는 미치지 못한다. 그러나 그는 같은 해 비즈니스 관계 연구에 대한 일부 연구를 대중화한 Give and Take라는 책을 출판했기 때문에 이 dip에 대해 사과할 수 있습니다. 이 책이 성공적이었다고 말하는 것은 과소평가입니다. 뉴욕타임스 매거진 표지에 실렸고 이후 대대적인 베스트셀러가 되었습니다. 그랜트는 2014년 정교수를 수상했을 때 베스트셀러 책 외에 이미 60여 권의 동료 검토 출판물을 집필했다.

내 마음속의 학문적 경력인 그랜트를 만난 직후, 나는 그에게 그의 생산성에 대해 묻지 않을 수 없었다. 다행히 그 주제에 대한 자신의 생각을 기꺼이 공유해주셨다. 그랜트는 엘리트 수준에서 생산하는 역학에 대해 많은 생각을 하는 것으로 드러났다. 그는 예를 들어, 그가 자신의 분야에서 다른 여러 교수들과 함께 참석한 워크숍의 파워포인트 슬라이드 모음을 나에게 보냈다. 행사는 최적의 비율로 학술작품을 어떻게 제작할 것인가에 대한 자료 중심의 관찰에 초점을 맞추었다. 이 슬라이드에는 계절별 시간 할당의 자세한 파이 차트, 공동 저자와의 관계 개발을 캡처하는 흐름도, 20개 이상의 제목이 있는 제안된 읽기 목록이 포함되었다. 이 경영학 교수들은 책에 실직되고 가끔 큰 아이디어에 걸려 넘어지는 무심한 학문가의 진부함을 살지 않는다. 그들은 생산성을 체계적으로 해결해야 할 과학적 문제로 보고 있는데, 이는 애덤 그랜트가 달성한 목표인 것 같다.

그랜트의 생산성은 많은 요인에 의존하지만 특히 그의 방법의 중심으로 보이는 한 가지 아이디어가 있는데, 그것은 힘들지만 중요한 지적 작업을 중단 없이 길게 묶는 것이다. 그랜트는 이 배치 작업을 여러 레벨에서 수행합니다. 한 해 안에 그는 자신의 가르침을 가을 학기에 쌓아두며 그 기간 동안 그는 자신의 모든 관심을 잘 가르치고 학생들에게 다가갈 수 있게 할 수 있다. (그랜트는 현재 와튼에서 최고 등급의 교사이며 여러 교직상 수상자이기 때문에 이 방법이 효과가 있는 것 같다.) 그랜트는 가을에 자신의 가르침을 일괄화함으로써 봄과 여름에 자신의 관심을 연구에 완전히 돌릴 수 있고 덜 산만하게 이 일을 다룰 수 있다.

그랜트는 또한 더 작은 시간 규모에서 그의 관심을 집중시킨다. 그는 연구에 전념하는 한 학기 동안 학생과 동료에게 자신의 문이 열려 있는 기간과 한 가지 연구 과제에 완전히 주의를 산만하게 할 수 있도록 자신을 고립시키는 기간을 번갈아 가며 공부한다. (그는 통상적으로 학술 논문의 작성을 자료 분석, 전체 초안 작성, 초안 편집 등 세 가지 개별 작업으로 나눈다. 최대 3~4일 동안 지속될 수 있는 이 기간 동안 그는 종종 사무실 밖 자동 응답기를 이메일에 올려서 통신원이 응답을 기대하지 않는 것을 알 수 있다. 그는 "언제나 동료들을 혼란스럽게 한다"고 말했다. "그들은 "너는 퇴근한 것이 아니라 지금 당신 사무실에서 당신을 본다!"라고 하지만 그랜트에게 있어서는 그가 당면한 작업을 완료할 때까지 엄격한 격리를 시행하는 것이 중요하다.

제 추측은 애덤 그랜트가 엘리트 연구 기관의 평균적인 교수보다 실질적으로 더 많은 시간을 일하지는 않지만(일착주의에 취약한 그룹인 것이 일반적이라) 그는 여전히 그의 분야에서 다른 누구보다 더 상당한 작업을 생산할 수 있다는 것이다. 나는 배치에 대한 그의 접근법이 이 역설을 설명하는 데 도움이 된다고 주장한다. 특히 그는 그의 작업을 강렬하고 중단되지 않는 펄스로 통합함으로써 다음의 생산성 법칙을 활용하고 있다.

고품질 작품 제작 = (시간 소비) x (포커스의 강도)

이 공식을 믿으면 그랜트의 습관은 의미가 있는데, 그랜트는 일할 때 강도를 극대화함으로써 일하는 시간 단위당 자신이 생산하는 결과를 극대화한다.

생산성에 대한 이런 공식적 개념을 접한 것은 이번이 처음이 아니다. 그것은 몇 년 전 제2책 '직선학생이 되는 법'을 연구할 때 처음 눈에 띄었다. 그 연구 과정에서 나는 미국에서 가장 경쟁력 있는 학교의 초고점 대학 학부생 50명 정도를 인터뷰했다. 이 인터뷰에서 내가 주목한 것은 최고 학생이 GPA 순위에서 바로 아래 학생 그룹보다 적게 공부하는 경우가 많다는 것이다. 이 현상에 대한 설명 중 하나는 앞서 설명한 공식으로 밝혀졌는데, 최고의 학생들은 생산성에서 역할 강도가 작용하는 것을 이해했기 때문에 결과의 질을 떨어뜨리지 않으면서 시험 준비나 논문 작성에 필요한 시간을 급격히 줄이는 등 집중력을 극대화하기 위해 노력했다.

Adam Grant의 사례는 이 강도 공식이 학부 GPA를 넘어 다른 인지적으로 까다로운 작업과도 관련이 있음을 의미한다. 그런데 이게 왜 그럴까요? 흥미로운 설명은 소피 레로이 미네소타대 경영학 교수로부터 나온다. 2009년 논문에서 흥미롭게도 내 일을 하는 것이 왜 그렇게 어려운가? 라는 제목의 레로이는 그녀가 주의 잔여물이라고 부르는 효과를 소개했다. 그녀는 이 논문의 서론에서 다른 연구자들이 멀티태스킹(다중 작업을 동시에 수행하려고 노력함)이 성과에 미치는 영향을 연구했지만 현대 지식 작업 사무실에서 충분히 높은 수준에 도달하면 여러 프로젝트를 수행하는 사람들을 순차적으로 찾는 것이 더 일반적이었다고 언급했다. "한 회의에서 다음 회의로 이동하여 한 프로젝트에서 작업을 시작하고 곧 다른 프로젝트로 전환해야 하는 것은 조직에서 삶의 일부일 뿐"이라고 르로이는 설명한다.

이 연구가 이 작업 전략에서 확인하는 문제는 어떤 작업 A에서 다른 작업 B로 전환할 때 주의가 즉시 따라오지 않는다는 것입니다. 이 잔여물은 전환하기 전에 작업 A에 대한 작업이 제한이 없고 강도가 낮으면 특히 두꺼워지지만 작업 A를 종료한 후 작업 A를 넘어가더라도 잠시 동안 주의가 분할된다.

레로이는 실험실에서 작업 전환을 강제하여 성능에 대한 이 주의 잔류물의 영향을 연구했다. 예를 들어, 그러한 실험 중 하나에서 그녀는 피험자들이 단어 퍼즐 세트를 작업하기 시작했다. 재판 중 한 번은 그들을 방해하고 이 경우 이력서를 읽고 가상의 채용 결정을 내리는 새롭고 도전적인 작업으로 넘어가야 한다고 말했을 것이다. 다른 실험에서는 피험자들에게 다음 과제를 부여하기 전에 퍼즐을 끝내도록 했다. 그녀는 당황스럽고 고용되는 사이에 첫 번째 작업에서 남은 잔여물의 양을 정량화하기 위해 빠른 어휘 결정 게임을 배치했다. \* 이 실험과 그녀의 유사한 실험의 결과는 분명했는데, "과제를 전환한 후 주의력 잔류물을 경험하는 사람들은 다음 과제에서 성과가 좋지 않을 가능성이 높다"며 잔류물이 강할수록 성과가 좋지 않다.

주의 잔차의 개념은 강도 공식이 왜 참인지 설명하는 데 도움이 되며 따라서 그랜트의 생산성을 설명하는 데 도움이 된다. 그랜트는 전환하지 않고 한 번의 힘든 작업을 오랫동안 수행함으로써 다른 의무로부터 주의 잔여가 받는 부정적인 영향을 최소화하여 이 한 번의 작업에서 성과를 극대화할 수 있다. 그랜트가 논문에서 며칠 동안 고립되어 작업할 때, 다시 말해서 그는 잔류물을 찌르는 중단으로 작업이 반복적으로 중단되는 더 산만한 전략에 따라 표준 교수보다 더 고수준의 효과로 작업하고 있다.

그랜트의 극단적인 고립을 완전히 복제할 수 없더라도(부 2에서 깊이 스케줄링을 위한 다양한 전략을 다룰 것) 주의 잔차 개념은 반 주의 분산 상태에서 일하는 일반적인 습관이 잠재적으로 성과에 파괴적임을 암시하기 때문에 여전히 말해준다. 10분 정도마다 받은 편지함을 한 번만 살펴보는 것은 무해해 보일 수 있습니다. 실제로 많은 사람들은 이 행동을 화면에 항상 받은 편지함을 열어 두는 오래된 관행(더 이상 거의 따르지 않는 빨대꾼 습관)보다 낫다고 정당화한다. 그러나 르로이는 이것이 실제로 큰 개선이 아니라는 것을 우리에게 가르친다. 그 빠른 확인은 당신의 관심을 끌 새로운 대상을 소개합니다. 더 나쁜 것은, 당신이 현재 (거의 항상 그렇듯이) 처리할 수 없는 메시지를 보고 당신은 미완성으로 남겨진 부차적인 과제를 가지고 1차 과제로 돌아가게 될 것이다. 이러한 해결되지 않은 스위치에 의해 남겨진 주의력 잔여물은 성능을 약화시킵니다.

우리가 이러한 개별적인 관찰에서 한 걸음 물러서면 우리는 명확한 논증 형태를 보게 된다: 최고 수준에서 생산하려면 주의 분산이 없는 단일 작업에 완전히 집중하면서 장기간 작업해야 한다. 즉, 성능을 최적화하는 작업 유형은 심층 작업입니다. 장기간 깊이 들어가기가 불편하다면 전문적으로 번창하는 데 점점 더 필요한 품질과 양의 최고 수준으로 성능을 끌어내기 어려울 것이다. 당신의 재능과 기술이 경쟁사보다 절대적으로 더 피상적인 일이 아니라면, 그들 중 깊은 노동자들이 당신을 능가할 것입니다.

### 잭 도시는 예외인가?

나는 이제 심층 작업이 우리 경제에서 점점 더 중요해지고 있는 능력을 지원하는 이유에 대해 내 주장을 했다. 그러나 이 결론을 받아들이기 전에 우리는 이 주제를 논의할 때 자주 발생하는 유형의 질문에 직면해야 한다.

잭 도시는 트위터를 찾는데 도움을 주었습니다. 대표이사직에서 물러난 뒤 결제처리 업체 '스퀘어'를 출범시켰다. 포브스의 프로필을 인용하자면, "그는 대규모의 교란자이며 반복범이다." 그는 심오한 작업의 상태에서 많은 시간을 보내지 않는 사람도 있다. 도르시는 포브스 프로필이 작성될 당시 트위터(회장직을 유지)와 스퀘어 모두에서 경영 업무를 유지했기 때문에 중단되지 않은 장기간의 사유의 사치를 갖지 못했으며 이는 회사가 예측 가능한 "주간 종결"을 보장하는 엄격하게 조정된 일정을 유도합니다.

예를 들어, 도르시는 밤에 검토하고 필터링하는 30~40세트의 회의 메모로 하루를 평균적으로 끝낸다고 보고한다. 그는 이 모든 회의 사이의 작은 공간에서 우연한 가용성을 믿는다. 도어지는 "나는 누구나 올라올 수 있는 입식 테이블에서 상당한 작업을 한다"고 말했다. "회사 주변에서 이런 대화를 모두 듣게 된다."

이런 작업 스타일은 깊지 않습니다. 이전 섹션의 용어를 사용하자면, 도르지의 주의 잔여물은 그가 한 회의에서 다른 회의로 다트를 던지면서 두꺼워질 가능성이 높으며 사람들이 그 사이의 짧은 중간 시간 동안 자유롭게 방해할 수 있다. 그러나 서론에서 정의한 피상적 작업은 가치가 낮고 쉽게 복제할 수 있는 반면 잭 도르시는 우리 경제에서 믿을 수 없을 정도로 가치가 있고 높은 보상을 받고 있기 때문에 도르지의 작업이 다고 말할 수 없습니다.

잭 도시는 우리가 무시할 수 없는 집단, 즉 깊이 없이 번성하는 개인의 예이기 때문에 우리의 논의에 중요하다. 이 섹션의 동기 부여 질문을 제목으로 "잭 도르시는 어떻습니까?"라고 했을 때, 나는 더 일반적인 질문의 구체적인 예를 제공하고 있었다. 이 장을 마무리하기 위해 앞 페이지에서 깊이의 주제에 더 깊이 들어가면서 이 질문이 주의를 끌지 않도록 이 질문을 다루고 싶다.

우선 잭 도시는 대기업(사실 두 회사)의 고위급 임원이라는 점에 유의해야 한다. 그러한 직책을 가진 개인은 깊이 없이 번영하는 사람들의 범주에서 중요한 역할을 하는데, 그러한 경영진의 생활 방식은 유명하고 피할 수 없을 정도로 산만하기 때문이다. 여기 케리 트레이너 비미오 대표가 이메일 없이 얼마나 오래 갈 수 있느냐는 질문에 답하려고 한다. "나는... 음, 낮 시간 대부분 없이, 없이, 없이 좋은 견고한 토요일을 보낼 수 있다.... 그러니까, 확인하겠지만 반드시 응답하지는 않을 것이다."

동시에 물론 이들 임원은 오늘날 미국 경제에서 역사상 어느 때보다 더 나은 보상이 되고 중요시된다. 이러한 엘리트 수준의 경영에서는 Jack Dorsey의 성공이 심도 없이 흔하다. 우리가 이 현실을 규정하고 나면, 우리는 그것이 깊이의 일반적인 가치를 훼손하지 않는다는 것을 상기시키기 위해 뒤로 물러나야 한다. 왜요? 왜냐하면 이러한 임원의 일상에 있어 산만성의 필요성은 그들의 특정 직무에 매우 특이적이기 때문이다. 훌륭한 최고 경영자는 본질적으로 IBM의 Jeopardy! 플레이 왓슨 시스템과 달리 자동화하기 어려운 의사 결정 엔진이다. 그들은 열심히 얻은 경험의 저장소를 구축했으며 시장에 대한 본능을 연마하고 입증했습니다. 그런 다음 전자 메일, 회의, 사이트 방문 등의 형태로 하루 종일 처리하고 조치를 취해야 하는 입력을 제공한다. CEO에게 한 가지 문제에 대해 깊이 고민하는 데 4시간을 할애하라고 요구하는 것은 자신을 가치 있게 만드는 것에 대한 낭비이다. 스마트한 부하 직원 3명을 고용하여 문제를 깊이 생각해보고 그 해결책을 임원에게 가져와 최종 결정을 내리는 것이 좋다.

이 구체성은 주요 기업의 고위 임원이라면 다음 페이지의 조언이 필요하지 않을 수 있음을 말해 주기 때문에 중요하다. 한편, 이러한 임원의 접근 방식을 다른 직무에 대해 외삽할 수 없다는 점도 말해준다. 도르지가 중단을 장려하거나 케리 트레이너가 그의 이메일을 지속적으로 확인한다는 사실이 당신이 그 뒤를 따를 경우 그들의 성공을 공유할 것이라는 것을 의미하지는 않는다.

이 구체성의 법칙은 이 책의 나머지 부분을 읽으면서 떠오르는 유사한 반례에도 적용되어야 한다. 깊이가 중요시되지 않는 우리 경제의 특정 구석이 있다는 것을 지속적으로 기억해야 한다. 임원 외에도 예를 들어 지속적인 연결이 가장 가치 있는 통화인 특정 유형의 판매원 및 로비스트를 포함할 수도 있습니다. 심층이 도움이 되는 분야에서 산만한 성공을 거둔 사람들도 있습니다.

그러나 동시에, 당신의 일을 반드시 심도가 없는 것으로 분류하는 것을 너무 서두르지 마십시오. 현재의 습관이 심층 작업을 어렵게 한다고 해서 이러한 심층 부족이 자신의 일을 잘 수행하는 데 근본적인 것은 아니다. 다음 장에서는 예를 들어, 고객에게 서비스를 제공하기 위해 지속적인 이메일 연결이 필요하다고 확신한 강력한 경영 컨설턴트 그룹의 이야기를 설명합니다. 하버드 교수가 (연구 연구의 일환으로) 더 규칙적으로 연결을 끊도록 강요하자, 그들은 놀랍게도 이 연결이 그들이 가정했던 것만큼 중요하지 않다는 것을 발견했다. 클라이언트는 항상 그들에게 다가갈 필요가 없었고 주의력이 덜 골절되면 컨설턴트로서의 성능이 향상되었다.

마찬가지로, 내가 아는 몇몇 관리자들은 그들이 프로젝트 로그를 방지하면서 팀의 문제에 신속하게 대응할 수 있을 때 그들이 가장 가치가 있다고 설득하려고 노력했다. 그들은 자신의 역할이 반드시 자신의 것을 보호하는 것이 아니라 다른 사람의 생산성을 가능하게 하는 것으로 본다. 그러나 후속 논의에서 이 목표가 실제로 주의를 분해하는 연결을 필요로 하지 않는다는 것이 곧 밝혀졌다. 실제로, 많은 소프트웨어 회사들은 이제 스크럼 프로젝트 관리 방법론을 전개하는데, 이 애드혹 메시징을 규칙적이고, 고도로 구조화되고, 무자비하게 효율적인 상태 회의(대부분 블로비에의 충동을 최소화하기 위해 서 있는 상태로 개최됨)로 대체한다. 이 접근법은 팀이 해결하고 있는 문제에 대해 깊이 생각할 수 있는 관리 시간을 더 많이 확보하여 종종 그들이 생산하는 제품의 전반적인 가치를 향상시킨다.

다시 말해, 심층근로가 우리 경제에서 가치 있는 유일한 기술은 아니며 이러한 능력을 키우지 않고도 잘할 수 있지만 이것이 바람직한 틈새 시장은 점점 더 드물다. 주의 분산이 특정 직업에 중요하다는 강력한 증거가 없는 한, 이 장의 앞부분에서 주장한 이유로 깊이에 대해 진지하게 고려하는 것이 가장 좋다.

## 2장. 딥 워크는 희소하다

2012년 페이스북은 프랭크 게리가 설계한 새로운 본사 계획을 공개했다. 이 새 건물의 중심에는 마크 저커버그 CEO가 '세계 최대 규모의 오픈플랜'이라고 부르는 것이 있는데, 3천 명 이상의 직원이 10에이커의 부지에 퍼져 있는 이동식 가구 작업을 할 것이다. 물론 오픈오피스 개념을 수용한 실리콘밸리 헤비급은 페이스북이 전부가 아니다. 지난 장의 마지막에 만난 잭 도르시는 스퀘어를 수용하기 위해 오래된 샌프란시스코 크로니클 건물을 사들였을 때, 그는 그의 개발자들이 긴 공유 책상 위에 공용 공간에서 작업하도록 공간을 구성했다. 도어지는 "우리는 세렌디피티를 믿기 때문에 사람들이 야외에 머물도록 권장하고 사람들이 서로 새로운 것을 가르치며 걷는 것"이라고 설명했다.

최근 몇 년 동안 또 다른 큰 비즈니스 트렌드는 인스턴트 메시지의 증가입니다. 타임즈 기사는 이 기술이 더 이상 '말이 많은 10대의 지방'이 아니라 이제는 '신생산성 향상과 고객 응대 시간 향상'으로 기업들이 혜택을 볼 수 있도록 돕고 있다고 지적했다. IBM의 선임 제품 관리자는 "IBM 내에서 250만 I.M.를 보냅니다. 매일.

비즈니스 IM 공간에 더 성공적인 최근 진입자 중 하나는 직원들이 단순히 채팅을 넘어 "실시간 협업"에 참여하도록 돕는 실리콘 밸리 스타트업인 홀입니다. Hall을 사용하는 회사에서 일하는 것이 어떤 것인지 설명하는 샌프란시스코 기반 개발자를 알고 있습니다. 그는 "가장 '효율적인' 직원들은 회사 홀 계정에 새로운 질문이나 댓글이 올라오면 화면에 경고를 깜박이게 하는 텍스트 편집기를 설정한다"고 설명했다. 그런 다음 일련의 연습된 키스트로크로 홀로 건너뛰고 생각을 입력한 다음 간신히 일시 중지 없이 코딩으로 다시 뛰어올 수 있다. 제 친구는 속도를 설명할 때 감명받았어요.

세 번째 경향은 모든 유형의 콘텐츠 생산자가 소셜 미디어 존재를 유지하도록 추진하는 것이다. 구시대 미디어 가치의 보루인 뉴욕타임스는 이제 직원들에게 트위터를 권장합니다. 현재 트위터 계정을 유지하는 800명 이상의 작가, 편집자 및 사진 작가가 취한 힌트입니다. 이것은 이상행동이 아니라 오히려 뉴노멀이다. 소설가 조너선 프랜젠이 문학계에서 트위터를 '강압적 전개'라고 부르는 가디언의 글을 쓰자 그는 크게 비웃음과도 맞지 않았다. 온라인 잡지 '슬레이트'는 프랜젠의 불만을 '인터넷에서의 외로운 전쟁'이라고 불렀고 동료 소설가 제니퍼 와이너는 신공화국에 '프랜젠은 1의 범주, 자기에게만 적용될 수 있는 외로운 목소리'라고 주장하는 답변을 썼다. 조나단 프랜젠헤이트스라는 비아냥한 해시태그는 곧 유행이 되었다.

이 세 가지 비즈니스 트렌드는 역설을 강조하기 때문에 언급합니다. 지난 장에서 나는 변화하는 우리 경제에서 딥워크가 그 어느 때보다 가치가 있다고 주장했다. 그러나 이것이 사실이라면 야심 찬 개인뿐만 아니라 직원을 최대한 활용하기를 원하는 조직에서도 이 기술을 장려하는 것을 볼 수 있을 것입니다. 제공된 예시가 강조하는 것처럼, 이것피상적 작업어나지 않는다. 우리가 방금 접한 것처럼 우연한 협력, 신속한 의사 소통, 소셜 미디어에서의 적극적인 존재를 포함하여 비즈니스 세계에서 심층 작업보다 더 중요한 많은 다른 아이디어가 우선시되고 있습니다.

심층 작업에 앞서 많은 경향이 우선시되는 것은 충분히 나쁘지만 부상에 모욕을 더하기 위해 이러한 경향 중 다수는 심층 작업 능력을 적극적으로 감소시킨다. 예를 들어, 열린 사무실은 협업의 더 많은 기회를 만들 수 있지만 사무실 건물의 비밀 생활이라는 제목의 영국 TV 스페셜을 위해 수행된 실험 결과를 인용하기 위해 "대량 산만"의 대가를 치르면서 그렇게 한다. 쇼를 위한 실험을 진행한 신경과학자는 "일단 어떤 일에 뛰어들고 있는데 배경에서 전화기가 울리면 집중하는 것이 망가진다"고 말했다. "당시 의식하지 못함에도 불구하고 뇌는 산만함에 반응한다."

실시간 메시징의 증가에도 유사한 문제가 적용된다. 이론적으로 이메일 받은 편지함은 당신이 그것을 열기로 선택해야만 당신을 주의를 산만하게 할 수 있는 반면, 인스턴트 메신저 시스템은 항상 활성화되어 중단의 영향을 확대한다. 글로리아 마크 어바인 캘리포니아대 정보학과 교수는 주의 분절화 과학의 전문가다. 잘 인용된 연구에서 Mark과 공동 저자들은 실제 사무실의 지식 노동자를 관찰했으며 중단이 짧더라도 작업을 완료하는 데 필요한 총 시간을 상당한 비율만큼 지연시킨다는 것을 발견했다. "이는 피험자들이 매우 해롭다고 보고했다"고 전형적인 학술적 과소 평가로 요약했다.

콘텐츠 제작자를 소셜 미디어에 강요하는 것은 깊이 들어갈 수 있는 능력에도 부정적인 영향을 미친다. 예를 들어, 진지한 기자들은 복잡한 출처에 뛰어들거나 연결 실을 꺼내거나 설득력 있는 산문을 만드는 등 진지한 저널리즘에 집중해야 하며 온라인 티터링의 거품 같은 앞뒤에 참여하기 위해 하루 종일 이러한 깊은 생각을 방해하도록 요청하는 것은 기껏해야 무관한(및 다소 비하적인) 것으로 보이며 최악의 경우 파괴적으로 산만해진다. 존경받는 뉴욕 작가 조지 패커는 자신이 왜 트위터를 하지 않는지에 대한 에세이에서 이 두려움을 잘 포착했다. 도덕적으로 그보다 우월해서가 아니라 내가 감당할 수 없을 것 같아서 두렵다. 나는 내 아들을 굶게 할까 두려워한다." 놀랍게도, 패커는 그 에세이를 쓸 때 그의 책인 풀림을 쓰느라 바빴고, 이 책은 곧바로 나왔고, 소셜 미디어 사용 부족에도 불구하고(혹은 아마도 도움으로) 즉시 국가 도서상을 받았다.

요약하면, 오늘날 비즈니스의 큰 트렌드는 이러한 트렌드에 의해 약속된 이점(예: 증가된 예의성, 요청에 대한 더 빠른 응답 및 더 많은 노출)이 딥 워크에 대한 헌신(예: 어려운 일을 빠르게 배우고 엘리트 수준에서 생산하는 능력)에서 나오는 이점(예: 어려운 일을 빨리 배우고 생산하는 능력)에 의해 틀림없이 왜소화됨에도 불구하고 사람들의 심층 작업을 수행하는 능력을 적극적으로 감소시킨다. 이 장의 목표는 이 역설을 설명하는 것이다. 나는 딥 워크의 희소성은 습관의 근본적인 약점 때문이 아니라고 주장할 것이다. 우리가 왜 일터에서 산만함을 받아들이는지 자세히 살펴보면 그 이유는 종종 지식 작업을 정의하는 모호성과 혼란과 결합된 결함 있는 사고에 기초하여 예상보다 더 자의적인 것임을 알게 될 것이다. 나의 목표는 우리의 현재 주의 분산에 대한 포용이 실제 현상이지만 불안정한 기반 위에 세워져 있으며 당신이 깊은 직업 윤리를 배양하기로 결정하면 쉽게 폐기될 수 있다는 것을 당신에게 확신시키는 것이다.

### 측정의 블랙홀

2012년 가을, 애틀랜틱 미디어의 최고 기술책임자 톰 코크란은 자신이 이메일로 얼마나 많은 시간을 보내는 것 같는지에 대해 경각심을 갖게 되었다. 그래서 그는 좋은 기술자처럼 이 불안을 정량화하기로 결정했다. 자신의 행동을 관찰한 그는 일주일 동안 511개의 이메일 메시지를 받았고 284개의 이메일을 보냈다고 측정했다. 이는 주 5일 근무 기간 동안 하루 평균 약 160개의 이메일을 보낸 것이다. Cochran은 추가 계산을 통해 그가 평균적으로 메시지당 30초만 보낼 수 있다고 하더라도, 이것은 여전히 인간 네트워크 라우터처럼 정보를 이동하는 데 전념하는 거의 하루 1시간 30분까지 더한다고 언급했다. 이것은 그의 직업 설명의 주요 부분이 아닌 것에 많은 시간을 보낸 것처럼 보였다.

코크란은 자신의 실험에 대해 쓴 블로그 글에서 하버드 비즈니스 리뷰에 대해 회고하듯이, 이 간단한 통계는 그가 나머지 회사에 대해 생각하게 했다. 애틀랜틱 미디어의 직원들은 자신이 임용된 전문 업무에 집중하지 않고 정보를 중심으로 이동하는 데 얼마나 많은 시간을 소비하고 있었는가? 이 질문에 답하기로 결정한 코크란은 하루에 보내는 이메일과 이메일당 평균 단어 수에 대한 전사 통계를 수집했다. 그는 그런 다음 이 숫자를 직원의 평균 타이핑 속도, 읽기 속도 및 급여와 결합했다. 그 결과 그는 애틀랜틱 미디어가 사람들에게 이메일을 처리하도록 돈을 지불하기 위해 연간 백만 달러 이상을 지출하고 있다는 것을 발견했으며 모든 메시지가 전송되거나 수신될 때마다 인건비 약 95센트에 회사를 두드린다. 코크란은 "자유롭고 마찰이 없는" 커뮤니케이션 방식은 "소규모 기업인 리어젯을 조달하는 것과 동등한 부드러운 비용을 가졌다"고 요약했다.

톰 코크란의 실험은 겉보기에 무해한 행동의 문자 그대로의 비용에 대한 흥미로운 결과를 산출했다. 하지만 이 이야기의 진짜 중요성은 실험 그 자체이고 특히 그 복잡성이다. 현재 우리의 이메일 습관이 궁극적으로 어떤 영향을 미치는가와 같은 간단한 질문에 답하기는 정말 어려운 것으로 드러났다. 코크란은 전사적인 설문조사를 실시하고 IT 인프라의 통계를 수집해야 했다. 그는 또한 급여 데이터와 타이핑 및 읽기 속도에 대한 정보를 모으고 전체적인 것을 통계 모델을 통해 실행해야 최종 결과를 뱉어내야 했다. 그리고 그 결과도 가변적일 수 있는데, 예를 들어 이 빈번하고 값비싼 이메일 사용으로 인해 비용이 어느 정도 상쇄되었는지 분리할 수 없기 때문이다.

이 예는 잠재적으로 심층 작업을 방해하거나 개선하는 대부분의 행동으로 일반화된다. 우리가 추상적으로 산만함에는 비용이 있고 깊이에는 가치가 있다는 것을 받아들이지만 톰 코크란이 발견한 것처럼 이러한 영향은 측정하기 어렵다. 이는 산만과 깊이와 관련된 습관에만 있는 특성이 아니라 일반적으로 지식 작업이 노동력에 더 복잡한 요구를 할수록 개인의 노력 가치를 측정하기가 더 어려워진다. 프랑스 경제학자 토마스 피케티는 임원 급여의 극단적 증가에 대한 연구에서 이 점을 명시적으로 언급했다. 그의 주장을 주도하는 가능한 가정은 "기업의 산출물에 대한 개인의 기여도를 객관적으로 측정하는 것이 어렵다." 이러한 조치가 없으면 임원의 한계 생산성에 비례하지 않는 임원 급여와 같은 비합리적 결과가 발생할 수 있다. 피케티 이론의 일부 세부 사항은 논란의 여지가 있지만 일반적으로 그의 비평가 중 하나를 인용하자면 개인의 기여도를 측정하기가 점점 더 어렵다는 기본 가정이 "무엇에도 사실"이라고 간주된다.

따라서 깊이 파괴 행동의 하위 영향이 쉽게 감지될 것으로 기대해서는 안 된다. 톰 코크란이 발견했듯이, 그러한 메트릭은 내가 메트릭 블랙홀이라고 부르는 영역인, 쉬운 측정에 저항하는 불투명한 영역에 속한다. 물론 딥워크와 관련된 메트릭을 측정하기 어렵다고 해서 기업이 이를 기각한다는 결론이 자동으로 도출되는 것은 아니다. 우리는 그들의 근본적인 영향을 측정하기 어렵지만 그럼에도 불구하고 우리 비즈니스 문화에서 번성하는 행동의 많은 예를 가지고 있습니다. 예를 들어 이 장을 연 세 가지 추세 또는 토마스 피케티를 혼란스럽게 했던 초대형 임원 급여를 생각해 보세요. 그러나 이를 뒷받침할 명확한 지표가 없으면 모든 비즈니스 행동은 불안정한 변덕과 변화하는 힘에 취약하며 이 변동성이 있는 스크럼 심층 작업은 특히 좋지 않습니다.

이 미터 블랙홀의 현실은 이 장에서 이어지는 논증의 배경이 된다. 이 다음 섹션에서 나는 비즈니스를 딥 워크에서 더 산만하게 만드는 대안으로 밀어낸 다양한 사고방식과 편향을 설명할 것이다. 이러한 행동 중 어느 것도 바닥에 상처를 입는 것이 분명하다면 오래 살아남지 못할 것이지만 메트릭 블랙홀은 이러한 명확성을 방지하고 우리가 점점 더 많은 직업계에서 접하는 산만으로의 이동을 허용한다.

### 최소 저항의 원칙

직장 내에서 받아들여지는 산만 행위에 대해서는 이메일을 읽고(및 관련 커뮤니케이션) 신속하게 응답할 것으로 예상되는, 현재 유비쿼터스화된 연결 문화에 지배적 지위를 부여해야 한다. 이 주제를 연구하면서, 하버드 경영대학원 레슬리 퍼로우 교수는 그녀가 조사한 전문가가 사무실 밖에서 일주일에 약 20~25시간을 보내 이메일을 모니터링하는 것을 발견했으며, 도착 후 1시간 이내에 모든 이메일(내부 또는 외부)에 답하는 것이 중요하다고 믿었다.

당신은 많은 사람들이 그렇듯이 이러한 행동이 많은 빠른 속도로 진행되는 비즈니스에서 필요하다고 주장할 수 있다. 그러나 이것이 흥미로운 부분입니다. 퍼로는 이 주장을 테스트했습니다. 더 자세하게는 연결 문화가 뿌리내린 고압 경영 컨설팅 회사인 보스턴 컨설팅 그룹의 임원들을 설득해 팀 중 한 팀의 업무 습관을 장난칠 수 있도록 했다. 그녀는 간단한 질문을 테스트하고 싶었습니다. 당신의 일이 지속적으로 연결되는 것이 정말 도움이 되나요? 그러기 위해 그녀는 극단적인 일을 했습니다. 그녀는 팀의 각 구성원에게 회사 안의 누구와도 연결되지 않는 주중 하루를 완전히 쉬도록 강요했습니다.

그녀는 실험 중 하나에 대해 "처음에는 팀이 실험에 저항했다. "기본적인 아이디어에 큰 지지를 보내던 담당 파트너는 갑자기 클라이언트에게 팀원 한 명 한 명씩 일주일에 하루 쉬게 될 것이라고 말해야 하는 것에 대해 긴장했다." 컨설턴트들도 똑같이 긴장하고 "경력을 위태롭게 하고 있다"고 걱정했지만 팀은 고객을 잃지 않았고 구성원들피상적 작업자리를 잃지 않았다. 대신 컨설턴트는 자신의 작업에서 더 많은 즐거움, 그들 사이의 더 나은 의사 소통, 더 많은 학습(지난 장에서 강조한 깊이와 기술 개발 사이의 연결을 고려할 때 예측했을 수 있듯이), 그리고 아마도 가장 중요한 "고객에게 전달되는 더 나은 제품"을 발견했다.

이것은 흥미로운 질문을 불러일으키는데, 왜 많은 사람들이 보스턴 컨설팅 그룹의 리더십을 따르고 연결 문화를 육성하는 반면, 퍼로가 연구에서 발견한 것처럼 직원의 웰빙과 생산성에 해를 끼치고 아마도 결론에 도움이 되지 않을 가능성이 있습니까? 나는 다음과 같은 직장행동의 현실에서 그 답을 찾을 수 있다고 생각한다.

최소 저항의 원칙: 비즈니스 환경에서 다양한 행동이 결과에 미치는 영향에 대한 명확한 피드백 없이 우리는 순간에 가장 쉬운 행동을 지향할 것이다.

연결성의 문화가 지속되는 이유에 대한 우리의 질문으로 돌아가서, 우리의 원칙에 따르면 대답은 더 쉽기 때문이다. 이것이 사실인 이유는 적어도 두 가지입니다. 첫 번째는 귀하의 요구에 대한 반응성에 관한 것입니다. 만약 당신이 필요성이 생기면 바로 질문에 대한 대답이나 특정 정보에 대한 답을 얻을 수 있는 환경에서 일한다면, 이것은 당신의 삶을 적어도 순간적으로 더 쉽게 만든다. 이 빠른 응답 시간에 의존할 수 없다면 대신 작업에 대한 사전 계획을 더 많이 하고 더 조직화해야 하며 요청한 것을 기다리는 동안 잠시 일을 제쳐두고 다른 곳으로 주의를 돌릴 준비를 해야 한다. 이 모든 것이 (장기적으로 더 많은 만족과 더 나은 결과를 낳더라도) 당신의 일상의 하루를 더 힘들게 만들 것입니다. 이 장의 앞부분에서 언급한 전문 인스턴트 메시징의 부상은 이러한 사고방식이 극단으로 밀려간 것으로 볼 수 있다. 1시간 이내에 이메일 회신을 받는 것이 하루를 더 쉽게 만든다면, 1분 이내에 인스턴트 메시지를 통해 답변을 받는 것은 이 이득을 훨씬 더 높일 것입니다.

연결 문화가 삶을 더 쉽게 만드는 두 번째 이유는 인박스에서 하루를 실행하는 것이 받아들여질 수 있는 환경을 만들어주기 때문입니다. 만약 이메일이 근무일 주변으로 이동한다면, 당신은 무엇을 어떻게 해야 하는지, 그리고 얼마나 오래 해야 하는지 파악하는 데 더 사려 깊은 접근법을 적용해야 할 것이다. 이런 종류의 계획은 어렵습니다. 경쟁 사업장 의무를 지능적으로 관리하기 위한 체계로 널리 인정받는 데이비드 앨런의 Things Getting Done 과제 관리 방법론을 예로 들어보자. 이 시스템은 다음으로 무엇을 해야 할지 결정하기 위한 15개 요소의 흐름도를 제안합니다! 최신 cc-d 이메일 스레드에 간단히 입력하는 것이 훨씬 더 쉽습니다.

이 논의에서 사례 연구로 일정한 연결성을 선택하지만, 이는 깊이에 반하는 비즈니스 행동의 많은 예 중 하나일 뿐이며, 그럼에도 불구하고 메트릭이 없으면 대부분의 사람들이 가장 쉬운 것으로 되돌아가고 있기 때문에 회사가 생산하는 바닥 가치를 감소시킬 수 있다.

또 다른 예를 들자면, 정기적으로 발생하는 프로젝트 회의들을 설정하는 일반적인 관행을 고려해 보자. 이러한 회의는 하루 동안의 지속적인 집중이 불가능해질 정도로 일정이 쌓이고 깨지는 경향이 있다. 왜 자꾸만 그러지? 더 쉬워. 많은 사람들에게 이러한 상설 회의는 단순한(그러나 둔탁한) 형태의 개인 조직이 된다. 그들은 시간과 의무를 스스로 관리하려고 하는 대신 매주 임박한 회의에서 주어진 프로젝트에 대해 조치를 취하도록 강요하고 보다 일반적으로 매우 가시적인 진행 상황을 제공합니다.

또한 "생각?"과 같이 짧은 개방형 질문으로 라벨이 붙단순 이메일을 하나 이상의 동료에게 전달하는 답답한 관행을 떠올려보자. 이러한 이메일은 발신자가 작성하는 데 몇 초밖에 걸리지 않지만 일관된 응답을 위해 수취자에게 많은 분(일부에서는 몇 시간이 아니라도)의 시간과 관심을 명령할 수 있다. 발신자가 메시지를 작성하는 데 조금 더 주의를 기울이면 모든 당사자가 소비하는 전반적인 시간이 상당한 비율만큼 감소할 수 있다. 그렇다면 왜 이러한 쉽게 피할 수 있고 시간이 많이 걸리는 이메일이 그렇게 일반적이죠? 발신자의 관점에서 보면, 그것들은 더 쉽다. 최소한의 에너지를 투입하여 적어도 일시적으로 그들의 받은 편지함에서 무언가를 제거하는 방법이다.

미터 블랙홀에 의한 정밀검사로부터 보호받는 최소저항의 원칙은 장기적인 만족과 실질적 가치 생산을 희생시키면서도, 집중과 계획이라는 단기적인 불편함으로부터 우리를 구제하는 작업문화를 지원한다. 그렇게 함으로써 이 원리는 점점 더 깊이를 보상하는 경제에서 피상적 작업을 하도록 우리를 몰아준다. 그러나 미터 블랙홀을 활용하여 깊이를 줄이는 유일한 추세는 아니다. 우리는 또한 다음으로 관심을 돌릴 주제인 "생산성"에 대한 항상 현재적이고 항상 괴롭히는 요구를 고려해야 한다.

### 생산성의 대리 지표가 된 바쁨

연구 중심 대학 교수라는 것은 어려운 점이 많다. 하지만 이 직업이 누리는 한 가지 이점은 명확성입니다. 학술 연구자로서 얼마나 잘하고 있는지, 얼마나 잘하고 있는지가 간단한 질문으로 요약될 수 있다. 이 질문에 대한 답은 h-index와 같이 단일 숫자로 정량화될 수도 있습니다. 발명자인 호르헤 히르쉬의 이름을 따서 이름 붙여진 공식은 출판물과 인용 수를 해당 분야에 대한 영향을 근사하는 단일 값으로 처리합니다. 예를 들어 컴퓨터 과학에서 h-index 점수가 40점 이상이면 달성하기 어렵고 한 번 도달하면 강력한 장기 경력의 표시로 간주된다. 반면에, 만약 당신의 사례가 재직 기간 검토를 위해 올라갈 때 당신의 h-지수가 한 자릿수라면, 당신은 아마도 곤경에 처했을 것이다. 학계에서도 연구 논문을 찾는 데 인기 있는 도구인 구글 스콜라는 h-index까지 자동으로 계산해 주당 몇 번씩 정확히 어디에 서 있는지 상기시킬 수 있다. (생각하실 경우, 제가 이 장을 쓰는 아침 현재 저는 21세입니다.)

이러한 명확성은 교수가 어떤 업무 습관을 채택하거나 포기하는지에 대한 결정을 단순화한다. 예를 들어, 노벨상을 수상한 고 물리학자 리처드 파인먼이 인터뷰에서 덜 정통적인 생산성 전략 중 하나를 설명하는 것이 여기에 있다.

물리학 작업을 제대로 하기 위해서는 절대적인 시간적 여유가 필요하고, 집중력이 필요하며, 어떤 일을 관리하는 직업이 있다면 시간이 없다. 그래서 나는 나를 위해 또 다른 신화를 발명했는데, 그것은 내가 무책임하다는 것이다. 나는 적극적으로 무책임하다. 나는 모든 사람에게 아무것도 하지 않는다고 말한다. 누가 입학위원회에 가입하라고 하면 '아니오'라고 말하면 나는 무책임하다.

파인만은 자신의 직업생활에서 가장 중요한 일인 '물리학 일을 잘하는 것'에 대한 능력이 떨어질 뿐이라는 것을 알고 행정직을 피하는 데 단호했다. 우리는 파인만이 아마도 이메일에 잘 반응하지 않았으며 당신이 그를 공개 사무실로 옮기거나 트윗을 요구했다면 대학을 갈아타게 될 것이라고 가정할 수 있다. 무엇이 중요한지에 대한 명확성은 무엇이 중요하지 않은지에 대한 명확성을 제공한다.

나는 교수들의 예를 언급하는데, 그 이유는 그들이 그들의 일을 얼마나 잘하고 있는지에 대한 투명성을 공유하지 않는 지식 노동자들 사이에서 다소 예외적이기 때문이다. 사회평론가 매튜 크로퍼드가 이 불확실성에 대해 설명한 바는 다음과 같다: "경영자 자신은 당혹스러운 정신적인 풍경에 거주하며 그들이 대답해야 하는 막연한 명령에 불안해진다."

크로포드가 지식 업무 중간 관리자의 곤경에 대해 구체적으로 이야기하고 있었지만 그가 언급하는 "혼란한 심리적 풍경"은 이 부문의 많은 직책에 적용된다. 크로포드가 2009년 트레이드에 대한 찬송가인 '샵 클래스 as Soulcraft'에서 설명하듯이 그는 이런 혼란을 피하기 위해 워싱턴 D.C. 싱크탱크 이사로서의 직업을 그만두고 오토바이 수리점을 열었다. 고장난 기계를 들고 고군분투하다가 결국 성공했다는 가시적 표시(자력으로 가게 밖으로 몰아치는 자전거)를 누리는 느낌은 그의 하루가 막연하게 보도와 커뮤니케이션 전략을 중심으로 돌아갔을 때 그가 반복하기 위해 고군분투했던 구체적인 성취감을 제공한다.

이와 유사한 현실은 많은 지식 종사자들에게 문제를 야기한다. 그들은 그들이 팀의 생산적인 구성원이고 자신의 생활을 유지하고 있다는 것을 증명하고 싶지만 이 목표가 무엇인지를 완전히 명확하게 알지 못한다. 그들은 가치가 있다는 증거로 지적할 수 있는 h 지수 상승이나 수리된 오토바이 랙이 없다. 이러한 격차를 극복하기 위해 많은 이들이 생산성이 보다 보편적으로 관측될 수 있었던 마지막 시기인 산업시대로 회귀하는 것으로 보인다.

이 주장을 이해하기 위해 조립선의 부상과 함께 작업자 이동의 효율성을 모니터링하는 스톱워치를 들고 서 있는 것으로 유명한 창립자 프레데릭 테일러와 동일시되는 효율성 운동의 부상도 있음을 상기하고 작업을 수행하는 속도를 높이는 방법을 찾는다. 테일러 시대에 생산성은 시간 단위당 생성되는 위젯이라는 명확한 것이었다. 오늘날의 비즈니스 환경에서 다른 아이디어가 없는 많은 지식 노동자들은 직업 생활의 혼란스러운 환경에서 가치를 확고히 하려고 하는 과정에서 생산성에 대한 오래된 정의로 눈을 돌리고 있는 것 같다. (예컨대 데이비드 앨런은 생산적인 작업 흐름을 설명하기 위해 '위젯 크랭킹'이라는 특정 문구까지 사용한다. 내가 주장하는 지식 노동자들은 자신의 가치를 입증할 더 나은 방법이 없기 때문에 점점 더 눈에 띄는 바쁜 경향을 보이고 있다. 이 경향에 이름을 붙이자.

생산성의 대리인으로서의 바쁜 모습: 직무에서 생산적이고 가치 있는 것이 무엇을 의미하는지 명확한 지표가 없는 상황에서 많은 지식 노동자들은 생산성의 산업적 지표인 가시적인 방식으로 상당한 작업을 하는 것으로 돌아간다.

이러한 사고방식은 많은 심층 파괴 행동의 인기에 대한 또 다른 설명을 제공한다. 당신이 항상 이메일을 보내고 답하는 경우, 당신이 지속적으로 회의에 일정을 잡고 참석하는 경우, 누군가가 새로운 질문을 제기할 때 몇 초 이내에 홀과 같은 인스턴트 메시지 시스템에 무게를 두거나, 당신이 만나는 모든 사람들을 향해 당신의 열린 사무실에서 아이디어를 던지는 경우, 이러한 모든 행동은 당신이 공공적인 방식으로 바쁜 것처럼 보이게 한다. 만약 당신이 생산성의 대용치로 바쁜 행동을 사용한다면, 이러한 행동은 당신이 당신의 일을 잘하고 있다고 자신과 다른 사람들에게 확신시키는 데 중요해 보일 수 있다.

이러한 사고방식이 반드시 비합리적인 것은 아니다. 어떤 사람들에게는 직업이 그러한 행동에 달려 있습니다. 예컨대 2013년 야후의 새로운 CEO인 마리사 메이어는 직원들의 재택근무를 금지했다. 그녀는 야후 직원들이 회사 서버에 원격으로 로그인하기 위해 사용하는 가상 사설망에 대한 서버 로그를 확인한 후 이 같은 결정을 내렸다. 메이어는 재택근무 직원들이 하루 종일 충분히 사인하지 않아 속상했다. 그녀는 어떤 의미에서 직원들이 이메일을 확인하는 데 더 많은 시간을 소비하지 않는다는 것을 처벌하고 있었다(서버에 로그인하는 주요 이유 중 하나). "만약 당신이 눈에 띄게 바쁘지 않다면", 그녀는 "나는 당신이 생산적이지 않다고 가정할 것이다."라고 신호를 보냈다.

그러나 객관적으로 본다면 이 개념은 시대착오적이다. 지식 작업은 집합선이 아니며 정보로부터 가치를 추출하는 것은 바쁘기와 종종 상충되는 활동이지 그것에 의해 뒷받침되지 않는다. 예를 들어, 저번 장의 학술가인 아담 그랜트를 기억하자, 그는 저술에 집중하기 위해 외부 세계로부터 자신을 반복적으로 차단함으로써 와튼의 최연소 정교수가 되었다. 그러한 행동은 공공연히 바쁜 것과 반대이다. 그랜트가 야후에서 일했다면 마리사 메이어가 그를 해고했을지도 모른다. 그러나 이 깊은 전략은 엄청난 양의 가치를 창출하는 것으로 판명되었습니다.

우리는 물론, 우리가 그 부정적인 영향을 바닥에 쉽게 입증할 수 있다면, 이러한 시대착오적인 바쁜 몰입을 제거할 수 있지만 메트릭 블랙홀은 이 지점에서 현장에 들어가 그러한 명확성을 방해한다. 직무의 모호성과 다양한 전략의 효과를 측정하는 지표의 부족의 강력한 혼합은 객관적으로 볼 때 우스꽝스럽게 보일 수 있는 행동이 점점 더 혼란스러운 일상 업무의 심리적 환경에서 번성하도록 한다.

그러나 다음에서 살펴볼 것처럼 지식 직업에서 성공한다는 것이 무엇을 의미하는지 명확하게 이해하는 사람들도 여전히 깊이에서 벗어나 유혹될 수 있다. 상식을 버리게 설득할 만큼 충분히 유혹적인 이데올로기가 필요한 것뿐이다.

### 인터넷 숭배

알리사 루빈을 생각해 보세요. 그녀는 파리에 있는 뉴욕타임스 사무국장이다. 그 이전에는 아프가니스탄 카불의 국장이었으며 전후 재건에 대해 최전선에서 보고했다. 이 장을 쓰는 즈음에는 르완다 집단학살에 대한 프랑스 정부의 공모를 바라보는 일련의 강경 기사를 발표하고 있었다. 루빈은 다시 말해 자신의 공예를 잘하는 진지한 언론인이다. 또한, 제가 추측할 수 있는 것은 고용주의 끈질긴 촉구인 트윗입니다.

루빈의 트위터 프로필은 루빈이 타임스 소셜 미디어 책상에서 (실제) 팔로워를 달래라고 상기시키는 정기적인 통지를 받는 것처럼 2~4일마다 하나씩 꾸준하고 다소 황폐한 일련의 미사일을 보여준다. 트윗에는 몇 가지 예외를 제외하고는 그녀가 최근에 읽고 좋아했던 기사를 언급하는 것뿐이다.

루빈은 언론 인물이 아니라 기자다. 그녀의 논문에 대한 가치는 중요한 출처를 배양하고 사실을 정리하고 돌풍을 일으키는 기사를 쓰는 능력이다. 타임스에게 명성을 제공하는 것은 세계의 알리사 루빈이며 유비쿼터스하고 중독적인 클릭 미끼 시대에 논문이 상업적으로 성공할 수 있는 기반을 제공하는 것은 바로 이 명성이다. 그렇다면 알리사 루빈이 실리콘밸리에 기반을 둔 관계없는 미디어 회사가 운영하는 서비스에 은 콘텐츠를 무료로 제공하기 위해 이 필연적으로 딥 워크을 정기적으로 중단해야 하는 이유는 무엇인가? 그리고 아마도 더 중요한 것은, 왜 이 행동이 대부분의 사람들에게 그렇게 평범해 보이는가? 우리가 이 질문에 답할 수 있다면, 왜 심층 작업이 역설적으로 희귀해졌는지의 문제와 관련하여 논의하고 싶은 마지막 경향을 더 잘 이해할 수 있을 것이다.

우리의 답에 대한 근거는 후기 의사소통 이론가이자 뉴욕대학교 교수인 닐 포스트먼이 제시한 경고에서 찾을 수 있다. 1990년대 초에 글을 쓰는 포스트먼은 퍼스널 컴퓨터 혁명이 처음 가속화되면서 우리 사회가 기술과 골치 아픈 관계로 미끄러지고 있다고 주장했다. 그는 "우리는 더 이상 새로운 기술을 둘러싼 절충점을 논의하지 않고 새로운 효율성과 도입된 새로운 문제의 균형을 맞추고 있었다"고 지적했다. 그것이 첨단 기술이라면, 우리는 대신 가정하기 시작했고 그것은 좋피상적인 일이다. 케이스 클로즈.

그는 그러한 문화를 테크노폴리라고 불렀고 그것에 대해 경고하는 데 말을 아끼지 않았다. 그는 이 주제에 대해 1993년 저서에서 "기술 독점은 알두스 슬리가 브레이브 뉴 월드에서 설명한 정확한 방식으로 자신에 대한 대안을 제거한다. "그것이 그들을 불법으로 만들지는 않는다. 그것이 그들을 비도덕적으로 만들지는 않습니다. 그것이 그들을 인기가 없도록 만들지도 않습니다. 그것은 그들을 보이지 않게 만들고 따라서 관련이 없다."

우편공은 2003년에 사망했지만 그가 오늘 살아있다면 1990년대부터의 두려움이 얼마나 빨리 결실을 맺었는지에 대해 놀라움을 표현할 것 같다. 다행히 포스트맨은 인터넷 시대에 이 주장을 이어갈 지적 계승자, 즉 과 인용적 사회 평론가인 에브게니 모로조프를 보유하고 있다. 모로조프는 2013년 저서 '모든 것을 살리기 위해, 여기에서 클릭하기'에서 "이데올로기로서의 역할을 강조하기 위해 의도적으로 공포 인용문에 넣은 용어"인 "인터넷"에 대한 우리의 기술 집착에 대한 커튼을 뒤로 당기려고 시도한다. "이것이 "인터넷"을 상당히 흥미롭지 않은 케이블과 네트워크 라우터 세트에서 유혹적이고 흥미진진한 이데올로기(아마도 오늘날의 우버 이데올로기)로 전환시키는 지혜와 정책 조언의 원천으로 보는 이러한

모로조프의 비판에서 우리는 "인터넷"을 기업과 정부의 혁명적 미래와 동의어로 만들었다. 귀사를 '인터넷'처럼 만드는 것은 시대에 부합하는 것이고 이러한 트렌드를 무시하는 것은 자동차 시대의 속담인 버기 채 제조업자가 되는 것이다. 우리는 더 이상 인터넷 도구를 영리 기업이 출시하고 수익을 기대하는 투자자가 자금을 지원하며 계속 계속 발명하는 20대들이 운영하는 제품으로 보지 않습니다. 우리는 대신 이러한 디지털 듀드아드를 진보의 상징이자 (내가 용기 있게 말하지만 용감한) 새로운 세계의 전조로 우상화하기에 빠릅니다.

이러한 인터넷 중심주의(또 다른 모로조프 용어를 훔치기 위한 것)는 오늘날 테크노폴리가 보이는 모습이다. 이 부분을 열어놓은 질문을 설명하기 때문에 우리가 이 현실을 인식하는 것이 중요하다. 뉴욕타임스는 소셜 미디어 데스크를 유지하고 알리사 루빈과 같은 작가들을 주의를 산만하게 하는 행동으로 압박합니다. 인터넷 중심의 기술 독점에서는 그러한 행동이 논의될 여지가 없기 때문입니다. 모든 것을 인터넷으로 포섭하지 않는 대안은 포스트맨이 말하듯 "보이지 않고 따라서 관련이 없다"는 것이다.

이 비가시성은 앞서 언급한 조나단 프랜젠이 소설가들이 트윗을 해서는 안 된다고 감히 제안하면서 일어난 소란을 설명한다. 사람들이 책 마케팅에 정통하고 프랜젠의 결론에 동의하지 않았기 때문이 아니라 진지한 사람이 소셜 미디어의 무관함을 시사한다는 사실에 놀랐기 때문이다. 인터넷 중심의 기술 독점에서 그러한 진술은 토론이 아니라 깃발 태우기-탈신에 해당한다.

아마도 이 사고방식의 거의 보편적인 범위는 내가 일하는 조지타운 캠퍼스로 출퇴근하는 동안 내가 최근에 겪은 경험에서 가장 잘 포착된다. 코네티컷 애비뉴를 건너기 위해 빛이 바뀌기를 기다리며 냉장 공급망 물류 회사의 트럭 뒤에 공회전했다. 냉동 배송은 노동조합 관리와 노선 일정을 동등하게 관리해야 하는 복잡하고 경쟁적인 사업이다. 그것은 궁극적인 구식 산업이며 여러 면에서 현재 많은 관심을 받고 있는 희박한 소비자 대면 기술 스타트업과 반대이다. 그러나 이 트럭 뒤에서 교통 체증에서 기다리다 우연히 들뜬 것은 이 회사의 복잡성이나 규모가 아니라 대신 의뢰를 받고 상당한 비용을 들여 이 트럭 전체의 뒷면에 부착된 그래픽("페이스북에 있는 우리와 같다")이었다.

심층 작업은 확실히 구식적이고 비기술적인 품질, 장인정신, 숙달과 같은 가치를 기반으로 하기 때문에 기술 독점에서 심각한 단점에 있다. 더 나쁜 것은 심층 작업을 지원하려면 새롭고 첨단 기술에 대한 많은 거부가 필요한 경우가 많다. 딥워크는 소셜 미디어의 전문적인 사용과 같이 더 주의를 산만하게 하는 하이테크 행동에 유리하게 유배되는데, 전자가 후자에 비해 경험적으로 열등하기 때문이 아니다. 실제로, 이러한 행동의 영향과 관련된 하드 메트릭이 바닥에 있다면 현재의 기술 독점이 무너질 가능성이 높다. 그러나 메트릭 블랙홀은 그러한 명확성을 방해하고 대신 인터넷을 모로조프가 두려워하는 "uber-이데올로기"로 끌어올릴 수 있게 한다. 그러한 문화에서 우리는 딥 워크이 트윗, 좋아요, 태그 사진, 벽, 게시물 및 우리가 지금 가르치는 다른 모든 행동의 반짝이는 에 맞서 경쟁하기 위해 고군분투한다는 사실에 놀라지 않아야 한다.

### 기업에는 손해일지라도, 개인에게는 기회다

오늘날 비즈니스 환경에서 딥워크는 우선 순위가 되어야 합니다. 그런데 그렇지 않아요. 나는 이 역설에 대한 다양한 설명을 요약했다. 그 중에는 딥 워크이 힘들고 피상적 작업이 더 쉽다는 현실, 자신의 직업에 대한 명확한 목표가 없으면 피상적 작업을 둘러싼 가시적인 바쁘기가 자기 보존적이 된다는 현실, 우리 문화는 행동이 '인터넷'과 관련되면 가치 있는 것을 생산하는 능력에 미치는 영향과 상관없이 좋다는 믿음을 발전시켰다는 사실도 있다. 이러한 경향들은 모두 깊이의 가치를 직접 측정하는 어려움이나 무시하는 비용에 의해 가능하게 된다.

깊이의 가치를 믿는다면, 이러한 현실은 기업 전반에 나쁜 소식을 의미하는데, 이는 기업들이 잠재적으로 막대한 가치 생산 증가를 놓치게 하고 있기 때문이다. 하지만 개인으로서 좋은 소식이 기다리고 있습니다. 동료와 고용주의 근시는 큰 개인적 이점을 드러냅니다. 여기에 요약된 경향이 계속한다고 가정하면 깊이는 점점 더 희귀해져서 점점 더 가치가 높아진다. 심층 작업에 근본적으로 결함이 없고 이를 대체하는 산만한 행동에 근본적으로 필요한 것이 없다는 것을 이제 막 확립한 다음, 이 책의 궁극적인 목표인 심층 작업에 대한 개인적인 능력을 체계적으로 개발하고 그렇게 함으로써 큰 보상을 얻을 수 있다는 것을 자신 있게 계속할 수 있다.

## 3장. 딥 워크는 의미 있다

릭 퓨러는 대장공입니다. 그는 고대와 중세의 금속 가공 관행을 전문으로 하며 그의 가게인 도어 카운티 단조 공장에서 이를 고심코 재창조한다. 그는 "모든 작업을 손으로 하고 나의 창의성이나 소재와의 상호 작용을 제한하지 않고 나의 힘을 곱하는 도구를 사용한다"고 작가의 진술에서 설명한다. 내가 손으로 100번 때려도 되는 것은 큰 스와징 기계로 한 번으로 할 수 있다. 이것은 나의 목표의 대립이며 이를 위해 나의 모든 작업은 그것을 만든 두 손의 증거를 보여준다."

2012년 PBS 다큐멘터리는 푸레르의 세계를 엿볼 수 있다. 우리는 그가 미시간 호수의 경치 좋은 스터건 만에서 내륙으로 멀지 않은 위스콘신 농촌의 개조된 헛간에서 일한다는 것을 알게 된다. 푸레르는 종종 헛간 문을 열어두는(조각의 열기를 내보내는 것, 한 사람은 의심) 농장이 수평선까지 뻗어 있는 그의 노력에 프레임을 뒀다. 설정은 고풍스럽지만 작품은 언뜻 보면 잔인해 보일 수 있다. 다큐멘터리에서 푸레르는 바이킹 시대의 칼을 재창조하려고 한다. 그는 1500년 된 기술을 사용하여 도가니 강철을 제련하는 것으로 시작하는데, 이 방법은 금속의 비정상적으로 순수한(당시) 형태이다. 그 결과 3~4개의 스택형 스마트폰보다 크게 크지 않은 잉곳이 됩니다. 이 조밀한 잉곳은 길고 우아한 칼날로 성형되고 연마되어야 한다.

"이 부분, 초기 고장, 끔찍하다"는 퓨러는 카메라에 잉곳을 체계적으로 가열하고 망치로 치고 뒤집어 치고 다시 불꽃에 넣어 다시 시작하면서 말한다. 화자는 이 망치질이 성형을 완성하는 데 8시간이 걸린다고 밝히고 있다. 그러나 푸레르의 작품을 보면서 노동의 감각이 바뀌게 된다. 그가 톱니를 채굴꾼처럼 금속을 쓸쓸하게 때리는 것이 아니라는 것이 분명해진다: 모든 타격은 비록 강력하지만 조심스럽게 제어된다. 그는 얇은 틀의 지적 안경(무겁게 턱수염과 넓은 어깨 위에 자리 잡지 않피상적인 일처럼 보이는)을 통해 금속을 집중적으로 주시하며 각 충격마다 그것을 그렇게 돌린다. "매우 부드럽게 해야 그렇지 않으면 깨질 것"이라고 설명한다. 몇 번의 해머 스트라이크를 더 한 뒤 그는 "너지는 넛지를 꽂아야 하고 천천히 깨진 다음 즐기기 시작한다"고 덧붙였다.

제련을 하는 중간쯤 되는 시점에서, 푸레어가 원하는 모양을 망치질하는 작업을 마친 후, 그는 타는 의 좁은 통에서 조심스럽게 금속을 회전시키기 시작한다. 칼날을 바라보는 그는 "다 준비됐다"라는 무언가가 클릭한다. 그는 기름이 가득 찬 파이프를 향해 빠르게 걸어가다가 칼에 몸을 담아 몸을 식히면서 열에 붉게 물든 칼을 들어 올린다. 칼날이 조각으로 갈라지지 않은 순간 -이 단계에서 흔히 발생하는 것- 후러는 오일에서 그것을 당긴다. 금속의 잔열은 연료를 점등시켜 칼의 전장을 노란 불꽃에 휩싸인다. 푸레르는 불타는 칼을 하나의 강력한 팔로 머리 위로 들고 불을 불기기 직전에 바라본다. 이 짧은 휴식기 동안 불꽃이 그의 얼굴을 비추며 그의 감탄을 수 있다.

"잘 하기 위해서는 내가 만드는 법을 아는 것 중 가장 복잡한 일"이라고 푸레르는 설명한다. 그리고 나를 움직이는 것은 바로 그 도전이다. 칼이 필요 없어요. 하지만 나는 그것들을 만들어야 한다.

리크 푸레르는 작업에 있어 하루의 대부분을 깊이 있는 상태에서 보내야 하는 명장이며 집중력의 작은 미끄러짐도 수십 시간의 노력을 망칠 수 있다. 그는 자신의 직업에서 분명히 큰 의미를 찾는 사람이기도 하다. 이러한 심층적 일과 좋은 삶의 연결은 장인의 세계를 고려할 때 익숙하고 널리 받아들여진다. 매튜 크로포드는 "수동적 역량을 통해 세상에 자신을 구체적으로 드러내는 만족은 사람을 조용하고 쉬워지게 만드는 것으로 알려져 왔다"고 설명한다. 그리고 우리는 그를 믿어요.

그러나 우리가 지식 작업으로 주의를 돌리면 이 연결은 흐려진다. 문제의 일부는 명확성입니다. 푸레르와 같은 장인들은 정의하기 쉽지만 실행하기 어려운 전문적인 도전을 다루는데, 이는 목적을 추구할 때 유용한 불균형이다. 지식 작업은 이러한 명확성을 모호성에 교환한다. 주어진 지식 노동자가 무엇을 하고 다른 직업과 어떻게 다른지 정확히 정의하기 어려울 수 있습니다. 최악의 날에는 모든 지식 작업이 이메일과 파워포인트의 동일한 지친 롤로 귀결되는 것처럼 보일 수 있으며 슬라이드에 사용된 차트만 한 직업을 다른 직업과 구별한다. 퓨러 자신은 "정보 초고속도로와 사이버 공간의 세계는 나를 다소 차갑고 황홀하게 만들었다"고 적으면서 이러한 무디함을 확인한다.

지식 작업에서 깊이와 의미의 연결을 흐트러뜨리는 또 다른 문제는 지식 작업자가 피상적인 활동에 더 많은 시간을 할애하도록 설득하려는 목소리의 카코포니이다. 지난 장에서 자세히 설명했듯이 인터넷과 관련된 모든 것이 기본적으로 혁신적이고 필요한 것으로 이해되는 시대에 살고 있다. 즉각적인 이메일 응답과 적극적인 소셜 미디어 존재와 같은 심층 파괴적인 행동은 칭찬받는 반면 이러한 경향을 회피하는 것은 의심을 불러일으킨다. 아무도 리크 푸레르가 페이스북을 사용하지 않는다고 비난하지 않을 것이지만 만약 지식 종사자가 같은 결정을 내린다면, 그는 (내가 개인적인 경험에서 배웠듯이) 편심자라고 낙인찍힌다.

그러나 깊이와 의미 사이의 이러한 연결이 지식 작업에서 덜 명확하다고 해서 그것이 존재하지 않는다는 의미는 아니다. 이 장의 목표는 딥워크가 공예 경제에서 분명히 하는 것처럼 정보 경제에서 많은 만족을 창출할 수 있다는 것을 당신에게 확신시키는 것이다. 앞으로의 섹션에서는 이 주장을 뒷받침하는 세 가지 주장을 할 것이다. 이러한 주장은 개념적으로 좁피상적인 일에서 넓피상적인 일, 즉 신경학적 관점으로 시작하여 심리학적 관점으로 이동하고 철학적 관점으로 끝나는 궤적을 대략적으로 따른다. 나는 깊이와 지식 작업의 문제를 어떤 각도에서 공격하든 피상적인 일을 넘어 깊이를 포용함으로써 릭 푸레르와 같은 장인을 몰고 가는 동일한 의미의 맥을 수 있다는 것이 분명하다는 것을 보여줄 것이다. 따라서 1부의 이 마지막 장의 논지는 깊은 삶은 경제적으로 수익적일 뿐만 아니라 잘 사는 삶이라는 것이다.

### 신경학적 관점에서 본 몰입의 가치

과학 작가 위니프레드 갤러거는 예상치 못한 무서운 사건, 암 진단 이후 주의력과 행복 사이의 연관성에 우연히 우연히 우연히 우연히 발견되었다고 그녀는 설명한다. "암은 단지 암이 아니라 특히 흉악하고 상당히 발전된 유형"이라고 그녀는 2009년 책 랩트에서 회고하고 있다. 그녀는 진단 후 병원을 떠나자 갑작스럽고 강한 직관을 형성했다. "이 질병은 내 주의를 독점하고 싶었지만 가능한 한 내 삶에 집중하겠다." 그 후의 암 치료는 지치고 끔찍했지만, 갤러거는 논픽 이 시기 그녀의 삶은 두려움과 안타까움에 휩싸였어야 했지만, 오히려 종종 꽤 즐거운 일이었다.

그녀의 호기심이 들끓자 갤러거는 주의가 우리 삶의 질을 정의하는 데 있어 어떤 역할을 하는지, 즉 우리가 집중하기로 선택한 것과 무시하기로 선택한 것을 더 잘 이해하기 시작했다. 그녀는 5년간의 과학 보고를 마치고 정신의 '대통일론'을 목격하고 있다는 확신을 갖고 나왔다.

달을 가리키는 손가락처럼 인류학에서 교육, 행동경제학에서 가족상담에 이르기까지 다양한 학문들도 마찬가지로 주의의 능숙한 관리가 좋은 삶의 필수 조건이며 경험의 거의 모든 측면을 개선하는 열쇠임을 시사한다.

이 개념은 대부분의 사람들이 주관적인 삶의 경험에 대해 생각하는 방식을 뒤집는다. 우리는 우리에게 일어난 일(혹피상적 작업어나지 않는 일)이 우리가 느끼는 것을 결정한다고 가정하면서 우리의 상황에 많은 비중을 두는 경향이 있다. 이런 관점에서 보면, 승진 여부나 더 좋은 아파트로의 이적 여부와 같은 대규모 결과가 중요하기 때문에 하루를 보내는 방식에 대한 소규모 세부 사항은 그다지 중요하지 않다. 갤러거에 따르면 수십 년의 연구는 이러한 이해와 모순된다. 우리의 뇌는 대신 우리가 주목하는 것에 기초하여 우리의 세계관을 구성한다. 암 진단에 집중하면 자신과 삶은 불행하고 어두워지지만 대신 저녁 마티니에 집중하면 두 시나리오의 상황이 같지만 자신과 삶은 더 즐겁다. 갤러거가 요약한 것처럼, "당신이 누구인가, 당신이 생각하고 느끼고 행하는 바, 당신이 사랑하는 바"는 당신이 집중하는 바의 총합이다.

랩트에서 갤러거는 이러한 마음의 이해를 뒷받침하는 연구를 조사한다. 그녀는 예를 들어 노스캐롤라이나 대학의 심리학자인 바버라 프레드릭슨을 인용하는데, 감정의 인지적 평가를 전문으로 하는 연구자이다. 프레드릭슨의 연구에서는 삶에서 나쁜 일이 발생하거나 방해가 되는 일이 발생한 후, 당신이 집중하기로 선택한 것이 앞으로의 태도에 상당한 지렛대를 행사한다는 것을 보여준다. 이러한 간단한 선택은 감정에 '리셋 버튼'을 제공할 수 있다. 그녀는 부당한 집안일 분할을 둘러싸고 싸우는 부부의 예를 제시한다. 그녀는 "상대의 이기심과 게으름에 계속 집중하기보다는, 적어도 문제가 불어난 갈등이 방영됐다는 사실, 즉 문제의 해결을 위한 첫걸음이라는 점, 기분 개선에 집중할 수 있다"고 제안한다. 이것은 밝은 면을 바라보는 단순한 권유처럼 보이지만 프레드릭슨은 이러한 감정적 '레버리지 포인트'를 능숙하게 사용하면 부정적인 사건 이후 훨씬 더 긍정적인 결과를 생성할 수 있다고 발견했다.

과학자들은 신경학적 수준까지 이 효과를 행동으로 관찰할 수 있다. 스탠퍼드 심리학자인 로라 카르스텐슨은 fMRI 스캐너를 사용하여 긍정적인 이미지와 부정적인 이미지가 모두 제시된 피험자의 뇌 행동을 연구했다. 그녀는 젊은 사람들에게 그들의 편도체(감정의 중심)가 두 가지 유형의 이미지에서 활동으로 발화한다는 것을 발견했다. 대신 할머니를 스캔했을 때, 편도체는 긍정적인 이미지만 발사했다. 카르스텐센은 노인 피험자들이 부정적 자극이 있는 상태에서 전전두엽 피질이 편도체를 억제하도록 훈련시켰다고 가정한다. 이들 노인 피험자들은 그들의 삶의 상황이 젊은 피험자들보다 낫기 때문에 더 행복하지 않았으며 오히려 부정적인 것을 무시하고 긍정적인 것을 음미하도록 그들의 두뇌를 재배선했기 때문에 더 행복했다. 그들의 주의를 능숙하게 관리함으로써, 그들은 그것에 대한 구체적인 어떤 변화도 없이 그들의 세계를 개선했다.

이제 한 걸음 물러서서 갈러거의 대이론을 활용하여 좋은 삶을 기르는 데 있어 심층근로가 갖는 역할을 더 잘 이해할 수 있다. 이 이론은 우리의 세계가 당신이 주목하는 것의 결과라는 것을 우리에게 말해 주므로, 깊은 노력에 상당한 시간을 할애할 때 구성되는 정신 세계의 유형을 잠시 생각해 보자. 칼을 만드는 Ric Furrer이든 알고리즘을 최적화하는 컴퓨터 프로그래머든 심층 작업에는 중력과 중요성이 내재되어 있다. 따라서 갤러거의 이론은 당신이 이 상태에서 충분한 시간을 보내면, 당신의 마음은 당신의 세계를 의미와 중요성이 풍부한 것으로 이해할 것이라고 예측한다.

그러나 일과에서 랩트 주의력을 배양하는 데 숨겨져 있지만 똑같이 중요한 이점이 있는데, 이러한 집중은 주의력을 탈취하여 피할 수 없고 지속적으로 우리 삶을 채우는 더 작고 덜 즐거운 것들을 알아차리지 못하게 한다. (다음 절에서 더 자세히 배울 심리학자인 미할리 칙센트미할이는 "무관한 것에 대해 생각하거나 문제에 대해 걱정하는 데 주의가 남지 않을 정도로 강렬한 집중"을 배양하는 이점을 강조할 때 이 이점을 명시적으로 식별한다.) 이 위험은 유비쿼터스 연결성에 의존하기 때문에 파괴적으로 매력적인 주의 분산 뷔페를 생성하는 지식 작업에서 특히 두드러진다. 이 중 대부분은 충분한 주의를 기울이면 정신이 구성한 세계에서 의미와 중요성을 침출한다.

이 주장을 보다 구체적으로 만들기 위해 나는 나를 시험 사례로 사용할 것이다. 예를 들어, 이 장의 첫 번째 초안을 쓰기 전에 보낸 마지막 5개의 이메일을 생각해 보자. 이 메시지들의 주제 라인과 내용 요약은 다음과 같다.

* **Re: [긴급] calnewport 브랜드 등록 확인 건**: 웹사이트 소유자에게 중국 도메인을 등록하라고 속이는 전형적인 피싱 스팸에 대한 답장이었습니다. 계속되는 스팸에 짜증이 나서 발끈한 나머지(물론 부질없는 짓이었지만), "이메일에서 'website' 철자나 똑바로 쓰면 사기가 더 그럴싸해 보일 것"이라고 쏘아붙였습니다.
* **Re: S R.**: 《월스트리트 저널》에서 본 기사에 관해 가족과 나눈 대화였습니다.
* **Re: 중요한 조언**: 최적의 은퇴 투자 전략에 관해 주고받은 대화였습니다.
* **Re: Fwd: Study Hacks**: 내가 사는 도시를 방문한 지인과 약속 시간을 잡으려던 대화였습니다. 방문 기간 동안 그의 일정이 쪼개져 있어 약속을 잡기가 꽤 복잡했습니다.
* **Re: 그냥 궁금해서**: 동료 교수와 학과 내 골치 아픈 사내 정치 문제(학계에서 흔히 볼 수 있는 뻔한 갈등)에 대해 이야기를 나눈 메시지였습니다.

이 이메일은 지식 업무 환경에서 관심을 끌 수 있는 은 문제의 유형에 대한 좋은 사례 연구를 제공한다. 이 샘플 메시지에 제시된 일부 문제는 흥미로운 기사를 논의하는 것과 같이 양호한 문제, 노후 저축 전략에 대한 대화(가까운 경우 항상 올바른 일을 하지 않는 것으로 결론을 맺는 대화 유형)와 같이 막연하게 스트레스 받는 것, 바쁜 일정을 위해 회의를 주선하려는 것과 같은 답답한 것, 사기꾼에 대한 분노한 반응이나 사무실 정치에 대한 걱정스러운 토론과 같은 명시적으로 부정적인 것 등이다.

많은 지식 종사자들은 이러한 유형의 은 고민과 상호 작용하면서 근무 일상의 대부분을 보낸다. 더 관련된 작업을 완료해야 하는 경우에도, 수시로 받은 편지함을 확인하는 습관은 이러한 문제가 주의의 최전선에 있도록 한다. 갤러거는 이것이 당신의 정신이 스트레스, 짜증, 좌절, 사소함으로 지배되는 직장생활에 대한 이해를 구성할 수 있도록 하기 때문에, 당신의 하루를 돌아가는 어리석은 방법이라고 가르친다. 당신의 편지함으로 대표되는 세계는, 다시 말해, 거주하기에 즐거운 세계가 아니다.

동료들이 모두 천재적이고 상호 작용이 항상 낙관적이고 긍정적이더라도, 당신의 주의가 피상적인 영역의 유혹적인 풍경 위로 표류하도록 허용함으로써, 당신은 갤러거가 "주의에 대한 5년의 보고가 몇 가지 가정의 진실을 확인했다"고 지적한 또 다른 신경학적 함정에 빠질 위험이 있다고 갤러거는 보고한다. "(그들 중에는) "유휴한 마음은 악마의 작업장"이라는 관념이 있다... 집중력을 잃으면 마음은 무엇이 옳피상적인 일 대신 자신의 삶에 잘못될 수 있는 것에 초점을 맞추는 경향이 있다." 신경학적 관점에서 피상적 작업에 의해 주도되는 하루는 주의를 사로잡는 피상적인 일의 대부분이 무해하거나 재미있어 보이더라도 지칠 수 있고 속상할 수 있는 날이 될 가능성이 높다.

이러한 발견의 의미는 분명하다. 업무(특히 지식 업무)에서 깊이 있는 상태에서 보내는 시간을 늘리는 것은 여러 가지 신경학적 이유로 인해 작업 생활과 연관시킬 의미와 만족을 극대화하는 방식으로 인간 뇌의 복잡한 기계를 활용하는 것이다. 갤러거는 저서에서 "힘든 실험을 (암으로) 실행한 후... 남은 삶을 살 계획을 가지고 있다"고 결론을 내린다. 나는 나의 대상을 신중하게 선택하고... 그리고 그들에게 나의 절실한 주의를 기울일 것이다. 요컨대, 나는 집중된 삶을 살 것이다, 왜냐하면 그것이 최고의 삶이기 때문이다." 우리는 그녀의 길을 따르는 것이 현명할 것이다.

### 심리학적 관점에서 본 몰입의 가치

깊이가 의미를 생성하는 이유에 대한 두 번째 주장은 세계에서 가장 잘 알려져 있는(그리고 가장 잘못 쓰여진) 심리학자인 미할리 칙센트미할리의 작업에서 나온다. 1980년대 초, 시카고 대학의 젊은 동료인 리드 라슨과 함께 일정한 행동의 심리적 영향을 이해하기 위한 새로운 기술을 발명한 칙센트미할이이다. 당시에는 서로 다른 활동이 주는 심리적 영향을 정확히 측정하기 어려웠다. 만약 당신이 누군가를 실험실에 데려와 몇 시간 전에 특정한 시점에서 느낀 것을 기억하라고 했다면, 그녀는 기억하지 못할 것 같다. 대신 그녀에게 일기를 주고 하루 종일 느낀 점을 기록하라고 요청했다면 그녀는 열심히 기재를 유지하지 않을 것입니다. 그것은 단순히 너무 상당한 작업입니다.

칙센트미할이와 라르손의 돌파구는 새로운 기술을 활용하여 문제가 있을 때 질문을 주제에 바로 전달하는 것이었다. 더 자세히 설명하자면 그들은 실험 대상에 페이저를 장착했다. 이 페이저는 무작위로 선택된 간격으로 삐를 울 것이다(이 방법의 현대적 구현에서 스마트폰 앱은 동일한 역할을 한다). 피험자들은 비퍼가 울리면, 그들이 정확히 어떤 순간에 무엇을 하고 있는지, 어떻게 느꼈는지 기록할 것이다. 어떤 경우에는 이 정보를 기록할 수 있는 저널을 제공받았고 다른 경우에는 현장 작업자가 제기한 질문에 답하기 위해 전화할 수 있는 전화 번호를 제공받았다. 삐는 가끔 들리지만 무시하기 어려웠기 때문에 피험자들은 실험 절차를 따를 가능성이 높았다. 그리고 피험자들피상적인 활동에 참여하는 바로 그 순간에 활동에 대한 응답을 기록하고 있었기 때문에 응답이 더 정확했다. 칙센트미할이와 라슨은 접근법을 경험 샘플링 방법이라고 불렀고 그것은 우리가 실제로 일상 생활의 박자에 대해 어떻게 느끼는지에 대한 전례 없는 통찰력을 제공했다.

많은 돌파구 중 ESM에 대한 칙센트미할이의 작업은 그가 지난 10년 동안 개발해 온 이론을 검증하는 데 도움이 되었는데, 칙센트미할이는 "사람의 몸이나 마음이 어렵고 가치 있는 것을 성취하기 위한 자발적인 노력으로 한계까지 뻗어 있을 때 가장 좋은 순간이 보통 발생한다." 칙센트미할이는 이 정신 상태 흐름을 부르고 있다. 당시 이 발견은 통념에 반하는 결과를 낳았다. 대부분의 사람들은 휴식이 자신을 행복하게 만든다고 가정했다(그리고 여전히 그렇게 하고 있다). 우리는 일을 덜 하고 해먹에서 더 많은 시간을 보내고 싶습니다. 그러나 칙센트미할이의 ESM 연구 결과는 대부분의 사람들이 다음과 같이 잘못 알고 있음을 보여준다.

아이러니하게도 직업은 자유 시간보다 실제로 즐기기 쉬우며 왜냐하면 흐름 활동과 마찬가지로 목표, 피드백 규칙 및 도전이 내장되어 있기 때문에 이 모든 것이 자신의 일에 참여하고 집중하고 일에 자신을 잃도록 장려하기 때문이다. 반면에 자유 시간은 비구조화되어 있고 즐길 수 있는 것으로 형상화되기 위해서는 훨씬 더 많은 노력이 필요하다.

실증적으로 측정했을 때, 사람들은 자신이 의심했던 것보다 직장에서 더 행복하고 휴식하는 데 덜 행복했다. 그리고 ESM 연구들이 확인한 바와 같이, 주어진 주에 발생하는 이러한 흐름 경험이 많을수록 대상자의 삶의 만족도가 높아지는 것으로 나타났다. 인간은 도전적인 것에 깊이 빠져 있을 때 최고인 것 같다.

유동론과 마지막 절에서 부각된 위니프레드 갤러거의 사상 사이에는 물론 중복이 있다. 둘 다 피상적인 일보다는 깊이의 중요성을 지적하지만 이 중요성에 대해 두 가지 다른 설명에 초점을 맞춘다. 갤러거의 글은 우리가 문제에 초점을 맞추는 내용에 대해 강조한다. 중요한 것에 급조하여 관심을 기울이고 따라서 은 부정적인 것들도 무시한다면 우리는 노동생활을 더욱 중요하고 긍정적으로 경험하게 될 것이다. 이와 대조적으로 칙센트미할이의 흐름 이론은 우리의 주의의 내용에 대해 대부분 불신론적이다. 그는 갤러거가 인용한 연구에 동의할 가능성이 높지만 그의 이론은 깊숙이 들어가는 느낌 자체가 매우 보람적이라고 지적한다. 우리의 마음은 주제에 관계없이 이 도전을 좋아합니다.

심층 작업과 흐름 사이의 연결은 명확해야 한다: 심층 작업은 흐름 상태를 생성하는 데 매우 적합한 활동이다. 그리고 우리가 방금 배웠듯이, 흐름은 행복을 만들어 냅니다. 이 두 가지 개념을 결합하면 심층에 찬성하는 심리학의 강력한 주장을 얻을 수 있다. 십센트미할이의 원래 ESM 실험에서 비롯된 수십 년의 연구는 깊숙이 가는 행위가 삶을 가치 있게 만드는 방식으로 의식을 명령한다는 것을 검증한다. 칙센트미할이는 심지어 현대 기업이 이러한 현실을 받아들여야 한다고 주장하는 데까지 이르러 "일들은 가능한 한 흐름 활동을 가깝게 닮도록 재설계되어야 한다"고 제안한다. 그러나 그러한 재설계는 어렵고 파괴적일 것이다(예: 이전 장의 내 주장 참조), 칙센트미할이는 그 다음 개인이 흐름의 기회를 찾는 방법을 배우는 것이 훨씬 더 중요하다고 설명한다. 이는 결국 우리의 실험심리학 세계로의 짧은 진출에서 얻을 교훈으로, 딥 워크에서 생산된 흐름의 경험을 중심으로 직장생활을 구축하는 것은 깊은 만족감으로 가는 입증된 길이다.

### 철학적 관점에서 본 몰입의 가치

깊이와 의미 사이의 연결에 대한 우리의 마지막 주장은 우리가 신경과학과 심리학의 보다 구체적인 세계에서 한 걸음 물러나고 대신 철학적 관점을 채택할 것을 요구한다. 이 논의를 위해 이 주제를 잘 아는 한 쌍의 학자, 즉 40년 이상 버클리에서 철학을 가르친 후베르트 드레이푸스와 이 글을 쓰는 시점에 하버드 철학과 학과장인 션 도렌스 켈리에게 도움을 요청할 것이다. 드레스와 켈리는 2011년 인류 문화의 역사를 통해 신성함과 의미에 대한 관념이 어떻게 진화해 왔는지를 탐구하는 책 '모든 것이 빛난다'를 발표했다. 그들은 이 역사를 재구성하기 시작했는데, 왜냐하면 그들은 우리의 현재 시대에 그 종착점을 걱정하기 때문이다. "세계는 다양한 형태로 신성한 빛나는 것의 세계였다" 드레스와 켈리는 책의 초반에 설명한다. "지금 빛나는 것들은 멀리 떨어져 있는 것 같다."

그때와 지금 사이에 무슨 일이 있었나요? 저자들이 주장하는 단답은 데카르트이다. 데카르트의 회의론으로부터 확실성을 추구하는 개인이 진리를 부여하는 신이나 왕보다 우월하다는 급진적 믿음이 나왔다. 그로 인한 계몽주의는 당연히 인권의 개념으로 이어져 많은 사람들을 억압으로부터 해방시켰다. 그러나 드레스와 켈리가 강조하듯이, 정치 영역에서 모든 것의 선, 형이상학의 영역에서 이 사고는 의미를 창조하는 데 필수적인 질서와 신성성의 세계를 박탈했다. 개화 이후의 세계에서 우리는 무엇이 의미 있고 무엇이 아닌지 식별하는 임무를 맡았으며 이는 자의적으로 보일 수 있고 기묘한 허무주의를 유도할 수 있는 운동이다. "계몽주의가 자율적인 개인을 형이상학적으로 포용하는 것은 지루한 삶으로만 이어지지 않는다"고 드레스와 켈리는 걱정하며 "거의 필연적으로 거의 살 수 없는 삶으로 이어진다"고 말했다.

이 문제는 처음에는 깊이의 만족을 이해하려는 우리의 탐구에서 멀리 떨어진 것처럼 보일 수 있지만 드레스와 켈리의 솔루션으로 진행하면 전문적인 추구에서 의미의 원천에 대한 풍부한 새로운 통찰력을 발견할 것이다. 이러한 연결은 현대적 허무주의에 대한 드레스와 켈리의 대응이 이 장을 연 바로 그 주제인 장인 위에 기반을 두고 있다는 사실이 밝혀지면 덜 놀라운 것처럼 보아야 한다.

책 결론에서 드레스와 켈리는 장인 정신은 책임감 있는 방식으로 신성감을 다시 열 수 있는 열쇠를 제공한다고 주장한다. 이 주장을 설명하기 위해 그들은 목재 마차 바퀴를 만드는 잃어버린 직업인 마스터 휠라이터의 설명을 조직화 예로 사용한다. "각 나무 조각이 뚜렷하기 때문에 각기 고유한 개성을 지니고 있다"는 휠로이트의 공예에 대한 세부적인 내용을 기술한 대목을 마치고 쓴다. 목공은 자신이 작업하는 목재와 친밀한 관계를 맺고 있다. 그것의 미묘한 덕목은 길러지고 보살펴야 한다고 호소한다." 그의 매체의 '미묘한 덕목'에 대한 이러한 감상에서, 그들은 장인이 개화 이후 세계에서 중요한 것, 즉 개인의 외부에 위치하는 의미의 원천을 우연히 발견했다고 지적한다. 휠라이트는 자신이 작업하는 나무의 어떤 덕목이 가치 있고 어떤 것이 가치 없는지를 임의로 결정하지 않으며 이 가치는 나무와 수행해야 할 작업에 내재되어 있다.

드레스와 켈리가 설명하듯이, 그러한 신성함은 장인정신에 공통적이다. 이들은 "공예가의 임무는 의미를 생성하는 것이 아니라 이미 존재하는 의미를 분별하는 기술을 스스로 배양하는 것"이라고 결론지었다. 이는 공예가를 자율적 개인주의의 허무주의로부터 해방시켜 질서 있는 의미 세계를 제공한다. 동시에 이 의미는 이전 시대에 인용된 출처보다 더 안전한 것으로 판단된다. 저자들은 휠라이트가 소나무 조각의 고유한 품질을 쉽게 사용하여 전제 군주제를 정당화할 수 없다고 암시한다.

직업적 만족의 문제로 돌아가서, 의미로의 경로로서의 장인정신에 대한 드레스와 켈리의 해석은 왜 릭 푸레르와 같은 사람들의 작업이 우리 중 많은 사람들에게 공명하는지에 대한 미묘한 이해를 제공한다. 이러한 철학자들이 주장하듯, 푸레르가 조금속으로부터 예술성을 추출하기 위해 노력하는 그의 얼굴에 나타난 만족스러운 표정은 근대성이 파악하기 어렵고 가치 있는 것, 즉 신성한 것을 엿볼 수 있는 것에 대한 감사를 표현하는 표정이다.

일단 이해하면 우리는 전통 장인의 정신에 내재된 이러한 신성함을 지식 작업의 세계와 연결시킬 수 있다. 그러기 위해서는 먼저 우리가 해야 할 두 가지 핵심 관찰이 있다. 첫 번째는 분명할 수 있지만 강조해야 합니다. 이 특정 의미의 원천을 생성하는 것과 관련하여 수동 거래에 본질적인 것은 없습니다. 고수준의 기술을 뒷받침하는 신체적이든 인지적이든 모든 추구는 또한 신성감을 생성할 수 있다.

이 점을 구체화하기 위해 나무를 조각하거나 금속을 제련하는 구식 사례에서 컴퓨터 프로그래밍의 현대적인 사례로 뛰어들자. 코딩 신동 산티아고 곤살레스가 인터뷰에 참석한 인터뷰자에게 자신의 작품을 설명하는 이 인용문을 생각해 보자.

아름다운 코드는 짧고 간결해서 다른 프로그래머에게 그 코드를 주면 '아, 잘 쓰여진 코드구나'라고 말할 것이다. 마치 시를 쓰는 것과 같다.

곤잘레스는 드레스와 켈리가 인용한 구절에서 목공들이 자신의 공예를 이야기하는 방식과 유사하게 컴퓨터 프로그래밍을 논의한다.

컴퓨터 프로그래밍 분야에서 잘 알려진 책인 프래그마틱 프로그래머는 서문에서 중세 채석장 노동자의 신조를 인용함으로써 코드와 구식 장인 정신 사이의 이러한 연결을 더 직접적으로 만든다. "단순한 돌을 자르는 우리는 항상 성당을 상상하고 있어야 한다." 그런 다음 이 책은 컴퓨터 프로그래머가 자신의 작업을 동일한 방식으로 보아야 한다고 자세히 설명한다.

프로젝트의 전체 구조 내에서 항상 개성과 장인 정신의 여지가 있습니다. 100년 후 우리의 공학은 중세 성당 건축가가 사용하는 기술이 오늘날의 토목 기술자에게 보이는 것처럼 고풍스럽게 보일 수 있지만 우리의 장인 정신은 여전히 영광으로 여겨질 것이다.

다시 말해, 드레스와 켈리의 의미를 생성할 수 있는 장인 정신의 유형으로 간주되기 위해 야외 헛간에서 고생할 필요가 없다. 이와 유사한 장인정신의 잠재력은 정보 경제의 대부분의 숙련된 직종에서 찾을 수 있다. 작가든 마케터든 컨설턴트든 변호사든 당신의 일은 공예이며 당신이 당신의 능력을 연마하고 존중과 주의를 기울여 적용한다면, 당신은 숙련된 휠드라이프처럼 직업적인 삶의 일상적인 노력에서 의미를 창출할 수 있다.

일각에서는 자신의 직업 주제가 너무 평범하기 때문에 자신의 지식 업무 직업이 그러한 의미의 원천이 될 수 없다고 응답할 수 있다. 그러나 이것은 우리의 전통적인 장인 정신에 대한 고려가 교정에 도움이 될 수 있다는 잘못된 생각입니다. 현재 우리 사회에서는 직무 설명에 많은 중점을 두고 있습니다. 예를 들어, "네 열정을 따라야 한다"는 조언(내 마지막 책의 주제)에 대한 우리의 집착은 경력 만족을 위해 가장 중요한 것은 당신이 선택한 직업의 세부 사항이라는 (결함 있는) 생각에 의해 동기가 부여된다. 이러한 사고 방식에서 만족의 원천이 될 수 있는 일부 희귀 직업(아마도 비영리 단체에서 일하거나 소프트웨어 회사를 시작하는 것)이 있는 반면 다른 모든 직업은 영혼이 없고 싱겁다. 드레스와 켈리의 철학은 우리를 그러한 함정으로부터 해방시킨다. 그들이 인용하는 장인들은 희박한 직업을 가지고 있지 않다. 인류 역사 전반에 걸쳐 대장장이나 휠라이터가 되는 것은 화려하지 않았다. 그러나 작품의 구체적 내용은 관련이 없기 때문에 이것은 중요하지 않다. 그러한 노력으로 드러난 의미는 그들의 작업의 결과가 아니라 장인 정신에 내재된 기술과 감상에 기인한다. 다시 말해 나무 바퀴는 고귀하지 않지만 모양은 그럴 수 있다. 지식 업무도 마찬가지입니다. 당신은 희박한 직업이 필요하지 않으며 대신 자신의 일에 대한 희박한 접근법이 필요하다.

이 논증의 두 번째 핵심적인 관찰은 장인정신을 함양하는 것은 반드시 심화 과제이므로 심화 작업에 대한 헌신이 필요하다는 것이다. (제1장에서 기술 연마를 위한 심층 작업이 필요하고 이를 엘리트 수준에서 적용하기 위해 필요하다는 주장을 했음을 상기한다. 따라서 심층 작업은 드레스와 켈리가 설명한 방식으로 직업에서 의미를 추출하는 열쇠이다. 자신의 경력에서 딥 워크을 포용하고 기술을 함양하는 방향으로 향하는 것은 분산되고 지친 의무에서 만족스러운 것으로 지식 업무 직업을 전환할 수 있는 노력이며 빛나는 놀라운 것들이 가득한 세계로의 포털이다.

### 호모 사피엔스 디펜시스

1부의 처음 두 장은 실용적이었다. 그들은 심층근로가 우리 경제에서 점점 더 가치가 높아지고 있는 동시에 (다소 자의적인 이유 때문에) 점점 더 희귀해지고 있다고 주장했다. 이것은 고전적인 시장 불일치를 나타낸다: 당신이 이 기술을 배양하면, 당신은 전문적으로 번창할 것이다.

대조적으로, 이 마지막 장은 직장 진출에 대한 이러한 실제적 논의에 거의 기여할 것이 없지만 이러한 초기 아이디어가 주목을 받기 위해서는 절대적으로 필요하다. 앞쪽 페이지에는 전문 생활을 깊이 중심으로 전환하기 위한 엄격한 프로그램이 설명되어 있습니다. 이것은 어려운 전환이며 그러한 많은 노력과 마찬가지로 합리적이고 실용적인 주장은 어느 정도만 동기를 부여할 수 있다. 결국 추구하는 목표는 보다 인간적인 수준에서 공명받아야 한다. 이 장에서는 깊이의 포용에 있어서는 그러한 공명이 불가피하다고 주장한다. 심층적으로 들어가는 활동을 신경과학, 심리학, 고상철학의 관점에서 접근하든, 이 모든 경로는 다시 깊이와 의미의 연결로 이어지는 것 같다. 마치 우리 종이 깊이에서 번성하고 피상적인 영역에서 움푹 들어가고 우리가 호모 사피엔스 딥엔시스라고 부를 수 있는 것으로 진화한 것과 같다.

나는 앞서 깊이의 개신한 제자 위니프레드 갈러거의 말을 인용하여 "집중된 삶을 살 것이다, 왜냐하면 그것이 최고의 삶이기 때문이다." 이것은 아마도 이 장과 1부의 주장을 더 광범위하게 요약하는 가장 좋은 방법일 것이다. 깊은 삶은 어떤 식으로 보든 좋은 삶이다.

# 2부. 딥 워크를 실천하는 4가지 규칙

## 규칙 1. 몰입하라 (Work Deeply)

데이비드 드완이 듀폰 서클 술집에서 술 한잔을 마시며 만난 직후 그는 유다이모니아 머신을 떠올렸다. 데완은 건축학 교수로 개념적인 것과 구체적인 것의 교차점을 탐구하는 것을 좋아한다. 이 교차로에 대한 좋은 예로 유다이모니아 머신을 들 수 있다. 고대 그리스의 유다이모니아(유다이모니아의 개념)(인간 잠재력을 최대한 발휘하는 상태)에서 이름을 따온 기계는 건물인 것으로 밝혀졌다. 데이비드는 "기계의 목표"는 "사용자들이 인간적으로 융성하는 딥 워크인 상태로 들어갈 수 있는 환경을 만드는 것"이라고 설명하며 "사용자들이 개인적인 능력의 절대적인 범위에서 작품을 만드는 것"이라고 말했다. 즉, 가능한 가장 깊은 심층 작업을 가능하게 하는 유일한 목적을 위해 설계된 공간이다. 예상하듯이, 흥미로웠어요.

Dewane가 기계에 대해 설명하면서 그는 펜을 잡고 제안된 레이아웃을 스케치했다. 구조는 5개의 방으로 이루어진 1층의 좁은 직사각형으로, 줄지어 배치되어 있다. 공유 복도는 없으며 한 방을 통과해야 다음 방으로 이동할 수 있다. 드완이 설명하듯이, "[순환의 부족]은 당신이 기계 속으로 더 깊어질수록 어떤 공간도 우회할 수 없도록 하기 때문에 중요하다."

길을 나서 처음 들어가는 방은 갤러리라고 합니다. 드완의 계획에서 이 방에는 건물에서 생산된 심층 작업의 예가 포함될 것이다. 그것은 기계의 사용자를 고무시켜 '건강한 스트레스와 동료 압력의 문화'를 만들어내기 위한 것이다.

갤러리를 떠나면 다음으로 미용실에 들어갑니다. 여기서, 드와니는 고품질의 커피와 아마도 풀 바에 대한 접근을 상상한다. 소파와 와이파이도 있습니다. 살롱은 "강렬한 호기심과 논쟁 사이에서 떠돌아가는" 분위기를 조성하도록 설계되었다. 이것은 기계에서 더 깊이 발전할 아이디어를 통해 토론하고 "브루드"하고 일반적으로 작업하는 장소이다.

미용실 너머로 도서관으로 들어갑니다. 이 방에는 기계에서 생산된 모든 작업과 이 이전 작업에 사용된 책 및 기타 자원의 영구 기록이 저장됩니다. 프로젝트에 필요한 정보를 수집하고 수집하기 위한 복사기와 스캐너가 있습니다. 데완은 라이브러리를 '기계의 하드 드라이브'라고 설명한다.

다음 방은 사무실 공간입니다. 화이트보드가 있는 표준 회의실과 책상이 있는 일부 칸막이가 있습니다. "사무실"은 "낮은 강도의 활동을 위한 것"이라고 드완은 설명한다. 우리의 용어를 사용하자면, 이것은 당신의 프로젝트에서 요구하는 은 노력을 완성할 수 있는 공간이다. Dewane는 사무실에 책상이 있는 관리자를 상상하여 사용자의 업무 습관을 개선하여 효율성을 최적화할 수 있도록 도와줄 수 있다.

이것은 우리를 기계의 마지막 방으로 데려오는데, 디완이 "딥 워크실"이라고 부르는 것의 모음이다. 각 챔버는 6 x 10피트로 설계되었으며 두꺼운 방음벽으로 보호된다(드웨인의 계획은 18인치의 단열재를 요구한다). 딥 워크 챔버의 목적은 완전한 포커스와 중단 없는 작업 흐름을 허용하는 것이라고 드완은 설명한다. 그는 당신이 내부에서 90분을 보내고, 90분간 휴식을 취하고, 두세 번 반복하는 과정을 상상한다.

현재로서는 유다이모니아 기계가 건축도면의 모음으로만 존재하지만 계획으로도 영향력 있는 작업을 지원할 수 있는 잠재력은 드완을 흥분시킨다. 그는 "내 마음속에 이 디자인은 내가 지금까지 제작한 건축물 중 가장 흥미로운 작품으로 남아 있다"고 말했다.

딥 워크의 진정한 가치가 받아들여지고 축하되는 이상적인 세계에서 우리 모두는 유다이모니아 기계와 같피상적인 일에 접근할 수 있을 것이다. 데이비드 드완의 정확한 설계가 아니라, 더 일반적으로 말하자면, 우리가 우리의 뇌에서 가능한 한 많은 가치를 추출하는 데 도움이 되도록 설계된 작업 환경(및 문화)이다. 불행히도 이 비전은 현재 우리의 현실과 거리가 멀다. 대신 우리는 우편함을 무시할 수 없고 회의가 끊이지 않는 산만한 오픈 오피스에 처해 있으며 동료들은 가능한 최상의 결과를 산출하기보다 최신 이메일에 신속하게 응답하기를 선호합니다. 이 책의 독자로서, 다시 말해 당신은 은 세계에서 깊이의 제자이다.

이 책의 2부에서 4가지 규칙 중 첫 번째 규칙인 이 규칙은 이러한 갈등을 줄이기 위해 고안되었다. 자신의 유다이모니아 머신에 접근할 수 없지만 다음에 따르는 전략은 산만하게 활동하는 직업 생활에서 그 효과를 시뮬레이션하는 데 도움이 될 것이다. 그들은 딥 워크을 열망에서 일상 일정의 규칙적이고 중요한 부분으로 전환하는 방법을 보여줄 것이다. (규칙 #2~#4는 집중력을 훈련하고 방해되는 방해를 방지하기 위한 전략을 제시함으로써 이러한 딥 워크 습관에서 최대한 활용하는 데 도움이 될 것이다.

그러나 이러한 전략으로 진행하기 전에 먼저 당신을 잔소리할 수 있는 질문을 해결하고 싶습니다. 왜 우리는 그러한 개입이 필요한가? 다시 말해, 일단 심층 작업이 가치 있다는 것을 받아들이면, 더 상당한 작업을 시작하기에 충분하지 않나요? 우리가 더 자주 집중하는 것을 기억하는 것만큼 간단한 것을 위해 정말로 유다이모니아 기계(또는 그 등가물)처럼 복잡한 것이 필요한가?

불행히도 주의 분산을 초점으로 대체하는 것에 관해서는 문제가 그렇게 간단하지 않습니다. 이것이 왜 사실인지 이해하기 위해 깊이 들어가기 위한 주요 장애물 중 하나인 더 피상적인 것에 주의를 돌리고자 하는 욕구를 자세히 살펴보도록 하자. 대부분의 사람들은 이러한 충동이 어려운 일에 집중하려는 노력을 복잡하게 만들 수 있음을 인식하지만 대부분 그 규칙성과 강도를 과소평가한다.

심리학자인 빌헬름 호프만과 로이 바우메이스터가 주도한 2012년 연구를 고려해 볼 때, 무작위로 선택된 시간에 활성화된 비퍼를 성인 205명에게 장착했다(이는 1부에서 논의된 경험 샘플링 방법이다). 피험자는 비퍼가 울리면 잠시 멈춰서 현재 느끼고 있거나 지난 30분 동안 느꼈던 욕구를 반성한 다음 이러한 욕구에 대한 일련의 질문에 답하도록 요청받았다. 일주일 후, 연구자들은 7,500개 이상의 샘플을 수집했다. 그들이 발견한 것의 짧은 버전은 다음과 같다: 사람들은 하루 종일 욕망과 싸웁니다. 바우메이스터는 그의 후속 저서인 Willpower(과학작가 John Tierney와 공동 저술)에서 요약했듯이, "욕구는 예외가 아닌 규범으로 판명되었다."

이 피험자들이 싸운 가장 흔한 다섯 가지 욕망에는 당연히 식사, 수면, 성관계가 포함된다. 그러나 상위 5위 목록에는 "[힘든] 일을 쉬고... 이메일과 소셜 네트워킹 사이트를 확인하고 웹 서핑을 하거나, 음악을 듣거나, 텔레비전을 시청한다."에 대한 욕구도 포함되었다. 인터넷과 텔레비전의 미끼는 특히 강력하게 입증되었는데, 피험자들은 이 특히 중독성 있는 산만함에 대해 절반 정도만 저항하는 데 성공했다.

이러한 결과는 깊은 업무 습관을 기르는 데 도움이 되는 이 규칙의 목표에 대한 나쁜 소식이다. 그들은 하루 종일 깊이 일하지 않고 무엇이든 하고 싶은 욕구에 충격을 받을 것으로 예상할 수 있으며 당신이 호프만과 바우메이스터 연구의 독일 피험자와 같은 경우 이러한 경쟁 욕구가 종종 승리할 것이라고 말한다. 당신은 깊이의 중요성을 이해하고 있기 때문에 이러한 과목이 실패한 곳에서 성공할 것이며 따라서 집중된 상태를 유지하려는 의지에 더 엄격할 것이라고 이 시점에서 대답할 수 있다. 이는 고귀한 정서이지만 이 연구를 선행한 수십 년간의 연구는 그 무용성을 강조한다. 로이 바우메이스터가 저술한 선구 논문 시리즈에서 시작된 이제 막대한 탐구 라인은 의지력에 대한 다음의 중요한 (그리고 당시에는 예상치 못한) 진실을 확립했다: 당신은 그것을 사용하면서 고갈되는 유한한 양의 의지를 가지고 있다.

즉, 당신의 의지는 당신이 한없이 전개할 수 있는 당신의 인격의 발현이 아니라 오히려 지쳐가는 근육과 같다. 이것이 호프만과 바우메이스터 연구의 피험자들이 욕망과 싸우는 데 그렇게 힘든 이유인데, 시간이 지남에 따라 이러한 산만함은 더 이상 저항할 수 없을 때까지 그들의 유한한 의지 풀을 배출했다. 당신의 의도에 관계없이, 즉 당신이 습관에 대해 똑똑하지 않은 한, 당신에게도 마찬가지일 것이다.

이는 다음 전략 뒤에 있는 동기 부여 아이디어로 이어진다: 딥 워크 습관을 형성하는 열쇠는 좋은 의도를 넘어 지속적인 집중 상태로 전환하고 유지하는 데 필요한 제한된 의지력의 양을 최소화하도록 설계된 작업 생활에 일상과 의식을 추가하는 것이다. 예를 들어, 당신이 갑자기, 웹 브라우징에 소비된 산만한 오후의 한가운데에서, 주의를 인지적으로 까다로운 작업으로 전환하기로 결정하면, 당신은 당신의 유한한 의지력으로부터 온라인 광채에서 주의를 끌기 위해 크게 끌 것이다. 따라서 그러한 시도는 종종 실패할 것이다. 반면에, 스마트 루틴과 의식을 배치했다면, 아마도 매일 오후에 딥 워크에 사용되는 설정된 시간과 조용한 장소를 배치한다면 시작하고 계속 진행하는 데 훨씬 적은 의지력이 필요할 것이다. 따라서 장기적으로 이러한 깊은 노력으로 훨씬 더 자주 성공할 수 있을 것이다.

이를 염두에 두고 다음의 6가지 전략피상적 작업정에 일관되게 수행하는 심화 작업의 양을 극대화하기 위해 제한된 의지력의 과학을 염두에 두고 설계된 루틴과 의식의 무기고로 이해할 수 있다. 무엇보다도, 그들은 당신에게 이 작업을 스케줄링하기 위한 특정 패턴에 전념하고 매 회기를 시작하기 전에 집중력을 높이기 위한 의식을 개발하도록 요청할 것이다. 이러한 전략 중 일부는 뇌의 동기 중심을 탈취하기 위해 간단한 휴리스틱을 배치하는 반면 다른 전략은 가능한 한 빠른 속도로 의지력 보유량을 충전하도록 설계되었다.

심층 작업을 우선시할 수 있습니다. 그러나 이 결정을 따르는 전략(또는 동일한 원칙에 의해 동기가 부여되는 자신의 계획)으로 지원하면 심층 작업을 직업 생활의 중요한 부분으로 만드는 데 성공할 가능성이 크게 높아진다.

### 나만의 몰입 철학을 선택하라

유명한 컴퓨터 과학자 도널드 커누스는 심층 작업을 신경 쓴다. 그가 자신의 웹사이트에서 설명하는 것처럼 "내가 하는 일은 오랜 시간의 공부와 중단 없는 집중력이 필요하다." 전업의 아버지인 브라이언 채펠이라는 박사 후보도 시간이 제한되어 있는 상황에서 논문을 진전시킬 수 있는 유일한 방법이기 때문에 딥 워크을 중요하게 여긴다. 채펠은 딥 워크이라는 아이디어를 처음 접한 것이 '감성적인 순간'이었다고 나에게 말했다.

나는 이러한 예를 언급하는데, 이는 넛과 채펠이 깊이의 중요성에 동의하지만 이 깊이를 자신의 작품 생활에 통합하는 철학에 대해서는 동의하지 않기 때문이다. 다음 절에서 자세히 설명하겠지만 노우스는 다른 모든 유형의 작업을 제거하거나 최소화하여 심층 작업을 우선시하는 수도원주의의 한 형태를 전개한다. 이에 반해 채플은 평일 아침마다 예외 없이 같은 시간(오전 5시∼오후 7시 30분)씩 일하다가 표준적인 산만함으로 쪼개진 일정을 시작하는 리듬적인 전략을 펼친다. 두 가지 접근법 모두 효과가 있지만 보편적이지 않다. 노우스의 접근법은 주요 직업적 의무가 큰 생각을 하는 사람에게는 의미가 있을 수 있지만 만약 채펠이 은 모든 것에 대한 유사한 거부를 채택했다면 그는 직장을 잃을 가능성이 있다.

딥 워크을 직업 생활에 통합하기 위한 자신만의 철학이 필요합니다. (이 규칙의 서론에서 주장한 바와 같이, 임시 방식으로 심층 작업을 스케줄링하려고 시도하는 것은 제한된 의지력을 관리하는 효과적인 방법이 아니다.) 그러나 이 예는 이 선택에 대한 일반적인 경고를 강조하는데, 여기에서 불일치가 굳어질 기회가 있기 전에 딥 워크 습관을 떨어뜨릴 수 있으므로 특정 상황에 맞는 철학을 선택하는 데 주의해야 한다. 이 전략은 내가 실제로 매우 잘 작동하는 것을 본 네 가지 다른 깊이 철학을 제시함으로써 이러한 운명을 피하는 데 도움이 될 것이다. 목표는 심층 작업을 일정에 통합하는 다양한 방법이 있음을 확신시키는 것이므로 자신에게 맞는 접근법을 찾는 데 시간을 할애할 가치가 있다.

심층 작업 스케줄링의 수도원 철학

도널드 커누스로 돌아가보자. 그는 특히 알고리즘 성능을 분석하는 엄격한 접근법의 개발을 포함하여 컴퓨터 과학의 많은 혁신으로 유명하다. 그러나 그의 또래들 사이에서도 노우트는 전자통신에 대한 접근방식에 대해 명예훼손의 아우라를 유지하고 있다. 만약 당신이 그의 이메일 주소를 찾으려고 스탠퍼드의 넛의 웹사이트를 방문한다면, 당신은 대신 다음의 메모를 발견할 것이다.

나는 더 이상 이메일 주소가 없는 1990년 1월 1일 이후로 항상 행복한 사람이었다. 나는 1975년경부터 이메일을 사용했는데, 15년의 이메일은 한 평생 동안 충분하다고 생각한다. 이메일이란 삶의 역할이 무엇보다 중요한 사람들에게 훌륭한 것입니다. 하지만 저에게는 그렇지 않습니다. 제 역할피상적 작업의 바닥에 있는 것입니다. 제가 하는 일은 오랜 시간 동안 공부하고 중단 없이 집중해야 합니다.

너트는 자신은 세상으로부터 완전히 자신을 단절하려는 의도가 아님을 인정한다. 그는 자신의 책을 쓰기 위해서는 수천 명의 사람들과의 소통이 필요하며 질문과 댓글에 반응하고 싶다고 언급한다. 그의 해결책? 그는 주소, 즉 우편 우편 주소를 제공한다. 그는 자신의 행정보조원이 그 주소로 도착하는 모든 편지를 분류하고 관련성이 있다고 생각하는 편지를 따로 남겨두겠다고 말한다. 그녀가 진정으로 급한 것은 무엇이든 즉시 노우트에게 가져다 줄 것이고 다른 모든 것은 그가 3개월에 한 번씩 대량으로 처리할 것이다.

노우트는 내가 말하는 딥 워크 스케줄링의 수도원 철학을 전개한다. 이 철학은 은 의무를 제거하거나 근본적으로 최소화함으로써 깊은 노력을 극대화하고자 한다. 수도원 철학의 실천자들은 그들이 추구하는 직업적 목표가 잘 정의되고 매우 가치 있는 경향이 있으며 그들의 직업적 성공의 대부분은 이 한 가지 일을 예외적으로 잘 수행하는 데서 비롯된다. 노동 세계에서 가치 제안이 더 다양하게 구성된 사람들을 위축시키는 경향이 있는 은 우려의 기를 제거하는 데 도움이 되는 것은 이러한 명확성이다.

예를 들어, 넛은 그의 직업적 목표를 다음과 같이 설명합니다. "컴퓨터 과학의 특정 영역을 철저히 배우려고 노력하다; 그런 다음 그러한 연구에 시간이 없는 사람들이 접근할 수 있는 형태로 그 지식을 소화하려고 노력합니다." 트위터에서 청중을 구축하는 무형의 수익에 대해 넛을 피칭하려고 시도하거나 이메일을 보다 자유롭게 사용함으로써 발생할 수 있는 예상치 못한 기회를 놓치려고 시도합니다. 이러한 행동은 컴퓨터 과학의 특정 코너를 철저히 이해하고 접근 가능한 방식으로 그것에 대해 작성하는 그의 목표를 직접적으로 돕지 않기 때문입니다.

수도원 딥 워크에 헌신한 또 다른 인물은 평가를 받는 SF 작가 닐 스티븐슨이다. 만약 당신이 스티븐슨의 저자 웹사이트를 방문한다면, 당신단순 이메일이나 우편 주소가 부족하다는 것을 알게 될 것이다. 우리는 2000년대 초에 스티븐슨이 자신의 초기 웹사이트(더 웰에서 호스팅)에 게시하고 인터넷 아카이브에서 보존한 한 쌍의 에세이에서 이러한 누락에 대한 통찰력을 얻을 수 있다. 2003년에 보관된 그러한 에세이 중 하나에서, 스티븐슨은 그의 커뮤니케이션 정책을 다음과 같이 요약한다.

나의 집중을 방해하려는 사람들에게는 그렇게 하지 말 것을 정중히 요청하고 나는 이메일에 답하지 않는다... [내 커뮤니케이션 정책의] 핵심 메시지가 구술에 빠져들지 않도록 주의를 기울여, 나는 여기에 간결하게 말할 것이다: 내 모든 시간과 주의가 여러 번 동안 말했다. 그들에게 요청하지 마십시오.

이러한 정책을 더욱 정당화하기 위해, 스티븐슨은 "내가 왜 나쁜 특파원인가"라는 제목의 에세이를 썼다. 그의 접근 불가능성에 대한 설명의 핵심은 다음과 같은 결정이다.

생산성 방정식은 비선형 방정식, 즉 생산성 방정식이다. 이것이 제가 나쁜 특파원인 이유와 제가 연설 약속을 거의 받아들이지 않는 이유를 설명합니다. 길고 연속적이며 끊김 없는 타임 을 많이 얻는 방식으로 삶을 정리하면 소설을 쓸 수 있다. 하지만 그 덩어리가 분리되고 파편화되면서 소설가로서의 생산성은 눈에 띄게 떨어집니다.

스티븐슨은 좋은 소설을 정규 비율로 쓸 수도 있고, 개별적인 이메일에도 많이 답하고 회의에 참석할 수도 있으며, 결과적으로 더 느린 비율로 질이 낮은 소설을 생산할 수도 있다는 두 가지 상호 배타적인 선택지를 본다. 그는 전자의 선택을 하였고 이 선택은 그가 직업생활에서 피상적 작업의 근원을 최대한 피하도록 요구한다. (이 문제는 스티븐슨에게 매우 중요하여 그는 2008년 SF 서사시인 아나템에서 그 함의를 탐구하기 위해 계속 갔는데, 이 문제는 지적 엘리트가 정신이 산만해진 대중과 기술로부터 고립된 채 깊은 생각을 하며 수도원 질서 속에서 사는 세계를 고려한다.)

나의 경험에 따르면, 수도원 철학은 많은 지식 노동자들을 방어적으로 만든다. 그것의 추종자들이 세계에 자신의 가치를 식별하는 명확성은 정보 경제에 대한 기여가 더 복잡한 사람들에게 생신경을 건드리는 것 같다. 물론 '더 복잡하다'는 '더 작다'는 것을 의미하지 않는다는 점에 주목하라. 예를 들어, 고위 관리자는 완성된 소설과 같은 별개의 것을 가리키지 못하고 "올해 내가 생산한 것이다."라고 말할 수 없더라도 수십억 달러 규모의 회사의 기능에 중요한 역할을 할 수 있다. 따라서 수도원 철학이 적용되는 개인의 풀은 제한적이며 그것은 괜찮다. 당신이 이 수영장 밖에 있다면, 그것의 급진적인 단순성은 너무 많은 부러움을 드러내지 않아야 한다. 반면에, 당신이 이 풀 안에 있다면, 이 세상에 대한 기여가 이산적이고 명확하며 개별화된 사람라면, 이 철학은 평균적인 경력과 기억될 경력 사이의 결정 요인이 될 수 있으므로 진지하깊이 있게 고려해야 한다.

심층 작업 스케줄링의 바이모달 철학

이 책은 혁명 심리학자이자 사상가인 칼 융에 대한 이야기로 개봉했다. 융은 멘토인 지그문트 프로이트의 제약으로부터 벗어나려는 동시대인 1920년대에 볼링겐이라는 작은 마을 밖 숲속에 지은 소박한 돌집으로 정기적인 수련을 시작했다. 그곳에 가면 융은 매일 아침 최소한으로 마련된 방에 자신을 가둬 쉬지 않고 글을 쓰곤 했다. 그는 다음 날 글을 쓰기 위해 명상을 하고 숲을 거닐면서 자신의 생각을 명확히 했다. 나는 이러한 노력들이 정의 심층적인 작업의 강도를 프로이트와 그의 많은 지지자들과의 지적 투쟁에서 성공할 수 있는 수준으로 높이기 위한 것이라고 주장했다.

이 이야기를 회상하면서 중요한 점을 강조하고 싶다: 융은 딥 워크에 대한 수도원적 접근을 전개하지 않았다. 앞서 본 우리의 예인 도널드 커누스와 닐 스티븐슨은 직업 생활에서 산만함과 함을 완전히 없애고자 하였다. 정은 이와는 대조적으로 그가 퇴각에서 보낸 기간 동안에만 이러한 제거를 추구했다. 융은 남은 시간을 수도원 생활 이외에 모든 것이 다름없는 취리히에서 보냈으며, 밤늦게까지 환자를 자주 볼 수 있는 바쁜 임상 실습을 운영했고, 취리히 커피하우스 문화의 적극적인 참여자였으며, 그는 도시의 존경받는 대학에서 많은 강의를 하고 참석했다. (아인슈타인은 취리히의 한 대학에서 박사 학위를 받았고 나중에 다른 대학에서 가르쳤는데, 흥미롭게도 그는 정을 알고 있었고 두 사람은 아인슈타인의 특수 상대성 이론의 핵심 아이디어를 논의하기 위해 여러 회식을 함께 했다.) 즉, 융의 취리히에서의 삶은 초연결된 디지털 시대 지식 노동자의 현대적 원형과 여러 면에서 유사하다. "주리히"를 "샌프란시스코"로, "편지"를 "트윗"으로 대체하고 우리는 일부 핫샷 기술 CEO에 대해 논의할 수 있다.

정의 접근 방식은 내가 심층 작업의 이원적 철학이라고 부르는 것이다. 이 철학은 당신이 시간을 나누고, 명확하게 정의된 스트레치를 깊은 추구에 할애하고, 나머지는 다른 모든 것에 열어 두도록 요청한다. 깊은 시간 동안 이중 모드 작업자는 강렬하고 중단되지 않은 집중을 추구하는 수도원적 행동을 할 것이다. 은 시간 동안에는 그러한 초점이 우선시되지 않는다. 딥 워크인 일과 열린 것 사이의 이러한 시간 분할은 여러 척도로 일어날 수 있다. 예를 들어, 일주일 규모로 4일간의 주말을 깊이에 할애하고 나머지는 개방 시간에 할애할 수 있습니다. 마찬가지로, 한 해의 규모에서, 당신은 당신의 깊은 스트레칭의 대부분을 담기 위해 한 계절을 할애할 수 있다(많은 학자들이 여름이나 안식일에 하는 것처럼).

이중 모드 철학은 심층 작업이 극도의 생산성을 생산할 수 있다고 믿지만 피험자가 그러한 노력에 충분한 시간을 할애하여 최대 인지 강도에 도달해야 진정한 돌파구가 발생하는 상태이다. 이 철학에서 심층 작업을 위한 최소 단위 시간은 적어도 하루가 넘치는 경향이 있는 이유이다. 예를 들어 아침에 몇 시간을 따로 두는 것은 이 접근법을 고수하는 사람에게 딥 워크 스트레치로 간주하기에는 너무 짧다.

동시에, 바이모달 철학피상적 작업반적으로 비심오한 추구에 대한 실질적인 약속이 없는 상황에서 성공할 수 없는 사람들에 의해 전개된다. 예를 들어, 융은 청구서를 지불하기 위해 그의 임상 실습과 그의 사고를 자극하기 위해 취리히 커피하우스 장면이 필요했다. 두 모드 사이에서 전환하는 접근법은 두 가지 요구를 모두 잘 충족시키는 방법을 제공한다.

행동에서 이원적 철학의 보다 현대적인 예를 제공하기 위해 우리는 Part 1에서 작업 습관에 대한 사려 깊이가 처음 소개된 워튼 비즈니스 스쿨의 교수인 Adam Grant를 다시 한 번 생각해 볼 수 있다. 기억하시겠지만 그랜트가 와튼에서 교수직을 급격히 상승한 동안의 일정은 좋은 이중 모달리티 사례 연구를 제공한다. 학년 규모에서 한 학기에 자신의 과정을 쌓아 두어 다른 한 학기를 심화 작업에 집중할 수 있도록 하였다. 이 깊은 학기 동안 그는 주간 규모에서 이중 모드 접근법을 적용했다. 그는 한 달에 한두 번쯤이면 2∼4일 정도 걸려 완전히 수도원이 될 것이다. 그는 문을 닫고 사무실 밖 자동 응답기를 자신의 이메일에 넣고 중단 없이 자신의 연구를 수행할 것이다. 이러한 깊은 세션 외부에서 그랜트는 공개되고 접근할 수 있는 것으로 유명하다. 어떤 의미에서 그는 2013년 베스트셀러인 Give and Take가 전문직 진출의 핵심 전략으로 어떤 대가로 무엇을 기대하지 않고 시간과 주의를 기울이는 관행을 촉진해야 했다.

심층근로의 이원적 철학을 전개하는 사람들은 수도원의 생산성에 감탄하면서도, 노동생활에서 은 행동으로부터 받는 가치를 존중한다. 아마도 이 철학을 구현하는 데 가장 큰 장애물은 짧은 기간의 심층 작업에도 현재 직책에서 부족한 많은 사람들이 두려워하는 유연성이 필요하다는 것이다. 만약 당신의 받은 편지함에서 한 시간 떨어져 있어도 불편하다면, 한 번에 하루 이상 사라지는 생각은 확실히 불가능해 보일 것이다. 하지만 저는 바이모달 작업이 당신이 추측하는 것보다 더 많은 유형의 작업과 호환될 수 있다고 생각합니다. 앞서 예를 들어, 나는 하버드 경영대학원 레슬리 펄로우 교수의 연구를 설명했다. 본 연구에서는 경영 컨설턴트 그룹에 매주 하루 종일 단절하도록 하였다. 컨설턴트들은 고객이 반항할 것을 두려워했습니다. 클라이언트는 신경 쓰지 않는 것으로 드러났다. Jung, Grant, Perlow의 연구 대상들이 발견했듯이, 사람들피상적 작업반적으로 이러한 기간이 잘 정의되고 잘 광고된다면 사람들이 접근할 수 없게 되는 권리를 존중할 것이며 이러한 기간을 벗어나면 다시 한 번 쉽게 찾을 수 있다.

심층 작업 스케줄링의 리드미컬 철학

세인펠드 쇼 초창기에는 제리 세인펠드가 바쁜 투어 일정을 소화하며 워킹 코믹으로 남았다. 당시 오픈 마이크 야간 작업을 하던 브래드 아이작이라는 작가이자 만화가 무대에 오르기 위해 대기하던 클럽에서 세인펠드를 우연히 만난 것도 이 시기였다. 아이작은 나중에 이제 고전적인 라이프하커 기사에서 설명했듯이 "나는 내 기회를 보았다. 나는 신펠드에 젊은 만화를 위한 팁이 있는지 물어봐야 했다. 그가 나에게 말한 것은 나에게 평생 유익할 것"이라고 말했다.

세인펠트는 아이작에게 충고를 시작한 것은 "더 좋은 만화가 되는 방법은 더 좋은 농담을 만드는 것"이라고 언급한 뒤, 더 좋은 농담을 만드는 방법은 매일 쓰는 것이라고 설명했다. 세인펠드는 이 규율을 유지하는데 도움을 주기 위해 그가 사용한 특정한 기술을 설명하면서 계속했다. 그는 벽에 달력을 보관합니다. 그가 농담을 쓰는 날마다 달력에 큰 빨간색 X로 날짜를 깎아낸다. "몇 날 후에 당신은 사슬을 갖게 될 것이다."라고 세인펠트는 말했다. "그냥 계속하면 그 사슬은 매일 더 길어질 것이다. 당신은 그 사슬을 보고 좋아할 것이고 특히 당신이 몇 주 동안 당신의 벨트 아래 있을 때. 다음으로 해야 할 일은 사슬을 끊지 않는 것뿐"이라고 말했다.

이 연쇄 방식(지금 어떤 사람들은 그것을 부르고 있음)은 곧 작가와 피트니스 애호가들 사이에서 히트를 탔습니다. 우리의 목적을 위해 그것은 당신의 삶에 깊이를 통합하는 일반적인 접근법, 즉 리듬 철학의 구체적인 예를 제공한다. 이 철학은 심층근무 세션을 일관되게 시작하는 가장 쉬운 방법은 단순 정규 습관으로 전환하는 것이라고 주장한다. 다시 말해, 목표는 당신이 깊숙이 들어갈 것인지 언제인지를 결정하는 데 에너지를 투자할 필요가 없는 이 작업의 리듬을 생성하는 것이다. 체인 방식은 간단한 스케줄링 휴리스틱(일일일 일을 하라)과, 캘린더에 적색의 큰 X를 떠올리는 쉬운 방법을 결합했기 때문에 심층 작업 스케줄링의 리드미컬한 철학의 좋은 예이다.

리듬 철학을 구현하는 또 다른 일반적인 방법은 체인 방식의 시각적 도움을 심층 작업을 위해 매일 사용하는 설정된 시작 시간으로 대체하는 것이다. 작업 진행의 시각적 지표를 유지하는 것이 심층 진입에 대한 장벽을 줄일 수 있는 것과 마찬가지로, 하루 중 작업을 수행하는 시간과 같은 가장 간단한 일정 결정도 제거하여 이 장벽을 줄인다.

이 전략의 서두에서 소개한 바쁜 박사 후보인 브라이언 채펠의 예를 생각해 보자. Chappell은 필요에 의해 심층적인 작업 스케줄링이라는 리듬 철학을 채택하였다. 그가 논문 작성을 강화하던 무렵, 그는 학생이었던 캠퍼스의 한 센터에서 정규직으로 취업 제안을 받았다. 프로적으로는 좋은 기회였고 채펠은 이를 기꺼이 받아들였다. 그러나 학문적으로 전일제 직업, 특히 최근 채펠의 첫째 자녀가 도착한 것과 결합했을 때 논문 장을 작성하는 데 필요한 깊이를 찾기가 어려웠다.

Chappell은 딥 워크에 대한 막연한 몰입을 시도하면서 시작하였다. 그는 90분 분량으로 심층 작업이 이루어져야 한다는 규칙을 만들었고(집중 상태에 도달하는 데 시간이 걸린다는 것을 정확히 인식하고) 자신의 일정에 적절한 개설이 발생할 때마다 임시 방식으로 이러한 분량을 계획하기로 결정했다. 당연히 이 전략은 많은 생산성을 산출하지 못했다. 채펠은 전년도에 참석한 논문 훈련 캠프에서 엄격한 심층 작업으로 일주일 만에 전체 논문 장을 제작할 수 있었다. 그는 정규직을 수락한 후, 근무하는 첫 해 전체에 단 한 개의 추가 장만 제작할 수 있었다.

채펠이 리듬적인 방식을 수용하게 된 계기는 바로 올해 동안의 빙하 글쓰기 진행이었다. 그는 매일 아침 5시 반까지 일어나 일을 시작한다는 규칙을 만들었다. 그는 7시 반까지 일하고 아침을 만들어 그날의 논문 의무를 이미 다한 채로 출근할 것이다. 그는 이른 진행에 만족해 곧 잠에서 깨는 시간을 45시까지 밀려 더 많은 아침 깊이를 끌어냈다.

이 책을 위해 채플을 인터뷰했을 때 그는 심층 작업 스케줄링에 대한 리드미컬한 접근법을 "천문학적으로 생산적이고 죄책감 없는" 것으로 설명했습니다. 그의 루틴은 하루에 4~5페이지의 학술 산문을 생산하고 2~3주에 한 장씩의 비율로 논문 장의 초안을 생성할 수 있었으며 이는 9~5개의 직무를 수행한 사람에게도 놀라운 결과물이었다. "내가 그렇게 생산적일 수 없다고 말하는 사람은 누구인가?"라고 그는 결론지었다. 왜 내가 안 돼.

리듬 철학은 이중 모드 철학과 흥미로운 대조를 제공한다. 아마도 이중 모달리스트가 선호하는 하루 동안의 집중 세션에서 추구하는 가장 강렬한 수준의 깊은 사고를 달성하지 못할 것이다. 그러나 이러한 접근 방식이 인간 본성의 현실과 더 잘 맞다는 것이 절충점이다. 규칙적으로 조금만 수행하도록 하는 단단한 루틴으로 심층 작업을 지원함으로써 리드미컬 스케줄러는 종종 연간 더 많은 총 심층 시간을 기록할 것이다.

리듬과 바이모달 사이의 결정은 이러한 스케줄링 문제에서 자기 통제로 귀결될 수 있다. 당신이 칼 융이고 지그문트 프로이트의 지지자들과 지적 다툼을 벌이고 있다면, 당신은 자신의 아이디어에 집중할 시간을 찾는 것의 중요성을 인식하는 데 큰 어려움이 없을 것이다. 반면에 논문을 작성하는 동안 아무도 그것을 하도록 강요하지 않는다면, 진보를 유지하기 위해 리듬 철학의 습관적 성격이 필요할 수 있다.

그러나 많은 사람들에게는 리듬 철학으로 편향되는 것은 자기 통제 문제뿐 아니라, 깊숙이 갈 필요가 생기는 시기에 일부 직업이 며칠 동안 사라지도록 허용하지 않는 현실이다. (대부분의 상사에게 있어서 그 기준은 상사의 이메일이 여전히 신속하게 회신되는 한... 마음껏 집중할 수 있다는 것이다. 이는 리듬 철학이 표준 사무직 심층근로자 사이에서 가장 흔한 것 중 하나인 가장 큰 이유일 것이다.

심층 작업 스케줄링의 저널리즘 철학

1980년대에는 30대인 언론인 월터 아이작슨이 타임지의 급속한 상승을 잘 따라갔다. 이쯤 되면 그는 의심할 여지 없이 사고 수업의 눈앞에 있었다. 예를 들어, 이 시기 런던 도서평론에 글을 쓴 크리스토퍼 히친스는 그를 "미국 최고의 잡지 저널리스트 중 한 명"이라고 불렀다. 그래서 아이작슨은 복잡한 주제인 냉전 초기 정책에 중요한 역할을 한 6명의 인물의 얽힌 서사적 전기를 선택하고 동료 젊은 타임 편집자인 에반 토머스와 팀을 이뤄 864페이지의 서사시 '지혜로운 남자: 여섯 명의 친구와 그들이 만든 세계'라는 제목의 적절한 무게를 지닌 책을 제작했다.

1986년에 출판된 이 책은 적임자들에게 좋은 평가를 받았다. 뉴욕타임스는 "풍부하게 짜여진 계정"이라고 불렀고 샌프란시스코 크로니클은 두 젊은 작가들이 "냉전 플루타르크를 양식화했다"고 기뻐했다. 10년도 채 되지 않아 아이작슨은 타임의 편집자로 임명되면서 저널리즘 경력의 정점에 도달했다.

그러나 아이작슨에 대해 내가 관심을 갖는 것은 그가 첫 책으로 무엇을 성취했는지가 아니라 그가 어떻게 썼는지이다. 이 이야기를 밝히는데 있어서 나는 행운의 인적 연결에서 도출해야 한다. 알고 보니, 위즈맨이 출판되기 전 몇 년 동안, 당시 뉴욕에서 기자로 활동하던 삼촌 존 폴 뉴포트는 아이작슨과 여름 해변 임대를 공유했다. 삼촌은 현재까지도 아이작슨의 인상적인 업무 습관을 기억하고 있다.

그는 항상 놀랍다... 그는 우리 모두가 파티오에서 또는 그 어떤 곳에서 서늘할 때 자신의 책을 작업하기 위해 잠시 침실로 후퇴할 수 있었고... 그는 20분 또는 1시간 동안 올라가, 우리는 타자기를 두드리는 소리를 듣고 그 다음 그는 우리처럼 편안하게 내려왔을 것이다... 일은 그를 괴롭히지 않는 것 같았으며 그는 여가 시간이 있을 때 행복하게 업그레이드했다.

아이작슨은 방법적이었는데, 자유시간을 찾을 때마다 딥 워크 모드로 전환하고 책을 망치질했다. 이렇게 해서, 결국, 하루의 대부분을 보내는 동안, 900페이지짜리 책을 옆으로 쓸 수 있는 것은, 국내 최고의 잡지 작가 중 한 명이 되는 것이다.

나는 당신이 할 수 있는 곳마다 심층 작업을 일정에 맞게 하는 이 접근 방식을 언론인 철학이라고 부른다. 이 이름은 월터 아이작슨과 같은 기자가 자신의 직업의 기한 중심적 성격이 요구하는 바와 같이 순간적으로 쓰기 모드로 전환하도록 훈련된다는 사실을 겨낸 것이다.

이 접근법은 심층 작업 초보자를 위한 것이 아닙니다. 내가 이 규칙의 서두에서 설시했듯이, 피상 모드에서 딥 워크 모드로 빠르게 마음을 전환하는 능력은 자연스레 오지 않는다. 연습이 없으면 그러한 스위치는 유한한 의지력 보유량을 심각하게 고갈시킬 수 있다. 이 습관은 또한 자신의 능력에 대한 자신감, 즉 자신이 하고 있는 일이 중요하고 성공할 것이라는 확신을 요구한다. 이러한 유형의 확신피상적 작업반적으로 기존의 전문적 성취를 기반으로 구축된다. 예를 들어, 아이작슨은 이 시점까지 존경받는 작가로 발돋움하기 위해 스스로 노력했기 때문에, 예를 들어, 첫 번째 소설가보다 글쓰기 모드로 전환하는 것이 더 쉬운 시간을 가졌을 것이다. 그는 자신이 서사전적 전기를 쓸 수 있는 역량을 가지고 있다는 것을 알고 있었고 이를 자신의 전문적 진출에 있어 핵심 과제로 이해했다. 이러한 자신감은 노력에 대한 동기 부여에 큰 도움이 된다.

나는 이러한 노력을 일정에 통합하는 것이 나의 주요 접근 방식이기 때문에 심층 작업이라는 저널리즘 철학에 편중한다. 즉, 나는 내 심오한 일에 승려가 아니지만(동료 컴퓨터 과학자 도널드 노우트의 사과 없는 단절에 가끔 질투를 느낀다), 바이모달리스트처럼 다일 깊이 뱅을 배치하지 않으며, 리듬 철학에 흥미를 느끼지만, 내 일정피상적 작업상적인 습관을 강요하려는 시도를 좌절시키는 방법이 있다. 대신 아이작슨에게 올리는 노랫말에서 나는 매주 도착하는 대로 마주하며 최대한 깊이를 짜내기 위해 최선을 다한다. 예를 들어, 이 책을 쓰기 위해, 나는 그들이 튀어나오는 곳마다 자유로운 시간을 활용해야 했다. 아이들이 잘 자고 있다면 노트북을 들고 집 사무실에 갇혀 있을 거예요. 아내가 주말에 인근 아나폴리스에 있는 부모님을 방문하고 싶다면, 나는 추가적인 돌봄을 이용하여 그들의 집의 조용한 구석으로 사라져 글을 쓸 것이다. 직장에서 회의가 취소되거나 오후가 남아 있으면 캠퍼스에서 내가 가장 좋아하는 도서관 중 하나로 퇴각하여 몇 백 단어를 더 짜낼 수도 있다. 그리고.

나는 내가 언론인 철학을 적용하는 데 순수하지 않다는 것을 인정해야 한다. 예를 들어, 나는 모든 심층 업무 결정을 순간적으로 내리지 않는다. 대신 나는 매주 초에 깊숙이 일할 때를 지도로 작성한 다음 매일의 시작에 필요한 대로 이러한 결정을 수정하는 경향이 있습니다. 순간순간 깊이 있는 일에 대한 의사결정을 할 필요성을 줄임으로써 깊이 있는 사고 자체를 위한 정신 에너지를 더 많이 보존할 수 있다.

최종 회계에서는 심층 업무 스케줄링이라는 저널리즘 철학이 여전히 잘 풀리지 않는다. 그러나 당신이 생산하려는 것의 가치에 자신이 있고 깊이 들어가기(추후 전략에서 계속 개발할 기술)의 기술을 연습한다면, 그것은 그렇지 않으면 까다로운 일정에서 많은 양의 깊이를 짜내는 놀라운 강력한 방법이 될 수 있다.

### 몰입을 일상적인 의식으로 만들어라

마음을 사용하여 가치 있는 것을 만드는 사람들에 대해 종종 간과되는 관찰은 그들이 작업 습관에 있어 거의 무작위적이지 않다는 것이다. 퓰리처상을 수상한 전기작가 로버트 카로를 생각해 보자. 2009년 잡지 프로필에서 드러난 것처럼, "[카로의] 뉴욕 사무실의 모든 인치는 규칙에 의해 지배된다." 그가 책을 어디에 배치하는지, 공책을 어떻게 쌓는지, 벽에 무엇을 씌우는지, 심지어 사무실에 무엇을 입는지: 모든 것은 카로의 오랜 경력에 걸쳐 거의 변하지 않은 루틴에 의해 지정된다. "정리적으로 조직되도록 스스로 훈련했다"고 설명했다.

찰스 다윈은 종의 기원에 대해 완성하던 시기에 그의 작품 생활에 대해 유사하게 엄격한 구조를 가지고 있었다. 아들 프란치스코가 나중에 기억한 것처럼 그는 7시에 곧바로 일어나 짧은 걸음을 걸었다. 그런 다음 아침을 혼자 먹고 8시에서 9시 30분까지 사무실로 은퇴했다. 다음 시간은 전날부터 그의 편지를 읽는 데 바쳤고 그 후 그는 10시 30분부터 정오까지 자신의 사무실로 돌아왔다. 이 세션이 끝나면 그는 온실에서 시작하여 자신의 재산에서 길을 돌아가는 지정된 경로를 걷는 동안 도전적인 아이디어를 고민할 것입니다. 그는 자신의 생각에 만족할 때까지 걸어가다가 자신의 일일이 끝났다고 선언할 것이다.

유명한 사상가와 작가(그리고 앞의 두 가지 예를 배운 사람)의 습관을 반 십 년 동안 목록화한 언론인 메이슨 커리는 이러한 체계화 경향을 다음과 같이 정리했다.

예술가들이 영감을 받아 일한다는 일반적인 개념이 있는데, 누가 알겠습니까? 어디서부터 어떤 파업이나 볼트 또는 창의적인 모지가 튀어나오지만 나는 (나의 작업) 영감을 기다려야 파업하는 것이 끔찍하고 끔찍한 계획이라는 것을 분명히 하고 싶다. 사실, 창의적인 일을 하려는 모든 사람에게 내가 줄 수 있는 가장 좋은 조언은 영감을 무시하는 것입니다.

데이비드 브룩스는 이 주제에 관한 뉴욕타임스 칼럼에서 "(위대한 창의적 정신은) 예술가처럼 생각하지만 회계사처럼 일한다"고 이 현실을 보다 뭉툭하게 정리한다.

이 전략은 다음을 제안한다: 심층 작업 세션을 최대한 활용하기 위해 앞서 언급한 중요한 사상가들과 같은 수준의 엄격성과 특이성의 의식을 구축한다. 이 모방에는 좋은 이유가 있다. 카로나 다윈 같은 위대한 사람들은 의식을 이상하게 배치하지 않았는데, 그들의 작업의 성공은 깊이 깊이 들어가고, 다시 돌아가며, 퓰리처상을 수상하거나 뇌를 한계로 밀지 않고는 거대 이론을 구상할 방법이 없기 때문에 그렇게 했다. 그들의 의식은 이러한 깊이로의 전환에서 마찰을 최소화하여 더 쉽게 깊이 들어가 더 오래 상태에 머물 수 있게 했다. 만약 그들이 진지한 일에 착수하기 전에 파업할 영감을 기다렸다면, 그들의 성취는 크게 줄어들었을 것이다.

올바른 심층 작업 의례는 없으며 올바른 적합은 사람과 추구하는 프로젝트 유형에 따라 다르다. 그러나 효과적인 의례가 해결해야 하는 몇 가지 일반적인 질문이 있습니다.

• 어디에서 얼마나 오래 일할 것인가. 당신의 의식은 당신의 딥 워크 노력을 위한 장소를 지정해야 합니다. 이 위치는 문을 닫고 책상을 청소한 일반 사무실만큼 간단할 수 있습니다. (내 동료는 어려운 일을 할 때 사무실 문에 "방해하지 마십시오"라는 호텔 스타일의 간판을 붙이는 것을 좋아합니다). 깊이만을 위해 사용되는 위치, 예를 들어 회의실이나 조용한 도서관을 식별할 수 있다면 긍정적인 효과는 훨씬 더 클 수 있다. (오픈오피스 플랜에서 근무하는 경우, 심층적인 업무 수련회를 찾아야 하는 이러한 필요성이 특히 중요해진다. 직장에 관계없이, 세션이 개방형 슬로그가 아닌 개별적인 도전으로 유지되도록 특정 시간 프레임을 주어야 합니다.

• 일하기 시작하면 어떻게 일할 것인가. 당신의 의례는 당신의 노력을 구조적으로 유지하기 위한 규칙과 과정이 필요하다. 예를 들어, 인터넷 사용 금지를 부과하거나 집중력을 높이기 위해 20분 간격으로 생성되는 단어와 같은 메트릭을 유지할 수 있습니다. 이런 구조가 없다면, 이 세션들 동안 무엇을 해야 하고 무엇을 하지 말아야 하는지를 정신적으로 반복해서 소송을 해야 하고 당신이 충분히 열심히 일하고 있는지 계속 평가하려고 노력해야 할 것이다. 이것은 당신의 의지력 보유에 불필요한 손실입니다.

• 당신이 당신의 일을 지원할 방법. 당신의 의식은 당신의 뇌가 높은 깊이에서 계속 작동하는 데 필요한 지원을 받을 수 있도록 해야 합니다. 예를 들어, 의식은 좋은 커피 한 잔부터 시작하거나 에너지를 유지하기 위해 적절한 유형의 충분한 음식에 접근할 수 있는지 확인하거나 정신을 명료하게 유지하는 데 도움이 되도록 걷기와 같은 가벼운 운동을 통합하도록 지정할 수 있다. (니체가 말했듯이, "걷기에서 얻은 아이디어만이 가치가 있다.") 이러한 지원에는 에너지 소산 마찰을 최소화하기 위해 작업의 원료를 구성하는 것과 같은 환경적 요인도 포함될 수 있다. 성공을 극대화하기 위해서는 깊숙이 들어가려는 노력을 지원해야 합니다. 동시에 이 지원은 당신이 필요한 것을 파악하는 데 정신적인 에너지를 낭비하지 않도록 체계화될 필요가 있다.

이러한 질문은 심층 작업 의례를 만들기 시작하는 데 도움이 될 것입니다. 하지만 끈끈이 붙는 의식을 찾는 것은 실험을 필요로 할 수 있으므로 기꺼이 노력해야 한다는 것을 명심하세요. 나는 그 노력의 가치가 있다고 확신합니다. 일단 당신이 옳다고 느끼는 것을 진화시켰을 때, 그 영향은 상당할 수 있다. 깊이 작업하는 것은 큰 문제이며 가볍게 수행되는 활동이 되어서는 안 된다. 복잡한(아마도 외부 세계로서는 상당히 이상한) 의례로 그러한 노력을 둘러싸는 것은 이 현실을 받아들이며 중요한 것을 창조하기 시작할 수 있는 초점의 상태로 미끄러지도록 필요한 구조와 헌신을 마음에 제공한다.

### 과감하게 환경을 전환하라

2007년 초겨울, JK 롤링은 그녀의 해리포터 시리즈의 마지막 책인 죽음의 성지를 완성하기 위해 고군분투하고 있었다. 이 책은 수억 명의 팬들을 만족시킬 수 있는 방식으로 선행 6편을 묶어야 한다는 책무가 컸기 때문에 압박이 강했다. 롤링은 이러한 요구를 충족시키기 위해 깊이 노력할 필요가 있었지만 그녀는 스코틀랜드 에든버러에 있는 그녀의 본사에서 지속적인 집중을 달성하기가 점점 더 어려워지고 있었다. 롤링은 인터뷰에서 "죽음의 전례를 마치고 있을 때 창문 청소원이 온 날이 왔고, 아이들은 집에 있었고, 개들은 짖고 있었다"고 회상했다. 너무 무리한 일이어서 JK 롤링은 에든버러 시내 중심부에 위치한 5성급 발모럴 호텔의 스위트룸에 체크인하면서 마음가짐을 바꿔가기 위해 극단적인 행동을 하기로 했다. "그래서 이 호텔은 아름다운 호텔이라서 왔는데, 여기에 머물 생각은 없었다"고 그녀는 설명했다. "그러나 첫날의 글이 잘 되어 계속 돌아왔고... 결국 [여기] 마지막 해리포터 책을 다 마쳤다."

돌이켜보면, 롤링이 결국 머물게 된 것은 놀라운 일이 아니다. 그 설정은 그녀의 프로젝트에 완벽했습니다. 스코틀랜드에서 가장 호화로운 호텔로 알려진 발모랄은 화려한 석축과 높은 시계탑이 완비된 클래식한 빅토리아 시대의 건물이다. 또한 로울링이 호그워트를 꿈꾸는 데 영감을 준 것 중 하나인 에든버러 성에서 불과 몇 블록 떨어진 곳에 위치해 있다.

에든버러 성 근처의 고급 호텔 스위트룸에 체크인하기로 한 롤링의 결정은 심층 작업의 세계에서 호기적이지만 효과적인 전략, 즉 거창한 제스처의 한 예이다. 그 개념은 간단하며, 일상 환경에 대한 급진적인 변화를 활용하고, 노력이나 자금의 상당한 투자와 함께, 모두 심층 작업 프로젝트를 지원하는 데 전념함으로써, 당신피상적 작업의 중요성을 높인다. 이러한 중요성의 증가는 지연하려는 마음의 본능을 감소시키고 동기 부여와 에너지를 전달한다.

예를 들어 해리포터 소설의 한 장을 쓰는 것은 힘든 작업이며 어디에서든 많은 정신적 에너지를 필요로 한다. 그러나 호그워츠 스타일의 성에서 거리의 오래된 호텔 스위트룸에 장을 쓰기 위해 하루에 1,000달러 이상을 지불할 때, 이 작업을 시작하고 지속하기 위한 에너지를 모으는 것은 당신이 대신 산만한 홈 오피스에 있는 것보다 더 쉽다.

다른 잘 알려진 딥 워커들의 습관을 연구하면 그랜드 제스처 전략이 자주 등장한다. 예를 들어 빌 게이츠는 마이크로소프트 CEO 시절 평소 일과 가족의 의무를 뒤로하고 종이와 책을 쌓아 오두막으로 후퇴하는 크위크를 가져 유명했다. 그의 목표는 그의 회사와 관련된 큰 문제에 대해 산만함 없이 깊이 생각하는 것이었다. 예를 들어, 그가 인터넷이 업계의 주요 힘이 될 것이라는 결론에 이른 것은 이 주 중 한 주 동안이었습니다. 게이츠가 마이크로소프트의 시애틀 본사 사무실에서 심도 있게 생각하는 것을 물리적으로 막을 수 있는 것은 없었지만 일주일 동안의 퇴각의 참신함은 그가 원하는 수준의 집중력을 달성하는 데 도움이 되었다.

MIT의 물리학자이자 수상 경력에 빛나는 소설가인 앨런 라이트먼도 웅장한 몸짓을 활용한다. 그의 경우, 그는 매년 여름에 메인의 '작은 섬'으로 물러나 깊이 생각하고 재충전한다. 적어도 그가 인터뷰에서 이 제스처를 설명한 2000년 현재, 섬에는 인터넷이 부족할 뿐만 아니라 전화 서비스도 없었다. 그러면서 "내 인생에서... 찾기 힘든 침묵을 회복할 수 있을 것 같은 느낌이 드는 것은 정말 두 달 반 정도"라고 정당화했다.

모든 사람이 메인에서 두 달을 보낼 자유가 있는 것은 아니지만 댄 핑크와 마이클 폴란을 포함한 많은 작가들은 종종 상당한 비용과 노력을 들여 부동산에 오두막을 짓는 방식으로 일년 내내 경험을 시뮬레이션한다. (폴란은 자신의 일부분으로, 자신의 전 코네티컷 집 뒤 숲에 자신의 오두막을 지은 경험에 대한 책을 쓰기도 했다.) 이러한 부속 건물은 노트북과 평평한 표면만 있으면 무역을 할 수 있는 이 작가들에게 엄격하게 필요하지 않다. 그러나 가치를 창출하는 것은 객실의 편의 시설이 아니라, 대신 더 나은 글쓰기를 가능하게 하는 유일한 목적으로 객실의 설계와 건물에 표현되는 웅장한 제스처이다.

모든 거창한 제스처가 그렇게 영구적이어야 하는 것은 아닙니다. 병리학적으로 경쟁적인 벨 연구소 물리학자 윌리엄 쇼클리가 트랜지스터의 발명에 대해 떠들썩한 후, 다음 전략에서 자세히 설명하듯이, 쇼클리가 다른 프로젝트를 위해 자리를 비운 시점에서 그의 팀의 두 구성원이 돌파구를 만들었으며 그는 시카고의 한 호텔 방에 자신을 가두었다. 그는 머릿속을 뒤흔드는 더 나은 디자인을 위해 세부 사항을 정리할 때까지 방에서 나오지 않았다. 마침내 방을 나갔을 때 그는 동료가 자신의 연구소 노트에 붙이고 혁신을 타임스탬프하기 위해 서명할 수 있도록 자신의 노트를 뉴저지 주 머레이 힐로 다시 항공 우편으로 보냈다. 쇼클리가 이 엄청난 깊이 속에서 개발한 트랜지스터의 접합 형태는 그의 발명으로 이후 수여된 노벨상 상의 몫을 차지하게 했다.

한 번 큰 몸짓이 결과를 낳는 더 극단적인 예는 기업가이자 소셜 미디어의 선구자인 피터 크먼과 관련된 이야기이다. 크맨은 인기 있는 연사로 비행기를 타는 데 많은 시간을 보낸다. 그는 결국 3만 피트가 그가 집중할 수 있는 이상적인 환경이라는 것을 깨달았다. 블로그 게시글에서 설명한 것처럼, "앞에 아무것도 없는 자리에 갇혀 있어, 나를 산만하게 할 것이 없고 내 '오! 오!'를 터트릴 것이 없다. 샤이니! DNA, 나는 내 생각과 하나 되는 것 외에는 할 수 없다. 크맨이 전체 원고를 완성할 수 있는 시간이 2주밖에 안 되는 책 계약을 체결한 것은 이 깨달음의 어느 순간이었다. 이 기한을 맞추려면 엄청난 집중력이 필요합니다. 이 상태를 이루기 위해 크만은 파격적인 일을 했다. 그는 도쿄로 가는 왕복 비즈니스 클래스 티켓을 예약했다. 그는 일본으로 가는 내내 글을 썼고 일본에 도착하자마자 비즈니스 클래스 라운지에서 에스프레소를 마신 다음 돌아서 비행기를 타고 돌아왔고, 다시 한 번 전 길을 썼으며, 이제 완성된 원고를 들고 처음 떠난 지 불과 30시간 만에 미국에 돌아왔다. 그는 "여행 비용은 4천 달러였고 한 푼도 안 날만한 가치가 있었다"고 설명했다.

이 모든 예에서 더 딥 워크인 일을 가능하게 하는 것은 환경의 변화나 조용함의 추구만이 아니다. 지배적인 힘은 당면한 과제에 그렇게 진지하게 헌신하는 심리이다. 자신을 이국적인 장소에 배치하여 글쓰기 프로젝트에 집중하거나, 단지 생각하기 위해 일주일 동안 일을 쉬거나, 중요한 발명을 완성할 때까지 호텔 방에 갇히는 것: 이러한 제스처는 당신의 깊은 목표를 필요한 정신 자원의 잠금을 푸는 데 도움이 되는 정신적 우선 순위 수준으로 밀어낸다. 가끔 깊숙이 들어가려면 먼저 크게 들어가야 합니다.

### 혼자 일하지 마라 (화이트보드 효과)

심층 작업과 협업의 관계는 까다롭습니다. 그러나 협업을 적절하게 활용하면 직업 생활에서 심층 작업의 품질을 높일 수 있기 때문에 시간을 내어 풀 가치가 있다.

처음에는 해결할 수 없는 갈등으로 보이는 것을 고려하는 데 한 걸음 물러서서 이 주제에 대한 논의를 시작하는 것이 도움이 된다. 이 책의 1부에서 나는 페이스북이 새로운 본사를 디자인하는 것에 대해 비판했다. 특히, 나는 세계에서 가장 큰 개방형 사무실 공간, 즉 2,800명의 근로자를 수용할 것으로 알려진 거대한 방을 만드는 회사의 목표가 집중력에 대한 터무니없는 공격을 나타낸다는 점에 주목했다. 직관과 연구의 증가로 인해 많은 동료들과 작업 공간을 공유하는 것이 심각하게 생각하려는 시도를 방해하는 환경을 만드는 믿을 수 없을 정도로 산만하다는 현실이 강조된다. 블룸버그 비즈니스위크는 이 주제에 대한 최근 연구를 요약한 2013년 기사에서 '개방형 사무의 횡포'를 종식할 것을 촉구하는 데까지 이르렀다.

그럼에도 불구하고 이러한 오픈 오피스 디자인은 무작위로 수용되지 않습니다. 마리아 코니코바가 뉴욕저에 보도한 바와 같이 이 개념이 처음 등장했을 때 그 목표는 "소통과 아이디어 흐름을 촉진"하는 것이었다. 이 주장은 스타트업의 파격적인 분위기를 받아들이려는 미국 기업들에게 울림을 주었다. 예를 들어 블룸버그 비즈니스위크의 조쉬 티랑지엘 편집자는 블룸버그 본사 사무실 부족을 다음과 같이 설명했다. "열린 계획은 꽤 화려하며 모두가 광범위한 임무에 조응하도록 하고,... 다른 분야에 종사하는 사람들 사이의 호기심을 조장한다." 잭 도시는 "우리는 정중함을 믿기 때문에 사람들이 야외에 머물도록 권장하고 서로 함께 걷는 사람들은 새로운 것을 가르친다"고 설명함으로써 스퀘어 본부의 개방 레이아웃을 정당화했다.

논의를 위해 사람들이 서로 스마트한 협업을 하게 하고 새로운 아이디어가 나올 때 이 원칙을 우연한 창의성 이론이라고 불러보자. 마크 저커버그가 세계에서 가장 큰 사무실을 짓기로 결정했을 때 이 이론은 실리콘 밸리 및 그 이상의 다른 곳에서 열린 작업 공간으로의 많은 움직임을 주도한 것처럼 그의 결정을 주도하는 데 도움이 되었다. (돈 절약과 감독 증가와 같은 다른 덜 돋보이는 요소도 역할을 하지만 섹시하지 않으므로 덜 강조된다.)

집중 촉진과 순응성 촉진 사이의 이러한 결정은 심층적 작업(개인적 노력)이 창의적 통찰력(협업적 노력)을 생성하는 것과 양립할 수 없음을 나타내는 것으로 보인다. 그러나 이 결론은 결함이 있습니다. 나는 그것이 우연적 창의성 이론에 대한 불완전한 이해를 바탕으로 한다고 주장한다. 이 주장을 뒷받침하기 위해 돌파구를 촉진하는 요인에 대한 이러한 특정 이해의 출처를 고려해 보자.

문제의 이론은 많은 출처를 가지고 있지만 우연히 더 잘 알려진 이론 중 하나와 개인적인 연관성이 있다. MIT에서 7년 동안 연구소의 유명한 빌딩 20 부지에서 일했습니다. 이스트 케임브리지의 메인 스트리트와 바서 스트리트의 교차점에 위치해 있으며 결국 1998년에 철거된 이 구조물은 2차 세계대전 동안 학교의 번화한 방사선 연구소에서 흘러나온 범람을 수용하기 위해 임시 대피소로 함께 버려졌다. 2012년 뉴욕 기사에서 언급한 바와 같이, 이 건물은 처음에는 실패로 간주되었는데, 환기가 불량하고 복도가 어둡다. 벽이 얇고 지붕이 새어오르고 건물은 여름에는 굽고 겨울에는 얼어붙었다고 말했다.

그러나 전쟁이 끝나자 케임브리지에 과학자들이 유입되는 일이 계속됐다. MIT는 공간이 필요했기 때문에 현지 관리들이 약속한 대로 20번 빌딩을 즉시 철거하는 대신(허가 허가의 대가로) 계속해서 넘쳐나는 공간으로 사용했다. 그 결과 원자력 과학에서 언어학, 전자학에 이르기까지 다양한 학과가 불일치하여 기계 작업장 및 피아노 수리 시설과 같은 더 난해한 세입자와 함께 낮은 경사를 가진 건물을 공유했다. 이 단체들은 건물의 시공이 저렴하기 때문에 필요에 따라 공간을 자유롭게 재배치할 수 있다고 느꼈다. 벽과 바닥을 이동하고 장비를 보에 볼트할 수 있습니다. 제롤드 자카리아스가 최초의 원자시계에 대한 작업을 수행한 이야기를 전하면서 위에서 언급한 뉴욕 기사에서는 실험 장치에 필요한 3층 실린더를 설치할 수 있도록 그의 20호 건물 실험실에서 2층을 제거하는 능력의 중요성을 지적한다.

MIT 학문에서 일반적으로 재구성 가능한 대형 건물에 함께 던져진 서로 다른 학문의 무작위 조합이 우연한 만남과 빠른 속도로 돌파구를 생성하는 발명 정신으로 이어졌으며 스키 문법, 로란 항법 레이더 및 비디오 게임과 같은 다양한 주제를 혁신하는 것으로 믿어진다. 이 건물이 마침내 철거되어 3억 달러의 프랭크 게리가 설계한 스타타 센터(내가 시간을 보냈던 곳)를 위해 자리를 잡았을 때, 그 손실은 애도했다. 스타타 센터의 인테리어 디자인에는 자신이 교체한 '합판 궁전'을 기리는 의미로 미완성 합판 판자와 건축 표시가 그대로 남아 있는 노출 콘크리트가 포함돼 있다.

빌딩 20이 서둘러 건설된 것과 비슷한 시기에 뉴저지 주 머레이 힐에서 남서쪽으로 200마일 떨어진 곳에서 더 체계적인 우연한 창의성 추구가 진행되었다. 벨 연구소 메르빈 켈리 이사가 과학자와 엔지니어가 다양한 혼합물 간의 상호 작용을 의도적으로 장려할 연구소의 새 집 건설을 안내한 곳이 바로 여기에 있다. 켈리는 다른 건물에 다른 학과를 수용하는 표준 대학식 접근법을 무시하고 대신 공간을 긴 복도로 연결된 하나의 연속 구조로 연결했으며 일부는 한쪽 끝에 서면 사라지는 지점으로 수렴하는 것처럼 보일 정도로 길다. 벨 연구소 연대기자 존 게르트너가 이 디자인에 대해 언급했듯이, "많은 지인들을 만나지 않고 홀의 길이를 여행하는 것은 문제, 전환 및 아이디어가 거의 불가능했다. 식당에서 점심을 먹으러 가는 물리학자는 철판을 지나가는 자석과 같았다.

이 전략은 켈리의 공격적인 세계 최고의 정신을 모집하는 것과 혼합되어 현대 문명 역사상 가장 집중된 혁신을 산출했다. 이 연구소는 2차대전 이후 수십 년 동안, 다른 업적들 중에서, 최초의 태양 전지, 레이저, 통신 위성, 셀룰러 통신 시스템, 광섬유 네트워킹을 생산했다. 동시에 그들의 이론가들은 정보 이론과 코딩 이론을 공식화했고, 그들의 천문학자들은 빅뱅 이론을 경험적으로 검증한 공로로 노벨상을 수상했으며, 아마도 무엇보다도 중요한 것은 그들의 물리학자들이 트랜지스터를 발명했다는 것이다.

우연적 창조성 이론, 즉 역사 기록에 의해 정당화되는 것은 잘 보인다. 우리는 어느 정도 확신을 가지고 주장할 수 있는 트랜지스터는 아마도 벨 연구소와 고체 상태 물리학자, 양자 이론가, 그리고 세계적 수준의 실험가를 우연히 서로 만나고 그들의 다양한 전문 지식으로부터 배울 수 있는 한 건물에 배치하는 능력을 필요로 했을 것이다. 이것은 칼 융의 석탑과 같은 학문적 가치를 깊이 생각하는 외로운 과학자로부터 나온 것 같지 않은 발명이었다.

그러나 빌딩 20이나 벨 연구소와 같은 현장에서 혁신을 일으킨 것을 이해하는 데 더 많은 뉘앙스를 받아들여야 한다. 그러기 위해 다시 한 번 MIT에서의 나의 경험으로 돌아가 보자. 2004년 가을 신입 박사과정생으로 입학했을 때, 언급한 대로 20동이 대체된 새로운 스타타 센터에 수용될 첫 번째 입학반의 일원이었다. 센터가 새것이라 입학생들에게 특징을 알리는 투어를 제공했습니다. 우리가 배운 프랭크 게리는 공동 공간 주위에 사무실을 배치하고 인접한 층 사이에 열린 계단 벽을 도입했으며 모두 전작을 정의한 우연한 만남의 유형을 지원하기 위한 노력이었다. 그러나 당시 나에게 놀라운 것은 게리에게 발생하지 않았지만 최근 교수진의 주장에 따라 추가된 기능, 즉 방음 기능을 개선하기 위해 사무실 문턱에 설치된 특수 개스킷이었다. 세계에서 가장 혁신적인 기술자 중 일부인 MIT의 교수들은 오픈 오피스 스타일의 작업 공간과 아무 관련이 있기를 원하지 않았다. 그들은 대신 스스로를 폐쇄할 수 있는 능력을 요구했다.

넓은 공용 영역에 연결된 방음 사무실의 이러한 조합은 우연한 만남과 고립된 깊은 사고가 모두 지원되는 혁신의 허브 앤 스포크 아키텍처를 산출한다. 한 극단에서는 영감을 받지 않지만 산만함에서 자유로운 독창적인 사고자를 찾고 다른 극단에서는 영감을 받으면서도 영감을 쌓는 데 필요한 깊은 사고를 지원하기 위해 고군분투하는 개방된 사무실에서 완전히 협력적인 사고자를 찾는 스펙트럼을 가로지르는 설정이다. \*

우리가 20동과 벨 연구소로 다시 눈을 돌리면 이것이 그들이 배치한 아키텍처라는 것을 알 수 있다. 어느 건물도 현대적인 오픈 오피스 플랜과 유사한 것을 제공하지 않았습니다. 대신 공유 복도에 연결된 개인 사무실의 표준 레이아웃을 사용하여 구성되었다. 그들의 창의적인 모지는 이 사무실이 소수의 긴 연결 공간을 공유한다는 사실과 더 관련이 있어 연구자들이 한 위치에서 다른 위치로 이동할 때마다 상호 작용해야 했다. 즉, 이러한 메가 홀은 매우 효과적인 허브를 제공했습니다.

따라서 우리는 우연적 창의성의 혁신 생산 이론을 무시하지 않고 여전히 깊이를 파괴하는 개방 사무실 개념을 무시할 수 있다. 핵심은 허브와 스포크 스타일의 배열에서 둘 다 유지하는 것입니다. 정기적으로 허브의 아이디어에 자신을 노출시키되, 마주치는 것에 대해 깊이 작업할 수 있는 스포크를 유지합니다.

그러나 이러한 노력의 분할은 전체 이야기가 아니기 때문에, 스포크로 돌아갔더라도 솔로 작업이 여전히 반드시 최선의 전략이 되는 것은 아니다. 예컨대, 앞서 언급한 벨 연구소에서의 (포인트-컨택트) 트랜지스터의 발명을 고려해 보자. 이 돌파구는 모두 별도의 전문 분야를 가진 대규모 연구자 그룹에 의해 지원되었으며, 이들은 고체물리학 연구 그룹을 구성하기 위해 함께 모였으며, 진공관에 대한 더 작고 신뢰할 수 있는 대안을 발명하기 위해 헌신하는 팀이다. 이 그룹의 협업 대화는 트랜지스터에 필요한 전제 조건이었고 허브 행동의 유용성에 대한 분명한 예였다.

일단 연구팀이 구성요소에 대한 지적 토대를 마련하게 되면 혁신 과정은 스포크로 전환되었다. 그러나 이 특정 혁신 프로세스를 흥미로운 사례로 만드는 것은 스포크로 전환하더라도 협업적으로 유지되었다는 것이다. 특히 1947년 한 달 동안 작동하는 고체 상태 트랜지스터를 최초로 만들어낸 일련의 돌파구를 만든 것은 실험가 월터 브라테인과 양자 이론가 존 바딘이라는 두 명의 연구자였다.

브라테인과 바르딘은 이 기간 동안 작은 연구실에서 함께 일했으며 종종 나란히 작업을 수행하여 더 좋고 효과적인 디자인을 위해 서로를 밀어붙였다. 이러한 노력은 주로 심층 작업으로 구성되었지만 우리가 아직 접하지 못한 일종의 심층 작업으로 구성되었다. 브라테인은 바르딘의 최신 이론적 통찰력을 활용할 수 있는 실험 설계를 설계하는 데 집중할 것이며 바르딘은 관찰과 일치하도록 이론적 프레임워크를 확장하려고 노력하면서 브라테인의 최신 실험이 밝혀낸 것을 이해하는데 집중할 것이다. 이 앞뒤는 내가 화이트보드 효과라고 부르는 것을 활용하는 협력적인 형태의 심층 작업(학계에서 흔히 볼 수 있음)을 나타낸다. 어떤 유형의 문제는 속담처럼 공유 화이트보드에서 다른 사람과 함께 작업하는 것이 혼자 작업하는 것보다 더 깊게 밀어낼 수 있습니다. 당신의 다음 통찰을 기다리는 상대방의 존재, 즉 물리적으로 같은 방에 있거나 가상적으로 당신과 협력하는 사람이든 간에 깊이를 피하기 위해 자연스러운 본능을 단락시킬 수 있다.

이제 한 걸음 물러서 심층 작업에서 협업의 역할에 대한 몇 가지 실용적인 결론을 도출할 수 있다. 빌딩 20과 벨 연구소의 성공은 생산적인 심층 작업을 위해 격리가 필요하지 않음을 나타낸다. 실제로, 그들의 예는 많은 유형의 작업, 특히 혁신을 추구할 때 협력적인 심층 작업이 더 나은 결과를 얻을 수 있음을 나타낸다. 따라서 이 전략은 전문적인 삶에 깊이를 통합하는 최선의 방법을 고려할 때 이 옵션을 고려하도록 요청합니다. 그러나 그렇게 할 때 다음 두 가지 지침을 염두에 두십시오.

첫째, 산만함은 깊이의 파괴자로 남아 있다. 따라서 허브 앤 스포크 모델은 중요한 템플릿을 제공한다. 우연한 만남의 추구와 깊이 생각하고 이러한 영감을 바탕으로 노력하는 것을 분리한다. 두 목표를 모두 방해하는 슬러지로 섞어쓰는 것이 아니라 각 노력을 개별적으로 최적화하려고 노력해야 한다.

둘째, 스포크로 물러나서 깊이 생각하더라도 화이트보드 효과를 활용하는 것이 합리적일 때 그렇게 한다. 누군가와 함께 문제를 해결하는 일을 함께 함으로써 서로를 더 깊은 깊이의 수준으로 밀어붙일 수 있으며 따라서 혼자 일하는 것보다 더 가치 있는 결과물을 생성할 수 있다.

심층 작업의 경우, 즉, 협업이 새로운 차원으로 나아가게 할 수 있으므로 적절한 경우 협업의 사용을 고려한다. 동시에, 상호작용과 긍정적인 무작위성에 대한 이 탐구를 우리 주변의 모든 아이디어의 소용돌이에서 유용한 것을 꼬아내는 데 궁극적으로 필요한 끊이지 않는 집중력을 압축하는 지점으로 삼지 마십시오.

### 비즈니스처럼 실행하라 (4DX 원칙)

그 이야기는 비즈니스 컨설팅 세계에서 통념이 되었습니다. 1990년대 중반 클레이튼 크리스텐슨 하버드 경영대 교수는 앤디 그로브 인텔 대표이사 겸 회장으로부터 전화를 받았다. 그로브는 파괴적 혁신에 대한 크리스텐슨의 연구를 접하고 그에게 캘리포니아로 날아와 이 이론이 인텔에 주는 의미를 논의해 달라고 요청했다. 도착했을 때 크리스텐슨은 혼란의 기초를 통과했는데, 고착화된 기업은 종종 시장의 낮은 끝에서 저렴한 제안으로 시작하지만 시간이 지남에 따라 고급 시장 점유율을 훔치기 시작할 만큼 저렴한 제품을 개선하는 스타트업에 의해 예기치 않게 축출된다. 그로브는 인텔이 AMD와 싸이릭스 등 신생 기업이 생산하는 저가형 프로세서로부터 이런 위협에 직면했다고 인식했다. 그로브는 파괴에 대한 새로운 이해에 힘입어 Intel이 아래로부터의 도전과 성공적으로 싸우는 데 도움이 된 저성능 제품인 셀레론 프로세서 계열로 이어지는 전략을 고안했다.

그러나 이 이야기에는 덜 알려진 부분이 있다. 크리스텐슨의 기억처럼, 이 회의에서 그루브는 휴식시간에 자신에게 "어떻게 하면 좋을까?"라고 물었고 크리스텐슨은 그로브가 어떻게 새로운 사업부문을 세울 수 있었는지 등을 설명하면서 사업전략에 대한 논의로 답했다. 그로브는 "너 정말 순진한 학자이다. 어떻게 해야 하는지 물어봤는데, 어떻게 해야 하는지 알려주셨죠. 내가 해야 할 일을 알고 있어. 나는 그냥 어떻게 해야 할지 모른다.

크리스텐슨이 나중에 설명했듯이, 무엇이 어떻게 구분되는지는 중요하지만 직업계에서는 간과되고 있다. 목표를 달성하는 데 필요한 전략을 식별하는 것은 종종 간단하지만 기업이 성공하는 것피상적 작업단 식별된 전략을 실행하는 방법을 찾는 것이다. 나는 크리스텐슨이 고수준의 전략을 성공적으로 구현하는 데 도움이 되는 4가지 "학문"(약칭, 4DX)을 설명하기 위해 광범위한 컨설팅 사례 연구를 기반으로 한 4가지 실행의 학문이라는 책을 위해 쓴 서문에서 이 이야기를 접했다. 읽으면서 눈에 띄었던 것은 무엇과 어떻게 사이의 이 간격이 더 딥 워크을 하는 데 더 많은 시간을 보내려는 나의 개인적인 탐구와 관련이 있다는 것이었다. 앤디 그로브가 저가형 프로세서 시장에서 경쟁의 중요성을 파악했듯이, 나는 깊이 우선순위를 우선시하는 것의 중요성을 파악했다. 제가 필요로 했던 것은 이 전략을 실행하는 방법을 찾는 데 도움이 필요했습니다.

이러한 병렬에 흥미를 느낀 나는 4DX 프레임워크를 나의 개인적인 작업 습관에 맞게 적응시키기에 착수했고 그들이 나를 깊이 일하는 목표에 대한 효과적인 행동으로 이끌는데 얼마나 도움이 되었는지에 놀랐다. 이러한 아이디어는 대기업 세계를 위해 위조되었을 수 있지만 많은 경쟁 의무와 산만함을 배경으로 중요한 일이 수행되어야 하는 모든 곳에 기본 개념이 적용되는 것 같다. 이를 염두에 두고 다음 섹션에서 4DX 프레임워크의 4가지 분야를 요약하고 각 섹션에 대해 심층 작업 습관을 개발하는 특정 문제에 어떻게 적응했는지 설명한다.

훈육 #1: 정말 중요한 것에 집중하세요

실행의 4가지 규율 저자들이 설명하듯이 "무엇을 더 하려고 노력할수록 실제로 성취하는 것은 줄어든다." 그들은 실행이 소수의 "혼란히 중요한 목표"를 목표로 해야 한다고 자세히 설명한다. 이러한 단순성은 실제 결과를 촉발하기에 충분한 강도로 조직의 에너지를 집중하는 데 도움이 될 것이다.

심층 업무에 집중하는 개인에게 심층 업무 시간으로 추구해야 할 소수의 야심찬 성과를 파악해야 한다는 함의가 있다. "깊이 일하면서 더 많은 시간을 보내라"는 일반적인 권고는 많은 열의를 불러일으키지 않는다. 대신 유형적이고 실질적인 전문적인 이익을 반환하는 특정 목표를 설정하는 것은 더 꾸준한 열의 흐름을 생성할 것이다. 데이비드 브룩스는 2014년 "포커스의 예술"이라는 칼럼에서 "주의를 얻기 위한 전쟁에서 이기려면 정보 스모어스보드에서 발견되는 사소한 산만함에 대해 "아니오"라고 말하지 말고, 무서운 그리움을 유발하는 주제에 대해 "예"라고 말하고, 무서운 그리움이 다른 모든 것을 몰아주도록 하라"고 설명하면서 야심찬 목표를 집중 행동을 유도하는 이 접근법을 지지했다.

예를 들어, 4DX로 처음 실험을 시작했을 때, 나는 다가오는 학년에 5개의 양질의 동료 검토 논문을 출판하는 것을 구체적인 중요한 목표로 설정했다. 이 목표는 내가 출판한 것보다 더 많은 논문이었고 거기에 부착된 유형적인 보상(연장 검토가 다가오고 있음)이 있었기 때문에 야심찬 것이었다. 이 두 가지 속성이 결합되어 목표가 나의 동기를 자극하는 데 도움이 되었다.

제2차 규율: 선도 조치에 대한 행동

당신이 아주 중요한 목표를 확인한 후에는, 당신은 당신의 성공을 측정해야 한다. 4DX에서는 이를 위한 지표의 종류가 시차 측정과 선행 측정의 두 가지로 나다. 지연 측정은 궁극적으로 개선하려고 하는 것을 설명한다. 예를 들어, 베이커리에서 고객 만족도를 높이는 것이 목표라면 관련 지연 측정은 고객 만족도 점수입니다. 4DX 저자들이 설명하듯이 시차 측정의 문제는 '받았을 때 그들을 몰아넣은 성과는 이미 과거'라는 행동 변화를 주기에는 너무 늦게 온다는 것이다.

반면 선도 측정은 "지연 측정에서 성공을 이끌 새로운 행동을 측정한다." 베이커리 예에서 좋은 선도 측정은 무료 샘플을 받는 고객 수일 수 있다. 이는 샘플을 더 많이 내주면 직접 늘릴 수 있는 수치입니다. 이 수치를 늘리면 지연 측정도 결국 개선될 것입니다. 즉, 리드 조치는 가까운 미래에 직접 통제하는 행동을 개선하는 데 주의를 기울이고 이는 장기 목표에 긍정적인 영향을 미칠 것이다.

심층 작업에 집중하는 개인의 경우 관련 선행 척도인 자신의 매우 중요한 목표를 향해 헌신적인 심층 작업 상태에서 보낸 시간을 쉽게 식별할 수 있다. 제 예로 돌아가서, 이 통찰은 제가 학문 연구를 어떻게 지시했는지에 중요한 영향을 미쳤다. 나는 연간 발표되는 논문과 같은 지연 측정에 집중했다. 그러나 이러한 측정은 이 장기 측정 지표에 즉각적으로 눈에 띄는 변화를 일으킬 수 있는 단기적으로 할 수 있는 것이 없었기 때문에 일상 행동에 영향을 미치지 못했다. 심층 작업 시간을 추적하는 것으로 전환했을 때 갑자기 이러한 조치가 일상과 관련이 되었으며 심층 작업의 추가 시간이 즉시 내 집계에 반영되었다.

3번 훈육: 설득력 있는 스코어보드를 유지하세요

4DX 저자들은 "사람들은 득점을 지키고 있을 때 다르게 놀고 있다"고 설명했다. 그런 다음 그들은 조직의 매우 중요한 목표를 향해 팀의 참여를 유도하려고 할 때 주도적 조치를 기록하고 추적할 수 있는 공개 장소를 갖는 것이 중요하다고 자세히 설명한다. 이 점수판은 다른 요구가 그들의 관심을 끌 때에도 이러한 조치에 집중하도록 하는 경쟁의식을 만든다. 또한 강화적인 동기 부여원을 제공합니다. 일단 팀이 선두 대책으로 성공을 알아차리면 이 성적을 영속화하기 위해 투자하게 된다.

앞선 학문에서 나는 심층 작업에 집중하는 개인에게 심층 작업에 투입된 시간이 선행 척도가 되어야 한다고 주장하였다. 따라서 개인의 점수판은 개인의 현재 심층 작업 시간을 표시하는 작업 공간의 물리적 인공물이어야 한다.

4DX를 사용한 초기 실험에서 나는 이 스코어보드를 구현하기 위한 간단하지만 효과적인 솔루션에 정착했다. 카드 재고 한 조각을 들고 현재 학기의 각 주에 한 줄씩 줄로 나누었습니다. 그런 다음 각 행에 해당 주의 날짜를 표시하고 컴퓨터 모니터 옆 벽에 테이프로 붙였다. 매주 진행됨에 따라 나는 그 주 행의 진드기 자국을 간단히 계산하여 그 주에 심층 작업에 보낸 시간을 추적했다. 이 점수판이 만들어내는 동기를 극대화하기 위해, 나는 학술 논문에서 중요한 이정표에 도달할 때마다(예를 들어, 핵심 증명을 푸는 것) 나는 결과를 마친 시간에 해당하는 집계 마크를 원형으로 만들 것이다. \* 이것은 두 가지 목적을 수행했습니다. 첫째, 내장적 차원에서 축적된 심층 작업 시간과 가시적인 결과를 연결할 수 있게 해주었다. 둘째, 결과당 몇 시간의 심층 작업이 필요한지에 대한 기대치를 조정하는 데 도움이 되었습니다. (처음 생각했던 것보다 더 큰) 이러한 현실은 내가 그러한 시간을 매주 더 많이 짜내는 데 힘을 실어 주었다.

4번 훈육: 책임의 종지를 생성합니다.

4DX 저자는 선도 조치에 대한 초점을 유지하는 데 도움이 되는 마지막 단계는 "무엇보다 중요한 목표를 소유한 모든 팀의 규칙적이고 빈번한 회의 리듬"을 설정하는 것이라고 자세히 설명합니다. 이러한 회의 동안 팀 구성원은 스코어 보드와 마주하고 다음 회의 전에 스코어를 개선하는 데 도움이 되는 특정 행동을 약속해야 하며 지난 회의에서 약속한 내용을 설명해야 한다. 이들은 이 검토가 몇 분으로 압축될 수 있지만 그 효과가 느껴지기 위해서는 규칙적이어야 한다는 점에 주목한다. 저자들은 '실제 실행이 일어나는' 것이 바로 이 학문이라고 주장한다.

자신의 깊은 업무 습관에 집중하는 개인의 경우 만날 팀이 없을 가능성이 높지만 그렇다고 해서 정기적인 책임의 필요성을 면제할 수는 없다. 이 책 전체의 여러 곳에서 나는 당신이 앞으로의 일주에 대한 계획을 세우는 주간 리뷰의 습관에 대해 논의하고 권장합니다. 4DX를 사용한 실험 동안, 나는 좋은 주를 축하하고, 나쁜 주를 초래한 이유를 이해하는 데 도움이 되며, 가장 중요한 것은 앞으로의 날을 위해 좋은 점수를 보장하는 방법을 알아내기 위해 스코어보드를 보기 위해 주간 리뷰를 사용했다. 이것은 내가 내 선도 조치의 요구에 맞게 일정을 조정하게 하여 그러한 검토를 완전히 피했다면보다 훨씬 더 딥 워크을 가능하게 했다.

4DX 프레임워크는 실행이 전략화보다 더 어렵다는 근본적인 전제에 기반한다. 수백 건의 사례 연구 끝에, 그 발명자들은 이 어려움을 극복하는 데 특히 잘 작동하는 것처럼 보이는 몇 가지 기본 분야를 분리할 수 있었다. 따라서 이러한 동일한 학문이 딥 워크 습관을 함양하는 개인적인 목표에 유사한 영향을 미칠 수 있다는 것은 놀라운 일이 아니다.

결론적으로 마지막으로 제 자신의 사례로 돌아가 보겠습니다. 앞서 언급했듯이 4DX를 처음 수용했을 때 2013-2014학년도에 5개의 동료 검토 논문을 출판하는 목표를 채택했다. 이는 전년도에 4편의 논문만 발표한 것을 감안할 때 야심찬 목표였다. 이 4DX 실험 전반에 걸쳐 이 목표의 명확성과 주요 측정 점수판의 간단하지만 피할 수 없는 피드백은 이전에 달성하지 못한 깊이 수준으로 나를 밀어넣었다. 돌이켜보면, 심층 작업 기간의 강도가 아니라 오히려 규칙성이 증가했다. 필자가 서류 제출 기한에 가까운 곳에 깊은 생각을 집적하던 데 반해 4DX 습관은 1년 내내 마음을 집중하게 했다. (특히 이 책을 동시에 쓰고 있다는 점을 감안할 때) 결국은 피곤한 한 해였음을 인정해야 한다. 그러나 4DX 프레임워크에 대한 설득력 있는 배서를 제공하는 것으로 나타났는데, 2014년 여름까지 9개의 전체 논문이 출판을 위해 승인되었으며 이는 이전 연도에 달성한 것보다 두 배 이상 증가했다.

### 게으름을 피워라 (완전한 휴식의 중요성)

논술가이자 만화가인 팀 크레이더는 2012년 뉴욕타임스 블로그에 쓴 글에서 "나는 바쁘지 않다. 나는 내가 아는 가장 게으른 야심찬 사람"이라며 "그러나 크레이더는 그의 게시글을 작성하기 몇 달 전부터 광란한 일에 대한 혐오가 시험대에 올랐다. "전문적 의무 때문에 부지런히 바빠지기 시작했다... 매일 아침 내 받은 편지함에 내가 하고 싶지 않피상적 작업을 해달라고 요청하거나 이제 해결해야 할 문제를 제시하는 이메일이 가득했다."

그의 해결책? 그는 TV와 인터넷이 없는 장소, 즉 "공개되지 않은 위치"로 도망쳤고(온라인으로 이동하려면 지역 도서관까지 자전거를 타야 한다), 고립되어 무해해 보이지만 깊은 업무 습관에 심각한 부상으로 집약되는 작은 의무의 꼼수 있는 공격에 무반응할 수 있다. 크레이더는 활동 후퇴에 대해 "버터컵, 노린재, 별에 대해 기억해 왔다."라고 말한다. 읽었어. 그리고 나는 마침내 몇 달 만에 진짜 글을 쓰고 있다.

크라이더가 토로가 아니라는 것을 인식하는 것은 우리의 목적에 중요하다. 그는 복잡한 사회적 비판을 강조하기 위해 바쁜 세상에서 물러서지 않았다. 그가 미공개 장소로 이사를 한 것은 오히려 놀라울지만 실용적인 통찰력에 의해 동기 부여되었는데, 그것은 그를 자신의 일을 더 잘하게 만들었다. 여기 크라이더의 설명이 있다.

공백은 단지 휴식, 탐닉 또는 흠결이 아니라 비타민 D가 몸에 없어서는 안 될 만큼 뇌에도 없어서는 안 될 것이며 그것을 박탈당하면 우리는 병충해처럼 변질되는 정신적 고통을 겪는다.... 역설적으로 어떤 일을 하려면 필요하다.

크라이더가 일을 끝내는 것을 이야기할 때, 그는 물론 피상적 작업을 언급하고 있지 않다. 대부분 피상적 작업에 몰입하여 보낼 수 있는 시간이 많을수록 더 상당한 작업을 할 수 있다. 그러나 작가이자 예술가로서 크라이더는 대신 세계가 가치 있는 것을 생산하는 진지한 노력인 딥 워크에 관심을 기울인다. 그는 이러한 노력은 정기적으로 여가에 풀어주는 마음의 지원이 필요하다고 확신한다.

이 전략피상적 작업상생활에 전문적인 고민으로부터 규칙적이고 실질적인 자유를 주입하여 (심층적인) 일을 끝내기 위해 역설적으로 필요한 유휴함을 제공함으로써 크라이더의 선도를 따라야 한다고 주장한다. 이 목표를 달성하는 데에는 여러 가지 방법이 있습니다. 예를 들어, 당신은 '미공개 장소'에 숨어 피상적 작업의 세계에서 완전히 물러나는 크라이더의 접근법을 사용할 수 있지만 이것은 대부분의 사람들에게 실용적이지 않다. 대신, 나는 더 적용 가능하지만 여전히 매우 강력한 휴리스틱을 제안하고 싶다: 작업일이 끝날 때, 저녁 식사 후 이메일 확인, 대화의 정신적 재연, 다가오는 도전을 어떻게 처리할지에 대한 계획 없이 다음 날 아침까지 작업 문제에 대한 고려를 중단하고 완전히 작업 사고를 중단한다. 시간이 더 필요하다면 일과를 연장하되 일단 문을 닫으면 마음도 자유롭게 놓아두어야 크라이더의 버터컵, 노린재, 별을 만날 수 있다.

이 전략을 뒷받침하는 몇 가지 전술을 설명하기 전에 먼저 다운이 가치 있는 산출물을 생산하는 능력에 이익이 되는 이유를 탐구하고 싶습니다. 물론 팀 크레이더의 개인적인 승인은 있지만 다운타임의 가치 뒤에 있는 과학도 이해하는 데 시간을 할애할 가치가 있다. 이 문헌을 자세히 살펴보면 이 값에 대한 다음 세 가지 가능한 설명이 드러난다.

이유 #1: 다운타임 보조 인사이트

학술지 사이언스에 실린 2006년 논문의 다음 발췌문을 생각해 보자.

과학 문헌은 수백 년 동안 의사 결정에서 의식적인 숙고의 이점을 강조해 왔다. 우리는 그렇지 않다고 가정한다.

이 싱겁게 표현된 것을 숨기는 것은 과감한 주장이다. 네덜란드의 심리학자인 Ap Dijksterhuis가 이끄는 이 연구의 저자들은 어떤 결정은 무의식에 맡겨져 풀리는 것이 더 낫다는 것을 증명하기 시작했다. 즉, 이러한 결정을 통해 능동적으로 작업하려고 노력하는 것은 관련 정보를 적재한 다음 다른 것으로 넘어가는 동시에 마음의 무의식적 층이 일을 숙고하도록 하는 것보다 더 나쁜 결과로 이어질 것이다.

다이크스터후이스의 연구팀은 피험자들에게 자동차 구매에 관한 복잡한 결정에 필요한 정보를 제공함으로써 이러한 효과를 분리했다. 대상자의 절반은 정보를 통해 생각해보고 최선의 결정을 내리게 하였다. 나머지 절반은 정보를 읽고 난 뒤 쉬운 퍼즐로 산만해지다가 의식적으로 숙고할 시간 없이 현장에 놓여 결정을 내렸다. 산만한 그룹이 더 나은 성과를 낸 것으로 나타났다.

이와 같은 실험을 관찰한 결과, 다이크스터후이스와 그의 공동 연구자들은 의사 결정에서 의식과 무의식의 다양한 역할을 이해하는 시도인 무의식적 사고 이론을 도입했다. 높은 수준에서 이 이론은 엄격한 규칙의 적용을 요구하는 결정에 대해 의식적인 마음이 관여해야 한다고 제안한다. 예를 들어, 당신이 수학 계산을 해야 한다면, 오직 의식적인 마음만이 정확성에 필요한 정확한 산술 규칙을 따를 수 있다. 반면에, 많은 양의 정보와 여러 모호하고 심지어 상충되는 제약을 포함하는 결정의 경우, 무의식은 문제를 해결하는 데 매우 적합하다. UTT는 뇌의 이러한 영역이 더 많은 신경 대역폭을 가지고 있기 때문에 의식적인 사고 중심보다 더 많은 정보를 이동하고 더 많은 잠재적인 솔루션을 통해 분석할 수 있기 때문이라고 가정한다. 이 이론에 따르면, 당신의 의식적 마음은 제한된 문제에 대한 정확한 답을 반환하는 신중하게 작성된 프로그램을 실행할 수 있는 가정용 컴퓨터와 같은 반면, 당신의 무의식은 통계 알고리즘이 구조화되지 않은 정보의 테라바이트를 엿보는 구글의 방대한 데이터 센터와 같으며 어려운 질문에 대한 놀라운 유용한 솔루션을 놀린다.

이 연구의 의미는 의식적인 뇌가 휴식을 취할 수 있는 시간을 제공하는 것이 무의식이 가장 복잡한 직업적 도전을 통해 교대 분류를 할 수 있게 한다는 것이다. 따라서 다운 습관은 생산적인 작업에 참여하는 시간을 반드시 줄이는 것이 아니라 배치하는 작업 유형을 다양화하는 것이다.

이유 #2: 다운타임은 심층 작업에 필요한 에너지를 충전하는 데 도움이 됩니다.

심리학과학 저널에 자주 인용되는 2008년 논문은 간단한 실험을 설명한다. 피험자들은 두 그룹으로 나뉘었다. 한 그룹은 연구가 수행된 미시간주 앤 아버 캠퍼스 근처의 수목원에서 숲이 우거진 길을 산책하도록 요청받았다. 다른 한 그룹은 번화한 도심 속을 산책하는 데 보내졌다. 그런 다음 두 그룹 모두 후방 지릿수 범위라는 집중 분석 작업을 받았다. 본 연구의 핵심 발견은 자연 집단이 과제를 최대 20% 더 잘 수행했다는 것이다. 자연의 이점은 연구자들이 같은 피험자를 다시 데려와 위치를 변경했을 때 다음 주에 여전히 유지되었는데, 성과를 결정하는 것은 사람이 아니라 숲을 걷어 준비할 기회를 얻었는지 여부였다.

이번 연구는 자연 속에서 시간을 보내는 것이 집중력을 향상시킬 수 있다는 주의력 회복 이론을 검증한 연구 중 하나인 것으로 밝혀졌다. 1980년대 미시간대 심리학자인 레이첼 카플란과 스티븐 카플란(후자는 마크 버먼과 존 조니데스와 함께 여기에서 논의된 2008년 연구를 공동 저술)에 의해 처음 제안된 이 이론은 주의 피로 개념에 기초한다. 집중하기 위해서는 ART가 지시된 주의를 요구하는 것이 필요하다. 이 자원은 유한한데, 만약 당신이 그것을 소진한다면, 당신은 집중하는데 어려움을 겪을 것이다. (우리의 목적을 위해 우리는 이 자원을 이 규칙의 서론에서 논의한 바우메이스터의 제한된 의지력 보유량과 같피상적인 일으로 생각할 수 있다. 2008년 연구는 바쁜 도시 거리를 걷는 것은 길을 넘어서 부딪히지 않도록 하는 시점이나 인도를 막는 느린 관광객 그룹을 언제 주행해야 하는지 파악하는 것과 같은 복잡한 작업을 탐색해야 하기 때문에 지시된 주의를 필요로 한다고 주장한다. 2008년 연구에서는 복잡한 도심 거리를 걸을 때 차에 치이지 않으려면 언제 길을 건너야 할지 판단하거나 인도를 가로막는 관광객 무리를 피하는 등 복잡한 상황을 헤쳐 나가야 하므로 '지향성 주의집중(directed attention)'이 소모된다고 설명합니다.) 이 집중된 탐색의 불과 50분 후에 피험자의 유도된 주의 저장소는 낮았다.

대조적으로, 자연을 걷는 것은 Marc Berman의 주요 저자가 일몰을 예로 들면서 "내재적으로 매혹적인 자극"이라고 부르는 것에 노출시킨다. 이러한 자극은 "중점된 주의 메커니즘이 보충할 기회를 허용하면서 적당히 주의를 불러일으킨다." 다른 말로, 자연을 걸을 때 탐색해야 할 도전이 거의 없기 때문에 주의를 집중할 필요가 없고(밀집된 거리 건널기와 같이), 주의를 적극적으로 집중할 필요가 없도록 충분히 정신을 충분히 점유할 수 있는 충분한 흥미로운 자극을 경험한다. 이 상태는 당신의 지향된 주의 자원 시간이 보충되도록 한다. 이러한 보충 50분 후 피험자들은 집중력이 향상되었다.

(물론, 여러분은 아마도 바깥에서 일몰을 보는 것이 사람들을 기분 좋게 만들고 기분이 좋다는 것이 이러한 작업 수행에 정말 도움이 된다고 주장할 수 있습니다. ( 하지만 사디스틱한 반전으로, 연구진은 혹독한 앤아버 겨울에 실험을 반복함으로써 그 가설을 반박했다. 잔인한 추운 조건에서 밖으로 걷기는 피험자들을 기분 좋게 만들지는 않았지만 그들은 여전히 집중 과제를 더 잘 수행했다.)

우리의 목적에 중요한 것은 ART의 의미가 자연의 이점을 넘어 확장된다는 것을 관찰하는 것이다. 이 이론의 핵심 메커니즘은 이 활동에 휴식을 주는 경우 주의를 집중시키는 능력을 회복할 수 있다는 생각이다. 자연을 걷는 것은 그러한 정신적 휴식을 제공하지만 자연에서 걷는 것은 유사한 "내재적으로 매혹적인 자극"과 지시된 집중으로부터의 자유를 제공하는 한, 많은 휴식 활동도 할 수 있다. 친구와 캐주얼한 대화를 나누거나 저녁을 만들면서 음악을 듣고, 아이들과 게임을 하고, 달리기를 하는 것(업무 중단령을 시행하면 저녁에 시간을 채울 수 있는 활동 유형)은 자연을 걷는 것과 같은 주의 회복 역할을 한다.

반면에 이메일을 확인하고 답하기 위해 저녁을 계속 방해하거나 저녁 식사 후 몇 시간을 남겨두고 다가오는 마감일을 따라잡는다면, 당신은 회복에 필요한 중단 없는 휴식을 당신의 지시된 주의 센터를 빼앗는다. 이러한 작업 대시는 적은 시간만을 소모하더라도 주의 회복이 일어날 수 있는 더 깊은 이완 수준에 도달하는 것을 방해한다. 다음날까지 일을 마쳤다는 자신감만이 뇌가 다음 날 충전을 시작할 수 있는 수준으로 하향 이동하도록 설득할 수 있다. 다시 말해, 저녁에 조금 더 상당한 작업을 짜내려고 하면 그 다음 날에는 휴업을 존중했다면보다 덜 할 수 있을 정도로 효과가 떨어질 수 있습니다.

이유 #3: 저녁 휴업을 대체하는 작업은 보통 그렇게 중요하지 않습니다.

작업일 기준을 명확하게 유지하기 위한 마지막 논거는 우리가 의도적 실천 이론의 발명자인 Anders Ericsson에게 간략히 돌아가야 한다. 1부에서 기억할 수 있듯이, 숙의적 실천은 주어진 기술에 대한 능력을 체계적으로 늘리는 것이다. 그것은 무언가를 더 잘하기 위해 필요한 활동이다. 내가 주장한 바와 같이 심층적인 작업과 의도적인 연습은 실질적으로 겹친다. 여기서 우리의 목적을 위해 우리는 인지적으로 요구하는 노력에 대한 범용적 대용치로서 의도적인 연습을 사용할 수 있다.

에릭슨의 주제에 대한 1993년 논문인 "전문가 성과 획득에서 고의적 실천의 역할"에서 그는 연구 문헌이 개인의 인지적 요구적 작업 능력에 대해 드러내는 것을 검토하는 섹션에 전념한다. 에릭슨은 초보자에게는 하루에 약 1시간 정도의 집중력이 한계인 것처럼 보이지만 전문가에게는 이 수치가 최대 4시간으로 확장될 수 있지만 드물게 더 많다고 지적한다.

예를 들어 인용된 연구 중 하나는 베를린의 Künste 대학에서 훈련하는 엘리트 바이올린 연주자 그룹의 연습 습관을 목록화한다. 이 연구는 엘리트 선수들이 의도적인 연습 상태에서 하루 평균 약 3시간 30분 동안, 일반적으로 두 개의 뚜렷한 기간으로 분리되는 것을 발견했다. 덜 성취한 선수들은 깊이 있는 상태에서 더 적은 시간을 보냈다.

이러한 결과의 시사점은 주어진 날에 심층 작업에 대한 능력이 제한된다는 것이다. 일정에 주의한다면(예: 규칙 4에서 설명한 생산성 전략의 유형을 사용함) 일과일 동안 일일 심층 작업 능력을 발휘해야 한다. 따라서 저녁이 되면 당신은 계속해서 효과적으로 깊이 일할 수 있는 지점을 넘어섰다는 것이다. 따라서 당신이 하는 어떤 작업도 밤에 적합하지 않고 당신의 경력을 진정으로 발전시키는 고가치 활동의 유형이 아닐 것이다. 대신 당신의 노력은 저가치의 피상적 작업(느린 에너지 저속으로 실행됨)에 국한될 것이다. 저녁 근무를 연기함으로써, 다시 말해 중요한 부분을 많이 놓치지 않는다는 것이다.

방금 설명한 세 가지 이유는 작업 일정의 엄격한 종점을 유지하는 일반적인 전략을 뒷받침한다. 실행에 관한 몇 가지 세부 사항을 작성하여 결론을 내립니다.

이 전략에 성공하려면 먼저 작업일이 종료되면 전문가의 관심 분야에 최소한의 문제도 침범할 수 없다는 약속을 받아들여야 합니다. 여기에는 결정적으로 이메일 확인은 물론 업무 관련 웹사이트를 탐색하는 것도 포함됩니다. 두 경우 모두, 짧은 업무 침입조차도 앞서 설명한 휴업 이점을 오랫동안 방해하는 자기 강화적인 주의 분산 흐름을 생성할 수 있습니다.

이 전략으로 성공하기 위한 또 다른 핵심적인 약속은 당신이 성공할 확률을 극대화하기 위해 작업 일정이 끝날 때 사용하는 엄격한 다운 의례로 다운에 대한 약속을 지원하는 것이다. 더 자세하게 이 의례는 모든 불완전한 과제, 목표 또는 프로젝트를 검토하고 각 완료를 위해 신뢰할 수 있는 계획이 있거나 시간이 적절할 때 다시 방문할 수 있는 장소에 캡처되었음을 확인해야 한다. 그 과정은 알고리즘이어야 하는데, 당신이 항상 일련의 단계를 차례로 진행한다. 당신이 끝나면, 당신이 말하는 완성을 나타내는 정해진 문구를 갖는다(내 자신의 의식을 끝내기 위해, 나는 "완성된 폐회"라고 말한다). 이 마지막 단계는 치즈처럼 들리지만 하루 종일 업무와 관련된 생각을 풀어내는 것이 안전하다는 간단한 단서를 마음속에 제공한다.

이 제안을 좀 더 구체화하기 위해 (박사 학위 논문을 작성할 때 처음 개발하고 그 이후로 일정한 형태로 배치) 내 자신의 다운 의식의 단계를 밟아보겠습니다. 가장 먼저 하는 일은 하루가 끝나기 전에 급한 답변이 필요한 것이 없는지 확인하기 위해 제 이메일 받은 편지함을 마지막으로 살펴보는 것입니다. 다음으로 제가 하는 일은 제 마음에 있거나 오늘 초에 적힌 새로운 작업을 공식 작업 목록으로 옮기는 것입니다. (나는 모든 컴퓨터에서 작업 목록을 액세스할 수 있는 능력을 좋아하기 때문에 작업 목록을 저장하는 데 Google Docs를 사용하지만 여기 기술은 실제로 관련이 없다.) 이 작업 목록을 열면 모든 목록의 모든 작업을 빠르게 스키하고 캘린더에서 다음 며칠을 봅니다. 이 두 가지 행동은 내가 잊고 있는 급한 일이나 나에게 몰래 다가오는 중요한 마감일이나 약속이 없도록 한다. 나는 이 시점에서 내 전문 플레이트에 있는 모든 것을 검토했다. 제사를 마무리하기 위해 이 정보를 활용하여 다음 날의 대략적인 계획을 세운다. 계획이 만들어지면 '다운 완료'라고 말하고 그날의 업무 생각이 완성된다.

다운 의식의 개념은 처음에는 극단적으로 보일 수 있지만 그 이유는 제이가르니크 효과라는 것이다. 20세기 초 심리학자인 블루마 제이가르니크의 실험 작업에서 명명된 이 효과는 불완전한 과제가 우리의 주의를 지배하는 능력을 설명한다. 그것은 당신이 오후 5시에 하고 있는 모든 일을 멈추고 "내일까지 일을 끝냈다"고 선언한다면, 블루마 제이가르니크의 실험에서처럼, 당신의 마음에 해결되지 않은 채로 남겨진 많은 의무들이 저녁 내내 당신의 관심을 얻기 위해 계속 싸워(일반적으로 이길 싸움) 정신을 전문적인 문제로부터 멀리하기 위해 고군분투할 가능성이 있음을 말해준다.

처음에는 이 문제를 해결할 수 없을 것 같습니다. 바쁜 지식 종사자라면 누구나 증명할 수 있듯이 항상 미완성으로 남겨진 작업이 있다. 모든 의무가 처리되는 지점에 도달할 수 있다는 생각은 환상입니다. 다행히도 우리는 그것을 마음에서 빼기 위해 어떤 일을 끝내지 않아도 된다. 이 문제에 우리를 구해줄 수 있는 것은 규칙의 초기부터 우리의 친구인 심리학자 로이 바우메이스터가 EJ와 함께 논문을 작성했다. "Consider It Done!"라는 제목의 마시캄포는 이 연구에서 두 연구자는 대상자에게 제이가르니크 효과를 복제하는 것으로 시작했지만(이 경우 연구자는 과제를 할당한 다음 잔인하게 조작된 중단), 중단 직후 피험자에게 나중에 불완전한 과제를 완료하는 방법에 대한 계획을 세우는 것으로 효과의 영향을 크게 줄일 수 있음을 발견했다. 논문을 인용하자면, "목표에 대한 특정 계획에 전념하는 것은 따라서 목표 달성을 촉진할 뿐만 아니라 다른 추구를 위한 인지 자원을 자유롭게 할 수 있다."

앞서 설명한 다운 의례는 이 전술을 활용하여 제이가르니크 효과와 싸운다. 과제 목록의 각 작업에 대한 계획을 명시적으로 식별하도록 강요하지는 않지만(부담한 요구 사항), 공통 목록의 모든 작업을 캡처한 다음 다음 다음 날 계획을 세우는 데 이 작업을 검토하도록 강요한다. 이 의례는 어떤 과제도 잊히지 않도록 보장하며 각각은 매일 검토되고 적절한 시간이 되면 해결된다. 즉, 당신의 마음은 매 순간 이러한 의무를 추적해야 하는 의무에서 해방되는데, 당신의 다운 의례는 그 책임을 떠맡았다.

휴업 의례는 작업 일정이 끝나면 10분에서 15분 정도 더 걸리므로 짜증날 수 있지만 이전에 요약한 체계적인 공백의 보상을 거두기 위해 필요하다. 내 경험에 따르면, 휴업 습관이 고착되기까지, 즉 저녁에 실제로 일과 관련된 생각을 풀기 시작할 만큼 정신이 제의에 대해 믿을 때까지는 1~2주가 걸린다. 하지만 일단 고착되면, 의례는 당신의 삶에서 영구적인 고정물이 될 것입니다. 일상을 건너뛰는 것이 불안감을 가득 채울 정도로요.

심리학의 여러 하위 분야의 수십 년간의 연구는 모두 정기적으로 뇌를 쉬는 것이 심층 작업의 질을 향상시킨다는 결론을 가리킨다. 일할 때는 열심히. 다 되면 다 해. 평균적인 이메일 응답 시간은 다소 어려움을 겪을 수 있지만 지친 동료보다 더 깊이 잠수하는 상쾌한 능력으로 낮 동안 생산된 진정한 중요한 작업의 양을 더 많이 만회할 수 있습니다.

## 규칙 2. 지루함을 받아들여라 (Embrace Boredom)

심층 작업의 기술을 어떻게 마스터하는지 더 잘 이해하기 위해 평일 오전 6시에 뉴욕 스프링 밸리에 있는 크네스 이스라엘 회당을 방문하는 것이 좋다. 그렇게 하면 주차장에서 최소 20대의 차를 찾을 수 있을 것이다. 내부에서 텍스트 작업을 하는 12명의 교인 회원을 만날 수 있습니다. 일부는 고대의 언어를 입으로 읽고 다른 일부는 토론하는 쌍을 이루고 있을 수 있습니다. 방의 한쪽 끝에서 랍비는 토론에서 더 많은 그룹을 이끌 것이다. 스프링 밸리에 모이는 아침 모임은 평일 아침마다처럼 그날 아침 일찍 일어나 유대교 랍비의 복잡한 서면 전통을 공부하는 데 매일 시간을 보내는 신앙의 중심 교리를 실천할 수 있는 수십만 명의 정통 유대인의 극히 일부에 불과하다.

나는 스 이스라엘 교단의 일원이자 아침 공부 모임의 단골 중 한 명인 아담 말린에 의해 이 세상에 소개되었다. 말린이 나에게 설명했듯이, 이 연습의 목표는 매일 한 장의 탈무드 페이지를 해독하는 것(때로는 여기까지도 만들지 못하지만), 종종 체브루타(공부 파트너)와 함께 작업하여 그의 이해를 인지 한계에 더 가깝게 밀어내는 것이다.

마르린에 대해 내가 관심을 갖는 것은 그의 고대 텍스트에 대한 지식이 아니라, 대신 이 지식을 얻기 위해 요구되는 노력의 유형이다. 인터뷰를 해보니 아침 제의의 정신적 강도를 강조했다. "정말 극단적이고 심각한 학문으로, 주로 '딥 워크'으로 구성되어 있다"고 설명했다. "나는 성장하는 사업을 운영하지만 이것은 내가 하는 가장 어려운 뇌 변형"이다. 이 변형은 말린만의 것이 아니라 실제로 뿌리내린 것" 그의 랍비가 한 번 그에게 "정신적 능력의 범위까지 뻗어 있지 않으면 자신을 이 일상적 의무를 다한다고 생각할 수 없다."라고 설명했다.

많은 정통 유대교들과 달리 말린은 20대까지 엄격한 탈무드 교육을 시작하지 않고 늦게 신앙에 도달했다. 이 사소한 것은 말린에게 이러한 정신 칼리스테닉의 영향에 대한 명확한 전후 비교를 허용하기 때문에 우리의 목적에 유용하다는 것을 증명하며 그 결과는 그를 놀라게 했다. 마린은 연습을 시작할 때 예외적으로 잘 교육되었지만, 그는 세 가지 다른 아이비리그 학위를 가지고 있지만, 그는 곧 작은 종교 학교에만 다녔지만 여전히 주위에 "지식층을 춤추"는 동료 신도를 만났다. 그는 "이들 중 많은 사람들이 [전문적으로] 매우 성공적"이라고 나에게 설명했지만 "그러나 그들의 지성을 더 높게 밀어낸 것은 어떤 화려한 학교가 아니라, 그 대신 5학년 초반에 시작된 일상적인 공부였음이 분명해졌다."

잠시 후 말린은 자신의 깊이 있는 사고 능력에 긍정적인 변화를 느끼기 시작했다. 그는 "최근 사업 생활에서 더 창의적인 통찰력을 얻고 있다"고 나에게 말했다. 나는 그것이 이 일상적인 정신 실천과 관련이 있다고 확신한다. 이 일관된 스트레스는 수년 동안 내 정신 근육을 구축해 왔습니다. 이게 내가 시작할 때 목표가 아니었지만 효과가 있다고 말했다.

애덤 말린의 경험은 심층 작업에 관한 중요한 현실을 강조하는데 집중력을 집중하는 능력은 반드시 훈련되어야 하는 기술이다. 이 아이디어는 한 번 지적되면 분명하게 들릴 수 있지만 대부분의 사람들이 그러한 문제를 이해하는 방식에서 벗어나는 것을 나타낸다. 제 경험상, 방해받지 않은 집중을 치실처럼 습관으로 취급하는 것이 일반적인데, 어떻게 해야 하는지 알고 있는 것이 자신에게 좋지만 동기부여가 부족하여 방치해 왔던 것이다. 이러한 사고방식은 단순히 충분한 동기를 모으기만 하면 하루아침에 업무 생활이 산만함에서 집중으로 전환될 수 있다는 것을 의미하기 때문에 매력적이다. 그러나 이러한 이해는 '정신근육'을 강화하는 데 필요한 집중의 어려움과 연습 시간을 무시한다. 아담 말린이 이제 직업생활에서 경험하는 창의적 통찰, 즉 더 깊이 생각하기로 한 일회적 결정과는 거의 관련이 없으며 매일 아침 일찍 이 능력을 훈련시키려는 헌신과 많은 관련이 있다.

그러나 이 아이디어에는 중요한 결과물이 있는데, 주의 분산에 대한 의존에서 마음을 동시에 벗어나지 않으면 초점을 심화하려는 노력이 힘들어질 것이다. 운동선수가 훈련 시간 밖에서 몸을 돌봐야 하는 것과 같은 방식으로, 당신은 지루함의 작은 힌트를 피해 남은 시간을 보내면 가장 깊은 수준의 집중력을 얻기 위해 고군분투할 것이다.

우리는 디지털 시대의 행동에 대한 연구로 잘 알려진 고 스탠퍼드 커뮤니케이션 교수인 클리포드 나스의 연구에서 이 주장에 대한 증거를 찾을 수 있다. 다른 통찰력 중에서도, NAS의 연구는 온라인에서 지속적인 주의 전환이 뇌에 지속적인 부정적인 영향을 미친다는 것을 밝혀냈다. 다음은 NPR의 Ira Flatow와의 2010년 인터뷰에서 이러한 발견을 요약한 NAS입니다.

그래서 우리는 사람들을 항상 멀티태스킹하는 사람들과 거의 하지 않는 사람들로 나눌 수 있는 척도를 가지고 있는데, 그 차이는 현저하다. 항상 멀티태스킹을 하는 사람들은 무관한 것을 걸러낼 수 없다. 그들피상적 작업 메모리를 관리할 수 없습니다. 그들은 만성적으로 주의가 산만해져 있다. 그들은 당면한 과제와 무관한 훨씬 더 큰 뇌 부분을 시작한다. 그들은 거의 정신적인 파손이다.

이 지점에서 플라토우는 만성적으로 산만해진 사람들이 그들의 뇌의 이 재배선을 인식하는지 NASA에게 묻는다.

우리가 대화하는 사람들은 계속 '봐, 내가 집중해야 할 때 나는 모든 것을 끄고 나는 레이저에 집중한다'고 말했고 불행히도 그들은 레이저에 집중하는 것을 불가능하게 만드는 마음의 습관을 발달시켰다. 그들은 무관한 것에 대해 빨아들이고 있다. 그들은 단지 일을 계속할 수 없다. (나의 강조)

나스는 "마치 뇌가 주문형 산만성에 익숙해지면 집중을 하고 싶을 때에도 중독을 떨치기 어렵다"고 밝혔다. 이를 좀 더 구체적으로 표현하면, 만약 당신의 삶에서 잠재적인 지루함의 모든 순간, 예를 들어 친구가 도착할 때까지 식당에서 5분 동안 줄을 서서 기다려야 하거나 혼자 앉아 있어야 하는 순간이 스마트폰을 한눈에 보면 안심된다면, 당신의 뇌는 NAS의 연구에서 "정신적 파손"과 같이 이 집중력을 연습하기 위해 정기적으로 시간을 잡더라도 딥 워크을 할 준비가 되지 않은 지점으로 다시 연결되었을 가능성이 있다.

규칙 #1은 심층 작업을 일정에 통합하고 집중력의 현재 한계에 일관되게 도달하도록 돕기 위해 고안된 루틴과 의례로 지원하는 방법을 가르쳤다. 규칙 #2는 이 한계를 크게 개선하는 데 도움이 될 것이다. 다음의 전략은 깊은 업무 습관을 최대한 활용하기 위해서는 훈련이 필요하다는 핵심 아이디어에 의해 동기를 부여하며 앞서 설명한 바와 같이 이 훈련은 집중력을 향상시키는 것과 주의 분산 욕구를 극복하는 두 가지 목표를 해결해야 한다. 이러한 전략은 산만함을 격리하는 것부터 특별한 형태의 명상을 마스터하는 것까지 다양한 접근법을 포함하며 이 전략은 결합되어 지속적인 산만함으로 인해 파괴되고 집중력에 익숙하지 않은 마음에서 진정으로 레이저와 같은 초점을 전달하는 기구로의 여정을 위한 실용적인 로드맵을 제공한다.

### 산만함 속에서 휴식하지 말고, 집중 속에서 휴식하라

많은 사람들은 필요에 따라 산만 상태와 집중 상태 사이에서 전환할 수 있다고 가정하지만, 방금 주장한 것처럼 이 가정은 낙관적이다: 일단 당신이 산만함을 위해 유선으로 연결되어 있으면 당신은 그것을 갈망한다. 이러한 현실에 동기를 부여하여 이 전략피상적 작업을 유지하는 데 더 적합한 구성으로 두뇌를 재배선하는 데 도움이 되도록 설계되었습니다.

세부 사항에 들어가기 전에 우리의 문제를 완전히 해결하지 못하는 산만 중독에 대한 인기 있는 제안인 인터넷 안식일(때혹 디지털 디톡스라고 함)을 고려하는 것으로 시작하자. 이 의례는 기본적인 형태로 네트워크 기술을 자제하는 데 규칙적인 시간(전형적으로 일주일에 하루)을 따로 두도록 요청한다. 히브리 성경의 안식일이 신과 그의 작품을 감상하기에 잘 맞는 조용하고 성찰하는 시간을 유도하는 것과 같은 방식으로, 인터넷 안식일은 스크린에 붙었을 때 놓치는 것을 상기시키려는 것이다.

누가 인터넷 안식일 개념을 처음 도입했는지 불분명하지만 그 개념을 대중화한 공은 종종 2010년 기술과 인간의 행복에 대한 성찰에서 이 관행을 홍보한 언론인 윌리엄 파워스에 돌아간다. 파워스가 나중에 인터뷰에서 요약하듯이, "연결된 세계 안에서 약간의 단절성을 갖는 것을 배우는, 토로가 한 일을 하라- 도망치지 말라."

산만함의 문제에 대한 많은 조언은 이 잡담에서 벗어나기 위한 시간을 가끔 찾는 일반적인 템플릿을 따른다. 어떤 사람들은 이러한 테더를 피하기 위해 1년에 한두 달을 따로 두기도 하고, 다른 사람들은 파워스의 일주일에 하루 충고를 따르기도 하고, 다른 사람들은 같은 목적을 위해 매일 한두 시간을 따로 두기도 한다. 이 조언의 모든 형태는 어느 정도 이점을 제공하지만 일단 뇌 배선 측면에서 주의 산만 문제를 보면 인터넷 안식일이 그 자체로 주의 산만한 뇌를 치료할 수 없다는 것이 분명해진다. 일주일에 하루만 건강하게 먹으면 대부분의 시간을 먹음으로 보내기 때문에 체중이 감소할 가능성이 없다. 마찬가지로, 주의 분산에 저항하는 데 일주일에 하루만 시간을 할애한다면, 대부분의 시간이 여전히 그것에 굴복하는 데 소비되기 때문에 이러한 자극에 대한 뇌의 갈망을 줄일 것 같지 않다.

인터넷 안식일에 대한 대안을 제안합니다. 집중할 수 있도록 산발적인 주의 분산 휴식을 예약하는 대신 집중에서 산발적인 휴식을 예약하여 주의 분산에 굴복해야 한다. 이 제안을 좀 더 구체화하기 위해 인터넷 사용이 산만함을 유발하는 자극을 추구하는 것과 동의어라는 단순화 가정을 해보자. (물론 집중적이고 깊은 방식으로 인터넷을 사용할 수 있지만 산만 중독자에게는 이것은 어려운 일이다.) 마찬가지로 인터넷이 없는 상태에서 일하는 것도 보다 집중된 업무와 동의어라고 생각해 보자. (네트워크 연결 없이도 주의가 산만해지는 방법을 찾을 수 있지만, 이런 것들은 저항하기 더 쉬운 경향이 있다.)

이러한 대략적인 분류가 확립된 상황에서, 이 전략은 다음과 같이 작동한다: 인터넷을 사용할 때를 미리 계획하고, 그런 다음 이러한 시간 이외에 완전히 피한다. 회사에서 컴퓨터 근처에 메모장을 보관하는 것이 좋습니다. 이 패드에는 다음에 인터넷 사용이 허용되는 시간을 기록하세요. 그 시간에 도착할 때까지 아무리 유혹적이더라도 네트워크 연결은 절대 허용되지 않습니다.

이 전략에 대한 동기는 주의를 산만하게 하는 서비스의 사용 자체가 뇌의 집중 능력을 감소시키지 않는다는 것이다. 오히려 지루함이나 인지적 도전의 아주 작은 힌트에서 낮은 자극/고부가가치 활동에서 높은 자극/저부가가치 활동으로 끊임없이 전환하는 것이 우리의 마음에 새로움의 부재를 결코 용납하지 않도록 가르치는 것이다. 이러한 일정한 전환은 관심을 끌기 위해 경쟁하는 여러 근원을 조직하는 역할을 하는 정신 근육을 약화시키는 것으로 유사하게 이해될 수 있다. 인터넷 사용을 분리함으로써(따라서 주의 분산을 분리함) 주의 분산에 굴복하는 횟수를 최소화하고 그렇게 함으로써 이러한 주의 선택 근육을 강화시킨다.

예를 들어, 당신이 지금 순간부터 30분 동안 다음 인터넷 블록을 계획하고 지루하고 산만함을 느끼기 시작한다면, 다음 30분 동안의 저항은 집중 칼리스테닉의 세션이 된다. 따라서 계획된 산만함의 하루는 유사한 정신 훈련의 하루가 된다.

이 전략의 기본 아이디어는 간단하지만 실행에 옮기는 것은 어려울 수 있습니다. 성공할 수 있도록 하기 위해 고려해야 할 세 가지 중요한 사항이 있습니다.

포인트 #1: 이 전략은 직무에 인터넷 사용 및/또는 신속한 이메일 회신이 필요한 경우에도 작동합니다.

매일 몇 시간을 온라인으로 보내거나 이메일에 빠르게 답해야 한다면 괜찮습니다. 이것은 단순히 직무에 연결이 덜 필요한 사람의 인터넷 차단보다 인터넷 차단이 더 많을 것임을 의미합니다. 인터넷 블록의 총 개수나 기간은 오프라인 블록의 무결성이 그대로 유지되는지 확인하는 것만큼 중요하지 않다.

예를 들어, 회의 사이에 2시간 동안 15분마다 이메일 확인 일정을 잡아야 한다고 상상해 보세요. 또한 이러한 검사는 평균 5분이 소요된다고 상상해 보자. 따라서 이 2시간의 스트레칭을 통해 15분마다 인터넷 블록을 예약하고 나머지 시간은 오프라인 블록에 할당하면 충분하다. 이 예에서 당신은 오프라인 상태에서 주의 분산에 적극적으로 저항하는 상태에서 이 2시간의 기간 중 90분 정도를 보내는 것을 끝으로 보게 된다. 이것은 연결성을 너무 많이 희생하지 않고도 달성되는 많은 양의 집중 훈련으로 작동한다.

포인트 #2: 인터넷 블록을 어떻게 예약하든 인터넷 사용에서 절대적으로 자유로운 시간으로 이 블록 외부의 시간을 유지해야 합니다.

이 목표는 원칙적으로 쉽게 진술할 수 있지만 표준 근무일의 지저분한 현실에서 빠르게 까다로워진다. 이 전략을 실행할 때 직면할 불가피한 문제는 오프라인 블록에서 현재 작업의 진행을 계속하기 위해 검색해야 하는 온라인에 중요한 정보가 있다는 것을 일찍부터 깨닫는 것이다. 다음 인터넷 차단이 잠시 시작되지 않으면 결국 갇힐 수 있습니다. 이 상황에서 유혹은 빨리 굴복하고 정보를 찾아본 다음 오프라인 블록으로 돌아가는 것이다. 이 유혹에 저항해야 해! 인터넷은 유혹적: 당신은 단지 당신의 받은 편지함에서 하나의 핵심 이메일을 검색하고 있다고 생각할 수 있지만 최근에 도착한 다른 "긴급한" 메시지를 보지 않는 것이 어려울 것이다. 당신의 마음이 인터넷과 오프라인 블록 사이의 장벽을 투과성으로 다루기 시작하기 전에 이러한 예외의 많은 부분을 필요로 하지 않으며 이 전략의 이점을 줄인다.

따라서 이 상황에서, 당신이 막혀 있을 때에도 오프라인 블록을 즉시 버리지 않는 것이 중요하다. 가능하다면, 현재 블록의 나머지 부분에 대해 다른 오프라인 활동으로 전환(또는 아마도 이 시간을 여유롭게 채우기도)한다. 이것이 불가능하다면, 아마도 현재의 오프라인 활동을 신속하게 완료해야 할 것인 경우, 올바른 대응은 다음 인터넷 차단이 더 빨리 시작되도록 일정을 변경하는 것이다. 그러나 이 변경의 핵심은 다음 인터넷 차단이 즉시 발생하도록 일정을 잡지 않는 것입니다. 대신 현재 순간과 다음 온라인 접속 시점 사이에 최소 5분 간격을 강제하세요. 이 격차는 미미하여 지나치게 진행을 방해하지는 않지만 행동주의적 관점에서 온라인에 가고 싶은 느낌과 실제로 온라인에 가고 싶은 보상을 분리하기 때문에 상당하다.

점 #3: 직장에서의 웰라로서 가정에서의 인터넷 사용을 스케줄링하는 것은 집중력 훈련을 더욱 향상시킬 수 있다.

저녁과 주말 내내 스마트폰이나 노트북에 매달린 자신을 발견하면, 업무 외 행동은 (두 설정을 거의 구분하지 않는) 당신의 두뇌를 재배선하려는 작업일 동안의 많은 시도를 무산시키고 있을 가능성이 있다. 이 경우 근무일이 끝난 후에도 인터넷 사용 일정을 잡는 전략을 유지해 주시기를 제안드립니다.

문제를 단순화하기 위해 퇴근 후 인터넷 사용 일정을 잡을 때 오프라인 블록에서 시간 민감한 통신(예: 저녁 식사 장소에 동의하기 위해 친구와 문자를 보내는 것)과 시간 민감한 정보 검색(예: 전화로 레스토랑 위치를 검색하는 것)을 허용할 수 있다. 그러나 이러한 실용적인 예외를 제외하고 오프라인 차단 시 휴대전화를 멀리하고 문자를 무시하고 인터넷 사용을 자제합니다. 이 전략의 직장 변종에서와 같이 저녁 엔터테인먼트에서 인터넷이 크고 중요한 역할을 한다면, 그것은 괜찮습니다. 많은 긴 인터넷 블록을 예약하십시오. 여기서 핵심은 주의를 산만하게 하는 행동을 하는 데 드는 시간을 피하거나 줄이는 것이 아니라, 오히려 지루한 순간에도 이러한 주의를 산만하게 하는 것으로 전환하는 것을 거부할 수 있는 충분한 기회를 저녁 내내 자신에게 주는 것이다.

이러한 전략이 특히 어려운 곳은 외부 업무에서 대기할 수밖에 없는 경우(예: 상점에서 줄을 서는 경우)이다. 이러한 상황에서 오프라인 블록에 있으면 일시적인 지루함에 대해 자신을 둘러보고 생각의 동반만으로 그것을 극복하는 것이 중요하다. 단순히 기다림과 지루함이 현대 생활에서 새로운 경험이 되었지만 집중력 훈련의 관점에서 볼 때 그것은 믿을 수 없을 정도로 가치가 있다.

요약하자면, 심층 작업에서 성공하려면 정신분산 자극에 편안하게 저항할 수 있도록 뇌를 재배선해야 합니다. 이것은 당신이 주의를 산만하게 하는 행동을 제거해야 한다는 것을 의미하지 않으며 대신 주의를 끌 수 있는 그러한 행동의 능력을 제거하는 것으로 충분하다. 인터넷 블록을 스케줄링하는 여기에서 제안된 간단한 전략은 이러한 주의 자율성을 회복하는 데 도움이 되는 데 큰 도움이 된다.

### 테디 루스벨트처럼 일하라 (고강도 집중 훈련)

1876-1877학년도에 하버드 대학에 다녔다면 테오도르 루스벨트라는 철이 있고 양고기를 잘게 썬, 당당한, 그리고 불가능하게 에너지가 넘치는 신입생을 알게 되었을 것이다. 만약 당신이 이 젊은 남자와 계속 친해졌다면, 당신은 곧 역설을 알게 될 것이다.

한편으로, 그의 관심은 한 반 친구들이 '놀라운 관심의 배열'이라고 부르는 목록, 즉 전기작가 에드먼드 모리스가 권투, 레슬링, 보디빌딩, 댄스 레슨, 시 낭독, 자연주의에 대한 평생의 집착을 포함하도록 목록에 담은 목록에 절망적으로 흩어져 있는 것처럼 보일 수 있습니다. 후자의 이러한 관심은 루스벨트가 1학년 이후 여름에 첫 책인 아디론닥스의 여름 새를 출판할 정도로 발전했다. 그것은 새 책을 매우 진지하게 받아들이는 출판물인 너틀 조류학 클럽의 게시물에서 좋은 평가를 받았고 이 젊은 나이에 모리스가 루스벨트를 "미국에서 가장 지식 있는 젊은 자연학자 중 한 명"이라고 평가할 만큼 충분했다.

이 과외적 풍요를 뒷받침하기 위해 루스벨트는 그의 주요 초점이었던 하버드에서의 공부에 남은 시간을 심각하게 제한해야 했다. 모리스는 이 시기의 루스벨트 일기와 편지를 이용하여 미래의 대통령이 공부하는 데 하루의 4분의 1을 넘지 않는 시간을 보내고 있다고 추정했다. 따라서 루스벨트의 성적이 화구로 갈 것이라고 예상할 수 있다. 하지만 그들은 그렇지 않았습니다. 그는 학급에서 최고 학생은 아니었지만 확실히 투쟁도 하지 않았는데, 1학년 때 그는 7개 과정 중 5개 과정에서 명예 등급을 받았다. 이 루스벨트 역설의 설명은 이 학업을 다루는 그의 독특한 접근 방식인 것으로 밝혀졌다. 루스벨트는 오전 8시 30분부터 오후 4시 30분까지의 8시간을 고려하여 일정을 시작할 것이다. 이어서 그는 낭송과 수업에 보낸 시간, 운동 훈련(하루에 한 번씩)과 점심 식사를 제거했다. 남아 있는 조각은 연구에만 전념하는 시간으로 간주되었다. 언급한 바와 같이, 이 조각들은 보통 많은 총 시간을 합치지는 않았지만 그는 이 기간 동안 학교 과제에만 집중하고 수포의 강도로 그렇게 함으로써 그 중 가장 많은 부분을 얻을 수 있었다. 모리스는 "책상에서 보내는 시간은 비교적 적었다"면서도 "하지만 집중력이 너무 강렬했고 읽기도 너무 빨라서 [학교 일에서] 더 많은 시간을 보낼 수 있었다"고 설명했다.

이 전략은 때때로 루스벨트 강도의 돌출을 자신의 작업일에 주입하도록 요청한다. 특히, 우선순위 목록에서 높은 심층 작업(즉, 완료하기 위해 심층 작업이 필요한 것)을 식별한다. 당신이 보통 이런 유형의 의무에 대해 얼마나 시간을 남겨두었을지 추정하고 이번에는 크게 줄이는 어려운 기한을 자신에게 부여하라. 가능하면, 예를 들어 완료된 프로젝트를 기대하는 사람에게 언제 예상해야 하는지 알려줌으로써 기한을 공개적으로 약속하십시오. 이것이 불가능하다면(또는 당신의 직장을 위태롭게 하는 경우), 당신의 전화기에 카운트다운 타이머를 설정하고 당신이 일하는 동안 그것을 볼 수 없는 곳에 지지함으로써 스스로 동기를 부여한다.

이 시점에서 딥 워크을 제때 완료하는 데는 한 가지 가능한 방법만 있어야 합니다. 이메일 휴식, 하루를 꿈꾸지 않고 페이스북 브라우징, 커피 머신으로의 반복적인 여행이 없습니다. 하버드의 루스벨트처럼, 모든 자유 뉴런으로 과제를 공격하여 그것이 당신의 흔들리지 않는 집중력 속에서 자리를 내줄 때까지 공격하라.

처음에는 이 실험을 일주일에 한 번 이상 시도하지 않는 것이 좋다. 초집중 훈련 효과는 뛰어나지만 뇌의 피로를 풀고 스트레스를 낮출 충분한 휴식 시간이 필요하기 때문이다. 완성 시간에 대한 집중력 거래 능력에 확신을 가지면 루스벨트 대시의 빈도를 높인다. 그러나 항상 자신이 설정한 기한을 실행 가능성의 한계에 맞추는 것을 기억하십시오. 버저를 지속적으로 치는 것이 가능해야 하지만(또는 적어도 가까이 있을 수 있어야 하지만), 그러기 위해서는 치아를 찌르는 집중력이 필요하다.

이 전략의 주요 동기는 간단합니다. 심층 작업은 대부분의 지식 작업자가 편안한 수준을 훨씬 넘어서는 수준의 집중력이 필요하다. 루스벨트는 인공 기한을 활용하여 정기적으로 달성할 수 있는 수준을 체계적으로 높이는 데 도움이 되며 어떤 의미에서는 뇌의 주의 집중 센터에 대한 간격 훈련을 제공한다. 추가적인 이점은 이러한 대시가 산만과 양립할 수 없다는 것입니다. 따라서 완성된 모든 대시는 잠재적으로 지루하고 더 새로운 자극을 찾고 싶은 세션을 제공하지만 저항한다. 앞의 전략에서 주장한 것처럼 그러한 충동에 저항하는 연습을 할수록 그러한 저항이 용이해진다.

이 전략을 몇 달 동안 실행한 후, 이전에 경험한 것보다 더 강한 강도 수준에 도달할 때 집중하는 것이 무엇을 의미하는지에 대한 이해가 변형될 것이다. 그리고 당신이 어린 루스벨트 같은 사람이라면, 당신은 너톨 조류학 동아리의 항상 신중한 구성원들에게 감동을 주기 위해 노력하는 것과 같이, 그것이 생성하는 여분의 자유 시간을 삶의 더 미세한 즐거움으로 재용도할 수 있다.

### 생산적으로 명상하라

MIT에서 박사 후 동료로 보낸 2년 동안 아내와 나는 역사적인 비콘 힐의 핀크니 스트리트에 있는 작지만 매력적인 아파트에서 살았다. 나는 보스턴에 살면서 케임브리지에서 일했지만 두 곳은 찰스 강 반대편에 앉아 1마일밖에 떨어져 있지 않았다. 길고 어두운 뉴잉글랜드 겨울에도 건강을 유지하기 위해, 나는 가능한 한 도보로 집과 직장을 여행함으로써 이러한 근접성을 이용하기로 결정했다.

내 루틴은 아침에는 롱펠로우 다리를 건너 캠퍼스로 걸어가야 했다(내 실망으로 도시가 눈보라가 나면 보행자 길을 삽질하는 데 종종 느리다). 점심시간을 전후하여 러닝 기어를 갈아입고 찰스 강둑을 따라가는 더 긴 길을 따라 집으로 달려가 매사추세츠 애비뉴 브릿지를 건다. 집에서 간단한 점심과 샤워를 한 후, 나는 보통 캠퍼스로 돌아가는 길에 강을 건너 지하철을 타고 (아마도 트레킹에서 1/3마일을 절약) 일정이 끝나면 집으로 걸어간다. 즉, 이 기간 동안 발로 서 있는 시간을 많이 보냈습니다. 내가 이제 네가 자신의 심층 작업 훈련에서 채택할 수 있는 실천, 즉 생산적인 명상을 개발하게 된 것은 바로 이 현실이었다.

생산적인 명상의 목표는 걷기, 조깅, 운전, 샤워 등 육체적으로 정신적으로 바쁘지는 않지만 정신적으로 바쁜 시간을 가져서 잘 정의된 하나의 전문적인 문제에 주의를 집중하는 것이다. 직업에 따라 이 문제는 기사를 개략적으로 설명하거나, 강연을 작성하거나, 증명에 대한 진전을 이루거나, 비즈니스 전략을 세밀하게 시도하는 것일 수 있습니다. 마음챙김 명상에서와 마찬가지로, 당신은 그것이 방황하거나 멈출 때, 계속해서 당면한 문제에 주의를 환기시켜야 한다.

나는 보스턴에 살면서 매일 하천을 건너는 산책 중 적어도 한 곳에서 생산적인 명상을 연습했고 내가 나아지면서 결과도 나타났다. 예를 들어, 나는 도보로 지난 책의 상당 부분의 장 개요를 작성했고 학문 연구에서 많은 매듭 같은 기술 문제에 대해 진전을 이뤘다.

나는 당신이 당신의 삶에서 생산적인 명상 연습을 채택할 것을 제안한다. 매일 진지한 세션이 반드시 필요한 것은 아니지만 당신의 목표는 일반적인 주에 적어도 두세 번의 세션에 참여하는 것이어야 한다. 다행히도 이 전략을 위한 시간을 찾는 것은 쉬우며, 그렇지 않으면 낭비될 기간(견을 걷거나 출퇴근하는 것과 같은)을 활용하고, 올바르게 수행하면 실제로 업무에서 시간을 빼앗는 대신 전문적인 생산성을 높일 수 있기 때문이다. 사실, 당신은 특히 생산적인 명상을 현재 가장 시급한 문제에 적용하기 위해 일과 중 산책을 계획하는 것을 고려할 수도 있다.

그러나 나는 (좋은데도) 생산성 이점 때문에 이 관행을 제안하지 않는다. 나는 대신 당신의 깊은 사고 능력을 빠르게 향상시키는 능력에 관심이 있다. 내 경험에 따르면 생산적 명상은 이 규칙의 시작 부분에서 소개된 두 가지 핵심 아이디어를 기반으로 한다. 주의 분산에 저항하고 잘 정의된 문제에 반복적으로 주의를 돌리게 함으로써 주의 분산 저항 근육을 강화하는데 도움을 주며 단일 문제에 집중력을 점점 더 깊게 밀어주도록 하여 집중력을 날카롭게 한다.

생산적인 명상에 성공하기 위해서는 어떤 형태의 명상과 마찬가지로 잘하기 위한 연습이 필요하다는 것을 인식하는 것이 중요하다. 포닥 초반에 이 전략을 처음 시도했을 때, 나는 내 노력에 대해 보여줄 새로운 것이 거의 없는 긴 "생각"을 끝내는 절망적으로 산만해졌다. 실제 결과를 경험하기까지 12회 정도 걸렸습니다. 비슷한 것을 기대해야 하므로 인내심이 필요할 것입니다. 그러나 이 램프업 프로세스를 가속화하기 위해 두 가지 구체적인 제안을 드릴게요.

제1의 권고사항: 주의가 산만해지고 고리가 되는 것을 경계하라

초보자로서, 당신이 생산적인 명상 세션을 시작할 때, 당신의 마음의 첫 번째 반항 행위는 관련이 없지만 겉보기에 더 흥미로운 생각을 제공하는 것이다. 예를 들어, 내 마음은 필자가 작성해야 한다는 것을 알고 있는 이메일을 작성하기 시작함으로써 종종 주의를 끌기에 성공했다. 객관적으로 말하면, 이 사고의 열은 매우 둔하게 들리지만 순간에는 불가능하게 유혹적이 될 수 있다. 눈앞의 문제에서 주의가 빠져나가는 것을 알면 나중에 그 생각으로 돌아갈 수 있음을 부드럽게 상기시킨 다음 주의를 다시 돌려준다.

이런 유형의 주의 분산은 여러 면에서 생산적인 명상 습관을 기르는 데 있어 패배해야 할 명백한 적이다. 미묘하지만 동등하게 효과적인 적은 루핑하고 있다. 어려운 문제에 직면했을 때, 당신의 마음은 그렇게 하도록 진화된 것처럼 가능하면 에너지의 과도한 소비를 피하려고 시도할 것이다. 이 지출을 회피하려는 한 가지 방법은 문제에 대해 이미 알고 있는 내용을 반복적으로 반복함으로써 문제에 더 깊이 빠져드는 것을 피하는 것이다. 예를 들어, 증명 작업을 할 때 내 마음은 필요한 해결책을 향해 이러한 결과를 기반으로 하는 더 힘든 작업을 피하기 위해 단순 예비 결과를 반복적으로 재조명하는 경향이 있다. 루핑은 생산적인 명상 세션을 빠르게 뒤집을 수 있으므로 조심해야 합니다. 당신이 그것을 알아차렸을 때, 당신은 루프에 있는 것처럼 느낀다고 스스로에게 언급한 다음, 다음 단계를 향해 주의를 환기시킨다.

제안 #2: 깊은 사고를 구조화하세요

문제에 대해 '깊게 생각'하는 것은 자명한 활동처럼 보이지만 실제로는 그렇지 않다. 산만함이 없는 정신적 풍경, 어려운 문제, 생각할 시간을 마주할 때 다음 단계는 의외로 분명하지 않을 수 있다. 제 경험상, 이 깊은 사고 과정을 위한 구조를 갖추는 것이 도움이 됩니다. 문제를 해결하기 위해 관련 변수를 주의 깊게 검토한 다음 작업 메모리에 이러한 값을 저장하는 것을 제안합니다. 예를 들어, 당신이 책 장의 개요를 작성하고 있다면, 관련 변수들이 당신이 장에서 만들고자 하는 주요 사항일 수 있다. 당신이 대신 수학 증명서를 풀려고 한다면, 이 변수들은 실제 변수들이거나 가정들, 또는 렘마들일 수 있다. 관련 변수가 확인되면 해당 변수를 사용하여 답해야 하는 구체적인 다음 단계를 정의한다. 책 장 예에서 이 다음 단계는 "어떻게 이 장을 효과적으로 열 것인가?"이고 증명으로 "이 속성이 성립한다고 가정하지 않으면 무엇이 잘못될 수 있습니까?"라고 말할 수 있다.

다음 단계를 해결할 수 있다고 가정하면, 깊은 사고에 대한 구조화된 접근법의 마지막 단계는 식별한 답을 명확하게 검토하여 얻은 결과를 통합하는 것이다. 이 시점에서 프로세스를 다시 시작함으로써 다음 차원의 깊이로 자신을 밀어낼 수 있습니다. 변수를 검토하고 저장하고 다음 단계를 식별하고 해결한 다음 얻은 결과를 통합하는 이 주기는 집중력을 위한 강렬한 운동 루틴과 같습니다. 생산적인 명상 세션을 더 많이 활용하고 깊이 갈 수 있는 능력을 향상시키는 속도를 가속화하는 데 도움이 될 것입니다.

### 카드 한 벌을 통째로 암기하라

단 5분만 주어지면 다니엘 킬로프는 카드 엇갈린 갑판, 무작위 숫자 100자리의 문자열, 또는 115개의 추상적인 모양(이 마지막 위업은 호주 국가 기록을 수립함) 중 하나를 외울 수 있다. 따라서 최근 호주 메모리 대회에서 킬로프가 연속 은메달을 딴 것은 놀라운 일이 아니다. 킬로프의 역사를 고려할 때 아마도 놀라운 것은 그가 결국 정신 운동선수가 되었다는 것이다.

킬로프는 나에게 "나는 특별한 기억을 가지고 태어나지 않았다. 실제로 고등학교 시절 그는 스스로를 잊고 조직되지 않은 존재로 여겼다. 학업적으로도 고전하다가 결국 주의력 결핍 장애 진단을 받았다. 킬로프가 기억력을 진지하게 훈련하기 시작한 것은 국내에서 가장 성공적이고 가시적인 기억력 챔피언 중 한 명인 탄셀 알리와 우연히 만난 뒤였다. 그가 대학 학위를 취득할 때까지 그는 첫 번째 국가대항전 메달을 획득했다.

세계적인 정신 운동선수로의 이러한 변신은 신속했지만 전례가 없는 것은 아니었다. 2006년 미국의 과학 작가 조슈아 포어는 2011년 베스트셀러인 '아인슈타인과 함께하는 달걸음'에서 기록한 여행인 (강도 높은) 훈련 1년 만에 미국 기억 선수권 대회에서 우승했다. 그러나 우리에게 중요한 것은 킬로프의 이야기에서 이 집중적인 기억 발달 기간 동안 그의 학업적 성과에 무슨 일이 일어났는지이다. 그는 뇌를 훈련하면서 주의력 결핍 장애로 어려움을 겪는 학생에서 1등급 명예로 까다로운 호주 대학을 졸업했다. 그는 곧 국내 최고 대학 중 한 곳의 박사 과정에 받아들여졌으며 현재 유명한 철학자의 밑에서 공부하고 있다.

이러한 변화에 대한 한 가지 설명은 세인트루이스에 있는 워싱턴대학에서 메모리 랩을 운영하는 헨리 로디거가 주도한 연구에서 나온다. 2014년 Roediger와 그의 협력자들은 인지 테스트 배터리를 갖춘 팀을 샌디에이고에서 열린 극한 기억 토너먼트에 보냈다. 그들은 이러한 엘리트 암기자들이 전체 인구와 차별화되는 점이 무엇인지 이해하고자 했다. 로디거는 뉴욕타임스 블로그 게시글(내 강조)에서 "기억 운동선수와 나머지 우리와 가장 큰 차이점 중 하나는 전혀 기억의 직접적인 척도가 아니라 주의의 인지 능력이라는 것을 발견했다"고 설명했다. 문제의 능력은 '주의 조절'이라고 하며 대상자가 필수 정보에 대한 집중력을 유지하는 능력을 측정한다.

기억 훈련의 부작용은 즉, 일반적인 집중력의 향상이다. 그런 다음 이 능력은 심층 작업을 요구하는 모든 작업에 유익하게 적용될 수 있습니다. 따라서 우리가 추측할 수 있는 다니엘 킬로프는 수상한 기억 때문에 스타 학생이 된 것이 아니라, 오히려 이 기억을 개선하려는 그의 탐구였으며 그것이 그에게 (공교롭게도) 학문적으로 번창하는 데 필요한 딥 워크의 가장자리를 제공했다.

여기에 설명된 전략은 킬로프 훈련의 핵심 부분을 복제하여 집중력을 향상시키는 것과 같은 몇 가지 개선 사항을 얻도록 요청한다. 특히 대부분의 정신 운동선수들의 레퍼토리에서 표준적이지만 상당히 인상적인 기술, 즉 믹스 카드 한 덱을 외우는 능력을 배우도록 요청한다.

내가 가르쳐 줄 카드 암기 기술은 이 특별한 도전에 대해 꽤 잘 아는 사람, 즉 전 미국 메모리 챔피언이자 카드 암기 세계 기록 보유자인 론 화이트에게서 나온 것이다. \* 화이트가 가장 먼저 강조하는 것은 전문 기억 운동선수들이 로테 암기를 시도하지 않는다는 것, 즉 단순히 정보를 머릿속으로 반복하면서 반복적으로 보고 있다는 것이다. 이러한 유지에 대한 접근법은 소진된 학생들 사이에서 인기가 있지만 우리의 뇌가 어떻게 작동하는지 잘못 이해한다. 우리는 추상적인 정보를 빠르게 내면화하기 위해 유선화되어 있지 않다. 그러나 우리는 장면을 기억하는 데 정말 능숙합니다. 회의 개막에 참석하거나 한동안 보지 못했던 친구를 만나 술 한 잔 하는 등 최근 인생에서 기억에 남는 사건을 떠올려 보세요. 최대한 현장을 선명하게 그려보세요. 이 시나리오의 대부분의 사람들은 당신이 그 당시 그것을 기억하기 위해 특별한 노력을 기울이지 않았음에도 불구하고 사건에 대한 놀라울 정도로 생생한 회상을 불러일으킬 수 있다. 이 기억에 있는 고유한 세부 사항을 체계적으로 세었다면, 전체 항목의 수는 놀라울 정도로 많을 것이다. 즉, 당신의 마음은 올바른 방식으로 저장된다면 많은 세부 정보를 빠르게 저장할 수 있다. 론 화이트의 카드 암기 기법은 이러한 통찰을 바탕으로 한다.

화이트는 이 대용량 암기 작업에 대비하기 위해 가정 내 5개 방을 걷는 정신적 이미지를 마음속에 담아두는 것부터 시작하라고 권고한다. 아마도 당신은 문 안으로 들어와 앞 복도를 지나 아래층 욕실로 돌아서고, 문 밖으로 나와 객실로 들어가고, 부엌으로 들어가고, 그 다음 계단을 내려서 지하로 향한다. 각 방에서 보이는 것에 대한 선명한 이미지를 불러일으켜 보세요.

잘 알려진 장소의 이 정신적 산책 과정을 쉽게 떠올릴 수 있게 되면, 이 각 방의 10가지 항목을 모아 놓피상적인 일을 마음속에 고정한다. 화이트는 이러한 물건들이 연필이 아닌 책상처럼 크기가 커야 한다고 권고한다. 다음으로 각 방에서 이러한 항목을 각각 살펴보는 순서를 설정합니다. 예를 들어, 앞 복도에서는 입장 매트, 매트 옆 바닥에 있는 신발, 신발 위 벤치 등을 볼 수 있습니다. 이것들을 합하면 50개의 아이템들만 나오므로, 나중에 이 이미지들을 표준 데크의 모든 카드들에 연결할 때 필요할 전체 52개의 아이템들을 얻기 위해, 아마도 당신의 뒤뜰에 2개의 아이템들을 더 추가하라.

방들을 돌아다니며 각 방의 물건들을 정해진 순서대로 바라보는 이 정신적인 운동을 실천한다. 이런 유형의 암기는 익숙한 장소와 사물에 대한 시각적 이미지를 기반으로 하기 때문에 학창시절 기억할 수 있는 로테 암기보다 훨씬 쉬울 것이다.

카드 한 덱을 외우기 위한 준비의 두 번째 단계는 기억에 남는 사람 또는 사물을 52개의 가능한 카드 각각과 연관시키는 것이다. 이 과정을 더 쉽게 하기 위해, 카드와 대응하는 이미지 사이에 어떤 논리적 연관성을 유지하려고 시도한다. 화이트는 다이아몬드가 부를 의미하기 때문에 도널드 트럼프를 다이아몬드의 왕과 연관시킨 예를 제시한다. 데크에서 카드를 무작위로 뽑고 관련 이미지를 즉시 회상할 수 있을 때까지 이러한 연상을 연습한다. 이전과 같이 기억에 남는 시각적 이미지와 연상의 활용은 이러한 연결을 형성하는 작업을 단순화할 것이다.

앞서 언급한 두 단계는 한 번만 하고 특정 데크를 암기할 때 반복적으로 활용할 수 있는 사전 단계이다. 이 단계들이 끝나면, 당신은 메인 이벤트, 즉 갓 섞인 데크에서 52장의 카드를 가능한 한 빨리 기억할 준비가 되어 있다. 여기 방법은 간단합니다. 집의 정신적인 탐방을 시작하세요. 각 항목을 접하면서 셔플드 데크에서 다음 카드를 보고 해당 기억에 남는 사람이나 사물이 해당 항목 근처에서 기억에 남는 일을 하는 것을 상상해 본다. 예를 들어, 첫 번째 항목과 위치는 앞쪽 입구 매트이고 첫 번째 카드가 다이아몬드 왕이라면, 앞 복도의 입구 매트에 있는 비싼 로퍼에서 토막을 닦고 있는 도널드 트럼프를 상상할 수 있습니다.

적절한 정신적 이미지와 사물을 적절한 순서로 연관시키면서 방을 조심스럽게 통과한다. 방을 완성한 후 이미지를 고정하기 위해 연속적으로 몇 번 걸어보고 싶을 수도 있습니다. 일단 당신이 끝나면, 당신은 친구에게 데크를 건네고 엿보지 않고 순서대로 카드를 거리며 그를 놀라게 할 준비가 되어 있다. 그러기 위해서는 물론 각 기억에 남는 인물이나 사물을 해당 카드에 연결하면서 정신적인 워크스루를 한 번 더 수행하는 것이 필요하다.

이 기술을 연습하면, 당신보다 앞서 온 많은 정신 운동 선수들처럼, 결국 몇 분 만에 전체 데크를 내면화할 수 있다는 것을 발견할 것이다. 물론 친구들에게 감동을 주는 능력보다 더 중요한 것은 그러한 활동이 당신의 마음을 제공하는 훈련이다. 앞서 설명한 단계를 진행하려면 명확한 목표에 계속해서 주의를 집중해야 한다. 이것은 체중에 반응하는 근육처럼 일반적인 집중 능력을 강화하여 더 쉽게 더 깊이 들어갈 수 있게 한다.

그러나 카드 암기에 특별한 것이 없다는 분명한 점은 강조할 가치가 있다. 규칙 #2의 도입부에서 나온 아담 말린처럼 탈무드를 공부하거나 생산적인 명상을 연습하거나 노래의 기타 부분을 귀로 배우려는 것(내가 과거에 즐겨 했던 것)과 같이 변함없는 주의를 요구하는 구조화된 사고 과정은 유사한 효과를 가질 수 있다. 카드 암기가 이상하게 느껴진다면, 다시 말해 비슷한 인지적 요구 사항을 만드는 대체품을 선택하세요. 이 전략의 핵심은 세부 사항이 아니라 집중하는 능력이 훈련에 대한 헌신만큼만 강하다는 동기 부여 아이디어입니다.

## 규칙 3. 소셜 미디어를 끊어라 (Quit Social Media)

2013년 저자이자 디지털 미디어 컨설턴트인 바룬데 써스턴이 실험을 시작했다. 그는 페이스북, 트위터, 포스퀘어(2011년 '올해의 시장'을 수상한 서비스), 이메일조차 없는 25일 동안 온라인 생활에서 단절하기로 결정했다. 휴식이 필요했어. 친구들로부터 "세계에서 가장 연결이 잘 된 남자"로 묘사되는 서스턴은 자신의 계산에 따라 5만 9천 건 이상의 Gmail 대화에 참여했으며 실험을 앞둔 해에 자신의 페이스북 벽에 1500번 게시했다. 전 소진됐어요. 튀겨. 됐어. 건배를 해달라"고 설명했다.

우리는 터스턴의 실험에 대해 알고 있는데, 그가 패스트 컴퍼니 잡지의 표지 기사에서 그것에 대해 쓴 것인데, 아이러니하게도 제목은 "#UnPlug"이다. 그는 "그 첫 주가 끝날 무렵, 나의 날들의 조용한 리듬은 훨씬 덜 이상하게 보였다"고 말했다. "새로운 것을 알지 못하는 것에 대한 스트레스가 덜했고 인터넷에서 그 존재에 대한 공유된 문서적 증거가 없음에도 불구하고 여전히 존재한다고 느꼈다." 써스턴은 낯선 사람들과 대화를 시작했다. 그는 인스타그램을 찍지 않고 음식을 즐겼습니다. 그는 자전거를 샀다("동시적으로 트위터를 확인하려고 하지 않을 때 그것을 타는 것이 더 쉽다는 것"). 터스턴은 "끝은 너무 빨리 왔다"고 한탄했다. 그러나 그는 창업 회사를 운영하고 책을 판매하기 때문에 25일이 지나자 마지못해 온라인 존재를 다시 활성화했습니다.

바라툰데 서스턴의 실험은 페이스북, 트위터, 인스타그램과 같은 소셜 네트워크와 비즈니스 인사더, 버즈피드와 같은 인포테인먼트 사이트와 우리 문화의 현재 관계에 대한 두 가지 중요한 점을 깔끔하게 요약한다. 첫 번째 점은 이러한 도구들이 우리의 시간을 파편화시키고 집중하는 능력을 감소시킨다는 것을 점점 더 인식하고 있다는 것이다. 이 현실은 더 이상 많은 논쟁을 일으키지 않으며 우리 모두는 그것을 느낀다. 이것은 여러 사람들에게 현실적인 문제이지만 특히 심도 있게 작업할 수 있는 능력을 향상시키려는 경우 문제가 심각하다. 예를 들어, 앞의 규칙에서 초점을 세밀하게 하는 데 도움이 되는 몇 가지 전략을 설명했습니다. 이러한 노력은 당신이 동시에 사전 실험 바룬데 서스턴처럼 행동하여 그러한 훈련 밖의 당신의 삶이 앱과 브라우저 탭의 산만한 흐릿한 상태로 남아 있도록 하면 훨씬 더 어려워질 것이다. 의지는 제한되어 있으므로 주의를 끌고 있는 유인 도구가 많을수록 중요한 것에 집중하는 것이 더 어려워진다. 따라서 심층 작업의 기술을 마스터하려면 시간을 빼앗으려는 많은 전환에서 시간과 주의를 다시 통제해야 합니다.

그러나 이러한 산만함에 맞서 싸우기 전에 전장을 더 잘 이해해야 합니다. 이는 바로운데 서스턴의 이야기에서 요약되는 두 번째 중요한 점, 즉 지식 종사자들이 현재 네트워크 도구와 주의의 이 문제를 논의하는 무력감으로 이어진다. 이러한 도구들의 요구에 당시에 압도된 터스턴은 자신의 유일한 선택이 (일시적으로) 인터넷을 아예 그만두는 것뿐이라고 느꼈다. 급격한 인터넷 안식일\*이 소셜 미디어와 인포테인먼트가 생성하는 산만함에 대한 유일한 대안이라는 이 생각은 점점 더 우리의 문화적 대화에 스며들어 있다.

이 문제에 대한 이항적 대응의 문제는 이 두 가지 선택이 너무 조잡해서 유용하지 않다는 것이다. 인터넷에서 그만두겠다는 생각은 물론 (분산에 관한 글을 쓰는 기자라면) 대부분의 사람들에게는 불가능한 과잉 충전된 빨대맨이다. 아무도 실제로 바라툰데 서스턴의 길을 따를 수 있는 것이 아니며 이 현실은 우리의 현재 산만 상태를 피할 수 없는 것으로 받아들이는 유일한 대안으로 남아 있는 정당성을 제공한다. 예를 들어, 써스턴이 인터넷 안식년 기간 동안 얻은 모든 통찰력과 명확성에도 불구하고 실험이 끝나면 그가 시작한 파편화된 상태로 다시 미끄러지는 데 오랜 시간이 걸리지 않았다. 터스턴의 글이 패스트컴퍼니에 처음 나온 지 6개월 만에 떨어진 이 장의 글을 처음 쓰기 시작한 날, 개혁된 커넥터는 그가 깨어난 지 몇 시간 만에 이미 12개의 트윗을 보냈다.

이 규칙은 세 번째 옵션을 제안함으로써 이러한 루트에서 벗어나려고 시도하는데, 이러한 도구가 본질적으로 악하지 않으며 그 중 일부가 당신의 성공과 행복에 매우 중요할 수 있음을 인정하는 동시에 사이트가 당신의 시간과 관심에 정기적으로 접근할 수 있도록 하는 임계값(개인 데이터 언급은 하지 않음)이 훨씬 더 엄격해야 하며 따라서 대부분의 사람들이 그러한 도구를 훨씬 적게 사용해야 한다는 것을 인정한다. 다시 말해, 나는 당신에게 2013년 바라툰데 써스턴이 25일 동안 했던 것처럼 인터넷을 완전히 그만두라고 요청하지 않을 것이다. 하지만 애초에 그를 그 과감한 실험으로 몰아넣었던 산만한 초연결 상태를 거부해 달라고 요청할 것이다. 중간 지대가 있는데, 만약 당신이 깊은 업무 습관을 길러내는 데 관심이 있다면, 당신은 거기에 도달하기 위해 반드시 싸워야 한다.

네트워크 도구 선택에서 이러한 중간 지점을 찾는 첫 번째 단계는 대부분의 인터넷 사용자가 현재 전개하는 기본 결정 프로세스를 이해하는 것이다. 2013년 가을에 페이스북에 가입하지 않은 이유를 설명하는 글을 써서 이 과정에 대한 통찰을 얻었다. 이 작품은 비난적이 아니라 설명적이어야 했지만 그럼에도 불구하고 많은 독자를 방어에 내세워 서비스 사용에 대한 정당화 사유로 답장을 하도록 이끌었다. 이러한 정당화의 몇 가지 예는 다음과 같다.

* "처음 페이스북을 시작한 이유는 재미 때문이었어요. 친구들이 뭘 하는지 보고, 재미있는 사진을 올리고, 가볍게 댓글을 달 수 있으니까요."
* "처음 가입했을 때는 왜 가입했는지도 몰랐어요... 단순한 호기심으로 단편 소설 포럼에 참여했는데, 거기서 글솜씨도 늘고 좋은 친구들도 사귀었죠."
* "고등학교 때 알던 사람들이 페이스북에 많이 있어서 사용해요."

이러한 응답에 대해 나에게 놀라운 점은 다음과 같다(이 주제에 대해 받은 많은 피드백을 대표한다): 놀랍게도 사소하다. 예를 들어, 이 목록의 첫 번째 댓글을 달는 사람이 페이스북을 사용하는 데 약간의 오락을 찾는지 의심하지 않지만 이 사람이 서비스에 등록하기 전에 오락 옵션의 심각한 결핍을 겪고 있지 않았다고 가정할 수도 있다. 나는 이 사용자가 갑자기 서비스가 중단되더라도 지루함을 해소하는 데 성공할 것이라고 더 장담합니다. 페이스북은 기껏해야 이미 존재했던 많은 엔터테인먼트 옵션에 (아마도 상당히 평범한) 하나의 옵션을 더 추가했다.

또 다른 논평가는 글쓰기 포럼에서 친구를 사귀는 것을 인용했다. 나는 이 친구들의 존재를 의심하지 않지만 우리는 이 친구 관계가 컴퓨터 네트워크를 통해 앞뒤로 짧은 메시지를 보내는 것을 기반으로 한다는 점을 감안할 때 가벼운 것이라고 가정할 수 있다. 그런 가벼운 우정은 별 문제가 없지만 이 사용자의 사회생활의 중심에 있을 가능성은 낮다. 고등학교 친구들과 다시 연결된 해설자에 대해서도 비슷한 것을 말할 수 있는데, 이것은 좋은 전환이지만 그의 사회적 연결감이나 행복감에 중심이 되는 것은 아니다.

분명히 말해서, 나는 이전에 확인된 이점을 하하려고 하는 것이 아니다. 그러나 내가 강조하는 것은 이러한 이점이 사소하고 다소 무작위적이라는 것이다. (대조적으로, 당신이 누군가에게 월드 와이드 웹 또는 이메일의 사용을 더 일반적으로 정당화하도록 요청했다면, 그 주장은 훨씬 더 구체적이고 설득력이 있을 것이다.) 이 관찰에 대해 가치는 가치라고 답할 수 있습니다. 페이스북과 같은 서비스를 사용하면 작은 경우에도 약간의 추가 이점을 찾을 수 있다면 왜 사용하지 않는가? 나는 이 사고방식을 어떤 이익이든지 네트워크 도구를 사용하기에 충분한 정당화로 식별하기 때문에 어떤 이익이든 사고방식이라고 부른다. 좀 더 자세히.

네트워크 도구 선택에 대한 모든 이점 접근법: 네트워크 도구를 사용할 때 가능한 이점을 식별할 수 있거나 사용하지 않으면 놓칠 수 있는 모든 것을 식별할 수 있는 경우 네트워크 도구를 사용하는 것이 정당하다.

물론 이 접근 방식의 문제는 문제가 되는 도구와 함께 오는 모든 부정적인 점을 무시한다는 것이다. 이러한 서비스는 당신의 직업적, 개인적 목표(심층 작업과 같은)를 보다 직접적으로 지원하는 활동으로부터 시간과 관심을 빼앗는 중독성 있게 설계되었다. 결국, 당신이 이 도구들을 충분히 사용하면, 당신은 바라툰데 서스턴과 그와 같은 수백만 명의 사람들을 괴롭혔던 소진되고 초간섭적인 연결 상태에 도달할 것이다. 여기서 우리는 어떤 이득이 있는 마음가짐의 진정한 속박한 성격을 접하게 된다. 네트워크 도구를 사용하면 해로울 수 있습니다. 장단점을 따지려고 하지 않고 도구의 억제되지 않은 사용에 대한 정당화로 잠재적인 이점을 엿볼 수 있는 방법을 사용하는 경우 무의식적으로 지식 작업 세계에서 성공할 수 있는 능력을 마비시킨다.

이 결론은 객관적으로 고려된다면 놀라운 일이 아니다. 네트워크 도구의 맥락에서 우리는 어떤 이득이든 사고방식에 편해졌지만 대신 줌아웃하여 숙련 노동의 광범위한 맥락에서 이러한 사고방식을 고려한다면 갑자기 도구를 선택하는 기괴하고 역사적인 접근법으로 보인다. 다시 말해, 일단 당신이 인터넷 모든 것을 둘러싼 혁명적 수사학(1부에서 요약된 감각)을 제쳐버리면, 당신이 "혁명"에 완전히 헌신했거나 루다이트 커머드건이라는 감각을 갖게 될 것이다. 당신은 곧 네트워크 도구가 예외적이지 않다는 것을 깨닫게 될 것이다. 그들은 숙련된 노동자들이 그들의 일을 더 잘하기 위해(때때로 그들의 여가를 향상시키기 위해) 사용하는 대장공의 망치나 예술가 붓과 다를 바 없는 도구이다. 역사를 통해 숙련된 노동자들은 새로운 도구를 접하는 데 정교함과 회의감을 적용했으며 이를 채택할지 여부에 대한 결정을 내렸다. 지식 노동자들이 인터넷에 관해서도 같피상적 작업을 할 수 없는 이유는 없습니다. 여기서 숙련 노동이 이제 디지털 비트를 포함한다는 사실은 이러한 현실을 바꾸지 않습니다.

이 보다 세심한 도구 큐레이션이 어떻게 보일지 이해하는 데 도움이 되려면 (비디지털) 도구로 생계를 유지하며 성공하기 위해 이러한 도구와의 복잡한 관계에 의존하는 사람과 이야기하는 것이 합리적이다. 다행히도 우리의 목적을 위해 나는 (거의 적절하게) 포레스트 프리차드라는 이름의 성공적 지속 가능한 농부가 된 랭키한 영어 전공의 그러한 개인을 발견했다.

포레스트 프리차드는 블루리지 산맥의 계곡에 모여 있는 많은 농장 중 하나인 DC에서 한 시간 서쪽에 위치한 가족 농장인 스미스 메도즈를 운영한다. 내가 알게 된 바와 같이 프리차드는 부모로부터 토지를 장악한 직후 전통적인 단일 재배 작물에서 벗어나 잔디로 만든 고기의 당시 새로운 개념으로 운영을 옮겼다. 농장은 도매를 우회합니다. 워싱턴 DC, 메트로 지역의 번화한 농민 시장에서 소비자에게 직접 판매하기 위해 Whole Foods에서 Smith Meadows 스테이크를 찾을 수 없습니다. 모든 설명에 따르면 농장은 소규모 작업에 거의 보상을 주지 않는 산업에서 번창하고 있다.

스미스 메도스가 좋은 사업을 하는 메릴랜드주 타코마 파크에 있는 지역 농민 시장에서 프리차드를 처음 만났다. 평소에 대부분의 교외 고객들보다 한 발 더 큰 프리차르가 농부의 의무적인 퇴색된 플란넬을 입고 서 있는 것을 보는 것은 그의 무역에 자신 있는 장인을 보는 것이다. 농사는 도구의 세심한 관리에 의존하는 기술이기 때문에 그에게 자신을 소개했고 비디지털 분야의 장인이 이 중요한 작업에 어떻게 접근하는지 이해 하고 싶었다.

그는 주제에 대한 대화 중 한 번에 이르지 않아 나에게 "건초가 좋은 예"라고 말했다. "기저 경제학에 대해 반짝일 필요 없이 기본 아이디어를 줄 수 있는 과목"이다.

그는 "프리차드가 스미스 메도즈를 인수할 때 이 농장은 방목이 불가능한 겨울철에 동물 사료로 쓰기 위해 자체적으로 건초를 만들었다"고 설명했다. 건초를 압축하여 베일로 묶는 트랙터 뒤에 당기는 장치인 건초 베일러라는 장비로 건초를 만든다. 동해안에서 동물을 키우면 건초를 소유하고 운영해야 하는 명백한 이유가 있습니다. 자신의 토양에서 무료로 자라는 완벽한 좋은 풀이 있는 동안 사료를 "구입"하는 데 돈을 쓰는 이유는 무엇입니까? 따라서 농부가 지식 노동자가 사용하는 모든 혜택 접근법에 가입했다면 반드시 건초 방목기를 구입할 것이다. 그러나 프리차드가 나에게 설명한 것처럼(잠시간의 말이 있는 동안 선제적으로 사과한 후), 농부가 실제로 그러한 단순한 사고방식을 채택했다면 "매매용" 표지판이 부동산에 올라갈 때까지 며칠을 세는 것"이다. 그리고 이 공정을 건초 배양기에 적용한 후 프리차드는 그것을 빨리 팔았는데, 스미스 메도스는 이제 사용하는 건초를 모두 구입한다.

이게 왜.

프리차드는 "건초를 만드는 데 드는 비용을 탐구하는 것부터 시작하자"고 말했다. 첫째, 실제 연료비, 수리비, 발레를 보관할 창고 등이 있다. 세금도 내야 한다." 그러나 이러한 직접 측정 가능한 비용은 그의 결정에서 가장 쉬운 부분이었다. 오히려 더 많은 주의를 요하는 것은 '기회비용'이었다. 그는 "내가 여름 내내 건초를 만들면 다른 일을 할 수 없다. 예를 들어, 지금은 그 시간을 대신 보일러를 키우는 데 사용합니다. 판매할 수 있기 때문에 긍정적인 현금 흐름을 창출합니다. 그러나 그들은 또한 내가 토양을 개선하는 데 사용할 수 있는 분뇨를 생산한다." 그런 다음 구매한 건초 베일의 2차 가치를 평가하는 똑같이 미묘한 문제가 있다. 프리차드가 설명한 것처럼 "내가 건초를 살 때 나는 동물성 단백질과 분뇨(한 번 동물 시스템을 통과하면)를 현금으로 거래하고 있으며 이는 내 돈의 대가로 토지에 더 많은 영양분을 공급받는다는 것을 의미한다. 나는 또한 여름 내내 내 땅에서 중장비를 운전하여 토양을 압축하는 것을 피하고 있다."

발레에 대한 최종 결정을 내릴 때 프리차르는 본질적으로 세척이 되는 직접적인 금전적 비용을 넘어서 대신 자신의 분야의 장기적 건강에 대한 보다 미묘한 문제에 주의를 기울였다. 이전에 설명한 이유로 프리차드는 건초를 사면 더 건강한 밭이 된다고 결론지었다. 그리고 그가 요약한 것처럼, "토양 비옥도는 나의 기준선" 이 계산에 의해, 발레는 가야 했다.

프리차드의 도구 결정의 복잡성에 주목하라. 이러한 복잡성은 중요한 현실을 강조하는데, 어떤 이익을 식별하는 것이 도구에 돈, 시간 및 관심을 투자하기에 충분하다는 개념은 그의 거래에 참여하는 사람들에게 거의 웃기기 쉽다. 물론 건초 방목기는 이점을 제공하며 농장 공급 상점의 모든 도구에는 유용한 것이 있다. 동시에 물론 부정적인 측면도 있습니다. 프리차드는 이 결정이 미묘할 것으로 예상했다. 그는 토양 건강이 그의 직업적 성공에 근본적으로 중요하다는 명확한 기준선으로 시작했고 특정 도구를 사용할지 여부에 대한 최종 결정을 향해 이 토대를 구축했다.

나는 당신이 지식 노동자, 특히 딥 워크 습관을 함양하는 데 관심이 있는 사람이라면 농부와 같은 다른 숙련된 노동자와 같은 수준의 주의를 기울여 도구 선택을 처리해야 한다고 제안한다. 다음은 이 평가 전략을 일반화하려는 시도이다. 나는 공구 선택에 대한 장인의 접근법이라고 부르는데, 공구는 궁극적으로 자신의 공예의 더 큰 목표에 도움이 된다는 것을 강조하는 이름이다.

공구선택에 대한 장인의 접근법: 직업적, 개인적 삶의 성공과 행복을 결정하는 핵심요인을 파악한다. 이러한 요인에 대한 긍정적인 영향이 부정적인 영향보다 훨씬 더 큰 경우에만 도구를 채택한다.

도구 선택에 대한 이러한 장인의 접근 방식은 이익이 있는 접근 방식과 대립한다는 점에 주목하라. 어떤 이득이든 마인드셋은 도구를 사용하는 데 있어 어떤 잠재적 긍정적 영향도 정당화하기 위한 것으로 파악하는 반면, 장인 변형은 이러한 긍정적 영향이 자신에게 중요한 것의 핵심인 요소에 영향을 미치고 부정적인 것보다 더 크다는 것을 요구한다.

장인 접근법은 어떤 이점도 얻을 수 있는 접근법의 단순성을 거부하지만 현재 사람들을 네트워크 도구로 몰아넣는 이점을 무시하거나 "좋은" 또는 "나쁜" 기술에 대해 사전 선언을 하지 않는다.

이 규칙에서 따르는 세 가지 전략은 이익이 되는 사고방식을 버리고 시간과 관심을 요구하는 도구를 선별하는 데 더 사려 깊은 장인 철학을 적용하여 편안함을 높이기 위해 고안되었다. 장인의 접근 방식이 -앤-드라이가 아니기 때문에 이러한 안내는 중요하다. 삶에서 가장 중요한 것을 식별한 다음 이러한 요인에 대한 다양한 도구의 영향을 평가하려고 시도하는 것은 단순한 공식으로 축소되지 않으며 이 작업에는 연습과 실험이 필요하다. 다음의 전략들은 당신이 당신의 네트워크 도구를 여러 다른 각도들로부터 재고하도록 강요함으로써 이 연습과 실험을 위한 어떤 구조를 제공한다. 결합하면, 그들은 당신이 2부의 나머지 아이디어가 성공할 수 있도록 시간과 주의에 대한 충분한 통제권을 되찾을 수 있는 도구와 더 정교한 관계를 배양하는 데 도움이 될 것이다.

### 인터넷 습관에 "소수의 중요한 법칙"을 적용하라

말콤 글래드웰은 트위터를 사용하지 않는다. 2013년 인터뷰에서 그는 "팬들이 트위터에서 나에게 말을 듣고 싶어한다고 말하는 사람은 누구냐"고 이유를 설명한 다음 "많은 사람들이 나를 덜 보고 싶어할 것이라는 것을 알고 있다"라고 농담을 냈다. 또 다른 초대형 베스트셀러 작가인 마이클 루이스도 서비스를 사용하지 않고 있다. 와이어에서 "나는 트위터를 하지 않는다, 트위터를 하지 않는다, 나는 트위터 메시지를 읽는 방법이나 찾는 곳을 알려줄 수도 없다." 그리고 1부에서 언급했듯이 수상 경력에 빛나는 뉴욕 작가 조지 패커도 서비스를 기피하고 있으며 실제로 최근에

이 세 명의 작가는 트위터가 쓸모없다고 생각하지 않는다. 그들은 다른 작가들이 그것이 유용하다고 생각하는 것을 쉽게 받아들인다. 사실, 패커가 비트위터 사용을 인정한 것은 고 뉴욕타임스 미디어 평론가 데이비드 카르의 뻔뻔한 친트위터 기사에 대한 응답으로 작성되었으며 카르가 다음과 같이 말했다.

그리고 이제 거의 1년이 지난 지금, 트위터가 내 뇌를 버섯으로 바꾸었습니까? 아니, 나는 한 순간에 내가 가능하다고 생각했던 것보다 더 많은 부분에 대해 서술하고 있으며 조명을 찾아 30분 동안 서핑하는 대신, 나는 스타벅스에서 커피를 기다리는 데 걸리는 시간 동안 그날의 뉴스와 사람들이 그것에 어떻게 반응하는지 감지한다.

그러나 동시에 글래드웰, 루이스 및 패커는 서비스가 특정 상황에서 부정적인 점을 상쇄하기에 거의 충분한 이점을 제공한다고 생각하지 않는다. 예를 들어 루이스는 접근성을 더하면 그의 에너지가 고갈되고 훌륭한 이야기를 연구하고 쓰는 능력이 떨어질 것이라고 걱정했다. 제 인생에서 풍부하지 않은 소통이 많고 그것은 빈곤하다." 패커는 "미디어 중독자들에게 트위터는 균열"이라며 산만함을 걱정하는 반면, 그는 서비스에 대한 카의 열광을 "새로운 10년 동안 지금까지 읽은 가장 무서운 미래의 그림"이라고 묘사할 정도로 멀리 간다.

우리는 이 저자들이 트위터(및 유사한 도구)를 피하려는 개인적인 결정에 옳았는지에 대해 논쟁할 필요가 없으며 그들의 판매 수와 수상 경력이 스스로 말해 주기 때문이다. 우리는 대신 이러한 결정을 도구 선택에 대한 장인의 접근 방식을 행동에서 용기 있게 보여주는 사례로 사용할 수 있다. 많은 지식 종사자, 특히 창조 분야 종사자들이 여전히 이득 추구에 갇혀 있는 시대에 그러한 서비스를 통해 분류하는 데 더 성숙한 접근 방식을 보는 것은 상쾌하다. 그러나 이러한 예의 매우 드문 점은 이러한 유형의 성숙하고 자신 있는 평가가 쉽지 않다는 것을 상기시킨다. 포레스트 프리차드가 건초 밸러에 대한 결정을 내리기 위해 이 통과해야 했던 생각 과정의 복잡성을 상기하자: 많은 지식 작업자와 그들의 삶에서 많은 도구의 경우 이러한 결정은 똑같이 복잡할 것이다. 따라서 이 전략의 목표는 이 사고 과정에 어떤 구조를 제공하는 것인데, 어떤 도구가 당신에게 정말로 중요한지 결정하는 것의 복잡성을 줄이는 방법입니다.

이 전략의 첫 번째 단계는 직업적, 개인적 삶의 주요 고위 목표들을 식별하는 것이다. 예를 들어, 가족이 있는 경우 개인 목표는 양육을 잘하고 조직적인 가정을 운영하는 것입니다. 직업 영역에서 이러한 목표의 세부 사항은 생계를 위해 무엇을 하느냐에 달려 있다. 예를 들어, 교수로서의 자신의 업무에서 나는 두 가지 중요한 목표를 추구하는데, 하나는 교실에서 효과적인 교사이고 대학원생들에게 효과적인 멘토가 되는 것에 중점을 두고 있고 다른 하나는 효과적인 연구자가 되는 것에 중점을 두고 있다. 당신의 목표는 다를 수 있지만 핵심은 가장 중요한 것으로 목록을 제한하고 설명을 적절하게 높은 수준으로 유지하는 것이다. (만약 당신의 목표가 특정 목표인 매출 백만 달러에 도달하는 것 또는 한 해에 50여 편의 논문을 출판하는 것을 포함한다면, 그것은 우리의 목적에 너무 구체적이다.) 당신이 끝나면 당신은 삶의 개인적 영역과 직업적 영역 모두에 대해 적은 수의 목표를 가지고 있어야 한다.

이러한 목표를 확인한 후 목표를 충족하는 데 도움이 되는 가장 중요한 두세 가지 활동을 각각 나열한다. 이러한 활동은 수행하는 것을 명확하게 상상할 수 있을 만큼 구체적이어야 합니다. 반면에, 그것들은 한 번의 결과에 묶이지 않을 만큼 충분히 일반적이어야 한다. 예를 들어 '더 잘 연구한다'는 것은 너무 일반적이어서 ('더 잘 연구한다'는 것은 어떤 모습인가?, "향후 회의 제출에 맞춰 방송 하한선에 대한 논문을 마무리"하는 반면 너무 구체적이다(일회성 결과이다)., 반면에 '다가오는 학회 제출 마감에 맞춰 브로드캐스트 하한선 논문 마무리하기'는 너무 구체적인 일회성 목표입니다.) 이러한 맥락에서 좋피상적인 활동은 '제 분야의 최첨단 결과를 정기적으로 읽고 이해한다'와 같피상적인 일일 것이다.

이 전략의 다음 단계는 현재 사용하는 네트워크 도구를 고려하는 것입니다. 각각의 도구에 대해 식별한 주요 활동을 살펴보고 도구 사용이 활동의 규칙적이고 성공적인 참여에 실질적으로 긍정적인 영향, 실질적으로 부정적인 영향 또는 거의 영향을 미치지 않는지 질문한다. 이제 중요한 결정이 내려진다: 이 도구가 상당한 긍정적인 영향을 미치고 이것이 부정적인 영향보다 크다는 결론을 내린 경우에만 계속 이 도구를 사용하십시오.

이 전략을 실행에 옮기도록 돕기 위해 사례 연구를 고려해 보자. 이 예제의 목적을 위해, 마이클 루이스에게 질문한다면, 그의 글쓰기 경력을 위해 다음의 목표와 그에 상응하는 중요한 활동을 생산했을 것이라고 가정하자.

전문적 목표: 사람들이 세상을 이해하는 방식을 바꾸는 잘 쓰여진 서사 중심의 이야기를 만드는 것입니다.

이 목표를 지원하는 주요 활동:

* 인내심을 갖고 깊이 있게 연구한다.
* 목적의식을 가지고 신중하게 글을 쓴다.

이제 루이스가 이 목표를 사용하여 트위터 사용 여부를 결정했다고 상상해 보자. 우리의 전략은 그가 자신의 목표를 뒷받침하는 그가 나열한 주요 활동에 대한 트위터의 영향을 조사하도록 요구한다. 트위터가 루이스를 이 두 가지 활동 중 하나에서 실질적으로 더 잘 만들 것이라고 주장하는 설득력 있는 방법은 없다. 루이스에 대한 깊은 연구는 그가 소수의 출처를 아는 데 몇 주와 몇 달을 보내야 한다고 가정합니다(그는 많은 세션에 걸쳐 출처의 이야기를 끌어내는 긴 형태의 저널리즘 기술의 마스터입니다), 그리고 신중한 글쓰기는 물론 산만함에서 자유롭기를 요구합니다. 두 경우 모두 트위터는 기껏해야 실제 영향이 없으며 최악의 경우 서비스의 중독 속성에 대한 루이스의 민감도에 따라 상당히 부정적인 영향을 미칠 수 있다. 따라서 결론은 루이스가 트위터를 사용해서는 안 된다는 것이다.

당신은 지금 이 시점에서 우리의 예를 이 단일 목표에 국한시키는 것은 인위적이라고 주장할 수 있는데, 이는 트위터와 같은 서비스가 기여할 수 있는 가장 좋은 기회를 갖는 영역을 무시하기 때문이다. 특히 작가들에게 트위터는 궁극적으로 더 많은 판매로 이어지는 청중과의 연결을 구축하는 도구로 종종 제시됩니다. 그러나 마이클 루이스와 같은 작가에게 마케팅은 직업적 삶에서 중요한 것을 평가할 때 자신의 목표를 달성할 가치가 없다. 그의 평판이 책이 정말 좋다면 막대한 영향력을 가진 언론 채널에서 대대적인 취재를 받을 것이라고 보장하기 때문이다. 따라서 그의 초점은 비효율적인 저자 주도 수단을 통해 몇 가지 추가 판매를 압착하려는 것보다 가능한 최고의 책을 작성하려는 목표에 훨씬 더 생산적으로 적용된다. 즉, 문제는 트위터가 루이스에게 어떤 생각할 수 있는 이점을 가지고 있는지가 아니라, 트위터 사용이 그의 직업 생활에서 가장 중요한 활동에 유의미하고 긍정적인 영향을 미치는지 여부이다.

덜 유명한 작가는 어때? 이 경우 책 마케팅이 목표에 더 중요한 역할을 할 수 있습니다. 그러나 이 목표를 뒷받침하는 가장 중요한 두세 가지 활동을 식별하도록 강요당했을 때 트위터가 가능하게 하는 가벼운 일대일 접촉 유형이 목록에 포함될 가능성은 거의 없다. 이것은 간단한 수학의 결과이다. 우리의 가상의 작가가 일주일에 5일씩 하루에 10개의 개별화된 트윗을 부지런히 보내는데, 각각의 트윗은 새로운 잠재 독자와 일대일로 연결된다. 이제 이렇게 연락을 취한 사람들 중 50%가 작가의 다음 책을 꼭 살 충성스러운 팬이 된다고 상상해 보자. 이 책을 쓰기까지 걸리는 2년 동안 2,000개의 판매량을 얻었는데, 베스트셀러 지위가 일주일에 2~3배 더 많은 판매를 요구하는 시장에서 기껏해야 약간의 증가를 보였다. 다시 한 번 질문은 트위터가 어떤 혜택을 제공하는지 아닌, 대신 시간과 주의력에 대한 방해를 상쇄하기에 충분한 혜택을 제공하는지 여부(작가에게 특히 가치 있는 두 가지 자원)이다.

이러한 접근법이 전문적인 맥락에 적용되는 예를 본 다음으로 개인 목표의 잠재적으로 더 파괴적인 설정을 고려해 보자. 특히, 이 접근법을 우리 문화에서 가장 유비쿼터스하고 치열하게 방어되는 도구 중 하나인 페이스북에 적용하자.

페이스북(혹은 이와 유사한 소셜 네트워크)의 사용을 정당화할 때, 대부분의 사람들은 그들의 사회적 삶에 그 중요성을 언급한다. 이를 염두에 두고 페이스북이 개인 목표의 이 측면에 긍정적인 영향을 미치기 때문에 삭감을 하는지 파악하기 위해 전략을 적용해 보자. 이를 위해 우리는 다시 한 번 가상의 목표와 핵심 지원 활동을 통해 작업할 것이다.

개인 목표 나에게 중요한 한 집단의 사람들과 친밀하고 보람 있는 우정을 유지한다.

이 목표를 지원하는 주요 활동:

1. 내게 가장 중요한 사람들과 의미 있는 교감을 나누기 위해 정기적으로 시간을 보낸다 (예: 깊은 대화, 식사, 함께하는 활동).
2. 내게 가장 중요한 사람들을 위해 나 자신을 헌신한다 (예: 그들의 삶을 개선하기 위한 실질적인 희생과 지원).

모든 사람이 이 정확한 목표나 지원 활동을 공유하는 것은 아니지만 많은 사람들에게 적용되도록 규정하기를 바란다. 이제 한 걸음 물러서서 이 개인적 목표의 맥락에서 우리의 전략의 필터링 논리를 페이스북의 예에 적용해 보자. 물론 이 서비스는 여러분의 사회생활에 많은 혜택을 제공합니다. 자주 언급되는 몇 가지를 말씀드리자면, 한동안 보지 못했던 사람들을 따라잡을 수 있고, 아는 사람들과 가볍게 접촉할 수 있지만 정기적으로 마주치지 않을 수 있으며, 사람들의 삶에서 중요한 사건(결혼 여부 또는 새 아기가 어떻게 생겼는지)을 더 쉽게 모니터링할 수 있으며, 관심사에 맞는 온라인 커뮤니티나 그룹에 우연히 들 수 있습니다.

이는 페이스북이 부인할 수 없는 실제 혜택이지만 이러한 혜택 중 어느 것도 우리가 나열한 두 가지 주요 활동에 중요한 긍정적인 영향을 미치지 않으며 둘 다 오프라인 및 노력 집약적이다. 따라서 우리의 전략은 아마도 놀랍지만 분명한 결론을 반환할 것입니다. 물론 페이스북은 당신의 사회 생활에 이점을 제공하지만 이 분야에서 당신에게 정말로 중요한 것이 당신의 시간과 관심에 대한 액세스를 정당화할 만큼 충분히 중요한 것은 없습니다. \*

분명히 말해서, 저는 모든 사람이 페이스북 사용을 중단해야 한다고 주장하는 것이 아닙니다. 대신 이 특정(대표적) 사례 연구의 경우 여기에서 제안된 전략이 이 서비스를 중단하는 것을 제안한다는 것을 보여주고 있다. 그러나 나는 반대 결론으로 이어질 다른 그럴듯한 시나리오를 상상할 수 있다. 예를 들어, 대학 신입생을 생각해 보세요. 이런 상황에 처한 누군가에게는 기존의 관계를 지지하는 것보다 새로운 우정을 맺는 것이 더 중요할 수 있다. 따라서 이 학생이 번창하는 사회생활을 지향하는 활동을 식별하는 활동에는 "많은 행사에 참석하고 다양한 사람들과 사교하는 것"과 같피상적인 일이 포함될 수 있다.

또 다른 예를 들면 해외에 배치된 군대를 생각해 보자. 이 가상의 군인에게 고향에 돌아간 친구나 가족과 자주 가볍게 접촉하는 것은 그럴듯한 우선 순위이며 소셜 네트워크를 통해 다시 한 번 가장 잘 지원될 수 있는 것이다.

이러한 예에서 명확해야 할 것은 이 전략이 설명된 대로 적용되면 현재 Facebook 또는 Twitter와 같은 도구를 사용하는 많은 사람들이 이를 포기하도록 이끌지만 모든 사람이 그러하지는 않다는 것이다. 이 시점에서 당신은 그러한 도구에 대한 결정을 지배하기 위해 소수의 활동만 허용하는 자의성에 대해 불평할 수 있다. 예를 들어, 우리가 이전에 확립했듯이, 페이스북은 당신의 사회생활에 많은 이점을 가지고 있는데, 왜 우리가 가장 중요하다고 판단했던 적은 수의 활동에 도움이 되지 않는다고 해서 그것을 포기할까? 그러나 여기에서 이해하는 핵심은 이러한 급진적인 우선 순위 축소가 자의적이지 않고 대신 클라이언트 수익성에서 사회적 평등, 컴퓨터 프로그램의 충돌 방지에 이르기까지 다양한 분야에서 반복적으로 발생한 아이디어에 의해 동기가 부여된다는 것이다.

생명 소수의 법칙\* 많은 상황에서 주어진 효과의 80%는 가능한 원인의 20%에 불과하다.

예를 들어, 비즈니스 이익의 80%가 고객의 20%에서만, 국가의 자산의 80%가 가장 부유한 20%의 시민이 소유하고 있거나 컴퓨터 소프트웨어 충돌의 80%가 식별된 버그의 20%에서만 발생하는 경우일 수 있다. 이 현상을 뒷받침하는 공식적인 수학적 근거가 있지만(80/20 분할은 실제 세계에서 양을 측정할 때 자주 나타나는 분포 유형인 영향에 대한 힘 법칙 분포를 설명할 때 대략 예상되는 것임), 많은 경우에 결과에 대한 기여가 고르게 분포되지 않는다는 점을 상기시키는 것으로 휴리스틱하게 적용할 때 가장 유용할 것이다.

앞으로 이 법칙이 당신의 삶에서 중요한 목표에 적용된다고 가정해 보자. 언급했듯이 다양한 활동이 이러한 목표를 달성하는 데 기여할 수 있습니다. 그러나 중요한 소수의 법칙은 이러한 활동의 가장 중요한 20% 정도가 대부분의 혜택을 제공한다는 것을 상기시킨다. 아마도 당신은 당신의 삶의 목표 각각에 대해 10개에서 15개의 구별되고 잠재적으로 유익한 활동을 나열할 수 있다고 가정하면, 이 법칙은 당신이 목표를 달성했는지 여부에 가장 큰 차이를 만드는 것은 그러한 활동의 상위 2개 또는 3개, 즉 이 전략이 당신에게 초점을 맞추라고 요구하는 수라고 말한다.

그러나 이 결과를 받아들이더라도 가능한 유익한 활동의 나머지 80%를 무시해서는 안 된다고 주장할 수 있다. 덜 중요한 활동들이 상위 1~2명만큼 목표에 기여하지는 않는 것은 사실이지만 약간의 이점을 제공할 수 있으므로, 그것들을 혼합하여 유지하는 것은 어떨까? 더 중요한 활동을 무시하지 않는 한 덜 중요한 대안도 지원하는 것은 나쁘지 않을 것 같다.

그러나 이 주장은 중요성에 관계없이 모든 활동이 동일한 제한된 시간과 주의를 소비한다는 핵심 사항을 놓친다. 따라서 저영향 활동에 서비스를 제공한다면 더 높은 영향 활동에 사용할 수 있는 시간을 빼앗고 있다. 제로섬 게임입니다. 그리고 시간이 낮은 영향 활동에 투자했을 때보다 높은 영향 활동에 투자했을 때 훨씬 더 많은 보상을 받기 때문에 후자로 전환할수록 전반적인 이익이 감소한다.

비즈니스 세계는 이 수학을 이해합니다. 이것이 회사가 비생산적인 고객을 해고하는 것을 흔히 볼 수 있는 이유이다. 이익의 80%가 고객의 20%에서 나온다면 수익이 낮은 고객의 에너지를 소수의 수익성 있는 계약에 더 나은 서비스를 제공하기 위해 재지정함으로써 더 많은 돈을 벌게 되는데, 후자에 지출한 시간당 전자에 지출한 시간보다 더 많은 수익을 얻는다. 귀하의 직업적, 개인적 목표에도 마찬가지입니다. 페이스북에서 오래된 친구를 찾는 것과 같은 저영향 활동에 소비되는 시간을 사용하고 좋은 친구를 점심에 데려가는 것과 같은 고영향 활동에 재투자함으로써 목표를 달성하는 데 더 성공한다. 따라서 이 논리를 사용하여 네트워크 도구를 포기하는 것은 잠재적인 작은 이점을 놓치는 것이 아니라 이미 알고 있는 활동에서 더 많이 얻어 큰 이점을 얻는 것이다.

우리가 시작한 곳으로 돌아가서 말콤 글래드웰, 마이클 루이스, 조지 패커에게 트위터는 그들의 글쓰기 경력에서 성공의 대부분을 창출하는 활동의 20%를 지원하지 않는다. 이 서비스가 별도로 약간의 혜택을 줄 수 있지만 그들의 경력을 전체적으로 볼 때, 그들이 관리해야 할 한 가지 더 많은 부분으로 일정에 추가하는 것보다 트위터를 사용하지 않고 그 시간을 더 알찬 활동으로 재지정하는 것이 더 성공적일 가능성이 높다. 당신은 자신의 제한된 시간과 관심을 청구할 수 있는 도구를 결정할 때 이 같은 주의를 기울여야 한다.

### 소셜 미디어 금식 실험

라이언 니코데모스가 자신의 삶을 단순화하기로 결정했을 때, 그의 첫 번째 목표 중 하나는 그의 소유물이었다. 당시 라이언은 침실 3개짜리 넓은 콘도에 혼자 살았다. 수년간 소비주의 충동에 이끌려 이 넉넉한 공간을 채우기 위해 최선을 다해 왔다. 이제 그의 물건에서 그의 생명을 되찾을 때였습니다. 그가 전개한 전략은 설명하기 간단했지만 개념상 급진적이었다. 그는 이사하려는 듯 자신이 소유한 모든 것을 판지 상자에 포장하는 데 오후를 보냈다. 그가 '어려운 사업'이라고 표현한 것을 덜 부담스러운 것으로 변화시키기 위해 '포장 파티'라고 부르며 "모든 것은 파티일 때 더 흥미진진한 것 아니냐"고 설명했다.

포장 작업이 끝나면 니코데모스는 다음 주 동안 정상적인 일상을 거쳤다. 포장된 것이 필요하면, 그는 그것을 풀고 예전의 곳에 다시 두곤 했다. 그는 주말에 자신의 물건의 대다수가 상자에 그대로 남아 있다는 것을 알아차렸다.

그래서 거야.

물건은 사람들의 삶에 축적되는데, 이는 부분적으로 특정 제거 행위에 직면했을 때 '언젠가 이것이 필요하면?'라고 걱정하기 쉽고 그런 다음 이 걱정을 핑계로 사용하여 문제의 물건을 계속 둘러앉게 하기 때문이다. 니코데모스의 짐을 싣는 일행은 그의 물건 대부분이 그가 필요로 하는 것이 아니라는 확실한 증거를 그에게 제공했고 따라서 단순화하려는 그의 탐구를 뒷받침했다.

마지막 전략은 현재 시간과 관심을 요구하는 네트워크 도구를 통해 분류를 시작하는 데 도움이 되는 체계적인 방법을 제공했다. 이 전략은 이러한 동일한 문제에 대해 다르지만 보완적인 접근법을 제공하며 Ryan Nicodemus의 쓸모없는 물건을 제거하는 접근법에서 영감을 얻었다.

보다 구체적으로, 이 전략은 현재 사용하는 소셜 미디어 서비스에 대해 포장 파티의 등가물을 수행하도록 요청한다. 30일 동안 해당 도구의 사용을 완전히 중단해보는 것이다. 페이스북, 인스타그램, 구글+, 트위터, 스냅, 와인 등 모든 서비스가 내가 처음 이 단어를 쓴 이후로 인기를 얻었다. 이러한 서비스를 공식적으로 비활성화하지 말고 온라인에서 서명할 것이라고 언급하지 마십시오. 콜드 칠면조, 사용을 중단하십시오. 누군가가 다른 방법으로 당신에게 연락하여 특정 서비스에 대한 활동이 중단된 이유를 묻는다면 설명할 수 있지만 사람들에게 말할 수 있는 길을 벗어나지 마십시오.

이러한 자기부과적 네트워크 격리 후 30일 후, 일시적으로 중단한 각 서비스에 대해 다음과 같은 두 가지 질문을 스스로에게 한다.

1. 지난 30일 동안 이 서비스를 이용할 수 있었다면 내 삶이 눈에 띄게 더 나아졌을까?
2. 내가 이 서비스를 쓰지 않는다는 사실을 다른 사람들이 신경이나 썼을까?

두 질문에 모두 '아니오'라고 답하면 서비스를 영구적으로 중단하십시오. 명확한 "예"가 있는 경우 서비스 사용으로 돌아가십시오. 귀하의 답변이 적합하거나 모호한 경우 서비스에 복귀할지 여부는 귀하의 몫이지만 저는 당신이 그만두는 것을 권장합니다. (나중에 언제든지 재가입 가능합니다.)

이 전략은 특히 소셜 미디어에서 선택되는데, 왜냐하면 당신의 시간과 관심을 요구할 수 있는 다양한 네트워크 도구들 중에서, 이러한 서비스들이 제한 없이 사용될 경우, 더 깊이 작업하려는 당신의 노력에 특히 파괴적일 수 있기 때문이다. 그들은 예측할 수 없는 간헐적인 일정에 도착하는 개인화된 정보를 제공하여 엄청난 중독성을 갖게 하고 따라서 집중의 어떤 행위로도 일정을 잡으려는 시도와 성공에 심각한 손상을 줄 수 있다. 이러한 위험을 감안할 때 더 많은 지식 노동자들이 이러한 도구를 완전히 피할 것으로 예상할 수 있습니다. 특히 컴퓨터 프로그래머나 작가와 같은 사람들은 생계가 딥 워크의 결과에 명시적으로 의존합니다. 그러나 소셜 미디어를 속임수로 만드는 부분 중 일부는 귀하의 관심을 받는 회사가 마스터블 마케팅 쿠데타로 성공했다는 것입니다. 즉 제품을 사용하지 않으면 놓칠 수 있다는 우리 문화를 설득합니다.

당신이 놓칠 수 있다는 이 두려움은 니코데모스가 옷장에 있는 방대한 물건이 언젠가 유용할 수 있다는 두려움과 명백한 유사성을 가지고 있는데, 이것이 내가 그의 짐을 싣는 일행과 평행한 교정 전략을 제안하는 이유이다. 이러한 서비스 없이 한 달을 보내면 이벤트, 대화, 공유된 문화 경험에서 놓칠 수 있다는 두려움을 현실의 양으로 대체할 수 있다. 대부분의 사람들에게 이 현실은 당신이 이러한 도구를 둘러싼 마케팅 메시지에서 자신을 해방시키는 힘든 일을 한 후에야 명백해 보이는 무언가를 확인합니다. 그것들은 당신의 삶에서 정말 중요하지 않습니다.

내가 30일간의 실험을 발표하지 말라고 요청하는 이유는 어떤 사람들에게는 소셜 미디어에 자신을 묶는 망상의 또 다른 부분이 사람들이 당신이 말한 것을 듣고 싶어한다는 생각이고 당신이 갑자기 당신의 논평을 놓치면 실망할 수 있다는 생각이기 때문이다. 나는 여기서 내 말에서 다소 까다롭지만 그럼에도 불구하고 이러한 기본 정서는 일반적이고 다루어야 할 중요성이 있다. 본 기재 시점, 예를 들어, 트위터 사용자에 대한 평균 팔로워 수는 208명이다. 당신이 말하려는 것을 듣기 위해 200명 이상의 사람들이 자원했다는 것을 알면, 이러한 서비스에 대한 당신의 활동이 중요하다고 믿기 쉬워진다. 내 아이디어를 사람들에게 팔려고 생계를 유지하는 사람으로서의 경험에서 말하는 것: 이것은 강력하게 중독성 있는 느낌이다!

하지만 소셜 미디어 시대의 관객의 현실은 여기에 있다. 이러한 서비스가 존재하기 전에는 가까운 친구나 가족을 넘어 모든 규모의 청중을 구축하려면 열심히 경쟁해야 했습니다. 예를 들어, 2000년대 초반에는 누구나 블로그를 시작할 수 있었지만 한 달에 소수의 고유 방문자만 얻으려면 누군가의 관심을 끌 만큼 가치가 있는 정보를 전달하기 위해 실제로 작업을 해야 했다. 이 난이도는 잘 알고 있습니다. 제 첫 블로그는 2003년 가을에 시작되었습니다. 그것은 충분히 영리하게 영감을 주는 모니커라고 불렸다. 저는 그것을 사용하여 21살의 대학생으로서의 제 삶에 대해 고민했습니다. 부끄럽게 인정하지만 아무도 그것을 읽지 않는 긴 뻗음이 있었다(문자 그대로 사용하고 있는 용어). 그 후 10년 동안 알게 된 바와 같이, 현재 블로그인 스터디 의 독자 수를 한 달에 소수의 독자에서 수십만 명으로 인내심과 수고로 구축한 기간은 온라인에서 사람들의 관심을 얻는 것이 힘들고 힘든 작업이라는 것이다.

지금은 그렇지 않습니다.

소셜 미디어의 빠른 동의를 촉진한 부분 중 하나는 실제 가치를 생산하는 힘든 작업과 사람들이 당신에게 관심을 기울이는 긍정적인 보상 사이의 이러한 연결을 단락시키는 능력이라고 주장한다. 대신 이 시대를 초월한 자본주의적 교환을 은 집단주의적 대안으로 대체했다: 나는 내가 말하는 것에 주의를 기울이면 나는 그것의 가치와 상관없이 네가 말하는 것에 주의를 기울일 것이다. 예를 들어, 일반적으로 페이스북 벽이나 트위터 피드를 채우는 콘텐츠를 포함하는 블로그 또는 잡지 또는 텔레비전 프로그램은 평균적으로 청중을 유치하지 않는다. 그러나 이러한 서비스의 사회적 관례 내에서 포착될 때 동일한 콘텐츠는 좋아요와 댓글의 형태로 관심을 끌 것입니다. 이러한 행동을 동기를 부여하는 암묵적인 합의는 친구와 팔로워로부터 (대부분, 마땅치 않은) 관심을 받는 대가로, 당신은 그들에게 (유사하게 마땅치 않은) 관심을 쏟음으로써 호의를 갚을 것이라는 것이다. 당신은 나의 상태 업데이트를 '좋아요'하고 나는 당신의 상태를 '좋아요'할 것이다. 이 협정은 많은 노력이 필요 없이 모두에게 중요한 시뮬라크럼을 제공합니다.

이러한 서비스를 예고 없이 중단하면 콘텐츠 제작자로서의 지위의 현실을 테스트할 수 있습니다. 대부분의 사람들과 대부분의 서비스에 대해 이 소식은 정신을 차릴 수 있습니다. 가장 가까운 친구나 가족 외부의 아무도 당신이 사인 다운을 알아차리지 못할 것입니다. 나는 이 문제에 대해 말할 때 내가 삐걱거리는 것처럼 느껴진다는 것을 인식하지만 자기 중요성에 대한 이 추구는 사람들이 계속해서 그들의 시간과 관심을 무심코 분절하도록 설득하는 데 중요한 역할을 하기 때문에 토론하는 것이 중요하다.

물론 일부 사람들에게는 이 30일간의 실험이 어렵고 많은 문제를 일으킬 것이다. 예를 들어 대학생이나 온라인 인성이라면 기권 행위는 삶을 복잡하게 만들며 주목할 것이다. 하지만 대부분의 사람들에게, 이 실험의 순 결과는 인터넷 습관에 대한 대대적인 정비가 아니라면, 소셜 미디어가 일상 생활에서 어떤 역할을 하는지 보다 근거 있는 관점이 될 것이라고 생각합니다. 이러한 서비스는 광고된 것처럼 반드시 현대 연결 세계의 생명체가 되는 것은 아니다. 그것들은 단지 민간 회사에서 개발하고, 넉넉하게 자금을 지원하고, 신중하게 마케팅하며, 궁극적으로 당신의 개인 정보와 광고주에게 관심을 포착하고 판매하도록 설계된 제품일 뿐이다. 그것들은 재미있을 수 있지만, 당신의 삶의 계획과 당신이 성취하고자 하는 것에서, 그것들은 가벼운 변덕이며, 더 깊은 몰입의 영역에서 당신을 탈선시킬 것을 위협하는 많은 부분들 중 하나의 중요하지 않은 산만함이다. 또는 소셜 미디어 도구가 당신의 존재의 핵심일 수도 있습니다. 당신은 그것들 없는 삶을 샘플링하기 전까지는 어느 쪽이든 알 수 없을 것이다.

### 오락거리로 인터넷을 소비하지 마라

아놀드 베넷은 20세기 전환기에 태어난 영국 작가로, 그의 모국의 경제가 격동하던 시기였다. 이 시점까지 수십 년 동안 웅성거렸던 산업혁명은 새로운 계층, 즉 화이트칼라 노동자를 생성하기에 충분한 잉여 자본을 제국의 자원에서 아냈다. 이제 사무실에서 주당 정해진 시간을 보내고 그 대가로 가정을 부양하기에 충분한 꾸준한 급여를 받는 직업을 가질 수 있었다. 그러한 생활 방식은 우리 시대에 완만한 익숙한 것이지만 베넷과 그의 동시대 사람들에게는 참신하고 여러 면에서 고통스러웠다. 베넷의 주요 관심사는 이 새로운 계층의 구성원들이 완전한 삶을 살 수 있는 기회를 놓치고 있다는 것이었다.

"사무시간이 10시에서 6시까지이고 집 문과 사무실 문을 오가는 데 아침과 밤으로 50분을 보내는 사무실에서 일하는 런던인의 경우를 생각해 보자" 베넷은 1910년 자조 고전인 24시간 어떻게 살아야 하는지에서 쓴다. 그는 이 가상의 런던 월급인은 이러한 업무 관련 시간을 넘어 하루에도 16시간이 조금 더 남았다고 지적한다. 베넷에게 이것은 많은 시간이지만 비극적으로 이 상황에 처한 대부분의 사람들은 그것의 잠재력을 깨닫지 못한다. 그는 "평범한 사람이 하루와 관련하여 저지르는 크고 심오한 실수"는 자신의 일을 특별히 즐기지 않더라도 "10시간에서 6시간까지의 시간을 "일일"로 간주하는 데 집착한다. 그로부터 앞선 10시간과 그 다음의 6시간은 프롤로그와 에필로그에 불과하다." 이것은 베넷이 "절대적으로 비논리적이고 건강에 해롭다"고 비난하는 태도이다.

이러한 상황의 대안은 무엇인가? 베넷은 그의 전형적인 사람이 16시간의 자유시간을 "하루 내의 하루"로 보라고 제안하며 "그 16시간 동안 그는 자유롭다; 그는 임금벌이자가 아니다; 그는 금전적 걱정에 몰두하지 않는다; 그는 사적 수입을 가진 사람만큼 좋다." 따라서 전형적인 사람은 대신 이 시간을 귀족이 할 때, 즉 엄격한 자기개선을 수행하는 데 사용해야 한다. 베넷에 따르면, 주로 훌륭한 문학과 시를 읽는 것을 포함하는 작업이다.

베넷은 1세기 이상 전에 이런 문제에 대해 썼다. 전 세계적으로 중산층이 폭발적으로 성장한 시기인 그 사이에 여가에 대한 우리의 사고가 진화했을 것이라고 예상할 수 있다. 하지만 그렇지 않습니다. 인터넷의 부상과 그것이 뒷받침하는 저 눈금 주의력 경제로 인해 평균 주당 40시간 직원, 특히 기술에 정통한 밀레니얼 세대의 직원은 주로 최소 공통 지표 디지털 엔터테인먼트에 대한 산만한 클릭의 흐릿함으로 구성된 여가 시간의 품질이 여전히 저하된 것으로 나타났다. 만약 베넷이 오늘 다시 살아났다면, 그는 인간 발전의 이 영역에서 진전이 없다는 것에 절망에 빠질 가능성이 높다.

분명히 말해서, 나는 베넷의 제안 뒤에 숨겨진 도덕적 기초에 무관심하다. 시와 위대한 책을 읽으며 중산층의 영혼과 마음을 고양시키는 그의 비전은 다소 구식적이고 계급주의적으로 느껴진다. 그러나 당신이 모두 업무 외 시간을 의도적으로 사용해야 하고 사용할 수 있다는 그의 제안의 논리적 토대는 특히 이 규칙의 목표와 관련하여 오늘날에도 여전히 관련이 있다.

더 자세히 설명하자면 이 규칙에서 지금까지 논의된 전략에서 우리는 깊이 싸움과 특히 관련이 있는 네트워크 도구의 한 종류에 대해 아직 많은 시간을 할애하지 않았습니다. 이 글을 쓸 당시, 그러한 사이트의 가장 인기 있는 예로는 허핑턴 포스트, 버즈피드, 비즈니스 인사이더 및 레딧이 있다. 이 목록은 의심할 여지 없이 계속 진화할 것이지만 이 일반적인 사이트 범주가 공유하는 것은 주의 깊게 제작된 제목과 쉽게 소화할 수 있는 콘텐츠를 사용하는 것이며 종종 알고리즘에 의해 연마되어 최대한 관심을 끌 수 있다.

일단 당신이 이 사이트들 중 한 사이트에서 한 기사에 도착하면, 페이지의 측면이나 하단의 링크는 당신에게 다른 기사를 클릭하도록 하고 다른 기사를 클릭하도록 유도한다. 제목을 "인기" 또는 "트렌드"로 나열하는 것부터 사진을 체포하는 사용까지 인간 심리학의 모든 가능한 트릭이 당신을 몰입시키는 데 사용된다. 예를 들어, 이 특정 순간에 버즈피드에서 가장 인기 있는 기사에는 "뒤로 맞물릴 때 완전히 다른 것을 의미하는 17개의 단어"와 "모든 것에서 승리하는 33개의 개"가 있다.

이러한 사이트는 일정이 끝나면 특히 유해하며 일정의 자유로움이 여가 시간의 중심이 될 수 있습니다. 줄을 서서 기다리거나, TV 쇼에서 줄거리가 시작되기를 기다리거나, 식사를 끝내기를 기다리는 경우, 지루할 가능성을 제거할 수 있는 인지 목발을 제공합니다. 그러나 Rule # 2에서 주장했듯이 그러한 행동은 주의 산만함에 저항하는 마음의 일반적인 능력을 약화시켜 나중에 집중하고 싶을 때 심층 작업을 어렵게 만들기 때문에 위험하다. 설상가상으로, 이러한 네트워크 도구는 당신이 가입하는 것이 아니며 따라서 (이전 두 가지 전략을 무관하게 만드는 것) 그만두어 삶에서 제거할 수 있는 것이 아니다. 클릭 한 번만 하면 언제든지 사용할 수 있습니다.

다행히도 아놀드 베넷은 백 년 전에 이 문제의 해법을 찾아냈는데, 여가 시간에 더 많은 생각을 한다. 즉, 이 전략은 휴식에 관한 한, 순간적으로 주의를 끄는 모든 것에 기복하지 말고 대신 "하루 안에 하루를 어떻게 보내고 싶은지에 대한 질문에 약간의 사전 생각을 할애하는 것을 시사한다." 앞서 언급한 유형의 중독 웹사이트는 진공에서 번창한다. 주어진 순간에 스스로 할 일을 주지 않았다면 항상 매력적인 옵션으로 손짓을 할 것이다. 대신 이 여가 시간을 더 좋피상적인 일으로 채우면 주의력을 느슨하게 할 것입니다.

따라서 저녁과 주말이 시작되기 전에 무엇을 할 것인지 미리 결정하는 것이 중요합니다. 구조화된 취미는 시간을 채우기 위한 특정 목표를 가진 특정 행동을 생성하기 때문에 이러한 시간에 좋은 먹이를 제공한다. 의도적으로 선택한 일련의 책을 진행하면서 매일 밤 규칙적인 시간을 보내는 책 읽기 프로그램인 아 라 베넷도 물론 운동이나 좋은 (인면)회사의 즐거움과 마찬가지로 좋은 선택이다.

예를 들어, 제 삶에서는 교수, 작가, 아버지로서의 시간에 대한 요구 사항(평균적으로 한 번에 3~5권씩 읽는다)을 고려할 때, 나는 보통 한 해에 놀라운 수의 책을 읽을 수 있다. 이는 아이들이 취침한 후 미리 계획된 여가 활동 중 가장 좋아하는 것이 흥미로운 책을 읽는 것이기 때문에 가능한 일이다. 결과적으로, 제 스마트폰과 컴퓨터, 그리고 그들이 제공할 수 있는 주의 분산피상적 작업반적으로 작업 일정이 끝날 때와 다음날 아침 사이에 무시됩니다.

이 시점에서 당신은 당신의 휴식에 그러한 구조를 추가하는 것이 많은 사람들이 계획이나 의무로부터 완전한 자유를 요구하는 휴식의 목적을 무산시킬 것이라고 걱정할 수 있다. 구조화된 저녁은 직장에서 다음날 당신을 피곤하게 만들지 않을까요? 베넷은 그의 공신력으로 이 불만을 예상했다. 그의 주장대로, 그러한 걱정은 인간 정신에 활력을 주는 것을 오해한다.

뭐야? 그 16시간에 주어진 모든 에너지가 비즈니스 8의 가치를 감소시킨다는 말씀이신가요? 그렇지 않아요. 오히려 8사업의 가치를 높일 수 있을 것이다. 나의 전형적인 남자가 배워야 할 주요한 것 중 하나는 정신적인 특성이 지속적인 힘든 활동이 가능하다는 것이다. 그들은 팔이나 다리처럼 피곤하지 않다. 그들이 원하는 것은 잠만 있으면 되는 것 외에는 휴식이 아닌 변화뿐이다.

제 경험상, 이 분석은 바로 그 점입니다. 당신이 정신을 깨는 모든 시간 동안 의미 있는 일을 하게 된다면, 반의식적이고 비구조화된 웹 서핑에서 정신을 몇 시간 동안 목욕하게 하는 것보다 더 만족스럽게 하루를 마무리하고 다음 하루를 더 편안하게 시작할 것이다.

요약하자면, 시간과 주의력에 대한 엔터테인먼트 사이트의 중독성 있는 끌림을 없애려면 뇌에 양질의 대안을 제공해야 합니다. 이것은 산만함과 집중력에 저항하는 능력을 보존할 뿐만 아니라, 아마도 처음으로, 단지 존재하는 것이 아니라 사는 것이 무엇을 의미하는지 경험하는 아놀드 베넷의 야심찬 목표를 달성할 수도 있다.

## 규칙 4. 피상적 작업을 줄여라 (Drain the Shallows)

2007년 여름 소프트웨어 회사 37signals(현재 Basecamp)는 주 5일에서 4일로 근무를 단축하는 실험을 시작했다. 직원들은 하루가 줄어든다고 해서 같은 양의 일을 하는 것 같아서 매년 5월부터 10월까지 37명의 시그널 직원이 월요일부터 목요일까지만 근무한다(여전히 일주일 내내 운영되는 고객지원을 제외한다). 회사 공동 설립자인 제이슨 프리드가 블로그 게시물에 '사람들은 여름에 날씨를 즐겨야 한다'는 결정을 농담으로 남겼다.

재계 언론에 잔소리가 나오기까지는 그리 오래 걸리지 않았다. 프리드가 4일 근무 주간을 영구적으로 결정했다고 발표한 지 몇 달 후, 기자인 타라 와이스는 포브스에 "주 4일 근무 주간이 작동하지 않는 이유"라는 제목의 비판적인 글을 썼다. 그녀는 이 전략에 대한 자신의 문제를 다음과 같이 요약했다.

40시간을 4일로 포장하는 것이 반드시 효율적인 작업 방법은 아니다. 많은 사람들은 8시간이 충분히 힘들다고 생각하며 2시간 더 머물게 하면 사기와 생산성이 떨어질 수 있다.

프라이드는 반응이 빨랐어요. 그는 "포브스는 주 4일 근무의 요점을 놓치고 있다"는 제목의 블로그 게시물에서 직원들이 40시간의 노력을 4일로 쌓는 것은 스트레스가 많을 것이라는 와이스의 전제에 동의하는 것으로 시작한다. 그러나 그가 분명히 밝힌 것처럼, 그것이 그가 제안하는 것이 아니다. "주 4일 근무의 요점피상적 작업을 적게 하는 것"이라고 쓴다. "10시간의 하루가 4일 정도가 아니라... 8시간의 정상적인 하루가 4일 정도"이다.

처음에는 혼란스러워 보일 수 있습니다. 앞서 프리드는 직원들이 5일 만에 하는 만큼 4일 만에 하는 일을 한다고 주장했다. 그러나 지금은 직원들이 더 적은 시간을 일하고 있다고 주장하고 있다. 어떻게 둘 다 사실일 수 있죠? 그 차이는 피상적 작업의 역할에 관한 것으로 밝혀졌다. 프라이드가 팽창하면서.

하루에 8시간이라도 일하는 사람은 극소수입니다. 당신은 평범한 일과정에 스며드는 모든 회의, 방해, 웹서핑, 사무실 정치, 개인 업무 사이에 몇 시간씩 좋은 시간을 얻으면 운이 좋다.

공식 근무 시간이 줄어들면 일반적인 근무 주간의 지방을 짜내는 데 도움이 됩니다. 모든 사람이 일을 할 시간이 줄어들면 그 시간을 더욱 존중합니다. 사람들은 자신의 시간에 인색해 지고 그것이 좋피상적 작업이다. 그들은 중요하지 않피상적 작업에 낭비하지 않는다. 시간이 적을 때 당신은 보통 시간을 더 현명하게 보낸다.

즉 37신호 주간 근무량의 감소는 심층 업무에 비해 피상적인 일을 불균형적으로 제거하였고 후자는 크게 그대로 두었기 때문에 중요한 업무는 계속 이루어졌다. 순간적으로 너무 급해 보일 수 있는 피상적인 일들이 의외로 필요 없는 것으로 드러났다.

이 실험에 대한 자연스러운 반응은 37개의 신호가 한 걸음 더 나아갔다면 어떻게 될지 궁금해 하는 것이다. 피상적 작업의 시간을 제거하는 것이 생성된 결과에 거의 영향을 미치지 않았다면, 피상적 작업을 제거했을 뿐만 아니라 새로 회수된 시간을 더 딥 워크으로 대체하면 어떻게 될까요? 다행히도 호기심에 따라 회사는 곧 이 더 과감한 아이디어를 테스트했습니다.

프리드는 직원들이 자기 주도적인 프로젝트에서 20%의 시간을 할애하는 구글과 같은 기술 기업의 정책에 항상 관심을 가져왔다. 그는 이 아이디어를 좋아했지만 바쁜 한 주 중 하루를 조각하는 것은 진정한 돌파구를 생성하는 끊이지 않는 딥 워크을 지원하기에 충분하지 않다고 느꼈다. 그는 "5주 동안 5일 동안 연속 5일을 걸 것"이라고 설명했다. "그래서 우리의 이론은 사람들이 중단되지 않은 긴 시간을 가질 때 더 나은 결과를 볼 것이라는 것이다."

이 이론을 테스트하기 위해 37개의 신호는 급진적인 것을 구현했습니다. 회사는 직원들에게 6월 한 달 내내 자신의 프로젝트에 깊이 있도록 쉬도록 했습니다. 이 달피상적인 상태 회의, 메모, 다행히 파워포인트 없이 은 업무 의무가 없는 기간이 될 것입니다. 이달 말에는 직원들이 작업해 온 아이디어를 피칭하는 '피치데이'를 열었다. Inc. 잡지 기사에서 실험을 요약하면서 Fried는 성공을 했다고 말했다. 피치데이에는 고객 지원을 처리하기 위한 더 나은 도구 제품군과 고객이 제품을 사용하는 방식을 회사가 이해할 수 있도록 돕는 데이터 시각화 시스템이라는 두 가지 프로젝트가 곧 생산에 투입되었다. 이러한 사업들은 기업에 상당한 가치를 가져다 줄 것으로 예측되지만 직원들에게 제공되는 방해받지 않는 심층 작업 시간이 없었다면 거의 확실히 생산되지 않았을 것이다. 그들의 잠재력을 끌어내기 위해서는 수십 시간의 방해받지 않는 노력이 필요했다.

"어떻게 우리는 새로운 아이디어로 '잘못'하기 위해 한 달 동안 사업을 보류할 여유가 있습니까?" 프리드는 수사적으로 물었다. "어떻게 우리가 그렇지 않을 수 있습니까?"

37시그널의 실험은 중요한 현실을 강조하는데, 지식 노동자들의 시간과 주의를 점점 더 지배하는 피상적 작업은 종종 순간적으로 보이는 것보다 덜 중요하다. 대부분의 기업에서 이러한 은 부분을 상당 부분 제거하면 수익률은 영향을 받지 않을 것입니다. 그리고 제이슨 프리드가 발견했듯이, 피상적 작업을 없애는 것뿐만 아니라 이 회복된 시간을 더 많은 딥 워크인 대안으로 대체한다면, 사업은 계속 기능할 뿐만 아니라 더 성공적일 수 있습니다.

이 규칙은 이러한 통찰력을 개인 직장 생활에 적용하도록 요청합니다. 다음의 전략은 당신이 현재의 일정의 은 부분을 무자비하게 식별한 다음 최소 수준으로 줄여 궁극적으로 가장 중요한 깊은 노력을 할 수 있는 더 많은 시간을 남길 수 있도록 설계되었다.

그러나 이러한 전략의 세부 사항에 들어가기 전에 먼저 이러한 은 사고에 한계가 있다는 현실에 직면해야 한다. 심층 작업의 가치는 피상적인 일의 가치보다 훨씬 더 크지만 그렇다고 해서 모든 시간을 심층적으로 투자하는 일정을 퀴소틱하게 추구해야 하는 것은 아니다. 첫째, 대부분의 지식 업무 일자리를 유지하기 위해서는 비보살적인 양의 은 업무가 필요하다. 당신은 10분마다 이메일을 확인하는 것을 피할 수 있지만 중요한 메시지에 응답하지 않으면 오래 지속되지 않을 것이다. 이런 의미에서 우리는 이 규칙의 목표를 당신의 일정에 있는 피상적 작업의 발자국을 길들이는 것으로 보아야 하며 그것을 제거하는 것이 아니다.

그리고 인지 능력의 문제가 있다. 심층적인 일은 능력의 한계로 밀리기 때문에 지치게 된다. 성과 심리학자들은 주어진 날에 개인이 얼마나 그러한 노력을 지속할 수 있는지 광범위하게 연구해 왔다. \* 고의적 실천에 대한 그들의 시미널 논문에서 Anders Ericsson과 그의 공동 연구자들은 이러한 연구를 조사한다. 그들은 그러한 관행을 처음 접하는 사람에게 (특히 전문가 수준의 기술을 개발하는 초기 단계의 어린이를 인용함) 하루에 한 시간이라는 것이 합리적인 한계라고 지적한다. 그러한 활동의 엄격함에 익숙한 사람들에게는 한계가 4시간 정도로 확장되지만 드물게 더 길어진다.

그 의미는 당신이 주어진 날에 당신의 딥 워크 한계를 달성한 후에는, 당신이 더 많이 넣으려 하면 감소하는 보상을 경험할 것이라는 것이다. 따라서 하루 동안의 제한된 깊은 노력을 밀어내기 시작할 만큼 충분히 추가할 때까지 피상적 작업은 위험하지 않다. 처음에는 이 경고가 낙관적으로 보일 수 있습니다. 평균 근무 시간은 8시간입니다. 가장 능숙한 깊은 사유자는 이 시간 중 4시간 이상을 진정한 깊이의 상태에서 보낼 수 없다. 따라서 반나절을 피상적인 영역에서 부작용 없이 안전하게 헤매며 보낼 수 있습니다. 이 분석에서 놓친 위험은 특히 회의, 약속, 전화 및 기타 예정된 이벤트의 영향을 고려할 때 이 시간이 얼마나 쉽게 소비될 수 있는지입니다. 상당한 작업에서 이러한 시간 소모로 인해 혼자 작업할 시간이 놀랍게도 거의 남지 않을 수 있습니다.

예를 들어, 교수로서의 제 직업은 전통적으로 그러한 약속에 덜 시달리지만 그럼에도 불구하고 특히 학년 중에 제 시간에 많은 양을 차지하는 경우가 많습니다. 예컨대, 전 학기 달력의 임의의 날에 대해 (나는 조용한 여름 달에 이것을 쓰고 있다) 예를 들어, 나는 내가 열한에서 열두까지, 다른 하나는 한 번에서 두 번으로, 그리고 세 번에서 다섯 번까지 가르칠 수업이 있었다는 것을 안다. 이 예에서 나의 8시간 근무일은 이미 4시간 감소된다. 남은 피상적 작업(메일, 작업)을 모두 30분으로 짜내더라도, 나는 여전히 매일 4시간의 심층 작업이라는 목표에 미치지 못할 것이다. 다시 말해, 우리가 행복한 깊이의 상태에서 하루 종일 보낼 수 없지만 이러한 현실은 전형적인 지식 작업일이 많은 의심자보다 쉽게 파편화되기 때문에 피상적 작업을 줄이는 긴급성을 줄이지 않아야 한다.

요약하자면, 피상적 작업은 종종 그 피해가 크게 과소평가되고 그 중요성이 크게 과대평가되기 때문에 의심스럽게 취급해 달라고 요청한다. 이러한 작업은 불가피하지만 궁극적으로 영향을 결정하는 더 깊은 노력을 최대한 활용하는 능력을 방해하지 않는 지점으로 제한해야 한다. 다음의 전략은 이러한 현실에 대응하는 데 도움이 될 것입니다.

### 하루의 모든 시간을 분 단위로 계획하라

당신이 25세에서 34세 사이이고 영국에 살고 있다면, 당신은 당신이 생각하는 것보다 더 많은 텔레비전을 볼 것이다. 2013년 영국 TV 라이선스 당국은 텔레비전 시청자들의 습관에 대해 설문조사를 실시했다. 설문조사에 참여한 25세에서 34세 사이의 사람들피상적 작업주일에 15시간에서 16시간 사이의 시간을 TV를 보는 것으로 추정했다. 이는 많은 부분 같지만 실제로는 상당히 과소평가된 것이다. 우리는 텔레비전 시청 습관에 관해서는 지상적 진실에 접근할 수 있기 때문에 이것을 알고 있다. 방송사 청중연구위원회(영국어 닐슨컴퍼니의 등가물)는 가구의 대표적인 표본에 미터를 배치한다. 이 미터는 편견이나 소원 없는 사고 없이 사람들이 실제로 얼마나 많이 시청하는지 기록합니다. 주 15시간을 시청한다고 생각했던 25세에서 34세들은 결국은 28시간을 더 시청하는 것으로 나타났다.

이러한 시간 사용량에 대한 나쁜 추정은 영국 텔레비전 시청에서만 나타나는 것은 아니다. 서로 다른 행동을 스스로 평가하는 다른 집단을 고려하면, 유사한 격차가 완고하게 남아 있다. 이와 관련한 월스트리트저널 기사에서 비즈니스 작가 로라 밴더캄은 이와 같은 사례를 몇 가지 더 지적했다. 미국 국립수면재단의 조사에 따르면 미국인들은 평균적으로 밤마다 약 7시간 정도 잠을 잘 것이라고 생각한다. 실제로 수면을 측정하는 미국 시간 사용 조사에서는 이 수치를 8.6시간으로 수정했다. 또 다른 연구에서는 주당 64시간을 일한다고 주장하는 사람들은 실제로 평균적으로 주당 44시간을 더 많이 일하고 있는 반면, 75시간 이상을 일한다고 주장하는 사람들은 실제로 55시간 미만을 일하고 있다는 것을 발견했다.

이러한 예는 중요한 점을 강조하는데, 우리는 하루의 많은 부분을 자동 조종에 소비하며 시간으로 무엇을 하고 있는지에 대해 별로 생각하지 않는다. 이것은 문제입니다. 심층과 피상적 작업 사이의 현재의 균형을 주춤없이 직면하지 않고 나서 행동 전에 잠시 멈추고 "지금 가장 의미가 있는 것은 무엇입니까?"라고 묻는 습관을 채택하면 사소한 것이 일정의 구석구석으로 잠기는 것을 방지하기 어렵다. 다음 단락에 설명된 전략은 이러한 행동에 강제하도록 설계되었다. 처음에는 극단적으로 보일 수 있지만 곧 심층 작업의 가치를 최대한 활용하기 위한 당신의 탐구에서 필수불가결한 것으로 판명될 아이디어: 하루의 모든 분을 스케줄링한다.

다음은 내 제안입니다. 매일 작업 시작 시, 이 목적을 위해 바치는 공책의 새로운 줄 종이 페이지로 돌십시오. 페이지의 왼쪽 아래에서, 당신이 일반적으로 일하는 전체 시간 세트를 포함하며 하루의 한 시간으로 다른 모든 행을 표시하세요. 이제 중요한 부분이 나오는데, 일일 시간을 블록으로 나누고 블록에 활동을 할당하세요. 예를 들어, 클라이언트의 보도 자료를 작성하기 위해 오전 9시부터 11시를 차단할 수 있습니다. 그러기 위해서는 실제로 이 시간에 해당하는 선을 덮는 상자를 그른 다음 상자 안에 "프레스 릴리스"라고 써야 한다. 모든 블록이 작업 작업에 전용될 필요는 없습니다. 점심이나 휴식 시간에는 시간 차질이 있을 수 있습니다. 합리적으로 깨끗하게 유지하려면 블록의 최소 길이가 30분(즉, 페이지의 한 줄)이어야 합니다. 예를 들어, 이는 하루 동안 플레이트에 작피상적 작업마다 고유한 작은 상자를 갖는 대신 상사의 이메일에 응답하고, 상환 양식을 제출하고, Carl에게 보고에 대해 묻는 대신 유사한 것을 보다 일반적인 작업 블록으로 묶을 수 있음을 의미한다. 이 경우, 작업 블록에서 해당 블록에서 수행할 계획인 작피상적 작업의 전체 세트를 나열할 수 있는 페이지의 열린 오른쪽으로 선을 그리는 것이 유용할 수 있다.

하루 일정을 짜고 나면, 모든 분은 블록의 일부가 되어야 한다. 당신은 사실상 하루의 매 분마다 직장을 부여받았다. 이제 하루를 보내면서 이 일정을 사용하여 안내해 주세요.

물론 대부분의 사람들이 곤경에 처하기 시작하는 것은 여기서이다. 하루가 진행되면 일정에 두 가지 문제가 발생할 수 있습니다. 첫 번째는 당신의 추정치가 틀린 것으로 판명된다는 것입니다. 예를 들어, 보도 자료 작성에 2시간을 할애할 수 있는데 실제로는 2시간 30분이 소요됩니다. 두 번째 문제는 당신이 중단되고 예상치 못한 새로운 의무가 당신의 접시에 나타날 것이라는 것이다. 이 행사들은 또한 당신의 일정을 깨뜨릴 것입니다.

이거 괜찮아. 일정이 방해를 받는다면, 다음으로 가능한 순간에 하루 동안 남은 시간에 대해 수정된 일정을 만드는 데 몇 분을 걸어야 합니다. 새로운 페이지로 넘어가실 수 있습니다. 블록을 지우고 다시 그릴 수 있습니다. 또는 내가 하는 것처럼: 하루의 나머지 블록을 잘라내고 페이지의 이전 블록의 오른쪽에 새 블록을 생성합니다. 어떤 날은 30번이나 일정을 다시 작성할 수도 있습니다. 이런 일이 발생해도 절망하지 마세요. 당신의 목표는 어떤 대가를 치르더라도 주어진 일정에 매달리는 것이 아니라, 하루가 진행됨에 따라 이러한 결정이 계속해서 재작업되더라도 당신이 앞으로 무엇을 하고 있는지 항상 사려 깊은 말을 하는 것이다.

일정 수정이 빈도수가 압도적일 경우, 좀 더 안정성을 주입할 수 있는 몇 가지 전술이 있다. 첫째, 당신은 대부분의 일에 필요한 시간이 얼마나 많은지 처음에는 거의 확실히 과소평가할 것이라는 것을 인식해야 한다. 사람들은 이 습관이 처음일 때 일정을 소원적 사고의 화신으로 사용하는 경향이 있는데, 이는 하루 동안의 최상의 시나리오이다. 시간이 지남에 따라 작업이 필요로 하는 시간을 정확하게(다소 보수적이지 않더라도) 예측하는 노력을 기울여야 한다.

도움이 되는 두 번째 전술은 오버플로 조건부 블록을 사용하는 것이다. 주어진 활동이 얼마나 걸릴지 확신이 없다면, 예상 시간을 차단한 다음, 별도의 목적을 가진 추가 블록으로 이를 따르세요. 이전 활동에 더 많은 시간이 필요하다면 이 추가 블록을 사용하여 계속 작업하십시오. 그러나 당신이 시간을 맞춰 활동을 마친다면, 추가 블록에 대해 이미 할당된 대체 용도(예를 들어, 일부 비급박한 작업)를 갖는다. 따라서 종이에 따라 일정을 계속 변경할 필요 없이 하루를 예측할 수 있습니다. 예를 들어, 보도 자료의 예로 돌아가서, 보도 자료를 작성하기 위해 2시간을 예약한 다음, 필요하다면 보도 자료를 계속 작성하는 데 사용할 수 있지만 그렇지 않으면 이메일을 따라잡는 데 할당할 수 있는 추가 시간 블록으로 따라갈 수 있다.

제가 제안하는 세 번째 전술피상적 작업 블록을 사용하는 데 자유로워지는 것입니다. 하루 종일 많은 부분을 배치하고 아침에 계획한 작업을 처리하는 데 필요한 것보다 더 오래 하세요. 전형적인 지식 노동자의 하루 동안 많은 부분들이 떠오르는데, 이러한 놀라움을 해결하기 위해 정기적으로 발생하는 시간 블록피상적 작업을 원활하게 운영하는 것을 유지한다.

이 전략을 실행에 옮기기 전에, 저는 일반적인 반대 의견을 해결해야 합니다. 일일 일정의 가치를 제시한 경험에서 많은 사람들이 이러한 수준의 계획이 부담스럽게 제한적일 것이라고 걱정한다는 것을 발견했다. 여기 예를 들어, 이 주제에 대해 내가 쓴 블로그 게시물에 대한 조셉이라는 독자의 댓글의 일부입니다.

나는 당신이 불확실성의 역할을 훨씬 과소평가한다고 생각한다... 나는 독자들이 이러한 관찰을 너무 심각하게 적용하여 자신의 일정에 대한 강박적인(그리고 건강에 해로운) 관계를 갖는다는 점에서 예술가들을 말하는 경우 종종 유일한 합리적인 행동 과정인 활동에서 길을 잃는 것에 대한 미세한 계산의 중요성을 과장하는 것처럼 보인다.

이러한 우려를 이해하며 조셉이 확실히 처음 제기한 것은 아니다. 그러나 다행히도 쉽게 해결된다. 나의 일상적인 스케줄링 학문에서, 나는 사변적 사고와 토론을 위해 상당한 시간 블록을 정기적으로 스케줄링하는 것 외에도, 중요한 통찰을 우연히 발견하면, 이것은 하루의 나머지 일정을 무시하는 완전히 타당한 이유(물론 건너뛸 수 없는 것들을 제외하고)라는 규칙을 유지한다. 그런 다음 나는 이 예상치 못한 통찰력을 증기가 날 때까지 유지할 수 있습니다. 이 시점에서 나는 한 걸음 물러서서 하루 중 남은 시간 동안 일정을 다시 만들 것이다.

즉, 나는 내 스케줄에 자발성을 허용할 뿐만 아니라, 그것을 장려한다. 조셉의 비판피상적 작업정의 목표가 자신의 행동을 경직된 계획으로 강제하는 것이라는 잘못된 생각에서 비롯된다. 그러나 이러한 유형의 일정은 제약에 관한 것이 아니라 사려 깊음에 관한 것이다. 하루 종일 계속 잠시 시간을 내어 '남은 시간에는 내가 무슨 일인가?'라고 묻는 단순한 습관, 답에 대한 당신의 굴절없는 충실함이 아니라 결과를 돌려주는 질문의 습관이다.

나는 종합적인 일정의 조합과 필요에 따라 계획을 조정하거나 수정하려는 의지를 따르는 사람이 하루가 개방되고 구조화되지 않은 더 전통적인 '자발적' 접근 방식을 채택하는 사람보다 더 창의적인 통찰력을 경험할 가능성이 있다고 주장할 정도로 멀리 갈 것이다. 구조가 없으면, 당신의 시간이 단순 이메일, 소셜 미디어, 웹 서핑으로 전락하는 것을 쉽게 허용한다. 이러한 유형의 은 행동은 비록 순간적으로 만족스럽지만 창의성에 도움이 되지 않는다. 반면에 구조를 사용하면 새로운 아이디어와 함께 일하거나 도전적인 작업을 심도 있게 하거나 고정된 기간 동안 브레인스토밍을 하도록 정기적으로 일정을 잡을 수 있습니다. (예컨대, 많은 위대한 창조적 사상가들이 뒤따르는 경직된 의례에 대한 규칙 #1에서의 논의를 상기하라.) 그리고 혁신적인 아이디어가 떠오를 때 계획을 기꺼이 포기하기 때문에, 당신은 이 음악이 닥쳤을 때 후속 조치를 취하는 산만한 창조적 존재만큼 적합하다.

요약하자면, 이 전략의 동기는 깊은 업무 습관이 시간을 존중하는 자세로 대할 것을 요구한다는 인식이다. 이러한 존중적 처리를 위한 좋은 첫 번째 단계는 여기에 요약된 조언입니다. 작업일의 매 분마다 무엇을 할 것인지 미리 결정하세요. 내적 변덕과 외적 요청의 쌍둥이 힘에 따라 일정을 주도하는 것이 더 쉬울 수밖에 없기 때문에 처음에는 이 생각에 저항하는 것이 당연하다. 그러나 중요한 것을 창조하는 사람으로서 자신의 진정한 잠재력에 접근하려면 구조에 대한 이러한 불신을 극복해야 합니다.

### 모든 활동의 몰입 깊이를 수치화하라

하루를 계획하는 것의 장점은 당신이 실제로 피상적인 활동에 얼마나 많은 시간을 보내고 있는지 결정할 수 있다는 것이다. 그러나 주어진 과제를 얼마나 깊이 있게 고려해야 하는지는 항상 명확하지 않기 때문에 일정에 이러한 통찰력을 추출하는 것은 실제로 까다로울 수 있다. 이 문제를 확장하기 위해 서론에서 소개한 피상적 작업의 공식적 정의를 상기시키는 것으로 시작하자.

피상적 작업: 인지적으로 요구되지 않는 물류 스타일의 작업으로, 종종 산만하게 수행된다. 이러한 노력은 세상에 새로운 가치를 많이 창출하지 못하는 경향이 있으며 복제하기 쉽다.

일부 활동은 분명히 이 정의를 충족합니다. 예를 들어 이메일을 확인하거나 전화 회의를 예약하는 것은 본질적으로 피상적인 일임에 틀림없다. 하지만 다른 활동의 분류는 더 모호할 수 있습니다. 다음 작업을 고려하십시오.

* **예시 1**: 공동 연구자와 함께 학술지에 곧 제출할 논문 초안을 교정 및 수정하는 작업.
* **예시 2**: 이번 분기 매출 실적에 관한 파워포인트 발표 자료를 제작하는 작업.
* **예시 3**: 중요 프로젝트의 현재 진행 상황을 점검하고 다음 실행 단계를 합의하기 위한 회의에 참석하는 일.

이러한 예들을 어떻게 분류할지는 처음에는 분명하지 않다. 앞의 두 가지는 상당히 까다로울 수 있는 과제를 설명하고 마지막 예는 핵심 업무 목표를 진전시키기 위해 중요한 것으로 보인다. 이 전략의 목적은 이러한 모호성을 해결하기 위한 정확한 측정값을 제공하는 것이며 주어진 작업 작업이 은 규모에서 깊이까지 어디에 해당하는지 명확하고 일관된 결정을 내릴 수 있는 방법을 제공하는 것이다. 그렇게 하기 위해, 그것은 당신이 간단한(그러나 놀랍게도 조명적인) 질문을 던져서 활동을 평가하도록 요청한다.

내 분야에서 전문적인 교육이 없는 똑똑한 대학 졸업자를 훈련시켜 이 과제를 완수하는 데 얼마나 걸리겠는가?

이 접근법을 설명하기 위해 이 질문을 모호한 작업의 예에 적용하자.

사례 1의 분석: 학술 논문을 제대로 편집하려면 작품의 뉘앙스(정확하게 기술되고 있는지 확인할 수 있도록)와 광범위한 문헌의 뉘앙스(정확하게 인용되고 있는지 확인할 수 있도록)를 이해해야 한다. 이러한 요구 사항은 학문 분야에 대한 최첨단 지식을 요구하며 이는 전문화 시대에 대학원 수준 및 그 이상에서 수년간의 부지런한 연구가 필요한 작업이다. 이 예의 경우, 우리의 질문에 대한 답은 아마도 50개월에서 75개월의 규모로 상당히 클 것이다.

• 분석 예제 #2: 두 번째 예제는 이 분석에 의해 그렇게 잘 되지 않는다. 분기 매출을 설명하는 파워포인트 프레젠테이션을 만들기 위해서는 첫째, 파워포인트 프레젠테이션을 만드는 방법에 대한 지식, 둘째, 조직 내 이러한 분기 성과 프레젠테이션의 표준 형식에 대한 이해, 셋째, 조직이 추적하는 매출 메트릭과 올바른 그래프로 변환하는 방법에 대한 이해가 필요합니다. 우리가 상상한 가상의 대졸자는, 우리가 짐작할 수 있는 바, 파워포인트를 사용하는 방법을 이미 알고 있을 것이고 조직의 발표를 위한 표준 형식을 배우는 데 일주일이 넘지 않아야 한다. 따라서 진정한 질문은 밝은 대학 졸업자가 추적하는 메트릭을 이해하는 데 얼마나 걸리고 결과를 어디에서 찾을 수 있으며 이를 정리하여 슬라이드 프레젠테이션에 적합한 그래프와 차트로 변환하는 방법이다. 이것은 사소한 작업은 아니지만 밝은 대학 졸업자의 경우 추가 교육이 한 달 이상 필요하지 않으므로 두 달을 보수적인 답으로 사용할 수 있다.

• 분석 예제 #3: 회의는 분석하기 어려울 수 있다. 때때로 지루해 보일 수 있지만 종종 조직의 가장 중요한 활동에서 핵심적인 역할을 하는 것으로 제시됩니다. 여기에 제시된 방법은 이 베니어를 절단하는 데 도움이 됩니다. 최근 대학 졸업생이 기획 회의에서 당신의 자리를 대신할 수 있도록 훈련하는 데 얼마나 걸리나요? 프로젝트의 이정표와 참여자의 기술을 알 수 있을 만큼 프로젝트를 잘 이해해야 합니다. 우리의 가상의 졸업생은 또한 대인 관계 역학과 그러한 프로젝트가 조직에서 실행되는 방식의 현실에 대한 통찰력이 필요할 수 있다. 이 시점에서 이 대학 졸업생도 프로젝트가 다루는 주제에 대한 깊은 전문 지식이 필요한지 궁금할 수 있습니다. 계획 회의의 경우 아마도 그렇지 않을 것입니다. 이러한 회의는 실질적인 내용에 대한 연구는 거의 없으며 참가자들이 실제로 참여하지 않고도 많은 부분을 약속하는 것처럼 보이도록 하는 작은 이야기와 자세가 많이 나타나는 경향이 있다. 밝은 최근 졸업생에게 줄타기를 배우기 위해 3개월을 주면 그러한 격투에서 문제 없이 당신의 자리를 대신할 수 있습니다. 그래서 우리는 3개월을 우리의 답으로 삼을 것이다.

이 질문은 사고 실험을 위한 질문(최근 대졸자를 실제로 고용하여 점수가 낮은 업무를 맡아달라고 요청하지는 않겠다)이다. 하지만 그것이 제공하는 답변은 다양한 활동의 은 면이나 깊이를 객관적으로 정량화하는 데 도움이 될 것입니다. 우리의 가상의 대졸자가 과제를 복제하기 위해 몇 개월의 훈련을 필요로 한다면, 이것은 과제가 열심히 얻은 전문 지식을 활용한다는 것을 나타낸다. 앞서 주장한 바와 같이 자신의 전문성을 활용하는 과제는 심층적인 과제이기 때문에 투입된 시간당 더 많은 가치를 반환하고 능력을 확장하여 향상시키는 이중의 이점을 제공할 수 있다. 반면, 우리의 가상의 대졸자가 빠르게 짚어낼 수 있는 과제는 전문성을 활용하지 않는 과제이므로 피상적인 일으로 이해할 수 있다.

이 전략으로 어떻게 해야 하나요? 활동이 깊은 몰입에서 피상적 작업까지의 스케일에서 어디에 해당하는지 알게 되면 전자를 향해 시간을 편향시킨다. 예를 들어, 사례 연구를 재고할 때 첫 번째 작업은 시간을 잘 활용하는 것으로 우선시하고 싶피상적 작업이고 두 번째와 세 번째는 최소화해야 하는 유형의 활동으로 생산적이라고 느낄 수 있지만 (시간) 투자에 대한 수익은 척박하다는 것을 알 수 있다.

물론, 어떻게 피상적인 영역에서 깊이로 편향되는지는 약속에 정확하게 라벨을 붙이는 방법을 알고도 항상 분명하지 않다. 이것은 우리를 이 까다로운 목표를 달성하는 방법에 대한 구체적인 지침을 제공할 다음 전략으로 연결한다.

### 상사에게 피상적 작업에 대한 허용 한도를 요구하라

여기서는 거의 묻지 않는 중요한 질문이다: 제 시간의 몇 퍼센트를 피상적 작업에 사용해야 합니까? 이 전략은 당신이 그것을 묻는 것을 암시합니다. 상사가 있다면, 다시 말해 이 질문에 대해 대화를 나누는 것이다. (여러분은 아마도 먼저 그에게 '은' 작업과 '깊은' 작업이 무엇을 의미하는지 정의해야 할 것이다.) 스스로 일을 한다면 이 질문을 스스로에게 해보세요. 두 경우 모두, 특정 답변에 합의하세요. 그렇다면, 그리고 이것이 중요한 부분인 이 예산을 고수하려고 노력한다. (이전에 그리고 이전에 따르는 전략이 이 목표를 달성하는 데 도움이 될 것입니다.)

대부분의 비진학 수준의 지식 업무에 종사하는 대부분의 사람들에게는 질문에 대한 답이 30~50% 범위(미숙련 업무에 대부분의 시간을 소비한다는 생각에 심리적 혐오가 있기 때문에 50%는 자연스러운 상한선임)에 있을 것이며 동시에 대부분의 상사는 이 비율이 30% 미만으로 너무 낮아지면 큰 생각을 하지만 이메일에 응답하지 않는 지식 업무 은둔자로 전락할 것이라고 걱정하기 시작할 것이다.

이 예산을 준수하려면 행동의 변화가 필요할 것입니다. 당신은 거의 확실하게 은 점이 주입된 것처럼 보이는 프로젝트에 대해 거절해야 하는 동시에 기존 프로젝트의 은 양을 더 공격적으로 줄일 수밖에 없다. 이 예산은 결과 기반 보고를 선호하는 주간 상태 회의의 필요성을 줄일 수 있습니다. 그것은 또한 당신이 통신 격리에서 더 많은 아침을 보내기 시작하거나 당신의 받은 편지함을 가로지르는 모든 cc-d 이메일에 빠르고 자세히 응답하는 것이 한때 생각했던 것만큼 중요하지 않다고 결정할 수도 있다.

이러한 변화는 모두 작업 생활의 중심에 딥 워크을 만드는 데 긍정적인 영향을 미칩니다. 한편으로는 여전히 그러한 노력에 많은 시간을 소비하고 있기 때문에 그들은 당신에게 당신의 핵심적인 은 의무(문제와 원한을 유발할 수 있는 행동)를 버리지 말라고 요구하지 않는다. 반면에, 그들은 당신이 당신의 일정에 속박하게 미끄러지도록 허용하는 덜 긴급한 의무의 양에 엄격한 제한을 강요합니다. 이 한계는 일관된 기준으로 상당한 양의 깊은 노력을 위한 공간을 확보한다.

이러한 결정이 상사와의 대화로 시작되어야 하는 이유는 이 합의가 직장의 암묵적인 지원을 확립하기 때문입니다. 타인을 위해 일한다면 이 전략은 피상적인 일을 최소화하기 위해 의무를 거절하거나 프로젝트를 재구성할 때 보장을 제공합니다. 당신은 자신이 정한 목표의 작업 유형 믹스를 맞추는 것이 필요하기 때문에 그 움직임을 정당화할 수 있다. 2장에서 논의한 바와 같이 지식 업무에서 은 업무가 대량으로 지속되는 이유의 일부는 그러한 노력이 우리 일정에 미치는 전체적인 영향을 거의 보지 못하기 때문이다. 우리는 대신 이러한 행동을 순간적으로 하나씩 평가하는 경향이 있는데, 각 작업이 상당히 합리적이고 편리해 보일 수 있는 관점이다. 그러나 이 규칙의 초기 도구는 이러한 영향을 명시적으로 만들 수 있도록 한다. 이제 상사에게 "이것이 지난 주에 피상적 작업에 사용한 시간의 정확한 비율"이라고 자신 있게 말하고 그 비율에 대해 명시적인 승인을 하도록 강요할 수 있다. 이러한 수치와 그들이 명확히 하는 경제적 현실(예: 고도로 훈련된 전문가를 고용하여 주 30시간 동안 이메일 메시지를 보내고 회의에 참석하는 것은 매우 낭비이다)에 직면하여 상사는 상사, 또는 귀하 또는 귀하의 동료에게 삶을 덜 편리하게 만들더라도 일부 사항에 대해 거절하고 다른 것을 효율화해야 한다는 자연스러운 결론으로 이끌릴 것입니다. 왜냐하면, 물론 결국 기업의 목표는 가치 창출이지 직원들의 삶을 최대한 쉽게 하기 위한 것이 아니기 때문이다.

스스로 일을 한다면 이 운동은 당신이 실제로 가치를 생산하고 있는 " 바쁜" 일정의 시간이 얼마나 적은 현실에 직면하게 할 것이다. 이 단단한 숫자는 시간을 낭비하는 피상적인 활동에 대한 스케일링을 시작하는 데 필요한 자신감을 줄 것입니다. 이러한 숫자가 없으면 기업가는 긍정적인 수익을 창출할 수 있는 기회에 거절하기 어렵다. "나는 트위터에 있어야 한다!" "나는 적극적인 페이스북 존재를 유지해야 한다!" "나는 내 블로그의 위젯을 조정해야 한다!"라고 스스로에게 말하며 왜냐하면 이러한 활동 중 하나에 대해 거절하는 것은 게으름처럼 보이기 때문이다. 대신 은 비율로 선택하고 고수함으로써, 당신은 이 죄책감에 의한 무조건적인 수용을 피상적 작업에 할애한 시간을 최대한 활용하려고 노력하는 더 건강한 습관으로 대체할 수 있습니다. (따라서 여전히 많은 기회에 노출됨), 그러나 이러한 노력을 시간과 주의의 충분히 작은 부분으로 제한하여 궁극적으로 비즈니스를 앞으로 몰고 가는 딥 워크을 가능하게 합니다.

물론 이 질문을 할 때 답이 뚜렷할 가능성이 항상 있다. 어떤 상사도 "시간의 100%가 아야 한다!"(입문 단계가 아니라면, 공식 업무 책임에 깊은 노력을 더할 수 있는 충분한 기술을 쌓을 때까지 이 운동을 연기해야 한다)라고 명시적으로 대답하지 않을 것이지만 상사는 "당시 우리에게 필요한 모든 것을 즉시 수행하는 데 필요한 만큼의 은 업무"라고 대답할 수 있습니다. 이 경우, 이 답은 여전히 유용합니다. 이는 딥 워크을 지원하는 직업이 아니며 딥 워크을 지원하지 않는 직업이 현재 정보 경제에서 성공하는 데 도움이 될 수 있는 직업이 아님을 알려줍니다. 이 경우 사장님께 피드백에 감사한 다음 깊이를 중시하는 새로운 직책으로 전환할 수 있는 방법을 즉시 계획하기 시작해야 합니다.

### 오후 5시 반에 하루 일과를 끝내라

처음 이 말을 쓰는 7일 동안 65개의 서로 다른 이메일 대화에 참여했다. 이 65개의 대화 중, 오후 5시 30분 이후에 정확히 5개의 이메일을 보냈습니다. 이 통계가 알려주는 즉각적인 이야기는 몇 가지 예외를 제외하고는 5시 30분 이후에 이메일을 보내지 않는다는 것이다. 하지만 이메일과 업무가 대체로 얼마나 얽혀있는지 생각해보면, 이 행동으로 암시되는 더 놀라운 현실이 있는데, 나는 오후 5시 30분 이후에 일을 하지 않는다.

나는 이 약속을 고정된 일정 생산성이라고 부르는데, 나는 일정 시간을 지나서 일을 하지 않는 확고한 목표를 고정하고 나서 이 선언을 충족시킬 수 있는 생산성 전략을 찾기 위해 역진적으로 노력한다. 저는 이제 반 십 년 이상 즐겁게 고정 일정 생산성을 실천해 왔으며 심층적인 일을 중심으로 생산적인 직업 생활을 구축하려는 노력에 결정적이었다. 앞으로의 페이지에서 이 전략을 채택하도록 설득하려고 노력할 것입니다.

기존의 통념에 따르면 내가 살고 있는 학계에서 이 전술이 실패해야 한다는 점에 주목하여 고정 일정 생산성을 위한 제 주장을 시작하겠습니다. 교수들, 특히 후배 교수들은 밤까지 그리고 주말까지 이어지는 힘든 일정을 채택하는 것으로 악명이 높다. 예를 들어, 내가 "톰"이라고 부를 젊은 컴퓨터 과학 교수가 게시한 블로그 게시물을 생각해 보자. 2014년 겨울에 톰이 쓴 이 게시물에서 그는 사무실에서 12시간을 보낸 최근 하루의 일정을 복제한다. 이 일정은 5개의 다른 회의와 3시간의 "행정" 작업을 포함하며 그는 "메일 부셸 처리, 관료적 양식 작성, 회의 메모 정리, 미래 회의 계획"이라고 설명합니다. 그의 추정에 따르면, 그는 사무실에 앉아 "진짜" 작업을 처리하는 총 12시간 중 절반만 보냈는데, 이는 그가 "연구 결과"를 향한 진전을 이루는 노력이라고 정의한다. 톰이 표준 근무일을 훨씬 초과하여 일하도록 강요받는 것은 놀라운 일이 아니다. 그는 또 다른 글에서 "나는 주말에 일할 것이라는 현실을 이미 받아들였다"고 마무리했다. "그렇게 운명을 피할 수 있는 후배 교직원은 극소수"이다.

그래도, 나는 가지고 있다. 나는 밤에 일하지 않고 주말에는 거의 일하지 않지만 2011년 가을에 조지타운에 도착하여 2014년 가을에 이 장에 대한 작업을 시작하는 사이에 약 20개의 동료 검토 기사를 출판했다. 나는 또한 두 번의 경쟁 보조금을 받았고, 한 권의 (비학문) 책을 출판했으며, (지금 당신이 읽고 있는) 다른 책을 거의 완성했다. 모든 것은 세계의 톰들이 필요하다고 생각하는 지친 일정을 피하면서 이루어집니다.

이 역설을 설명하는 이유는 무엇인가요? 우리는 그녀의 경력을 더 발전시켜 한 학자가 2013년에 널리 보급된 기사에서 설득력 있는 답을 찾을 수 있으며 하버드 대학의 프레드 카블리 컴퓨터 과학 교수인 나: 라디카 나그팔보다 훨씬 더 성취했다. 낙팔은 재임교수들이 겪는 스트레스의 상당 부분이 자기부과라고 주장하며 글을 시작한다. 그녀는 "R1" [연구 중심] 대학의 재직 과정 교수로서의 삶에 대한 무서운 신화와 무서운 데이터가 풍부하다"고 시작하면서 마침내 통념을 무시하고 대신 "의도적으로... 내 행복을 보존하기 위해 특정 일을 한다"고 결정한 이유를 계속 설명한다. 이 의도적인 노력으로 인해 나그팔은 "엄청나게" 전임 시간을 즐겼다.

나가팔은 이러한 노력의 몇 가지 예를 자세히 설명하지만 특히 익숙하게 들릴만한 한 가지 전술이 있다. 나그팔이 인정하듯이, 학업 초기 그녀는 아침 7시에서 자정 사이에 매일 자유 시간에 일을 처리하려고 노력하는 자신을 발견했다(아이가 있기 때문에, 이번에는 특히 저녁에 심한 골절이 자주 발생했다). 그녀는 이 전략이 지속 불가능하다고 결정하기까지 오래 걸리지 않았으므로 일주일에 50시간의 한도를 설정하고 이 제약을 충족시키기 위해 어떤 규칙과 습관이 필요한지 결정하기 위해 역진적으로 노력했다. Nagpal은 즉, 고정된 일정의 생산성을 전개했습니다.

우리는 이 전략이 그녀의 학업 경력에 영향을 미치지 않았다는 것을 알고 있는데, 그녀는 결국 일정대로 재직을 얻은 다음 3년만 더 (인상적인 상승) 정교수 수준으로 뛰어들었다. 어떻게 이걸 해냈어? 그녀의 기사에 따르면, 그녀의 시간 제한을 존중하는 주요 기법 중 하나는 그녀의 학업 생활에서 은 노력의 주요 출처에 대한 과감한 할당량을 설정하는 것이었다. 예를 들어, 그녀는 여행이 (숙박 준비에서 회담 작성까지) 긴급한 은 의무의 놀라운 많은 부하를 생성할 수 있기 때문에 어떤 목적으로든 1년에 5번만 여행하기로 결정했다. 1년에 다섯 번은 여전히 많은 여행처럼 들릴 수 있지만 학업적인 것은 가볍다. 이 점을 강조하기 위해 하버드 컴퓨터과학과 내그팔의 동료였던 맷 웰시(현재 구글에서 일)는 한 번 저니어 교수들이 일 년에 12~24번 여행을 하는 것이 일반적이라고 주장하는 블로그 글을 썼다. (나그팔이 10~15번의 추가 여행을 피하면서 피했던 은 노력을 상상해 보세요!) 여행 할당량은 나가팔이 일과를 통제하기 위해 사용한 여러 전술 중 하나일 뿐(예: 그녀는 또한 연간 검토할 논문의 수에 제한을 두었다) 그러나 그녀의 모든 전술이 공유한 것은 궁극적으로 그녀의 직업적 운명을 결정하는 깊은 노력, 즉 독창적인 연구를 보호하면서 피상적인 일을 무자비하게 제한하겠다는 약속이었다.

제 예로 돌아가서, 고정된 스케줄로 성공할 수 있게 해주는 것은 비슷한 약속이다. 나도 자신의 생산성 어휘에서 가장 위험한 단어인 "예"를 사용하는 것에 대해 믿을 수 없을 정도로 조심스럽다. 피상적 작업을 산출하는 것에 동의하기 위해 나를 설득하는 데 많은 부분이 필요하다. 꼭 필요 없는 대학 사업에 관여를 요청하면, 나를 고용한 학과 의장으로부터 배운 방어로 대답할 수 있다. "임기 후 나에게 이야기하라." 나에게 잘 맞는 또 다른 전술은 거절에 있어 명확하지만 거절에 대한 설명이 모호하다는 것이다. 핵심은 요청자가 이를 소극화할 기회가 있다는 변명에 대해 충분한 구체성을 제공하는 것을 피하는 것이다. 예를 들어, 비슷한 시간에 다른 여행이 예정되어 있다는 빌미로 시간이 많이 걸리는 연설 초대장을 거절하면, 나는 세부 사항을 제공하지 않으며 이는 요청자에게 자신의 행사를 나의 기존 의무에 맞추는 방법을 제안할 수 있는 능력을 남길 수 있다. 대신 "흥미롭게 들리지만 일정 갈등으로 인해 할 수 없다." 의무를 거절할 때, 나는 또한 내 일정의 거의 대부분을 소비하는 위로 상을 제공해야 한다는 충동에 저항한다(예: "미련하게 당신의 위원회에 합류할 수 없지만 당신의 제안이 함께 와서 내 생각을 제시하는 데 일부 기쁘게 생각한다 깨끗한 휴식이 가장 좋습니다.

나는 나의 의무를 조심스럽게 지키는 것 외에도 나의 시간 관리에 대해 믿을 수 없을 정도로 양심적이다. 나는 매일 시간이 제한되어 있기 때문에, 스마트한 계획을 세우는 데 잠시 시간을 들이지 않았기 때문에 큰 기한이 나에게 다가오거나 사소한 일에 아침을 낭비할 여유가 없다. 일정이 정해진 생산성에 의해 시행되는 근무일의 다모클린 캡은 조직의 노력을 날카롭게 유지하는 방법이 있다. 이 절단기가 없었으면, 나는 내 습관에 더 느슨해질 것이다.

이러한 관찰을 종합하면, 나그팔과 나는 두 가지 이유로 톰 스타일의 과부하 없이 학계에서 모두 성공할 수 있다. 첫째, 우리는 고정된 일정에 대한 약속에 의해 강요된 도태에서 비대칭적이다. 이 전략은 깊이를 보존하면서 피상적인 일을 무자비하게 줄임으로써 우리가 창출하는 새로운 가치의 양을 줄이지 않고 시간을 자유롭게 한다. 실제로, 나는 피상적인 영역의 감소가 딥 워크인 대안에 더 많은 에너지를 내어 더 전형적인 붐비는 일정에 불이행했을 때보다 더 많은 부분을 생산할 수 있게 한다고 주장할 정도로 갈 것이다. 둘째, 우리 시간의 한계는 조직 습관에 대한 더 세심한 생각을 필요로 하며 또한 길지만 덜 조직화된 일정에 비해 더 많은 가치가 생성된다.

이 전략의 핵심 주장은 이러한 동일한 이점이 대부분의 지식 작업 분야에 적용된다는 것이다. 즉, 교수라고 할 수 없더라도 일정 고정 생산성은 강력한 이점을 가져올 수 있다. 대부분의 지식 업무에서 고립되어 무해해 보이는 은 몰입을 거부하기 어려울 수 있는데, 커피를 마시라는 초대를 받아들이거나 "대화를 끊으러" 동의하는 것이든 간에, 고정된 일정에 대한 생산성에 대한 몰입은 희소성 마인드로 전환된다. 갑자기 당신의 깊은 노력을 넘어서는 어떤 의무도 의심스럽고 잠재적으로 파괴적인 것으로 간주된다. 기본 답은 아니오가 되고, 시간과 관심에 접근하기 위한 막대가 급격히 높아지고, 당신은 이러한 장애물을 넘기는 노력을 무자비한 효율성으로 조직하기 시작한다. 그것은 또한 당신이 철로 싸인다고 생각했지만 가식성이 있는 것으로 판명된 회사의 작업 문화에 대한 가정을 테스트하도록 이끌 수 있다. 예를 들어, 시간 경과 후 상사로부터 이메일을 받는 것이 일반적이다. 일정 생산성은 다음 날 아침까지 이러한 메시지를 무시하게 합니다. 많은 사람들이 이러한 반응이 예상되는 것처럼 이것이 문제를 일으킬 것이라고 의심하지만 많은 경우에 상사가 밤에 받은 편지함을 청소한다고 해서 그녀가 즉각적인 반응을 기대한다는 것은 아닙니다. 이 전략이 곧 발견하는 데 도움이 될 수 있다는 교훈입니다.

즉, 고정 일정 생산성은 채택하기 쉽지만 영향이 광범위한 메타 습관이다. 만약 당신이 심층으로 초점을 재지향시키는 하나의 행동만을 선택해야 한다면, 이것은 당신의 가능성 목록에서 높아야 한다. 그러나 일과에 대한 인위적인 제한이 당신을 더 성공하게 만들 수 있다는 생각에 대해 여전히 확신이 없다면, 나는 다시 한 번 고정 일정을 옹호하는 라디카 나그팔의 경력에 주의를 기울일 것을 촉구한다. 만족스러운 우연의 일치로, 톰이 젊은 교수로서 어쩔 수 없이 격렬한 업무량에 대해 온라인에서 한탄하고 있었던 거의 같은 시기에, 나그팔은 고정된 일정에 불구하고 그녀가 경험한 많은 직업적 승리 중 가장 최근의 것을 축하하고 있었다.

### 쉽게 연락 닿지 않는 사람이 되어라

피상적 작업에 대한 논의는 이메일을 고려하지 않고는 완전하지 않다. 이 전형적인 피상적인 활동은 특히 당신에게 특별히 언급된 산만함을 지속적으로 전달하기 때문에 대부분의 지식 작업자의 관심을 사로잡는 데 까다롭다. 일상적인 이메일 접근은 우리의 직업 습관에 너무 뿌리내려서 우리 삶에서 그 역할에 대해 말할 수 있는 말이 없다는 감각을 잃기 시작했다. 존 프리먼은 2009년 저서인 '이메일의 횡포'에서 경고했듯이, 이 기술의 부상으로 "왜 우리가 업무 일정을 관리할 수 있도록 불평하거나 저항하거나 재설계하는 것이 너무 잘못된지 신중하고 복잡한 방식으로 설명하는 능력을 천천히 잠식하고 있다." 이메일은 기정사실처럼 보인다. 저항은 헛되이야.

이 전략은 이러한 운명론을 밀어내고 있다. 당신이 이 도구를 완전히 피할 수 없다고 해서 정신적인 환경에서 그것의 역할에 대한 모든 권한을 양보해야 한다는 것은 아니다. 다음 섹션에서는 이 기술이 시간과 주의에 접근하는 방법에 대한 권한을 회복하고 프리먼이 식별한 자율성의 침식을 저지하는 데 도움이 되는 세 가지 팁을 설명한다. 저항은 헛되지 않습니다. 처음에는 생각할 수 있는 것보다 전자 통신을 더 많이 제어할 수 있습니다.

::: {.callout-tip title="팁 1: 이메일 발신자가 더 많은 수고를 들이게 하라 (발신자 필터 활용)"}
대부분의 논픽션 작가들은 쉽게 연락할 수 있습니다. 저자 웹사이트에 이메일 주소를 포함하고 떠오르는 요청이나 제안을 보낼 수 있는 공개 초대장을 포함합니다. 많은 사람들은 독자들 사이에서 '커뮤니티 구축'의 이해하기 어렵지만 널리 강조되는 중요성에 대한 필요한 약속으로 이 피드백을 장려하기도 한다. 하지만 문제는 내가 그것을 사지 않는다는 것이다.

제 저자 홈페이지의 연락처를 방문하시면 범용 이메일 주소가 없습니다. 대신 특정 목적으로 연락할 수 있는 다양한 개인을 나열합니다. 예를 들어 권리 요청에 대한 문학 대리인 또는 연설 요청에 대한 연설 대리인. 저에게 연락을 원하시면 조건과 답변을 줄일 수 있는 특수 목적의 이메일 주소만 제공합니다.

내 삶을 더 흥미롭게 만들 수 있는 제안, 기회 또는 소개가 있으면 [칼뉴포트닷컴]에서 나에게 이메일을 보내주십시오. 위에서 언급한 이유로 나는 내 일정과 관심사에 잘 맞는 제안에만 응답할 것이다.

나는 이 접근법을 발신자 필터라고 부르는데, 나는 내 통신원들에게 나에게 연락을 시도하기 전에 자신을 필터링하도록 요청하기 때문이다. 필터로 받은 편지함에 보내는 시간을 크게 줄였습니다. 발신자 필터를 사용하기 전에, 제 웹사이트에 표준 범용 이메일 주소가 나열되어 있었습니다. 당연히 나는 특정(그리고 종종 상당히 복잡한) 학생이나 진로 질문에 대한 조언을 요청하는 긴 이메일을 대량으로 받곤 했다. 나는 개인을 돕는 것을 좋아하지만 이러한 요청은 압도적이 되었는데, 그들은 송신자가 제작하는 데 시간이 오래 걸리지 않았지만 응답하려면 많은 설명과 글이 필요했다. 제 발신자 필터는 그러한 대부분의 통신을 제거했고 그렇게 함으로써 필기 받은 편지함에서 만나는 메시지 수를 크게 줄였습니다. 독자를 돕는 데 대한 나의 관심에 대해, 나는 이제 이 에너지를 내가 신중하게 선택한 설정으로 재지향하여 영향을 극대화한다. 예를 들어, 전 세계의 어떤 학생도 저에게 질문을 보낼 수 있도록 하는 대신, 저는 이제 접근성이 매우 높고 보다 내실 있고 효과적인 멘토링을 제공할 수 있는 소수의 학생 그룹과 긴밀히 협력합니다.

발신자 필터의 또 다른 장점은 기대치를 재설정한다는 것입니다. 내 설명에서 가장 중요한 줄은 다음과 같다: "나는 내 일정과 관심사에 잘 맞는 제안에만 응답할 것이다." 이것은 사소해 보이지만 내 특파원이 나에게 보내는 메시지에 대해 생각하는 방식에 실질적인 차이를 만든다. 이메일을 둘러싼 기본 사회 관습은 유명하지 않으면 누군가가 당신에게 무언가를 보내면 그에게 응답을 빚진다는 것이다. 따라서 대부분의 경우 메시지로 가득 찬 받은 편지함은 큰 책임감을 유발합니다.

대신 당신이 응답하지 않을 것이라는 현실에 대한 당신의 특파원들의 기대를 재설정함으로써, 경험은 변형된다. 이제 받은 편지함은 당신이 참여할 수 있는 합리적인 기회를 찾는 자유 시간이 있을 때 볼 수 있는 기회의 모음입니다. 하지만 읽지 않은 메시지의 더미는 더 이상 책임감을 생성하지 않습니다. 원한다면, 그것들을 모두 무시할 수 있고 나쁜 일은 작업어나지 않을 것입니다. 심리적으로, 이것은 해방적일 수 있습니다.

나는 처음 발신 필터를 사용하기 시작했을 때 그것이 마치 독자들의 시간보다 내 시간이 더 가치 있는 것처럼 가식적으로 보일 것이고 사람들을 화나게 할 것이라고 걱정했다. 그러나 이러한 두려움은 실현되지 않았다. 대부분의 사람들은 이 같은 권리를 누리고 싶어서 자신의 입국 커뮤니케이션을 통제할 권리가 있다는 생각을 쉽게 받아들인다. 더 중요한 것은, 사람들은 명확함을 높이 평가한다는 것입니다. 대부분의 사람들은 그들이 그것을 기대하지 않는다면 응답을 받지 않는 것이 괜찮습니다(일반적으로 저자와 같이 대중의 존재감이 적은 사람들은 사람들이 메시지에 대한 응답에 얼마나 관심을 기울이는지를 과대평가합니다).

어떤 경우에는 이 기대 재설정이 응답할 때 더 많은 신용을 얻을 수도 있습니다. 예를 들어, 온라인 출판물의 편집자가 필터로 설정된 게스트 포스트 기회를 저에게 보내서 제가 응답하지 않을 가능성이 있다고 가정했습니다. 그랬을 때, 그것은 행복한 놀라움으로 증명되었습니다. 다음은 그녀의 상호 작용에 대한 요약이다.

그래서 칼에게 [출판]에 기여하고 싶은지 물어보려고 이메일을 보냈을 때, 제 기대는 설정되었다. 그는 게스트 블로그를 하고 싶다는 것을 [발신자 필터]에 아무것도 가지고 있지 않았기 때문에, 내가 엿보기를 듣지 않았다면 어떤 억울함도 없었을 것이다. 그러자 그가 대답했을 때, 저는 감격했습니다.

제 특정 발신자 필터는 이 일반적인 전략의 한 예일 뿐입니다. 기술 창업 기업을 위한 크라우드 펀딩 캠페인을 운영하는 전문가인 클레이 허버트 컨설턴트를 생각해 보자. 포브스닷컴의 발신자 필터 기사가 보도한 것처럼, "어느 시점에 손을 내민 사람의 수가 [허버트의] 용량을 초과해서 도움을 요청하는 사람에게 부담을 주는 필터를 만들었다"고 한다.

비록 그와 비슷한 동기에서 출발했지만 허버트 필터는 결국 다른 형태를 취하게 되었다. 그에게 연락하려면 먼저 FAQ를 참조하여 질문에 대한 답변이 이미 확인되지 않았는지 확인해야 합니다. 이 FAQ 체를 통해 만들면 그는 자신의 전문 지식과 특히 관련이 있는 것으로 보이는 연결을 추가로 선별할 수 있는 설문 조사를 작성하도록 요청한다. 이 단계를 넘어서면 허버트에게 그와 의사소통하기 전에 지불해야 하는 소정의 수수료를 부과한다. 이 수수료는 추가 돈을 벌기 위한 것이 아니라 조언을 받고 행동하는 데 진지한 개인을 선택하는 것입니다. 허버트의 필터는 여전히 그를 사람들을 돕고 흥미로운 기회를 만날 수 있게 한다. 그러나 동시에, 그들은 그가 쉽게 처리할 수 있는 수준으로 그의 들어오는 커뮤니케이션을 축소했습니다.

또 다른 예를 들면 인기 있는 리얼맨 스타일 블로그를 운영하는 안토니오 센테노를 생각해 보자. 센테노의 발신자 필터는 2단계 과정을 구성한다. 질문이 있으면 공개된 장소로 안내하여 게시합니다. 센테노는 사적인 일대일 대화에서 같은 질문에 반복해서 답하는 것은 낭비라고 생각한다. 이 단계를 넘어서면 체크 박스를 클릭하여 다음 세 가지 약속을 이행하도록 합니다.

✓ 구글에서 10분만 검색해도 찾을 수 있는 스타일 질문을 하지 않겠습니다.
✓ 무관한 사업 홍보를 위해 복사-붙여넣기 한 스팸성 문의를 보내지 않겠습니다.
✓ 안토니오가 23시간 이내에 답장을 준다면 모르는 타인을 위해 선행을 베풀겠습니다.

메시지를 입력할 수 있는 메시지 상자는 세 가지 약속 모두 상자를 클릭한 후에야 연락처 페이지에 표시된다.

요약하자면, 이메일에 기반을 둔 기술은 변혁적이지만 우리가 이 기술을 어떻게 적용하는지를 안내하는 현재의 사회적 관습은 저개발되어 있다. 목적이나 발신자에 관계없이 모든 메시지가 동일한 미분화 받은 편지함에 도착하고 모든 메시지가 (적절한) 응답을 받아야 한다는 기대가 있다는 개념은 터무니없이 비생산적이다. 발신자 필터는 작지만 더 나은 상황을 향한 유용한 단계이며 적어도 많은 의사소통을 받고 접근성을 지시할 수 있는 능력을 가진 점점 더 많은 기업가와 프리랜서에게 시간이 온 아이디어이다. (나는 또한 유사한 규칙이 대기업의 사무실 내 커뮤니케이션에 편재하는 것을 보고 싶지만 2장에서 주장한 이유로 우리는 아마도 그 현실에서 멀리 떨어져 있을 것이다.) 만약 당신이 그렇게 할 수 있다면, 당신의 시간과 주의력에 대한 통제를 회복하는 방법으로 발신자 필터를 고려해 보십시오.
:::

::: {.callout-tip title="팁 2: 이메일을 보내거나 답장할 때 '프로세스 중심'으로 작성하라"}

다음과 같은 전형적인 이메일 사례를 살펴보자.

메일 #1: 지난주에 만나서 반가웠습니다. 우리가 논의한 몇 가지 문제에 대해 후속 조치를 취하고 싶습니다. 커피 한잔 할래?

이메일 #2: 지난번 방문 때 논의했던 연구 문제로 돌아가야겠다. 우리가 어디에 있는지 상기시켜줘요?

이메일 #3: 우리가 논의했던 그 기사를 찔렀다. 붙어 있어. 생각?

이 세 가지 예는 대부분의 지식 작업자에게 친숙해야 하는데, 이는 받은 편지함을 채우는 많은 메시지를 대표하기 때문이다. 그들은 또한 잠재적인 생산성 지뢰입니다. 이에 대한 대응 방식은 결과 대화가 궁극적으로 얼마나 많은 시간과 관심을 소비하는지에 상당한 영향을 미칠 것입니다.

특히, 이와 같은 질문적 이메일은 수신함에서 메시지를 일시적으로 제거할 가능한 가장 빠른 응답을 내보내는 초기 본능을 생성한다. 빠른 응답은 단기적으로 약간의 완화를 제공할 것입니다. 왜냐하면 당신은 메시지가 암시하는 책임을 법정에서 벗어나 발신자에게 다시 돌리고 있기 때문입니다. 그러나 이 책임은 계속해서 반복되어 시간과 주의를 지속적으로 아들일 것이기 때문에 이 구제는 수명이 짧습니다. 따라서 이러한 유형의 질문에 직면했을 때 올바른 전략은 회신하기 전에 잠시 멈춰서 다음 핵심 프롬프트에 답변하는 시간을 갖는 것이 좋다.

이 메시지로 대표되는 프로젝트는 무엇이며 이 프로젝트를 성공적으로 마무리하기 위한 가장 효율적인(메시지 생성 측면에서) 프로세스는 무엇인가?

이 질문에 스스로 답한 후, 당신이 식별한 과정을 설명하는 데 시간을 두고 현재 단계를 지적하고 다음 단계를 강조하는 빠른 응답으로 대체한다. 나는 이것을 이메일의 과정 중심 접근이라고 부르며 이것은 당신이 받는 이메일의 수와 그들이 생성하는 정신적 혼란의 양을 최소화하도록 설계되었다.

이 프로세스와 작동 이유를 더 잘 설명하기 위해 앞서 샘플 이메일에 대한 다음 프로세스 중심 응답을 고려한다.

1. 이메일에 대한 프로세스 중심의 응답: "나는 커피를 마시고 싶다. 캠퍼스 스타벅스에서 만나자. 아래는 제가 시간이 있는 다음 주 이틀을 나열했습니다. 하루에 세 번 나열했어요. 해당 요일 및 시간 조합 중 하나라도 귀하에게 적합하다면 알려주십시오. 회의를 위한 회신 확인을 고려하겠습니다. 만약 그 날짜와 시간 조합이 작동하지 않는다면, 아래 번호로 전화해 주시면 작동하는 시간을 알아낼 수 있을 것입니다. 기대하고 있습니다.
2. 이메일에 대한 프로세스 중심의 응답: "이 문제로 돌아가야 한다는 데 동의한다. 제가 제안하는 것은 다음과 같습니다.

"다음 주 중으로 문제에 대한 우리의 논의에 대해 기억하는 모든 것을 이메일로 보내주십시오. 그 메시지를 받으면 프로젝트에 대한 공유 디렉토리를 시작하고 지난 토론에 대한 내 기억과 함께 보내주신 내용을 요약한 문서를 추가할 것입니다. 문서에서 나는 가장 유망한 다음 단계의 두세 가지를 강조할 것이다.

그런 다음 몇 주 동안 다음 단계를 수 있고 다시 체크인할 수 있다. 이를 위해 지금부터 한 달 동안 전화 일정을 잡는 것이 좋습니다. 아래에 제가 통화할 수 있는 날짜와 시간을 나열했습니다. 메모로 응답할 때 가장 적합한 날짜와 시간 조합을 표시하면 전화에 대한 회신 확인을 고려할 것입니다. 이 문제를 파헤쳐나갈 수 있기를 기대한다.

3. 이메일에 대한 프로세스 중심 응답: "회신해 주셔서 감사합니다. 이 기사의 초안을 읽고 주석이 달린 편집본을 금요일(10일)에 다시 보내드리겠습니다. 제가 다시 보내드리는 이 버전에서는 제가 할 수 있는 일을 직접 편집하고 당신이 개선에 더 적합하다고 생각하는 곳에 주의를 환기시키기 위해 댓글을 추가할 것입니다. 그 시점에서 최종 초안을 다듬고 제출하는 데 필요한 것이 있어야 하므로, 물론 문제가 없는 한 이 메시지에 답장하거나 편집을 반환한 후 후속 조치를 취할 필요가 없습니다.

이러한 샘플 응답을 작성하는 데 있어, 나는 메시지가 암시하는 프로젝트를 식별하는 것으로 시작했다. 주목하자면, 여기서 프로젝트라는 단어는 느슨하게 사용된다. 연구 문제에 대한 진전(예제 #2)과 같이 크고 명백한 프로젝트인 것을 포괄할 수 있지만 커피 미팅을 설정하는 것과 같은 작은 물류 문제에 대해서도 마찬가지로 쉽게 적용된다(예제 #1). 그런 다음 필요한 최소한의 메시지로 현재 상태에서 원하는 결과로 이어지는 과정을 생각하며 1~2분을 보냈다. 마지막 단계는 이 과정과 우리가 어디에 서 있는지 명확하게 설명하는 회신을 작성하는 것이었다. 이러한 예들단순 이메일 회신을 중심으로 하였지만 처음부터 이메일 메시지를 작성할 때에도 유사한 접근법이 작동한다는 점을 분명히 해야 한다.

이메일의 프로세스 중심 접근법은 이 기술이 시간과 주의력에 미치는 영향을 크게 완화할 수 있습니다. 이러한 효과는 두 가지 이유가 있다. 첫째, 수신함에 있는 이메일의 수를 줄이는 것(때로는 상당히 감소한다(커피 미팅 일정을 잡는 것처럼 간단한 것은 회신에 주의하지 않으면 며칠 동안 50개 이상의 메시지로 쉽게 나선형으로 번질 수 있다)이다. 이는 결과적으로 받은 편지함에 보내는 시간을 줄이고 보낼 때 소비해야 하는 두뇌력을 줄입니다.

둘째, 데이비드 앨런의 용어를 훔치기 위해 좋은 프로세스 중심 메시지는 당면한 프로젝트와 관련하여 즉시 "고리를 닫는다. 프로젝트가 당신이 보내거나 받는 이메일로 시작되면, 그것은 당신의 정신 지형에 스쿼팅되어 그것이 당신의 주의를 끌고 왔고 결국 해결되어야 한다는 의미에서 "당신의 접시에 있는" 무언가가 된다. 이 방법은 이 열린 고리가 형성되는 즉시 닫는다. 전체 프로세스를 통해 작업하고, 작업 목록과 캘린더에 귀하의 모든 관련 약속을 추가하고, 상대방을 빠르게 알려줌으로써, 귀하의 마음은 프로젝트가 한 번 요구한 정신적 부동산을 회복할 수 있습니다. 정신적인 혼란이 적다는 것은 깊은 사고를 할 수 있는 정신적인 자원이 더 많다는 것을 의미한다.

프로세스 중심의 이메일은 처음에는 자연스럽지 않을 수 있습니다. 첫째, 메시지를 작성하기 전에 메시지를 생각하는 데 더 많은 시간을 할애해야 합니다. 현재로서는, 이것은 당신이 이메일로 더 많은 시간을 보내는 것처럼 보일 수 있습니다. 그러나 중요한 점은 이 시점에서 추가로 2~3분을 보내는 것이 나중에 불필요한 추가 메시지를 읽고 응답하는 데 훨씬 더 많은 시간을 절약한다는 것입니다.

다른 문제는 프로세스 중심의 메시지가 정체되고 지나치게 기술적으로 보일 수 있다는 것이다. 이메일을 둘러싼 현재의 사회적 관습은 프로세스 중심의 의사소통에서 일반적으로 사용되는 보다 체계적인 일정이나 의사결정 트리와 충돌하는 대화적 톤을 촉진한다. 이것이 귀하에게 문제가 된다면, 저는 귀하의 메시지에 더 긴 대화 프리앰블을 추가하는 것을 제안합니다. 심지어 대화 개막에서 프로세스 중심 부분을 분할선으로 분리하거나 "제안된 다음 단계"로 라벨을 붙여 기술적인 톤이 맥락에서 더 적절해 보이도록 할 수도 있다.

결국, 이 사소한 번거로움이 그만한 가치가 있습니다. 수신함에 들락날락하는 이메일 메시지가 실제로 제안하는 것에 대해 더 많은 생각을 함으로써 이 기술이 실제로 중요한 작업을 수행하는 능력에 미치는 부정적인 영향을 크게 줄일 수 있습니다.
:::

::: {.callout-tip title="팁 3: 무의미한 이메일에는 응답하지 마라"}
MIT 대학원생으로서 유명 학자들과 교류할 수 있는 기회를 가졌다. 그렇게 함으로써, 많은 사람들이 이메일에 대한 매혹적이고 다소 희귀한 접근법을 공유한다는 것을 알아차렸는데, 이메일 메시지를 받을 때 그들의 기본 행동은 응답하지 않는 것이다.

시간이 지나면서 나는 이 행동을 주도하는 철학을 배웠는데, 그들단순 이메일에 관해서는 답장이 가치가 있다고 받는 사람에게 확신시키는 것이 발신자의 책임이라고 믿었다. 설득력 있는 사례를 만들어내지 않고 교수에게 요구되는 대응 노력을 충분히 최소화하지 않으면 응답을 얻지 못했다.

예를 들어, 다음 이메일은 연구소의 유명한 이름 중 많은 이름으로 회신을 생성하지 않을 것입니다.

안녕 교수님. 나는 <주제 X에 대해 이야기하기 위해 언젠가 들러보고 싶다. 혹시 시간 괜찮으세요?

이 메시지에 응답하려면 너무 상당한 작업이 필요하다("할 수 있습니까?"는 너무 모호하여 신속하게 응답할 수 없다). 또한 이 대화가 교수님의 시간적 가치가 있다고 주장하려는 시도도 없다. 이러한 비판을 염두에 두고 답장을 생성할 가능성이 더 높은 동일한 메시지 버전을 다음과 같이 제시한다.

안녕 교수님. 나는 나의 조언자인 <교수 Y와 <주제 X와 유사한 프로젝트를 진행하고 있다. 목요일 사무실 근무 시간 중 마지막 15분 동안 들러 우리가 하고 있는 일을 더 자세히 설명하고 현재 프로젝트를 보완할 수 있는지 확인해도 될까요?

첫 번째 메시지와 달리 이 메시지는 이 회의가 왜 의미가 있는지 명확하게 설명하고 수신자가 응답하는 데 필요한 노력을 최소화한다.

이 팁은 귀하의 전문적인 맥락에서 가능한 한 이 교수적 양면성을 이메일로 복제하도록 요청합니다. 이러한 노력에 도움이 되도록 다음 세 가지 규칙을 적용하여 응답이 필요한 메시지와 그렇지 않은 메시지를 분류해 보세요.

교수용 이메일 분류: 다음 중 어느 하나라도 해당되는 경우, 이메일 메시지에 회신하지 마십시오.

* 내용이 모호하거나 합리적인 답변을 작성하기 까다로운 경우.
* 본인의 관심사나 전문성에 부합하지 않는 질문이나 제안인 경우.
* 답장을 보내도 딱히 좋피상적 작업이 생기지 않고 답장을 보내지 않아도 별다른 나쁜 일이 일어나지 않는 경우.

모든 경우에 명백한 예외가 많이 존재한다. 예를 들어, 당신이 관심 없는 프로젝트에 대한 모호한 메시지가 회사의 CEO로부터 온다면, 당신은 응답할 것이다. 그러나 이러한 예외를 넘어서서 볼 때, 이 교수적 접근법은 '응답'을 클릭할지 여부를 결정할 때 훨씬 더 무자비하게 할 것을 요청한다.

이 팁은 메시지의 관련성이나 적절성과 상관없이 현재 이메일을 둘러싼 핵심 규약을 깨게 하기 때문에 처음에는 불편할 수 있습니다. 이 접근법을 취하면 나쁜 일이 생길 것이라는 것을 피할 방법이 없다. 최소한, 어떤 사람들은 혼란스럽거나 화가 날 수 있습니다. 특히 표준 이메일 관례에 의문을 제기하거나 무시한 적이 없는 경우 그렇습니다. 이게 문제야, 이거 괜찮아. 저자 팀 페리스는 한때 "작은 나쁜 일이 일어나도록 하는 습관을 길러라. 그렇지 않으면, 당신은 인생을 바꾸는 큰 일을 할 시간을 결코 찾을 수 없을 것이다. MIT의 교수들이 발견했듯이, 사람들은 당신의 의사소통 습관의 세부 사항에 대한 기대를 빠르게 조정한다는 사실을 깨닫는 것이 당신을 위로해야 한다. 그들이 서둘러 쓴 메시지에 응답하지 않았다는 사실은 아마도 그들의 삶의 중심적인 사건이 아닐 것이다.

일단 이 접근법의 불편함을 극복하면, 당신은 그것의 보상을 경험하기 시작할 것이다. 사람들이 이메일 과부하에 대한 솔루션을 논의할 때 두 가지 일반적인 트로프가 있습니다. 하나는 이메일을 보내는 것이 더 많단순 이메일을 생성한다고 말하는 반면, 다른 하나는 모호하거나 관련이 없는 이메일로 씨름하는 것이 수신함 관련 스트레스의 주요한 원인이라고 말한다. 여기에서 제안된 접근법은 두 가지 문제에 공격적으로 반응합니다. - 당신은 더 적은 수의 이메일을 보내고 처리하기 쉽지 않단순 이메일을 무시합니다. - 그렇게 함으로써 당신의 시간과 관심에 따라 받은 편지함이 쥐고 있던 통제력을 크게 약화시킬 수 있을 것입니다.
:::

# 결론: 몰입하는 삶이 좋은 삶이다

마이크로소프트 창업 이야기는 전설의 영역에 들어갔을 정도로 여러 번 전해졌다. 1974년 겨울, 빌 게이츠라는 이름의 하버드 대학생 어린이는 인기전자 표지에 세계 최초의 개인용 컴퓨터인 알테어를 본다. 게이츠는 기계에 소프트웨어를 설계할 기회가 있다는 것을 깨닫고 모든 것을 버리고 폴 앨런과 몬테 데이비도프의 도움으로 알테어용 BASIC 프로그래밍 언어 버전을 함께 해킹하는 데 8주를 보낸다. 이 이야기는 게이츠의 통찰력과 과감함의 한 예로 종종 거론되지만 최근 인터뷰에서 이야기의 해피엔딩에 결정적인 역할을 한 또 다른 특성인 게이츠의 초자연적인 심오한 작업 능력이 드러났다.

월터 아이작슨이 2013년 하버드 게지트 주제의 기사에서 설명했듯이 게이츠는 이 두 달간의 스트레치 기간 동안 코드 한 줄을 쓰는 도중 종종 키보드에서 잠에 빠질 정도로 강렬하게 작업했다. 그는 한두 시간 동안 자고 일어나서, 여전히 감명받는 폴 앨런이 "집중력의 엄청난 위업"이라고 묘사하는 능력을 끊은 바로 그 곳에서 픽업했다. 나중에 아이작슨은 그의 저서 '혁신자'에서 깊이에 대한 게이츠의 독특한 경향을 다음과 같이 요약했다. 앨런의 마음은 많은 생각과 열정 사이에서 활보할 것이지만 게이츠는 연쇄적인 집착자였다.

게이츠의 강박적 초점의 이 이야기에서 우리는 딥 워크을 위한 나의 가장 강력한 주장의 형태를 마주하게 된다. 급속도로 진화하는 정보화 시대의 난류 속에서 변증법적 불평에 기복하기 쉽다. 우리 중 굴곡꾼들은 사람들이 휴대폰에 기울이는 관심에 막연히 불안해하며, 서두르지 못한 집중의 날을 소나무로 삼는 반면, 디지털 힙스터들은 그러한 향수를 러디즘과 지루함과 동일시하며, 연결의 증가가 유토피아적 미래의 토대가 된다고 믿는다. 마셜 맥루언은 '매체는 메시지'라고 선언했지만 이러한 주제에 대한 우리의 현재 대화는 '매체는 도덕'이라는 것을 암시하는 것 같다.

필자는 이 책의 서론에서 강조했듯이 이 논쟁에 관심이 없다. 심층적인 일에 대한 헌신은 도덕적 자세가 아니며 철학적 진술도 아니며 오히려 집중하는 능력이 가치 있는 일을 수행하는 기술이라는 실용적인 인식이다. 심층 작업이 중요한데, 즉 산만함이 악재이기 때문이 아니라 빌 게이츠가 한 학기도 채 안 돼 10억 달러 규모의 산업을 시작할 수 있게 했기 때문이다.

이는 내가 개인적으로 자신의 경력에서 반복해서 재학습한 교훈이기도 하다. 나는 10년 넘게 깊이의 열성자였지만 심지어 나는 여전히 그것의 힘에 정기적으로 놀란다. 이 기술을 처음 접하고 우선순위를 두기 시작한 시기가 대학원 때, 딥 워크으로 매년 양질의 동료 검토 논문을 한 쌍 작성할 수 있게 되었음을 알게 되었어요.

하지만 교수직으로의 전환이 가까워지면서 걱정이 시작됐다. 학생이자 포닥으로서 나의 시간 약속은 최소한이었고 대부분의 하루를 내가 원하는 모양으로 만들게 했다. 나는 내 경력의 다음 단계에서 이 사치를 잃을 것이라는 것을 알고 있었고 생산성을 유지하기 위해 이 더 까다로운 일정에 충분한 심층 작업을 통합할 수 있는 내 능력에 확신이 없었다. 불안에 푹 빠지는 대신 뭔가 해야겠다고 결심했고 심부근육을 강화하는 계획을 세웠다.

이러한 훈련 노력은 MIT에서 지난 2년 동안 교수직을 찾기 시작한 포닥을 하는 동안 전개되었다. 나의 주요 전술은 교수로서 예상했던 더 제한된 자유 시간을 더 잘 근사화하기 위해 내 일정에 인위적인 제약을 도입하는 것이었다. 야간에는 일하지 않는 규칙에 더해, 한낮에 점심시간을 연장해서 달리기하고 나서 다시 아파트에서 점심을 먹기 시작했습니다. 또한 이 기간 동안 네 번째 책인 '너를 무시할 수 없는 너무 좋음'을 쓰기로 계약을 맺었는데, 물론 이 프로젝트는 곧 제 시간에 강렬한 요구를 부과했다.

이러한 새로운 제약을 보완하기 위해 깊이 있는 작업 능력을 다듬었다. 다른 방법들 중에서, 나는 딥 워크 시간을 더 조심스럽게 차단하고 침입으로부터 보존하기 시작했다. 또한 매주 걸어서 보내는 많은 시간 동안 생각을 통해 신중하게 작업하는 능력(생산성에 도움이 되는 것)을 개발했으며 집중에 도움이 되는 연결되지 않은 위치를 찾는 데 집착하게 되었다. 예를 들어, 여름에는 수업이 있을 때 너무 붐비는 기분 좋게 해면성인 바커 엔지니어링 라이브러리의 돔 아래에서 작업하는 경우가 많았고 겨울에는 약간의 침묵을 위해 더 모호한 위치를 찾았고 결국 작지만 잘 정비된 루이스 음악 라이브러리를 선호했다. 어느 순간, 나는 그것의 비용이 내 사고에 더 많은 주의를 유도할 것이라고 믿으며 수학 증명 작업을 위해 50달러의 고급 격자 안감 실험실 노트북을 샀다.

나는 이 깊이에 대한 재약속이 얼마나 잘 작동했는지에 놀랐다. 2011년 가을에 조지타운대 컴퓨터과학과 교수로 취임한 후, 의무는 실제로 급격히 증가했다. 하지만 저는 이 순간을 위해 훈련을 하고 있었습니다. 연구 생산성을 보존했을 뿐만 아니라 실제로 개선되었습니다. 부담 없는 대학원생으로서 유지하던 예전의 좋은 논문 2편 비율은 한 번 훨씬 더 부담스러운 교수가 되면 평균적으로 한 해에 4편 좋은 논문으로 도약했다.

그러나 이것이 나에게 인상적이었지만 나는 딥 워크이 무엇을 생산할 수 있는지에 대한 한계에 아직 도달하지 못했다는 것을 곧 알게 되었다. 이 수업은 교수로서 3년차에 있을 거예요. 2013년 가을부터 2014년 여름까지 이어진 조지타운 3년차에 더 많은 개선 기회를 찾아 깊은 업무 습관으로 눈을 돌렸다. 깊이에 대한 이러한 재헌신을 하는 큰 이유는 당신이 현재 읽고 있는 책인데, 대부분이 이 시기에 쓰여졌기 때문이다. 7만 단어의 책 원고를 쓰는 것은 물론 이미 바쁜 일정에 갑자기 새로운 제약을 가했고 나는 나의 학업 생산성이 그에 상응하는 타격을 받지 않도록 하고 싶었다. 내가 다시 깊이로 돌아선 또 다른 이유는 임기 과정이 다가왔기 때문이다. 재직 기간이 1~2년 남았는데, 재직 기간이 제출되기 전까지 출판물이 남아있었다. 즉, (특히 아내와 나는 재임 전 마지막 해에 둘째 아이와 함께 가정을 키우려고 계획하고 있었다는 점에서) 나의 능력에 대해 진술할 수 있는 시간이었다. 내가 다시 깊이로 돌아간 마지막 이유는 더 개인적인 것이고 (인정하건대) 터치 페런트였다. 나는 많은 동료들이 받고 있는 존경받는 보조금에 지원하고 거절당했다. 화가 나며 당황스러웠기 때문에, 나는 단지 불평하거나 자기 의구심에 허덕이는 대신, 내 출판물의 비율과 인상을 높여서 보조금 손실을 보상하기로 결정했다.

나는 이미 능숙한 심층 노동자였지만 이 세 가지 힘들이 나를 이 습관을 극단으로 밀어붙이게 했다. 시간이 많이 걸리는 약속을 거부하는 데 무자비해졌고 사무실 밖의 고립된 장소에서 더 많이 일하기 시작했습니다. 나는 내 깊은 근무 시간의 집계를 내 책상 근처의 눈에 띄는 위치에 배치했고 충분히 빠른 속도로 성장하지 못하자 속상했다. 아마도 가장 큰 영향은 개를 걷거나 출퇴근하는 좋은 시간이 presented 될 때마다 머릿속의 문제를 작업하는 MIT 습관으로 돌아갔다는 것이다. 예전에는 마감일이 다가오면만 심층 작업을 늘리는 경향이 있었지만 올해는 집요하지 않았는데, 특정 마감일이 가까워졌는지 여부에 관계없이 결과와 함께 고심하기 위해 매주 하루가 가장 쉬웠다. 지하철을 타는 동안과 눈을 는 동안 증명서를 풀었어요. 주말에 아들이 낮잠을 자면 마당을 가하고 교통체증에 갇히면 나를 방해하는 문제를 체계적으로 해결했다.

올해가 진행되면서 나는 딥 워크 기계가 되었고 이러한 변화의 결과는 나를 놀라게 했다. 책을 쓰고 큰 아들이 끔찍한 둘에 들어간 같은 해 동안 나는 9개의 동료 검토 논문을 출판하면서 평균 학업 생산성을 두 배 이상 높이는 동시에 저녁에 일하는 금지를 유지했다.

나는 나의 극심한 깊이가 한 해가 어쩌면 너무 극단적이었음을 처음으로 인정한다. 그것은 인지적으로 지친 것으로 판명되었으며 앞으로 나는 이 강도를 조절할 것이다. 그러나 이 경험은 이 결론을 연 요점을 강화합니다. 심층 작업은 대부분의 사람들이 이해하는 것보다 훨씬 강력합니다. 빌 게이츠가 새로운 산업을 창조할 뜻밖의 기회를 최대한 활용할 수 있게 해주고 동시에 책을 쓰기로 결정한 그 해에 학업 생산성을 두 배로 높일 수 있게 해준 것은 바로 이 기술에 대한 헌신이다. 산만해진 대중을 떠나 집중된 소수에 합류하는 것은, 내가 주장하는 바, 변혁적 경험이다.

물론 깊은 삶은 모든 사람을 위한 것이 아닙니다. 그것은 당신의 습관에 대한 노력과 과감한 변화를 요구합니다. 많은 사람들에게는 급격한 이메일 메시징과 소셜 미디어 자세의 인위적인 바쁜 데 위안이 있는 반면, 깊은 삶은 많은 부분을 뒤로 남겨두어야 한다고 요구한다. 또한 당신이 생산할 수 있는 최고의 것을 생산하려는 모든 노력을 둘러싸고 있는 불안감이 있는데, 이는 당신이 당신의 최고가 (아직) 그렇게 좋지 않을 가능성에 직면하도록 강요하기 때문이다. 루스벨트 반지에 발을 들여놓아 더 나피상적인 일으로 씨름하려는 것보다 우리 문화에 대해 논평하는 것이 더 안전하다.

그러나 당신이 이러한 편안함과 두려움을 기꺼이 피해가며 대신 중요한 것을 창조하기 위해 정신을 최대한 발휘하기 위해 고군분투한다면, 다른 사람들이 당신보다 앞서 경험한 것처럼, 깊이가 생산성과 의미가 풍부한 삶을 생성한다는 것을 발견할 것이다. 1부에서 나는 작가 위니프레드 갤러거의 말을 인용했는데, 그는 "집중된 삶을 살 것이다, 왜냐하면 그것이 최고의 삶이기 때문이다." 나는 동의한다. 빌 게이츠도 그렇고. 그리고 이 책을 다 읽으셨으니, 당신도 동의하기를 바랍니다.
