project:
  type: book
  output-dir: docs

book:
  title: "Mastering Python for Bioinformatics (KO)"
  author: "Ken Youens-Clark (Trans. Gemini CLI)"
  date: "1/24/2026"
  chapters:
    - index_ko.qmd
    - index.qmd

bibliography: references.bib

format:
  html:
    theme:
      - flatly
      - brand
    number-sections: false

execute:
  freeze: auto
